// Warnings and project-specific rules: mix of pre_warn (fully-deterministic
// or low-FP) and post (heuristic) phases. Two severity=error entries
// (focused_tests, migration_ordering) live here because they sit alongside
// related project rules rather than the pure correctness checks in
// entries-errors.ts.

import {
	checkAccumulatingSpread,
	checkAsyncEventHandler,
	checkBooleanTrap,
	checkBroadObjectTypes,
	checkCatchAndLog,
	checkCircularImports,
	checkConstantCondition,
	checkDeadExports,
	checkDeeplyNestedCallback,
	checkDefaultExport,
	checkDeferInLoop,
	checkDirectDomAccess,
	checkDisabledTests,
	checkDivisionByVariable,
	checkExcessiveUseEffect,
	checkExcessiveUseState,
	checkExtraneousDependencies,
	checkFloatEquality,
	checkFloatingPromises,
	checkFocusedTests,
	checkGoroutineNoWaitgroup,
	checkHardcodedTimeout,
	checkIndexAsKey,
	checkInlineObjectProps,
	checkJavaOptionalGet,
	checkJsLooseEquality,
	checkJsonParseUnsafe,
	checkLargeFunction,
	checkLifecycleCleanup,
	checkMagicLiteralInConditional,
	checkMagicNumberNoConst,
	checkMigrationOrdering,
	checkMissingEffectCleanup,
	checkNestedTernaries,
	checkNonNullAssertions,
	checkNumberPrecisionLoss,
	checkNumericComparisonChain,
	checkEvalInputTainted,
	checkOsSystemTainted,
	checkOverMocking,
	checkPickleUntrustedLoad,
	checkPrintDebugLeak,
	checkPyMutableDefaultArg,
	checkRegexInLoopNoCompile,
	checkRequireAwait,
	checkSequentialAwaits,
	checkSqlStringConcat,
	checkSnapshotOveruse,
	checkSqlSchemaConsistency,
	checkTargetBlankNoRel,
	checkTempfileMktempRace,
	checkTestImportingTest,
	checkTimeFormatLocaleDep,
	checkUbsHardcodedLocalhost,
	checkUbsStringConcatInLoop,
	checkUncheckedRedirect,
	checkUnsafeFormatString,
	checkUnvalidatedJsonBoundary,
	checkVisibilityFilterMissing,
	checkXmlExternalEntity,
} from "../generic-checks.js";
import type { CheckRegistration } from "./types.js";

export const WARNING_ENTRIES: CheckRegistration[] = [
	{
		id: "default_export",
		phase: "post",
		name: "Default Export Hygiene",
		description:
			"Flags anonymous default exports or default exports whose symbol name does not match the filename — grep-hostile for cold readers",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Prefer a named export: `export function Foo() {}` + `import { Foo } from './foo'`. If you must use a default export (framework convention), give the symbol a name that matches the filename so grep and rename tools work: `export default function Foo() {}` in foo.ts. Anonymous `export default (...) => ...` is the worst case — rename to a named function.",
		fn: checkDefaultExport,
		resultsPropName: "defaultExport",
	},
	{
		id: "lifecycle_cleanup",
		phase: "post",
		name: "Lifecycle Cleanup",
		description:
			"Detects classes with a lifecycle method (dispose/destroy/close/unmount/stop) that register setInterval / setTimeout / addEventListener without the paired cleanup in the lifecycle body",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Store the handle returned by setInterval/setTimeout (or the listener function you passed to addEventListener) and pair it with clearInterval/clearTimeout/removeEventListener inside the lifecycle method. Otherwise the subscription outlives the class — a memory leak plus work that keeps happening after dispose.",
		fn: checkLifecycleCleanup,
		resultsPropName: "lifecycleCleanup",
	},
	{
		id: "circular_imports",
		phase: "post",
		name: "Circular Imports",
		description:
			"Detects import cycles involving the edited file (A → B → C → A) — unclear module boundaries that can cause runtime undefined-at-import-time bugs",
		tier: 3,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Break the cycle by moving shared types/constants to a third module that both sides depend on, or by flipping one edge to a type-only import (if it's only used in type positions). Cycles cause hard-to-debug `undefined` values at runtime because ES modules initialize one side before the other completes.",
		fn: (content, filePath) => checkCircularImports(content, filePath, process.cwd()),
		resultsPropName: "circularImports",
	},
	{
		id: "dead_exports",
		phase: "post",
		name: "Dead Exports",
		description:
			"Detects named exports that no other file in the project imports — inflates the apparent public surface for cold readers",
		tier: 3,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Either remove the unused export (so the public surface reflects what's actually consumed) or leave a comment explaining that it's deliberately part of the public API for external consumers. Cold readers — including agents — waste time trying to understand handles that nothing actually uses.",
		fn: (content, filePath) => checkDeadExports(content, filePath, process.cwd()),
		resultsPropName: "deadExports",
	},
	{
		id: "unvalidated_json_boundary",
		phase: "post",
		name: "Unvalidated JSON Boundary",
		description:
			"Detects `JSON.parse(...)` / `await <x>.json()` results that reach property access without passing through a schema parser (zod, valibot, ajv, yup, io-ts, arktype)",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Pipe the parsed value through a schema parser before using it: `const parsed = MySchema.parse(JSON.parse(raw));`. This gives you both a runtime validation error on malformed input AND a typed value downstream — cold readers see `parsed.field` and know the shape is guaranteed, not just a hope.",
		fn: checkUnvalidatedJsonBoundary,
		resultsPropName: "unvalidatedJsonBoundary",
	},
	{
		id: "magic_literal_in_conditional",
		phase: "post",
		name: "Magic Literal in Conditional",
		description:
			"Detects if/switch branches that compare against a bare numeric or string literal instead of a named constant — cold readers can't tell what the branch means",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Extract the literal into a named constant or enum so the conditional reads as intent. `if (status === ORDER_FULFILLED)` tells a cold reader what branch they're in; `if (status === 2)` forces them to grep for where 2 is defined.",
		fn: checkMagicLiteralInConditional,
		resultsPropName: "magicLiteralInConditional",
	},
	{
		id: "boolean_trap",
		phase: "post",
		name: "Boolean Trap",
		description:
			"Detects function calls with 2+ boolean literal arguments — the reader can't tell what each bool means without jumping to the definition",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Replace positional booleans with an options object so the intent is visible at the call site: `createUser('alice', { admin: true, verified: false })` instead of `createUser('alice', true, false)`. Alternatively, use an enum when the booleans represent a discrete mode.",
		fn: checkBooleanTrap,
		resultsPropName: "booleanTrap",
	},
	{
		id: "broad_object_types",
		phase: "pre_warn",
		name: "Broad Object Types",
		description:
			"Detects Record<K, any>, index signatures to any, and bare Function/object type annotations that hide shape information",
		tier: 1,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This type hides the shape of the value. Replace `Record<K, any>` / `{ [k: string]: any }` with a specific interface or typed map (e.g., `Record<UserId, UserProfile>`). Replace bare `Function` with a specific signature (`(x: number) => string`). Replace bare `object` with the actual object shape. Cold readers can't know what's expected otherwise.",
		fn: checkBroadObjectTypes,
		resultsPropName: "broadObjectTypes",
	},
	{
		id: "floating_promises",
		phase: "pre_warn",
		name: "Floating Promises",
		description:
			"Detects calls to async-declared functions (or fetch) at statement position without await, return, void, assignment, or .catch()/.finally() handling",
		tier: 1,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"An async function's return value is being ignored at statement position. Unhandled rejections silently fail and trigger `unhandledRejection` warnings. Add `await` if the caller is async, `return` if the caller propagates, or `.catch(err => ...)` to explicitly handle the rejection. Only use `void foo()` when fire-and-forget is intentional and documented.",
		fn: checkFloatingPromises,
		resultsPropName: "floatingPromises",
	},
	{
		id: "extraneous_deps",
		phase: "pre_warn",
		name: "Extraneous Dependencies",
		description: "Detects imported packages not in package.json",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This import references a package not listed in package.json. Run `npm install <package>` or remove the import.",
		fn: checkExtraneousDependencies,
		resultsPropName: "extraneousDeps",
	},
	{
		id: "non_null_assertion",
		phase: "post",
		name: "Non-Null Assertion",
		description: "Detects TypeScript non-null assertions (!)",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Avoid the non-null assertion operator (!). Use optional chaining (?.), nullish coalescing (??), or add a proper null check instead.",
		fn: checkNonNullAssertions,
		resultsPropName: "nonNullAssertions",
	},
	{
		id: "constant_condition",
		phase: "post",
		name: "Constant Condition",
		description: "Detects always-true/false conditions",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This condition is always true or always false. Remove the dead branch or fix the logic.",
		fn: checkConstantCondition,
		resultsPropName: "constantCondition",
	},
	{
		id: "number_precision_loss",
		phase: "pre_warn",
		name: "Number Precision Loss",
		description: "Detects integer literals beyond safe precision",
		tier: 2,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This integer exceeds Number.MAX_SAFE_INTEGER (2^53-1) and will lose precision. Use BigInt (append 'n') for large integers.",
		fn: checkNumberPrecisionLoss,
		resultsPropName: "numberPrecisionLoss",
	},
	{
		id: "require_await",
		phase: "post",
		name: "Require Await",
		description: "Detects async functions without await",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This async function never uses await. Remove the async keyword — it unnecessarily wraps the return value in a Promise and misleads callers about the function's behavior.",
		fn: checkRequireAwait,
		resultsPropName: "requireAwait",
	},
	{
		id: "accumulating_spread",
		phase: "post",
		name: "Accumulating Spread",
		description: "Detects spread operator in reduce (O(n^2))",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Spreading the accumulator in .reduce() creates a new copy on every iteration (O(n²)). Use a for loop with mutation, Object.fromEntries(), or Map instead.",
		fn: checkAccumulatingSpread,
		resultsPropName: "accumulatingSpread",
	},
	{
		id: "excessive_use_state",
		phase: "post",
		name: "Excessive useState",
		description: "Detects components with too many useState hooks",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Too many useState hooks in one component. Consider useReducer or extracting state into a custom hook.",
		fn: checkExcessiveUseState,
		resultsPropName: "excessiveUseState",
	},
	{
		id: "direct_dom_access",
		phase: "post",
		name: "Direct DOM Access",
		description: "Detects direct DOM manipulation in React components",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Avoid direct DOM access in React components. Use refs (useRef) or state-driven rendering.",
		fn: checkDirectDomAccess,
		resultsPropName: "directDomAccess",
	},
	{
		id: "inline_object_props",
		phase: "post",
		name: "Inline Object Props",
		description: "Detects inline object/array creation in JSX props",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Move inline object/array props to a const outside the component to prevent unnecessary re-renders.",
		fn: checkInlineObjectProps,
		resultsPropName: "inlineObjectProps",
	},
	{
		id: "async_event_handler",
		phase: "post",
		name: "Async Event Handler",
		description: "Detects async event handlers that may cause unmounted-component issues",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Async event handlers should handle errors internally. Wrap the body in try/catch.",
		fn: checkAsyncEventHandler,
		resultsPropName: "asyncEventHandler",
	},
	{
		id: "nested_ternaries",
		phase: "post",
		name: "Nested Ternaries",
		description: "Detects nested ternary expressions",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Nested ternaries hurt readability. Use if/else blocks or extract to a helper function.",
		fn: checkNestedTernaries,
		resultsPropName: "nestedTernaries",
	},
	{
		id: "catch_and_log",
		phase: "post",
		name: "Catch and Log",
		description: "Detects catch blocks that only log and rethrow",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Catching and only logging an error swallows it. Re-throw, return an error value, or add explicit recovery logic.",
		fn: checkCatchAndLog,
		resultsPropName: "catchAndLog",
	},
	{
		id: "json_parse_unsafe",
		phase: "post",
		name: "JSON Parse Unsafe",
		description: "Detects JSON.parse without try/catch",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction: "Wrap JSON.parse() in a try/catch to handle malformed input gracefully.",
		fn: checkJsonParseUnsafe,
		resultsPropName: "jsonParseUnsafe",
	},
	{
		id: "hardcoded_timeout",
		phase: "post",
		name: "Hardcoded Timeout",
		description: "Detects magic number timeouts (setTimeout/setInterval)",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Extract magic timeout numbers into named constants (e.g., const POLL_INTERVAL_MS = 5000).",
		fn: checkHardcodedTimeout,
		resultsPropName: "hardcodedTimeout",
	},
	{
		id: "disabled_tests",
		phase: "pre_warn",
		name: "Disabled Tests",
		description: "Detects skipped tests (it.skip, xit, xdescribe)",
		tier: 2,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Remove it.skip/xit/xdescribe markers. Disabled tests become stale and mask regressions.",
		fn: checkDisabledTests,
		resultsPropName: "disabledTests",
	},
	{
		id: "target_blank_no_rel",
		phase: "pre_warn",
		name: "Target Blank No Rel",
		description: 'Detects target="_blank" without rel="noopener"',
		tier: 2,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			'Add rel="noopener noreferrer" to links with target="_blank" to prevent reverse tabnapping.',
		fn: checkTargetBlankNoRel,
		resultsPropName: "targetBlankNoRel",
	},
	{
		id: "snapshot_overuse",
		phase: "pre_warn",
		name: "Snapshot Overuse",
		description: "Detects excessive snapshot testing",
		tier: 2,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Too many snapshot tests. Use targeted assertions (expect specific props, text content) instead of snapshots.",
		fn: checkSnapshotOveruse,
		resultsPropName: "snapshotOveruse",
	},
	{
		id: "test_importing_test",
		phase: "pre_warn",
		name: "Test Importing Test",
		description: "Detects test files importing from other test files",
		tier: 2,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Tests should not import from other test files. Extract shared test utilities to a separate helpers file.",
		fn: checkTestImportingTest,
		resultsPropName: "testImportingTest",
	},
	{
		id: "excessive_use_effect",
		phase: "post",
		name: "Excessive useEffect",
		description: "Detects components with too many useEffect hooks",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Too many useEffect hooks. Combine related effects or extract into custom hooks.",
		fn: checkExcessiveUseEffect,
		resultsPropName: "excessiveUseEffect",
	},
	{
		id: "sequential_awaits",
		phase: "post",
		name: "Sequential Awaits",
		description: "Detects sequential await calls that could be parallelized",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"These awaits can run in parallel. Use Promise.all([...]) for independent async operations.",
		fn: checkSequentialAwaits,
		resultsPropName: "sequentialAwaits",
	},
	{
		id: "index_as_key",
		phase: "post",
		name: "Index as Key",
		description: "Detects array index used as React key prop",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Use a stable, unique identifier as key instead of array index. Index keys cause incorrect rendering when items are reordered.",
		fn: checkIndexAsKey,
		resultsPropName: "indexAsKey",
	},
	{
		id: "missing_effect_cleanup",
		phase: "post",
		name: "Missing Effect Cleanup",
		description: "Detects useEffect with subscriptions but no cleanup",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This useEffect adds a subscription but returns no cleanup function. Return a cleanup to prevent memory leaks.",
		fn: checkMissingEffectCleanup,
		resultsPropName: "missingEffectCleanup",
	},
	{
		id: "over_mocking",
		phase: "post",
		name: "Over-Mocking",
		description: "Detects excessive mocking in test files",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This test file has extensive mocking. Consider testing with real implementations where possible, or restructure to reduce mock surface.",
		fn: checkOverMocking,
		resultsPropName: "overMocking",
	},
	{
		id: "focused_tests",
		phase: "pre_block",
		name: "Focused Tests",
		description: "Detects shipped focus markers (.only, fit, fdescribe)",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"Remove .only / fit / fdescribe markers — focused tests cause CI to silently skip the rest of the suite.",
		fn: checkFocusedTests,
		resultsPropName: "focusedTests",
	},
	{
		id: "migration_ordering",
		phase: "pre_block",
		name: "Migration Ordering",
		description: "Detects CREATE INDEX on a column not in the same-block CREATE TABLE",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"Add the column via addColumnIfNotExists() FIRST, then run CREATE INDEX in a SEPARATE sql.exec() call. CREATE TABLE IF NOT EXISTS is a no-op for existing tables, so any column added later won't be present when CREATE INDEX runs in the same block.",
		fn: checkMigrationOrdering,
		resultsPropName: "migrationOrdering",
	},
	{
		id: "sql_schema_consistency",
		phase: "pre_warn",
		name: "SQL Schema Consistency",
		description: "Detects SQL queries referencing columns not declared in same-file schema",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This SQL query references a column not declared in any CREATE TABLE or addColumnIfNotExists() call in the same file. Either add it to the schema, or move the query to a file that has access to the correct schema.",
		fn: checkSqlSchemaConsistency,
		resultsPropName: "sqlSchemaConsistency",
	},
	{
		id: "visibility_filter_missing",
		phase: "pre_warn",
		name: "Visibility Filter Missing",
		description: "Detects soft-delete table queries without an archived_at/deleted_at filter",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This query targets a table with a soft-delete column (archived_at / deleted_at / is_archived / is_deleted) but does not filter on it. Add the filter — list/count queries diverging from this contract is a known regression source. If you intentionally want all rows including archived ones, add a WHERE/AND clause that explicitly references the soft-delete column.",
		fn: checkVisibilityFilterMissing,
		resultsPropName: "visibilityFilterMissing",
	},
	// === UBS Plan 04 — rows 27–30 (warning/post tier) ===
	{
		id: "ubs_js_loose_equality",
		phase: "pre_warn",
		name: "UBS JS Loose Equality",
		description:
			"Detects `==` / `!=` in JS/TS files. The triple-equality form (`===` / `!==`) avoids JS type coercion. The `x == null` / `x != null` idiom is allowed (Plan 04 §4.2 documented exception).",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Use `===` / `!==` instead of `==` / `!=`. Loose equality triggers JavaScript type coercion (`'' == 0`, `null == undefined`, `'1' == 1` are all true) and is a documented bug source. The one allowed loose form is `x == null`, which checks both null AND undefined in one expression.",
		fn: checkJsLooseEquality,
		resultsPropName: "jsLooseEquality",
		content_keywords: ["==", "!="],
	},
	{
		id: "ubs_float_equality",
		phase: "pre_warn",
		name: "UBS Float Equality",
		description:
			"Detects `===` / `!==` against a non-IEEE-safe float literal — floating-point representation makes direct comparison unreliable.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Float equality is unreliable due to IEEE 754 representation: `0.1 + 0.2 === 0.3` is false. Compare with an epsilon: `Math.abs(a - b) < 1e-9`. Values exactly representable in binary (0.0, 0.5, 1.0, etc.) are skipped by the detector.",
		fn: checkFloatEquality,
		resultsPropName: "floatEquality",
		content_keywords: ["==", "!="],
	},
	{
		id: "ubs_java_optional_get",
		phase: "post",
		name: "UBS Java Optional.get()",
		description:
			"Detects Java `Optional<T>....get()` without an `isPresent()` / `orElse(...)` guard — NullPointerException risk.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"`Optional.get()` throws `NoSuchElementException` when the optional is empty. Guard with `isPresent()` first, or replace with `orElse(default)` / `orElseGet(() -> ...)` / `orElseThrow(() -> new IllegalStateException(...))`. The whole point of `Optional` is to make absence explicit; `.get()` discards that signal.",
		fn: checkJavaOptionalGet,
		resultsPropName: "javaOptionalGet",
		content_keywords: ["Optional"],
	},
	{
		id: "ubs_division_by_variable",
		phase: "post",
		name: "UBS Division by Variable",
		description:
			"Detects `expr / identifier` — the divisor variable might be zero (advisory; high FP rate, ships in DEFAULT_ADVISORY_SKIPS).",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Division by a variable can throw `Division by zero` (Python) / produce `Infinity` / `NaN` (JS) at runtime. Add an explicit zero-check (`if (divisor === 0) ...`) or assert the precondition before the division. If the divisor is provably non-zero by construction, leave a comment so cold readers don't repeat the analysis.",
		fn: checkDivisionByVariable,
		resultsPropName: "divisionByVariable",
	},
	// ---- Plan 04 D.1 partial — three high-leverage backlog entries. ----
	// `eval_usage` (entries-errors.ts) and `cross-language.ts:checkSqlInjection`
	// already pre_block on broad eval / SQL cases; the two `error`-severity
	// pre_warn entries below specialize on the tainted-input subset (non-
	// literal first arg / template-literal interpolation) and add extra
	// pre-event signal without flipping decision semantics. The third entry
	// is a Python-specific post warning.
	{
		id: "ubs_eval_input_tainted",
		phase: "pre_warn",
		name: "Eval / Function / exec on tainted input",
		description:
			"Detects eval / Function / exec / compile invoked with a non-literal first argument (likely a parameter or external value).",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"Evaluating attacker-controllable input as code is the most direct RCE pattern. If you genuinely need dynamic dispatch, keep the input on a strict allowlist (lookup table → preset function); never pass it to eval / Function / exec / compile.",
		fn: checkEvalInputTainted,
		resultsPropName: "evalInputTainted",
		content_keywords: ["eval", "Function", "exec", "compile"],
	},
	{
		id: "ubs_sql_string_concat",
		phase: "pre_warn",
		name: "SQL string concatenation",
		description:
			"Detects SQL keywords inside a quoted string immediately followed by JS/Py concatenation or template-literal interpolation — the canonical SQL-injection shape.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"Use parameterized queries / prepared statements: `db.query('SELECT * WHERE id = $1', [id])`. Concatenating input into the SQL string is a SQLi vector even on internal queries — values that look safe today get reached by external code paths tomorrow.",
		fn: checkSqlStringConcat,
		resultsPropName: "sqlStringConcat",
		content_keywords: ["SELECT", "INSERT", "UPDATE", "DELETE"],
	},
	{
		id: "ubs_python_mutable_default_arg",
		phase: "post",
		name: "Python mutable default argument",
		description:
			"Detects `def f(x=[])` / `def f(x={})` — Python evaluates default values once at def time, sharing them across calls.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Python evaluates default-argument values exactly once, at function-def time. Mutable defaults (`[]`, `{}`, `set()`) are shared across every invocation — appending to a default list mutates state visible to the next caller. Use `def f(x=None): if x is None: x = []` instead.",
		fn: checkPyMutableDefaultArg,
		resultsPropName: "pyMutableDefaultArg",
		content_keywords: ["def "],
	},
	// ---- Plan 04 D.1 backlog (17 of 20) ----
	{
		id: "ubs_tempfile_mktemp_race",
		phase: "pre_warn",
		name: "Tempfile mktemp Race",
		description:
			"Detects Python `tempfile.mktemp(...)` — TOCTOU race; an attacker can substitute a symlink between the name return and open.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"`tempfile.mktemp()` only generates a name — the caller has to open the file separately, leaving a window where an attacker can substitute a symlink. Use `tempfile.NamedTemporaryFile()` / `tempfile.mkstemp()` which atomically open the file with O_EXCL.",
		fn: checkTempfileMktempRace,
		resultsPropName: "tempfileMktempRace",
		content_keywords: ["mktemp", "tempfile.mktemp"],
	},
	{
		id: "ubs_pickle_untrusted_load",
		phase: "pre_warn",
		name: "Pickle Untrusted Load",
		description:
			"Detects Python `pickle.load(...)` / `pickle.loads(...)` / `cPickle` — unpickling attacker-controlled bytes executes arbitrary `__reduce__` code.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"`pickle.load`/`loads` is effectively `eval` for bytes — a crafted pickle can run any Python code via `__reduce__`. For data interchange use JSON / msgpack; if you must use pickle, sign the payload (HMAC) and verify before unpickling, and only ever unpickle bytes you produced yourself.",
		fn: checkPickleUntrustedLoad,
		resultsPropName: "pickleUntrustedLoad",
		content_keywords: ["pickle.load", "pickle.loads", "cPickle"],
	},
	{
		id: "ubs_xml_external_entity",
		phase: "pre_warn",
		name: "XML External Entity",
		description:
			"Detects `xml.etree` / `xml.dom` / `xml.sax` / `lxml` imports without `defusedxml` — XXE attacks read arbitrary files / cause DoS via billion-laughs.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"Python's stdlib XML parsers do NOT disable external-entity resolution by default — XXE attacks can exfiltrate `/etc/passwd` or cause DoS via billion-laughs expansion. Use `defusedxml` (which mirrors the same APIs but with safe defaults) instead of `xml.etree` / `xml.dom` / `xml.sax` / `lxml`.",
		fn: checkXmlExternalEntity,
		resultsPropName: "xmlExternalEntity",
		content_keywords: ["etree", "xml.dom", "xml.sax"],
	},
	{
		id: "ubs_os_system_tainted",
		phase: "pre_warn",
		name: "os.system / os.popen with tainted input",
		description:
			"Detects Python `os.system(name)` / `os.popen(name)` invoked with a non-literal first argument — command-injection vector.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"`os.system` / `os.popen` always go through `/bin/sh`, so any non-literal argument is a command-injection vector. Use `subprocess.run([\"cmd\", \"arg\"])` (list form) so the shell is bypassed, or shell-quote with `shlex.quote(...)` if a shell really is needed.",
		fn: checkOsSystemTainted,
		resultsPropName: "osSystemTainted",
		content_keywords: ["os.system", "os.popen"],
	},
	{
		id: "ubs_unsafe_format_string",
		phase: "pre_warn",
		name: "Unsafe Format String",
		description:
			"Detects C/C++ `printf` / `sprintf` / `fprintf` with a non-literal format argument — `%n` writes arbitrary memory; `%x` leaks stack.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"A user-controlled format string can leak stack memory (`%x`) or write arbitrary bytes (`%n`). Always pass a literal format spec and route the variable into the value position: `printf(\"%s\", input)`, never `printf(input)`.",
		fn: checkUnsafeFormatString,
		resultsPropName: "unsafeFormatString",
		content_keywords: ["printf(", "sprintf(", "fprintf("],
	},
	{
		id: "ubs_unchecked_redirect",
		phase: "pre_warn",
		name: "Unchecked Redirect",
		description:
			"Detects JS/TS `redirect(url)` / `location.href = url` / `window.location = url` with a non-literal URL — open-redirect vector.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"Open-redirect bugs let attackers craft links that go through your domain before bouncing to a phishing site. Validate the redirect target against an allowlist or ensure it's a relative path (`url.startsWith('/')`) before redirecting.",
		fn: checkUncheckedRedirect,
		resultsPropName: "uncheckedRedirect",
		content_keywords: ["redirect(", "location.href"],
	},
	{
		id: "ubs_goroutine_no_waitgroup",
		phase: "post",
		name: "Goroutine without WaitGroup",
		description:
			"Detects Go `go func()` started without an accompanying `wg.Add` / `wg.Done` / errgroup — fire-and-forget leak risk.",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"A bare `go func() { ... }()` leaks if the caller exits before the goroutine completes — work is silently dropped. Pair with `sync.WaitGroup` / `errgroup.Group`, or pass a context the goroutine respects so the lifetime is explicit.",
		fn: checkGoroutineNoWaitgroup,
		resultsPropName: "goroutineNoWaitgroup",
		content_keywords: ["go func", "goroutine"],
	},
	{
		id: "ubs_defer_in_loop",
		phase: "post",
		name: "Defer in Loop",
		description:
			"Detects Go `defer` inside a `for` loop — defers run at function return, accumulating resources across iterations.",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Go `defer` runs at FUNCTION return, not loop iteration. `for { f, _ := os.Open(...); defer f.Close() }` accumulates open file handles across every iteration. Wrap the loop body in a closure or a helper function, or close the handle inline before the next iteration.",
		fn: checkDeferInLoop,
		resultsPropName: "deferInLoop",
		content_keywords: ["defer ", "for "],
	},
	{
		id: "ubs_string_concat_in_loop",
		phase: "post",
		name: "String Concat in Loop",
		description:
			"Detects `result += chunk` inside a loop in immutable-string languages (Python, Java, JS, Go) — O(n²).",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"`s += chunk` in a loop is O(n²) in Python / Java / JS / Go because each `+=` allocates a new string. Use a `list.append` + `''.join` (Python), `StringBuilder` (Java), `[].push` + `.join('')` (JS), or `strings.Builder` (Go).",
		fn: checkUbsStringConcatInLoop,
		resultsPropName: "ubsStringConcatInLoop",
	},
	{
		id: "ubs_numeric_comparison_chain",
		phase: "post",
		name: "Numeric Comparison Chain",
		description:
			"Detects 3+ consecutive `instanceof` / `compareTo` lines in Java — typically missing polymorphism.",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"A chain of `if (x instanceof A)` / `if (x instanceof B)` is a sign of missing polymorphism. Move the per-type behavior onto the types themselves and call a virtual method, or use a `switch` on a sealed/enum discriminant.",
		fn: checkNumericComparisonChain,
		resultsPropName: "numericComparisonChain",
		content_keywords: ["instanceof", "compareTo"],
	},
	{
		id: "ubs_print_debug_leak",
		phase: "post",
		name: "Print Debug Leak",
		description:
			"Detects `console.log` / Python `print(...)` / Go `fmt.Println` left in non-test, non-CLI code — typically forgotten debug breadcrumbs.",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"`console.log` / `print` / `fmt.Println` left in library code is almost always a forgotten debug print. Use a structured logger (with a level) so the noise can be filtered, or remove the line if it was just a breadcrumb.",
		fn: checkPrintDebugLeak,
		resultsPropName: "printDebugLeak",
		content_keywords: ["console.log", "print(", "fmt.Println"],
	},
	{
		id: "ubs_hardcoded_localhost",
		phase: "post",
		name: "Hardcoded Localhost",
		description:
			"Detects `localhost` / `127.0.0.1` baked into source outside of test/config/example files.",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"`localhost` / `127.0.0.1` baked into production source breaks in deploy and is a frequent dev-default leak. Read it from an env var (`process.env.API_URL`) or a config file, with a clear default for local dev.",
		fn: checkUbsHardcodedLocalhost,
		resultsPropName: "ubsHardcodedLocalhost",
		content_keywords: ["localhost", "127.0.0.1"],
	},
	{
		id: "ubs_magic_number_no_const",
		phase: "post",
		name: "Magic Number No Const",
		description:
			"Detects 3+ digit numeric literals in expression context (not initializer) — magic numbers without a named constant.",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"`setTimeout(fn, 5000)` tells nobody what `5000` represents. Hoist into a named constant (`const RETRY_DELAY_MS = 5000`) so cold readers see intent without grepping for the value.",
		fn: checkMagicNumberNoConst,
		resultsPropName: "magicNumberNoConst",
	},
	{
		id: "ubs_large_function",
		phase: "post",
		name: "Large Function",
		description:
			"Detects a single function spanning 80+ body lines — review/refactor candidate.",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Functions over ~80 lines stretch the cold-reader's working memory. Extract internal stages (parse / validate / dispatch / serialize) into helpers with names that explain what each stage does.",
		fn: checkLargeFunction,
		resultsPropName: "largeFunction",
	},
	{
		id: "ubs_deeply_nested_callback",
		phase: "post",
		name: "Deeply Nested Callback",
		description:
			"Detects 4+ levels of nested function/arrow callbacks — callback-hell smell.",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Nesting 4+ callbacks deep is callback hell. Refactor with `async`/`await`, `Promise.all`, or extract each level into a named function so the structure is grep-able and the failure modes are isolatable.",
		fn: checkDeeplyNestedCallback,
		resultsPropName: "deeplyNestedCallback",
		content_keywords: ["function", "=>"],
	},
	{
		id: "ubs_time_format_locale_dep",
		phase: "post",
		name: "Time Format Locale Dependent",
		description:
			"Detects JS `toLocaleString()` / Java `DateTimeFormatter.ofLocalized*` without an explicit locale — formatting drifts by environment.",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"`date.toLocaleString()` (no args) or Java `DateTimeFormatter.ofLocalized*` (no `withLocale`) produces different strings depending on the JVM/Node locale. Pass an explicit locale (`'en-US'`) or use a fixed pattern (ISO-8601) when serializing for storage / wire formats.",
		fn: checkTimeFormatLocaleDep,
		resultsPropName: "timeFormatLocaleDep",
		content_keywords: ["toLocaleString", "DateTimeFormatter"],
	},
	{
		id: "ubs_regex_in_loop_no_compile",
		phase: "post",
		name: "Regex in Loop No Compile",
		description:
			"Detects Python `re.match` / `re.search` / `re.sub` inside a loop without `re.compile` — recompiles per iteration.",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Calling `re.match(pattern, ...)` inside a loop recompiles `pattern` on every iteration. Hoist `re.compile(pattern)` outside the loop and call `pattern.match(...)` per iteration — Python caches compilations but the cache lookup itself is overhead.",
		fn: checkRegexInLoopNoCompile,
		resultsPropName: "regexInLoopNoCompile",
		content_keywords: ["re.match", "re.search", "re.compile"],
	},
];
