// Warnings and project-specific rules: mix of pre_warn (fully-deterministic
// or low-FP) and post (heuristic) phases. Two severity=error entries
// (focused_tests, migration_ordering) live here because they sit alongside
// related project rules rather than the pure correctness checks in
// entries-errors.ts.

import {
	checkAccumulatingSpread,
	checkAsyncEventHandler,
	checkBooleanTrap,
	checkBroadObjectTypes,
	checkCatchAndLog,
	checkCircularImports,
	checkConstantCondition,
	checkDeadExports,
	checkDefaultExport,
	checkDirectDomAccess,
	checkDisabledTests,
	checkExcessiveUseEffect,
	checkExcessiveUseState,
	checkExtraneousDependencies,
	checkFloatingPromises,
	checkFocusedTests,
	checkHardcodedTimeout,
	checkIndexAsKey,
	checkInlineObjectProps,
	checkJsonParseUnsafe,
	checkLifecycleCleanup,
	checkMagicLiteralInConditional,
	checkMigrationOrdering,
	checkMissingEffectCleanup,
	checkNestedTernaries,
	checkNonNullAssertions,
	checkNumberPrecisionLoss,
	checkOverMocking,
	checkRequireAwait,
	checkSequentialAwaits,
	checkSnapshotOveruse,
	checkSqlSchemaConsistency,
	checkTargetBlankNoRel,
	checkTestImportingTest,
	checkUnvalidatedJsonBoundary,
	checkVisibilityFilterMissing,
} from "../generic-checks.js";
import type { CheckRegistration } from "./types.js";

export const WARNING_ENTRIES: CheckRegistration[] = [
	{
		id: "default_export",
		phase: "post",
		name: "Default Export Hygiene",
		description:
			"Flags anonymous default exports or default exports whose symbol name does not match the filename — grep-hostile for cold readers",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Prefer a named export: `export function Foo() {}` + `import { Foo } from './foo'`. If you must use a default export (framework convention), give the symbol a name that matches the filename so grep and rename tools work: `export default function Foo() {}` in foo.ts. Anonymous `export default (...) => ...` is the worst case — rename to a named function.",
		fn: checkDefaultExport,
		resultsPropName: "defaultExport",
	},
	{
		id: "lifecycle_cleanup",
		phase: "post",
		name: "Lifecycle Cleanup",
		description:
			"Detects classes with a lifecycle method (dispose/destroy/close/unmount/stop) that register setInterval / setTimeout / addEventListener without the paired cleanup in the lifecycle body",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Store the handle returned by setInterval/setTimeout (or the listener function you passed to addEventListener) and pair it with clearInterval/clearTimeout/removeEventListener inside the lifecycle method. Otherwise the subscription outlives the class — a memory leak plus work that keeps happening after dispose.",
		fn: checkLifecycleCleanup,
		resultsPropName: "lifecycleCleanup",
	},
	{
		id: "circular_imports",
		phase: "post",
		name: "Circular Imports",
		description:
			"Detects import cycles involving the edited file (A → B → C → A) — unclear module boundaries that can cause runtime undefined-at-import-time bugs",
		tier: 3,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Break the cycle by moving shared types/constants to a third module that both sides depend on, or by flipping one edge to a type-only import (if it's only used in type positions). Cycles cause hard-to-debug `undefined` values at runtime because ES modules initialize one side before the other completes.",
		fn: (content, filePath) => checkCircularImports(content, filePath, process.cwd()),
		resultsPropName: "circularImports",
	},
	{
		id: "dead_exports",
		phase: "post",
		name: "Dead Exports",
		description:
			"Detects named exports that no other file in the project imports — inflates the apparent public surface for cold readers",
		tier: 3,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Either remove the unused export (so the public surface reflects what's actually consumed) or leave a comment explaining that it's deliberately part of the public API for external consumers. Cold readers — including agents — waste time trying to understand handles that nothing actually uses.",
		fn: (content, filePath) => checkDeadExports(content, filePath, process.cwd()),
		resultsPropName: "deadExports",
	},
	{
		id: "unvalidated_json_boundary",
		phase: "post",
		name: "Unvalidated JSON Boundary",
		description:
			"Detects `JSON.parse(...)` / `await <x>.json()` results that reach property access without passing through a schema parser (zod, valibot, ajv, yup, io-ts, arktype)",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Pipe the parsed value through a schema parser before using it: `const parsed = MySchema.parse(JSON.parse(raw));`. This gives you both a runtime validation error on malformed input AND a typed value downstream — cold readers see `parsed.field` and know the shape is guaranteed, not just a hope.",
		fn: checkUnvalidatedJsonBoundary,
		resultsPropName: "unvalidatedJsonBoundary",
	},
	{
		id: "magic_literal_in_conditional",
		phase: "post",
		name: "Magic Literal in Conditional",
		description:
			"Detects if/switch branches that compare against a bare numeric or string literal instead of a named constant — cold readers can't tell what the branch means",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Extract the literal into a named constant or enum so the conditional reads as intent. `if (status === ORDER_FULFILLED)` tells a cold reader what branch they're in; `if (status === 2)` forces them to grep for where 2 is defined.",
		fn: checkMagicLiteralInConditional,
		resultsPropName: "magicLiteralInConditional",
	},
	{
		id: "boolean_trap",
		phase: "post",
		name: "Boolean Trap",
		description:
			"Detects function calls with 2+ boolean literal arguments — the reader can't tell what each bool means without jumping to the definition",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Replace positional booleans with an options object so the intent is visible at the call site: `createUser('alice', { admin: true, verified: false })` instead of `createUser('alice', true, false)`. Alternatively, use an enum when the booleans represent a discrete mode.",
		fn: checkBooleanTrap,
		resultsPropName: "booleanTrap",
	},
	{
		id: "broad_object_types",
		phase: "pre_warn",
		name: "Broad Object Types",
		description:
			"Detects Record<K, any>, index signatures to any, and bare Function/object type annotations that hide shape information",
		tier: 1,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This type hides the shape of the value. Replace `Record<K, any>` / `{ [k: string]: any }` with a specific interface or typed map (e.g., `Record<UserId, UserProfile>`). Replace bare `Function` with a specific signature (`(x: number) => string`). Replace bare `object` with the actual object shape. Cold readers can't know what's expected otherwise.",
		fn: checkBroadObjectTypes,
		resultsPropName: "broadObjectTypes",
	},
	{
		id: "floating_promises",
		phase: "pre_warn",
		name: "Floating Promises",
		description:
			"Detects calls to async-declared functions (or fetch) at statement position without await, return, void, assignment, or .catch()/.finally() handling",
		tier: 1,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"An async function's return value is being ignored at statement position. Unhandled rejections silently fail and trigger `unhandledRejection` warnings. Add `await` if the caller is async, `return` if the caller propagates, or `.catch(err => ...)` to explicitly handle the rejection. Only use `void foo()` when fire-and-forget is intentional and documented.",
		fn: checkFloatingPromises,
		resultsPropName: "floatingPromises",
	},
	{
		id: "extraneous_deps",
		phase: "pre_warn",
		name: "Extraneous Dependencies",
		description: "Detects imported packages not in package.json",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This import references a package not listed in package.json. Run `npm install <package>` or remove the import.",
		fn: checkExtraneousDependencies,
		resultsPropName: "extraneousDeps",
	},
	{
		id: "non_null_assertion",
		phase: "post",
		name: "Non-Null Assertion",
		description: "Detects TypeScript non-null assertions (!)",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Avoid the non-null assertion operator (!). Use optional chaining (?.), nullish coalescing (??), or add a proper null check instead.",
		fn: checkNonNullAssertions,
		resultsPropName: "nonNullAssertions",
	},
	{
		id: "constant_condition",
		phase: "post",
		name: "Constant Condition",
		description: "Detects always-true/false conditions",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This condition is always true or always false. Remove the dead branch or fix the logic.",
		fn: checkConstantCondition,
		resultsPropName: "constantCondition",
	},
	{
		id: "number_precision_loss",
		phase: "pre_warn",
		name: "Number Precision Loss",
		description: "Detects integer literals beyond safe precision",
		tier: 2,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This integer exceeds Number.MAX_SAFE_INTEGER (2^53-1) and will lose precision. Use BigInt (append 'n') for large integers.",
		fn: checkNumberPrecisionLoss,
		resultsPropName: "numberPrecisionLoss",
	},
	{
		id: "require_await",
		phase: "post",
		name: "Require Await",
		description: "Detects async functions without await",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This async function never uses await. Remove the async keyword — it unnecessarily wraps the return value in a Promise and misleads callers about the function's behavior.",
		fn: checkRequireAwait,
		resultsPropName: "requireAwait",
	},
	{
		id: "accumulating_spread",
		phase: "post",
		name: "Accumulating Spread",
		description: "Detects spread operator in reduce (O(n^2))",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Spreading the accumulator in .reduce() creates a new copy on every iteration (O(n²)). Use a for loop with mutation, Object.fromEntries(), or Map instead.",
		fn: checkAccumulatingSpread,
		resultsPropName: "accumulatingSpread",
	},
	{
		id: "excessive_use_state",
		phase: "post",
		name: "Excessive useState",
		description: "Detects components with too many useState hooks",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Too many useState hooks in one component. Consider useReducer or extracting state into a custom hook.",
		fn: checkExcessiveUseState,
		resultsPropName: "excessiveUseState",
	},
	{
		id: "direct_dom_access",
		phase: "post",
		name: "Direct DOM Access",
		description: "Detects direct DOM manipulation in React components",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Avoid direct DOM access in React components. Use refs (useRef) or state-driven rendering.",
		fn: checkDirectDomAccess,
		resultsPropName: "directDomAccess",
	},
	{
		id: "inline_object_props",
		phase: "post",
		name: "Inline Object Props",
		description: "Detects inline object/array creation in JSX props",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Move inline object/array props to a const outside the component to prevent unnecessary re-renders.",
		fn: checkInlineObjectProps,
		resultsPropName: "inlineObjectProps",
	},
	{
		id: "async_event_handler",
		phase: "post",
		name: "Async Event Handler",
		description: "Detects async event handlers that may cause unmounted-component issues",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Async event handlers should handle errors internally. Wrap the body in try/catch.",
		fn: checkAsyncEventHandler,
		resultsPropName: "asyncEventHandler",
	},
	{
		id: "nested_ternaries",
		phase: "post",
		name: "Nested Ternaries",
		description: "Detects nested ternary expressions",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Nested ternaries hurt readability. Use if/else blocks or extract to a helper function.",
		fn: checkNestedTernaries,
		resultsPropName: "nestedTernaries",
	},
	{
		id: "catch_and_log",
		phase: "post",
		name: "Catch and Log",
		description: "Detects catch blocks that only log and rethrow",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Catching and only logging an error swallows it. Re-throw, return an error value, or add explicit recovery logic.",
		fn: checkCatchAndLog,
		resultsPropName: "catchAndLog",
	},
	{
		id: "json_parse_unsafe",
		phase: "post",
		name: "JSON Parse Unsafe",
		description: "Detects JSON.parse without try/catch",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction: "Wrap JSON.parse() in a try/catch to handle malformed input gracefully.",
		fn: checkJsonParseUnsafe,
		resultsPropName: "jsonParseUnsafe",
	},
	{
		id: "hardcoded_timeout",
		phase: "post",
		name: "Hardcoded Timeout",
		description: "Detects magic number timeouts (setTimeout/setInterval)",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Extract magic timeout numbers into named constants (e.g., const POLL_INTERVAL_MS = 5000).",
		fn: checkHardcodedTimeout,
		resultsPropName: "hardcodedTimeout",
	},
	{
		id: "disabled_tests",
		phase: "pre_warn",
		name: "Disabled Tests",
		description: "Detects skipped tests (it.skip, xit, xdescribe)",
		tier: 2,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Remove it.skip/xit/xdescribe markers. Disabled tests become stale and mask regressions.",
		fn: checkDisabledTests,
		resultsPropName: "disabledTests",
	},
	{
		id: "target_blank_no_rel",
		phase: "pre_warn",
		name: "Target Blank No Rel",
		description: 'Detects target="_blank" without rel="noopener"',
		tier: 2,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			'Add rel="noopener noreferrer" to links with target="_blank" to prevent reverse tabnapping.',
		fn: checkTargetBlankNoRel,
		resultsPropName: "targetBlankNoRel",
	},
	{
		id: "snapshot_overuse",
		phase: "pre_warn",
		name: "Snapshot Overuse",
		description: "Detects excessive snapshot testing",
		tier: 2,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Too many snapshot tests. Use targeted assertions (expect specific props, text content) instead of snapshots.",
		fn: checkSnapshotOveruse,
		resultsPropName: "snapshotOveruse",
	},
	{
		id: "test_importing_test",
		phase: "pre_warn",
		name: "Test Importing Test",
		description: "Detects test files importing from other test files",
		tier: 2,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Tests should not import from other test files. Extract shared test utilities to a separate helpers file.",
		fn: checkTestImportingTest,
		resultsPropName: "testImportingTest",
	},
	{
		id: "excessive_use_effect",
		phase: "post",
		name: "Excessive useEffect",
		description: "Detects components with too many useEffect hooks",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Too many useEffect hooks. Combine related effects or extract into custom hooks.",
		fn: checkExcessiveUseEffect,
		resultsPropName: "excessiveUseEffect",
	},
	{
		id: "sequential_awaits",
		phase: "post",
		name: "Sequential Awaits",
		description: "Detects sequential await calls that could be parallelized",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"These awaits can run in parallel. Use Promise.all([...]) for independent async operations.",
		fn: checkSequentialAwaits,
		resultsPropName: "sequentialAwaits",
	},
	{
		id: "index_as_key",
		phase: "post",
		name: "Index as Key",
		description: "Detects array index used as React key prop",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Use a stable, unique identifier as key instead of array index. Index keys cause incorrect rendering when items are reordered.",
		fn: checkIndexAsKey,
		resultsPropName: "indexAsKey",
	},
	{
		id: "missing_effect_cleanup",
		phase: "post",
		name: "Missing Effect Cleanup",
		description: "Detects useEffect with subscriptions but no cleanup",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This useEffect adds a subscription but returns no cleanup function. Return a cleanup to prevent memory leaks.",
		fn: checkMissingEffectCleanup,
		resultsPropName: "missingEffectCleanup",
	},
	{
		id: "over_mocking",
		phase: "post",
		name: "Over-Mocking",
		description: "Detects excessive mocking in test files",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This test file has extensive mocking. Consider testing with real implementations where possible, or restructure to reduce mock surface.",
		fn: checkOverMocking,
		resultsPropName: "overMocking",
	},
	{
		id: "focused_tests",
		phase: "pre_block",
		name: "Focused Tests",
		description: "Detects shipped focus markers (.only, fit, fdescribe)",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"Remove .only / fit / fdescribe markers — focused tests cause CI to silently skip the rest of the suite.",
		fn: checkFocusedTests,
		resultsPropName: "focusedTests",
	},
	{
		id: "migration_ordering",
		phase: "pre_block",
		name: "Migration Ordering",
		description: "Detects CREATE INDEX on a column not in the same-block CREATE TABLE",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"Add the column via addColumnIfNotExists() FIRST, then run CREATE INDEX in a SEPARATE sql.exec() call. CREATE TABLE IF NOT EXISTS is a no-op for existing tables, so any column added later won't be present when CREATE INDEX runs in the same block.",
		fn: checkMigrationOrdering,
		resultsPropName: "migrationOrdering",
	},
	{
		id: "sql_schema_consistency",
		phase: "pre_warn",
		name: "SQL Schema Consistency",
		description: "Detects SQL queries referencing columns not declared in same-file schema",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This SQL query references a column not declared in any CREATE TABLE or addColumnIfNotExists() call in the same file. Either add it to the schema, or move the query to a file that has access to the correct schema.",
		fn: checkSqlSchemaConsistency,
		resultsPropName: "sqlSchemaConsistency",
	},
	{
		id: "visibility_filter_missing",
		phase: "pre_warn",
		name: "Visibility Filter Missing",
		description: "Detects soft-delete table queries without an archived_at/deleted_at filter",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This query targets a table with a soft-delete column (archived_at / deleted_at / is_archived / is_deleted) but does not filter on it. Add the filter — list/count queries diverging from this contract is a known regression source. If you intentionally want all rows including archived ones, add a WHERE/AND clause that explicitly references the soft-delete column.",
		fn: checkVisibilityFilterMissing,
		resultsPropName: "visibilityFilterMissing",
	},
];
