// Warnings and project-specific rules: mix of pre_warn (fully-deterministic
// or low-FP) and post (heuristic) phases. Two severity=error entries
// (focused_tests, migration_ordering) live here because they sit alongside
// related project rules rather than the pure correctness checks in
// entries-errors.ts.

import {
	checkCommentClaimsIdempotentMutates,
	checkCommentClaimsLimitNoGuard,
	checkCommentClaimsNullThrowsInstead,
	checkCommentClaimsThrowsDoesnt,
	checkCommentClaimsValidationMissing,
} from "../checks/comment-drift.js";
import {
	checkAccumulatingSpread,
	checkAgentThumbprintProse,
	checkAsyncEventHandler,
	checkAwaitStateToctou,
	checkBoundaryCopyNoRevalidation,
	checkCleanupReentrancy,
	checkBooleanTrap,
	checkBroadObjectTypes,
	checkCatchAndLog,
	checkCircularImports,
	checkCleanupSkippedOnEarlyExit,
	checkConstantCondition,
	checkDeadBranchLiteral,
	checkDeadExports,
	checkDemoDataUnmarked,
	checkDemoRuntimeMissingBanner,
	checkDuplicateTestNames,
	checkEmptyBodyHandler,
	checkDeeplyNestedCallback,
	checkDefaultExport,
	checkDeferInLoop,
	checkDirectDomAccess,
	checkDisabledTests,
	checkDivisionByVariable,
	checkDoubleCastUnknown,
	checkExcessiveUseEffect,
	checkExcessiveUseState,
	checkExtraneousDependencies,
	checkFetchWithoutTimeout,
	checkFileLevelSuppression,
	checkHardcodedTimeoutInTests,
	checkFloatEquality,
	checkFloatingPromises,
	checkFocusedTests,
	checkGoroutineNoWaitgroup,
	checkHardcodedTimeout,
	checkIndexAsKey,
	checkFreshCollectionKeyLookup,
	checkIndexBoundsUnchecked,
	checkInlineObjectProps,
	checkIteratorInvalidation,
	checkJavaOptionalGet,
	checkJsLooseEquality,
	checkJsonParseUnsafe,
	checkLargeFunction,
	checkListenerPairing,
	checkMigrationParity,
	checkLifecycleCleanup,
	checkLossyErrorRethrow,
	checkMagicLiteralInConditional,
	checkMagicNumberNoConst,
	checkMigrationOrdering,
	checkMissingEffectCleanup,
	checkMockingTheSutSelf,
	checkNestedTernaries,
	checkNodeEnvBranchInProd,
	checkNonNullAssertions,
	checkNumberPrecisionLoss,
	checkNumericComparisonChain,
	checkEvalInputTainted,
	checkOsSystemTainted,
	checkOverMocking,
	checkPackageJsonScriptPaths,
	checkPickleUntrustedLoad,
	checkPrintDebugLeak,
	checkPyMutableDefaultArg,
	checkRealIoInTests,
	checkRegexInLoopNoCompile,
	checkRequireAwait,
	checkSchemaTypeDrift,
	checkSequentialAwaits,
	checkSilentDemoFallback,
	checkSilentPromiseSwallow,
	checkSqlStringConcat,
	checkSnapshotOveruse,
	checkSqlSchemaConsistency,
	checkStubNotImplementedThrow,
	checkTaintedToPrivilegedSink,
	checkSyncIoOnHotPath,
	checkTargetBlankNoRel,
	checkTempfileMktempRace,
	checkTestImportingTest,
	checkTestMissingSutImport,
	checkTestNondeterminism,
	checkTimeFormatLocaleDep,
	checkUbsStringConcatInLoop,
	checkUnboundedPromiseAll,
	checkUncheckedRedirect,
	checkUnionWidenedWithString,
	checkUnsafeFormatString,
	checkUntestableTimeInSource,
	checkUnvalidatedJsonBoundary,
	checkVisibilityFilterMissing,
	checkXmlExternalEntity,
} from "../generic-checks.js";
import type { CheckRegistration } from "./types.js";

export const WARNING_ENTRIES: CheckRegistration[] = [
	{
		id: "default_export",
		phase: "post",
		name: "Default Export Hygiene",
		description:
			"Flags anonymous default exports or default exports whose symbol name does not match the filename — grep-hostile for cold readers",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Prefer a named export: `export function Foo() {}` + `import { Foo } from './foo'`. If you must use a default export (framework convention), give the symbol a name that matches the filename so grep and rename tools work: `export default function Foo() {}` in foo.ts. Anonymous `export default (...) => ...` is the worst case — rename to a named function.",
		fn: checkDefaultExport,
		resultsPropName: "defaultExport",
	},
	{
		id: "lifecycle_cleanup",
		phase: "post",
		name: "Lifecycle Cleanup",
		description:
			"Detects classes with a lifecycle method (dispose/destroy/close/unmount/stop) that register setInterval / setTimeout / addEventListener without the paired cleanup in the lifecycle body",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Store the handle returned by setInterval/setTimeout (or the listener function you passed to addEventListener) and pair it with clearInterval/clearTimeout/removeEventListener inside the lifecycle method. Otherwise the subscription outlives the class — a memory leak plus work that keeps happening after dispose.",
		fn: checkLifecycleCleanup,
		resultsPropName: "lifecycleCleanup",
	},
	{
		id: "circular_imports",
		phase: "post",
		name: "Circular Imports",
		description:
			"Detects import cycles involving the edited file (A → B → C → A) — unclear module boundaries that can cause runtime undefined-at-import-time bugs",
		tier: 3,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Break the cycle by moving shared types/constants to a third module that both sides depend on, or by flipping one edge to a type-only import (if it's only used in type positions). Cycles cause hard-to-debug `undefined` values at runtime because ES modules initialize one side before the other completes.",
		fn: (content, filePath) => checkCircularImports(content, filePath, process.cwd()),
		resultsPropName: "circularImports",
	},
	{
		id: "dead_exports",
		phase: "post",
		name: "Dead Exports",
		description:
			"Detects named exports that no other file in the project imports — inflates the apparent public surface for cold readers",
		tier: 3,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Either remove the unused export (so the public surface reflects what's actually consumed) or leave a comment explaining that it's deliberately part of the public API for external consumers. Cold readers — including agents — waste time trying to understand handles that nothing actually uses.",
		fn: (content, filePath) => checkDeadExports(content, filePath, process.cwd()),
		resultsPropName: "deadExports",
	},
	{
		id: "unvalidated_json_boundary",
		phase: "post",
		name: "Unvalidated JSON Boundary",
		description:
			"Detects `JSON.parse(...)` / `await <x>.json()` results that reach property access without passing through a schema parser (zod, valibot, ajv, yup, io-ts, arktype)",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Pipe the parsed value through a schema parser before using it: `const parsed = MySchema.parse(JSON.parse(raw));`. This gives you both a runtime validation error on malformed input AND a typed value downstream — cold readers see `parsed.field` and know the shape is guaranteed, not just a hope.",
		fn: checkUnvalidatedJsonBoundary,
		resultsPropName: "unvalidatedJsonBoundary",
	},
	{
		id: "magic_literal_in_conditional",
		phase: "post",
		name: "Magic Literal in Conditional",
		description:
			"Detects if/switch branches that compare against a bare numeric or string literal instead of a named constant — cold readers can't tell what the branch means",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Extract the literal into a named constant or enum so the conditional reads as intent. `if (status === ORDER_FULFILLED)` tells a cold reader what branch they're in; `if (status === 2)` forces them to grep for where 2 is defined.",
		fn: checkMagicLiteralInConditional,
		resultsPropName: "magicLiteralInConditional",
	},
	{
		id: "iterator_invalidation",
		phase: "post",
		name: "Iterator Invalidation",
		description:
			"Detects mutating an array, Map, or Set inside iteration over the same collection (push/splice/delete/clear/set/add inside for-of, for-in, forEach, or other iteration callbacks)",
		tier: 1,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Mutating the same collection you're iterating leads to skipped elements, double-visits, or in C++ analogs (Firefox bug 2025977) freed-backing-store UAFs. Either snapshot first (`for (const x of [...items]) { items.delete(x); }`), build a deletion list and apply it after the loop, or switch to a primitive that documents safe-during-iteration semantics (e.g. `filter` returning a new array).",
		fn: checkIteratorInvalidation,
		resultsPropName: "iteratorInvalidation",
	},
	{
		id: "fresh_collection_key_lookup",
		phase: "post",
		name: "Fresh Collection Key Lookup",
		description:
			"Detects Map/Set .set/.get/.has/.add called with a fresh-identity value (NaN, empty/spread object literal, fresh Symbol, fresh `new` instance) — the lookup is a guaranteed miss because identity differs from any previously inserted key",
		tier: 1,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"`new Map().set({}, 1).get({})` returns `undefined` — the two `{}` literals have different identities. Use a stable key: a primitive (string/number, with NaN explicitly excluded), a value held in a variable across the set/get pair, or a WeakMap keyed on the stable object reference itself.",
		fn: checkFreshCollectionKeyLookup,
		resultsPropName: "freshCollectionKeyLookup",
	},
	{
		id: "await_state_toctou",
		phase: "post",
		name: "Await State TOCTOU",
		description:
			"Detects `if (X.Y) { ... await ...; X.Y.method() }` shapes where the same dotted field is checked before an await and used after, with no re-check between. State may have changed during the await — use the value through the original reference at risk.",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"After the await, re-verify the field exists before using it: `if (state.entry) { await sync(); if (state.entry) state.entry.touch(); }`. Or hoist the value to a local before the await: `const entry = state.entry; if (entry) { await sync(); entry.touch(); }` — the local survives the await regardless of whether `state.entry` was reassigned. Firefox bugs 2021894/2022733 were the C++ analog: IPC race over async boundaries.",
		fn: checkAwaitStateToctou,
		resultsPropName: "awaitStateToctou",
	},
	{
		id: "cleanup_reentrancy",
		phase: "post",
		name: "Cleanup Reentrancy",
		description:
			"Detects dispose/destroy/close/teardown methods that recurse into themselves, or useEffect cleanups that mutate React state — re-entry during teardown can fire another lifecycle event on a partially-destroyed instance",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"For class cleanup: guard recursion with a destroyed-flag (`if (this.destroyed) return; this.destroyed = true; ...`) or restructure so the cleanup is idempotent and only owns its own resources, not delegated re-cleanup. For useEffect: cleanups should release resources, not mutate state — calling setState in a cleanup triggers a render after teardown. Firefox bugs 2024653/2027298 were the C++ analog: UAF via re-entry during actor teardown.",
		fn: checkCleanupReentrancy,
		resultsPropName: "cleanupReentrancy",
	},
	{
		id: "boundary_copy_no_revalidation",
		phase: "post",
		name: "Boundary Copy No Revalidation",
		description:
			"Detects Object.assign / spread copy of external input (req.body|query|params, process.argv|env, JSON.parse output) into a typed slot without passing through a recognized validator first",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Validate before copying: `Object.assign(slot, Schema.parse(req.body))` or `const validated = Schema.parse(req.body); slot = { ...slot, ...validated };`. Without it, the typed slot now holds whatever shape the external input had — TypeScript types lie, runtime shape doesn't match the declared interface, and downstream code crashes on the unexpected shape. Firefox bug 2029813 was the C++ analog: RLBox copy verification gap.",
		fn: checkBoundaryCopyNoRevalidation,
		resultsPropName: "boundaryCopyNoRevalidation",
	},
	{
		id: "tainted_to_privileged_sink",
		phase: "post",
		name: "Tainted to Privileged Sink",
		description:
			"Detects external-input values (req.body|query|params, process.argv|env) reaching a privileged sink (eval, new Function, vm.run*, child_process.exec*, fs.write*) without passing through a recognized validator (zod/.parse, .safeParse, .validate, typeof, instanceof, Array.isArray, allow-list .has)",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Validate the value before it reaches the sink. Preferred: schema-parse it (`const cmd = CmdSchema.parse(req.body.cmd)`). Acceptable: typeof + allow-list (`if (typeof cmd !== 'string' || !ALLOW.has(cmd)) return`). Avoid passing un-narrowed external input to eval / new Function / child_process.exec / vm.run / fs.write — Firefox bug 2023817 was the C++ analog: the parent process trusted sandbox-supplied input that hadn't been re-validated at the trust boundary.",
		fn: checkTaintedToPrivilegedSink,
		resultsPropName: "taintedToPrivilegedSink",
	},
	{
		id: "cleanup_skipped_on_early_exit",
		phase: "post",
		name: "Cleanup Skipped on Early Exit",
		description:
			"Detects setInterval/setTimeout/subscribe/addEventListener acquisitions where a throw or return reaches before the matching release, with no try/finally wrap — the resource leaks on the early-exit path",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Wrap the acquisition + body in `try { ... } finally { <cleanup> }` so the cleanup runs on every exit path including thrown exceptions and early returns. Without it, the throw skips the cleanup, leaking the timer/listener/subscription. Firefox bug 2024653/2027298 — same shape, different language: the `try { ... } finally { ctrl.abort(); ws.close(); }` pattern is the JS-side fix.",
		fn: checkCleanupSkippedOnEarlyExit,
		resultsPropName: "cleanupSkippedOnEarlyExit",
	},
	{
		id: "index_bounds_unchecked",
		phase: "post",
		name: "Index Bounds Unchecked",
		description:
			"Detects external-input numeric values (Number/parseInt/parseFloat applied to req.body|query|params or process.argv|env) reaching an array subscript without a Number.isFinite or length-bound guard between parse and use",
		tier: 1,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Validate the parsed number before indexing: `if (!Number.isFinite(n) || n < 0 || n >= rows.length) return null; return rows[n];`. Without the guard, NaN/Infinity, negatives, or values past the end give `undefined` (or worse: silently match string-keyed properties). Firefox bug 2026305 was a 16-bit field overflow in this shape — same logic, different language.",
		fn: checkIndexBoundsUnchecked,
		resultsPropName: "indexBoundsUnchecked",
	},
	{
		id: "boolean_trap",
		phase: "post",
		name: "Boolean Trap",
		description:
			"Detects function calls with 2+ boolean literal arguments — the reader can't tell what each bool means without jumping to the definition",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Replace positional booleans with an options object so the intent is visible at the call site: `createUser('alice', { admin: true, verified: false })` instead of `createUser('alice', true, false)`. Alternatively, use an enum when the booleans represent a discrete mode.",
		fn: checkBooleanTrap,
		resultsPropName: "booleanTrap",
	},
	{
		id: "broad_object_types",
		phase: "pre_warn",
		name: "Broad Object Types",
		description:
			"Detects Record<K, any>, index signatures to any, and bare Function/object type annotations that hide shape information",
		tier: 1,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This type hides the shape of the value. Replace `Record<K, any>` / `{ [k: string]: any }` with a specific interface or typed map (e.g., `Record<UserId, UserProfile>`). Replace bare `Function` with a specific signature (`(x: number) => string`). Replace bare `object` with the actual object shape. Cold readers can't know what's expected otherwise.",
		fn: checkBroadObjectTypes,
		resultsPropName: "broadObjectTypes",
	},
	// === Comment-vs-behavior drift detectors (Mythos blog adaptation) ===
	// "Spotting contradictions between code comments and actual behavior"
	// was Mythos's strongest signal. Five narrow per-function detectors
	// here; all advisory (heuristic by nature — comments rot independently
	// of code, and the regex shape can't perfectly recognize every guard).
	{
		id: "comment_claims_limit_no_guard",
		phase: "post",
		name: "Comment Claims Limit With No Guard",
		description:
			'Detects functions whose comment says "max N" / "at most N" / "limited to N" but whose body has no `< N` / `<= N` guard for that number.',
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"The comment promises a numeric limit but no guard in the body enforces it. Either remove the limit claim from the comment (if no limit is actually enforced) or add the missing `if (n > N) ...` / `slice(0, N)` / `Math.min(n, N)` guard so the comment and code agree.",
		fn: checkCommentClaimsLimitNoGuard,
		resultsPropName: "commentClaimsLimitNoGuard",
	},
	{
		id: "comment_claims_null_throws_instead",
		phase: "post",
		name: "Comment Claims Null Return But Body Throws",
		description:
			'Detects functions whose comment says "returns null on failure" / "may return undefined" but whose body contains an unhandled `throw`.',
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"The comment promises null/undefined on failure but the body throws. Either wrap the failure path in try/catch and return null, or rewrite the comment to reflect that the function throws. Cold callers will write `if (result === null)` and miss the exception.",
		fn: checkCommentClaimsNullThrowsInstead,
		resultsPropName: "commentClaimsNullThrowsInstead",
	},
	{
		id: "comment_claims_validation_missing",
		phase: "post",
		name: "Comment Claims Validation But No Check Present",
		description:
			'Detects functions whose comment says "validates X" / "sanitizes Y" / "escapes Z" but whose body contains no conditional, regex, or encode call.',
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"The comment claims validation/sanitization/escaping but the body has none — no conditional, regex test, or encode call. Either implement the validation or remove the claim. Cold callers (and downstream agents) will treat the output as safe.",
		fn: checkCommentClaimsValidationMissing,
		resultsPropName: "commentClaimsValidationMissing",
	},
	{
		id: "comment_claims_idempotent_mutates",
		phase: "post",
		name: "Comment Claims Idempotent But Body Mutates",
		description:
			'Detects functions whose comment says "idempotent" but whose body contains an unconditional mutation (++=, push, set, etc.) with no guard.',
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"The comment promises idempotency but the body unconditionally mutates state. Either guard the mutation (`if (!set.has(x)) set.add(x)`) or remove the idempotency claim. Retry-safe callers will assume calling twice is safe and will be wrong.",
		fn: checkCommentClaimsIdempotentMutates,
		resultsPropName: "commentClaimsIdempotentMutates",
	},
	{
		id: "comment_claims_throws_doesnt",
		phase: "post",
		name: "Declared @throws Never Thrown",
		description:
			"Detects JSDoc @throws {ErrorX} declarations where the body never throws that error class.",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"The function declares `@throws {ErrorX}` but never throws `new ErrorX(...)`. Either remove the declaration or add the missing throw. Documented exception contracts that don't match behavior produce useless catch sites downstream.",
		fn: checkCommentClaimsThrowsDoesnt,
		resultsPropName: "commentClaimsThrowsDoesnt",
	},
	{
		id: "floating_promises",
		phase: "pre_warn",
		name: "Floating Promises",
		description:
			"Detects calls to async-declared functions (or fetch) at statement position without await, return, void, assignment, or .catch()/.finally() handling",
		tier: 1,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"An async function's return value is being ignored at statement position. Unhandled rejections silently fail and trigger `unhandledRejection` warnings. Add `await` if the caller is async, `return` if the caller propagates, or `.catch(err => ...)` to explicitly handle the rejection. Only use `void foo()` when fire-and-forget is intentional and documented.",
		fn: checkFloatingPromises,
		resultsPropName: "floatingPromises",
	},
	{
		id: "extraneous_deps",
		phase: "pre_warn",
		name: "Extraneous Dependencies",
		description: "Detects imported packages not in package.json",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This import references a package not listed in package.json. Run `npm install <package>` or remove the import.",
		fn: checkExtraneousDependencies,
		resultsPropName: "extraneousDeps",
	},
	{
		id: "non_null_assertion",
		phase: "post",
		name: "Non-Null Assertion",
		description: "Detects TypeScript non-null assertions (!)",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Avoid the non-null assertion operator (!). Use optional chaining (?.), nullish coalescing (??), or add a proper null check instead.",
		fn: checkNonNullAssertions,
		resultsPropName: "nonNullAssertions",
	},
	{
		id: "constant_condition",
		phase: "post",
		name: "Constant Condition",
		description: "Detects always-true/false conditions",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This condition is always true or always false. Remove the dead branch or fix the logic.",
		fn: checkConstantCondition,
		resultsPropName: "constantCondition",
	},
	{
		id: "number_precision_loss",
		phase: "pre_warn",
		name: "Number Precision Loss",
		description: "Detects integer literals beyond safe precision",
		tier: 2,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This integer exceeds Number.MAX_SAFE_INTEGER (2^53-1) and will lose precision. Use BigInt (append 'n') for large integers.",
		fn: checkNumberPrecisionLoss,
		resultsPropName: "numberPrecisionLoss",
	},
	{
		id: "require_await",
		phase: "post",
		name: "Require Await",
		description: "Detects async functions without await",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This async function never uses await. Remove the async keyword — it unnecessarily wraps the return value in a Promise and misleads callers about the function's behavior.",
		fn: checkRequireAwait,
		resultsPropName: "requireAwait",
	},
	{
		id: "accumulating_spread",
		phase: "post",
		name: "Accumulating Spread",
		description: "Detects spread operator in reduce (O(n^2))",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Spreading the accumulator in .reduce() creates a new copy on every iteration (O(n²)). Use a for loop with mutation, Object.fromEntries(), or Map instead.",
		fn: checkAccumulatingSpread,
		resultsPropName: "accumulatingSpread",
	},
	{
		id: "excessive_use_state",
		phase: "post",
		name: "Excessive useState",
		description: "Detects components with too many useState hooks",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Too many useState hooks in one component. Consider useReducer or extracting state into a custom hook.",
		fn: checkExcessiveUseState,
		resultsPropName: "excessiveUseState",
	},
	{
		id: "direct_dom_access",
		phase: "post",
		name: "Direct DOM Access",
		description: "Detects direct DOM manipulation in React components",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Avoid direct DOM access in React components. Use refs (useRef) or state-driven rendering.",
		fn: checkDirectDomAccess,
		resultsPropName: "directDomAccess",
	},
	{
		id: "inline_object_props",
		phase: "post",
		name: "Inline Object Props",
		description: "Detects inline object/array creation in JSX props",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Move inline object/array props to a const outside the component to prevent unnecessary re-renders.",
		fn: checkInlineObjectProps,
		resultsPropName: "inlineObjectProps",
	},
	{
		id: "async_event_handler",
		phase: "post",
		name: "Async Event Handler",
		description: "Detects async event handlers that may cause unmounted-component issues",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Async event handlers should handle errors internally. Wrap the body in try/catch.",
		fn: checkAsyncEventHandler,
		resultsPropName: "asyncEventHandler",
	},
	{
		id: "nested_ternaries",
		phase: "post",
		name: "Nested Ternaries",
		description: "Detects nested ternary expressions",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Nested ternaries hurt readability. Use if/else blocks or extract to a helper function.",
		fn: checkNestedTernaries,
		resultsPropName: "nestedTernaries",
	},
	{
		id: "catch_and_log",
		phase: "post",
		name: "Catch and Log",
		description: "Detects catch blocks that only log and rethrow",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Catching and only logging an error swallows it. Re-throw, return an error value, or add explicit recovery logic.",
		fn: checkCatchAndLog,
		resultsPropName: "catchAndLog",
	},
	{
		id: "lossy_error_rethrow",
		phase: "post",
		name: "Lossy Error Rethrow",
		description:
			"Detects catch (e) { throw new Error('...') } that constructs a fresh Error without forwarding the caught exception via the ES2022 { cause: e } option — drops the original stack trace and breaks downstream error.cause inspection.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Pass the original error through as the rethrow's cause: `throw new Error('wrapped', { cause: e })`. Without it the caught exception's stack and metadata are silently discarded — debuggers, logs, and any code walking `error.cause` see only the new prose message. If the caught error is genuinely uninteresting, document why with a comment alongside the rethrow.",
		fn: checkLossyErrorRethrow,
		resultsPropName: "lossyErrorRethrow",
		content_keywords: ["catch"],
	},
	{
		id: "silent_promise_catch",
		phase: "post",
		name: "Silent Promise Catch",
		description:
			"Detects .catch(() => {}), .catch(() => undefined), .catch(() => null), and .catch(function () {}) — a swallowed rejection silently masks bugs. The async cousin of bare-catch swallowing; promoted from the heuristic suggestion pipeline because the FP profile is tight (named handler refs, intent comments, and explicit param-ack bodies are exempt).",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"A `.catch(() => {})` swallows the rejection without reading it — anyone debugging a downstream symptom has no thread to pull. Either: (a) handle the error meaningfully (`.catch((e) => log.warn({ err: e }, 'failed'))`), (b) name the handler so its intent is documented (`.catch(reportAndContinue)`), or (c) if you genuinely don't care, leave an inline comment on the same line (`/* fire and forget */`) so the next reader knows the omission was deliberate.",
		fn: checkSilentPromiseSwallow,
		resultsPropName: "silentPromiseSwallow",
		content_keywords: [".catch"],
	},
	{
		id: "json_parse_unsafe",
		phase: "post",
		name: "JSON Parse Unsafe",
		description: "Detects JSON.parse without try/catch",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction: "Wrap JSON.parse() in a try/catch to handle malformed input gracefully.",
		fn: checkJsonParseUnsafe,
		resultsPropName: "jsonParseUnsafe",
	},
	{
		id: "hardcoded_timeout",
		phase: "post",
		name: "Hardcoded Timeout",
		description: "Detects magic number timeouts (setTimeout/setInterval)",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Extract magic timeout numbers into named constants (e.g., const POLL_INTERVAL_MS = 5000).",
		fn: checkHardcodedTimeout,
		resultsPropName: "hardcodedTimeout",
	},
	{
		id: "disabled_tests",
		phase: "pre_warn",
		name: "Disabled Tests",
		description: "Detects skipped tests (it.skip, xit, xdescribe)",
		tier: 2,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Remove it.skip/xit/xdescribe markers. Disabled tests become stale and mask regressions.",
		fn: checkDisabledTests,
		resultsPropName: "disabledTests",
	},
	{
		id: "target_blank_no_rel",
		phase: "pre_warn",
		name: "Target Blank No Rel",
		description: 'Detects target="_blank" without rel="noopener"',
		tier: 2,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			'Add rel="noopener noreferrer" to links with target="_blank" to prevent reverse tabnapping.',
		fn: checkTargetBlankNoRel,
		resultsPropName: "targetBlankNoRel",
	},
	{
		id: "snapshot_overuse",
		phase: "pre_warn",
		name: "Snapshot Overuse",
		description: "Detects excessive snapshot testing",
		tier: 2,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Too many snapshot tests. Use targeted assertions (expect specific props, text content) instead of snapshots.",
		fn: checkSnapshotOveruse,
		resultsPropName: "snapshotOveruse",
	},
	{
		id: "test_importing_test",
		phase: "pre_warn",
		name: "Test Importing Test",
		description: "Detects test files importing from other test files",
		tier: 2,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Tests should not import from other test files. Extract shared test utilities to a separate helpers file.",
		fn: checkTestImportingTest,
		resultsPropName: "testImportingTest",
	},
	{
		id: "excessive_use_effect",
		phase: "post",
		name: "Excessive useEffect",
		description: "Detects components with too many useEffect hooks",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Too many useEffect hooks. Combine related effects or extract into custom hooks.",
		fn: checkExcessiveUseEffect,
		resultsPropName: "excessiveUseEffect",
	},
	{
		id: "sequential_awaits",
		phase: "post",
		name: "Sequential Awaits",
		description: "Detects sequential await calls that could be parallelized",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"These awaits can run in parallel. Use Promise.all([...]) for independent async operations.",
		fn: checkSequentialAwaits,
		resultsPropName: "sequentialAwaits",
	},
	{
		id: "index_as_key",
		phase: "post",
		name: "Index as Key",
		description: "Detects array index used as React key prop",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Use a stable, unique identifier as key instead of array index. Index keys cause incorrect rendering when items are reordered.",
		fn: checkIndexAsKey,
		resultsPropName: "indexAsKey",
	},
	{
		id: "missing_effect_cleanup",
		phase: "post",
		name: "Missing Effect Cleanup",
		description: "Detects useEffect with subscriptions but no cleanup",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This useEffect adds a subscription but returns no cleanup function. Return a cleanup to prevent memory leaks.",
		fn: checkMissingEffectCleanup,
		resultsPropName: "missingEffectCleanup",
	},
	{
		id: "over_mocking",
		phase: "post",
		name: "Over-Mocking",
		description: "Detects excessive mocking in test files",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This test file has extensive mocking. Consider testing with real implementations where possible, or restructure to reduce mock surface.",
		fn: checkOverMocking,
		resultsPropName: "overMocking",
	},
	{
		id: "focused_tests",
		phase: "pre_block",
		name: "Focused Tests",
		description: "Detects shipped focus markers (.only, fit, fdescribe)",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"Remove .only / fit / fdescribe markers — focused tests cause CI to silently skip the rest of the suite.",
		fn: checkFocusedTests,
		resultsPropName: "focusedTests",
	},
	{
		id: "migration_ordering",
		phase: "pre_block",
		name: "Migration Ordering",
		description: "Detects CREATE INDEX on a column not in the same-block CREATE TABLE",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"Add the column via addColumnIfNotExists() FIRST, then run CREATE INDEX in a SEPARATE sql.exec() call. CREATE TABLE IF NOT EXISTS is a no-op for existing tables, so any column added later won't be present when CREATE INDEX runs in the same block.",
		fn: checkMigrationOrdering,
		resultsPropName: "migrationOrdering",
	},
	{
		id: "sql_schema_consistency",
		phase: "pre_warn",
		name: "SQL Schema Consistency",
		description: "Detects SQL queries referencing columns not declared in same-file schema",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This SQL query references a column not declared in any CREATE TABLE or addColumnIfNotExists() call in the same file. Either add it to the schema, or move the query to a file that has access to the correct schema.",
		fn: checkSqlSchemaConsistency,
		resultsPropName: "sqlSchemaConsistency",
	},
	{
		id: "visibility_filter_missing",
		phase: "pre_warn",
		name: "Visibility Filter Missing",
		description: "Detects soft-delete table queries without an archived_at/deleted_at filter",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This query targets a table with a soft-delete column (archived_at / deleted_at / is_archived / is_deleted) but does not filter on it. Add the filter — list/count queries diverging from this contract is a known regression source. If you intentionally want all rows including archived ones, add a WHERE/AND clause that explicitly references the soft-delete column.",
		fn: checkVisibilityFilterMissing,
		resultsPropName: "visibilityFilterMissing",
	},
	// === UBS Plan 04 — rows 27–30 (warning/post tier) ===
	{
		id: "ubs_js_loose_equality",
		phase: "pre_warn",
		name: "UBS JS Loose Equality",
		description:
			"Detects `==` / `!=` in JS/TS files. The triple-equality form (`===` / `!==`) avoids JS type coercion. The `x == null` / `x != null` idiom is allowed (Plan 04 §4.2 documented exception).",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Use `===` / `!==` instead of `==` / `!=`. Loose equality triggers JavaScript type coercion (`'' == 0`, `null == undefined`, `'1' == 1` are all true) and is a documented bug source. The one allowed loose form is `x == null`, which checks both null AND undefined in one expression.",
		fn: checkJsLooseEquality,
		resultsPropName: "jsLooseEquality",
		content_keywords: ["==", "!="],
	},
	{
		id: "ubs_float_equality",
		phase: "pre_warn",
		name: "UBS Float Equality",
		description:
			"Detects `===` / `!==` against a non-IEEE-safe float literal — floating-point representation makes direct comparison unreliable.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Float equality is unreliable due to IEEE 754 representation: `0.1 + 0.2 === 0.3` is false. Compare with an epsilon: `Math.abs(a - b) < 1e-9`. Values exactly representable in binary (0.0, 0.5, 1.0, etc.) are skipped by the detector.",
		fn: checkFloatEquality,
		resultsPropName: "floatEquality",
		content_keywords: ["==", "!="],
	},
	{
		id: "ubs_java_optional_get",
		phase: "post",
		name: "UBS Java Optional.get()",
		description:
			"Detects Java `Optional<T>....get()` without an `isPresent()` / `orElse(...)` guard — NullPointerException risk.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"`Optional.get()` throws `NoSuchElementException` when the optional is empty. Guard with `isPresent()` first, or replace with `orElse(default)` / `orElseGet(() -> ...)` / `orElseThrow(() -> new IllegalStateException(...))`. The whole point of `Optional` is to make absence explicit; `.get()` discards that signal.",
		fn: checkJavaOptionalGet,
		resultsPropName: "javaOptionalGet",
		content_keywords: ["Optional"],
	},
	{
		id: "ubs_division_by_variable",
		phase: "post",
		name: "UBS Division by Variable",
		description:
			"Detects `expr / identifier` — the divisor variable might be zero (advisory; high FP rate, ships in DEFAULT_ADVISORY_SKIPS).",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Division by a variable can throw `Division by zero` (Python) / produce `Infinity` / `NaN` (JS) at runtime. Add an explicit zero-check (`if (divisor === 0) ...`) or assert the precondition before the division. If the divisor is provably non-zero by construction, leave a comment so cold readers don't repeat the analysis.",
		fn: checkDivisionByVariable,
		resultsPropName: "divisionByVariable",
	},
	// ---- Plan 04 D.1 partial — three high-leverage backlog entries. ----
	// `eval_usage` (entries-errors.ts) and `cross-language.ts:checkSqlInjection`
	// already pre_block on broad eval / SQL cases; the two `error`-severity
	// pre_warn entries below specialize on the tainted-input subset (non-
	// literal first arg / template-literal interpolation) and add extra
	// pre-event signal without flipping decision semantics. The third entry
	// is a Python-specific post warning.
	{
		id: "ubs_eval_input_tainted",
		phase: "pre_warn",
		name: "Eval / Function / exec on tainted input",
		description:
			"Detects eval / Function / exec / compile invoked with a non-literal first argument (likely a parameter or external value).",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"Evaluating attacker-controllable input as code is the most direct RCE pattern. If you genuinely need dynamic dispatch, keep the input on a strict allowlist (lookup table → preset function); never pass it to eval / Function / exec / compile.",
		fn: checkEvalInputTainted,
		resultsPropName: "evalInputTainted",
		content_keywords: ["eval", "Function", "exec", "compile"],
	},
	{
		id: "ubs_sql_string_concat",
		phase: "pre_warn",
		name: "SQL string concatenation",
		description:
			"Detects SQL keywords inside a quoted string immediately followed by JS/Py concatenation or template-literal interpolation — the canonical SQL-injection shape.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"Use parameterized queries / prepared statements: `db.query('SELECT * WHERE id = $1', [id])`. Concatenating input into the SQL string is a SQLi vector even on internal queries — values that look safe today get reached by external code paths tomorrow.",
		fn: checkSqlStringConcat,
		resultsPropName: "sqlStringConcat",
		content_keywords: ["SELECT", "INSERT", "UPDATE", "DELETE"],
	},
	{
		id: "ubs_python_mutable_default_arg",
		phase: "post",
		name: "Python mutable default argument",
		description:
			"Detects `def f(x=[])` / `def f(x={})` — Python evaluates default values once at def time, sharing them across calls.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Python evaluates default-argument values exactly once, at function-def time. Mutable defaults (`[]`, `{}`, `set()`) are shared across every invocation — appending to a default list mutates state visible to the next caller. Use `def f(x=None): if x is None: x = []` instead.",
		fn: checkPyMutableDefaultArg,
		resultsPropName: "pyMutableDefaultArg",
		content_keywords: ["def "],
	},
	// ---- Plan 04 D.1 backlog (17 of 20) ----
	{
		id: "ubs_tempfile_mktemp_race",
		phase: "pre_warn",
		name: "Tempfile mktemp Race",
		description:
			"Detects Python `tempfile.mktemp(...)` — TOCTOU race; an attacker can substitute a symlink between the name return and open.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"`tempfile.mktemp()` only generates a name — the caller has to open the file separately, leaving a window where an attacker can substitute a symlink. Use `tempfile.NamedTemporaryFile()` / `tempfile.mkstemp()` which atomically open the file with O_EXCL.",
		fn: checkTempfileMktempRace,
		resultsPropName: "tempfileMktempRace",
		content_keywords: ["mktemp", "tempfile.mktemp"],
	},
	{
		id: "ubs_pickle_untrusted_load",
		phase: "pre_warn",
		name: "Pickle Untrusted Load",
		description:
			"Detects Python `pickle.load(...)` / `pickle.loads(...)` / `cPickle` — unpickling attacker-controlled bytes executes arbitrary `__reduce__` code.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"`pickle.load`/`loads` is effectively `eval` for bytes — a crafted pickle can run any Python code via `__reduce__`. For data interchange use JSON / msgpack; if you must use pickle, sign the payload (HMAC) and verify before unpickling, and only ever unpickle bytes you produced yourself.",
		fn: checkPickleUntrustedLoad,
		resultsPropName: "pickleUntrustedLoad",
		content_keywords: ["pickle.load", "pickle.loads", "cPickle"],
	},
	{
		id: "ubs_xml_external_entity",
		phase: "pre_warn",
		name: "XML External Entity",
		description:
			"Detects `xml.etree` / `xml.dom` / `xml.sax` / `lxml` imports without `defusedxml` — XXE attacks read arbitrary files / cause DoS via billion-laughs.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"Python's stdlib XML parsers do NOT disable external-entity resolution by default — XXE attacks can exfiltrate `/etc/passwd` or cause DoS via billion-laughs expansion. Use `defusedxml` (which mirrors the same APIs but with safe defaults) instead of `xml.etree` / `xml.dom` / `xml.sax` / `lxml`.",
		fn: checkXmlExternalEntity,
		resultsPropName: "xmlExternalEntity",
		content_keywords: ["etree", "xml.dom", "xml.sax"],
	},
	{
		id: "ubs_os_system_tainted",
		phase: "pre_warn",
		name: "os.system / os.popen with tainted input",
		description:
			"Detects Python `os.system(name)` / `os.popen(name)` invoked with a non-literal first argument — command-injection vector.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"`os.system` / `os.popen` always go through `/bin/sh`, so any non-literal argument is a command-injection vector. Use `subprocess.run([\"cmd\", \"arg\"])` (list form) so the shell is bypassed, or shell-quote with `shlex.quote(...)` if a shell really is needed.",
		fn: checkOsSystemTainted,
		resultsPropName: "osSystemTainted",
		content_keywords: ["os.system", "os.popen"],
	},
	{
		id: "ubs_unsafe_format_string",
		phase: "pre_warn",
		name: "Unsafe Format String",
		description:
			"Detects C/C++ `printf` / `sprintf` / `fprintf` with a non-literal format argument — `%n` writes arbitrary memory; `%x` leaks stack.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"A user-controlled format string can leak stack memory (`%x`) or write arbitrary bytes (`%n`). Always pass a literal format spec and route the variable into the value position: `printf(\"%s\", input)`, never `printf(input)`.",
		fn: checkUnsafeFormatString,
		resultsPropName: "unsafeFormatString",
		content_keywords: ["printf(", "sprintf(", "fprintf("],
	},
	{
		id: "ubs_unchecked_redirect",
		phase: "pre_warn",
		name: "Unchecked Redirect",
		description:
			"Detects JS/TS `redirect(url)` / `location.href = url` / `window.location = url` with a non-literal URL — open-redirect vector.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"Open-redirect bugs let attackers craft links that go through your domain before bouncing to a phishing site. Validate the redirect target against an allowlist or ensure it's a relative path (`url.startsWith('/')`) before redirecting.",
		fn: checkUncheckedRedirect,
		resultsPropName: "uncheckedRedirect",
		// Mirror EVERY trigger surface in the regex: `redirect(`,
		// `location.href`, AND `window.location`. Omitting any one form
		// turns the gate into a silent false-negative — a JS/TS edit that
		// only adds `window.location = nextUrl` would bypass the
		// pre_warn check. Audit pass: keep this list 1:1 with `callRe` in
		// `checkUncheckedRedirect` (`src/harness/checks/ubs-language-specific.ts`).
		content_keywords: ["redirect(", "location.href", "window.location"],
	},
	{
		id: "ubs_goroutine_no_waitgroup",
		phase: "post",
		name: "Goroutine without WaitGroup",
		description:
			"Detects Go `go func()` started without an accompanying `wg.Add` / `wg.Done` / errgroup — fire-and-forget leak risk.",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"A bare `go func() { ... }()` leaks if the caller exits before the goroutine completes — work is silently dropped. Pair with `sync.WaitGroup` / `errgroup.Group`, or pass a context the goroutine respects so the lifetime is explicit.",
		fn: checkGoroutineNoWaitgroup,
		resultsPropName: "goroutineNoWaitgroup",
		content_keywords: ["go func", "goroutine"],
	},
	{
		id: "ubs_defer_in_loop",
		phase: "post",
		name: "Defer in Loop",
		description:
			"Detects Go `defer` inside a `for` loop — defers run at function return, accumulating resources across iterations.",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Go `defer` runs at FUNCTION return, not loop iteration. `for { f, _ := os.Open(...); defer f.Close() }` accumulates open file handles across every iteration. Wrap the loop body in a closure or a helper function, or close the handle inline before the next iteration.",
		fn: checkDeferInLoop,
		resultsPropName: "deferInLoop",
		content_keywords: ["defer ", "for "],
	},
	{
		id: "ubs_string_concat_in_loop",
		phase: "post",
		name: "String Concat in Loop",
		description:
			"Detects `result += chunk` inside a loop in immutable-string languages (Python, Java, JS, Go) — O(n²).",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"`s += chunk` in a loop is O(n²) in Python / Java / JS / Go because each `+=` allocates a new string. Use a `list.append` + `''.join` (Python), `StringBuilder` (Java), `[].push` + `.join('')` (JS), or `strings.Builder` (Go).",
		fn: checkUbsStringConcatInLoop,
		resultsPropName: "ubsStringConcatInLoop",
	},
	{
		id: "ubs_numeric_comparison_chain",
		phase: "post",
		name: "Numeric Comparison Chain",
		description:
			"Detects 3+ consecutive `instanceof` / `compareTo` lines in Java — typically missing polymorphism.",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"A chain of `if (x instanceof A)` / `if (x instanceof B)` is a sign of missing polymorphism. Move the per-type behavior onto the types themselves and call a virtual method, or use a `switch` on a sealed/enum discriminant.",
		fn: checkNumericComparisonChain,
		resultsPropName: "numericComparisonChain",
		content_keywords: ["instanceof", "compareTo"],
	},
	{
		id: "ubs_print_debug_leak",
		phase: "post",
		name: "Print Debug Leak",
		description:
			"Detects `console.log` / Python `print(...)` / Go `fmt.Println` left in non-test, non-CLI code — typically forgotten debug breadcrumbs.",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"`console.log` / `print` / `fmt.Println` left in library code is almost always a forgotten debug print. Use a structured logger (with a level) so the noise can be filtered, or remove the line if it was just a breadcrumb.",
		fn: checkPrintDebugLeak,
		resultsPropName: "printDebugLeak",
		content_keywords: ["console.log", "print(", "fmt.Println"],
	},
	// `ubs_hardcoded_localhost` was promoted to pre_block / error severity in
	// Phase 1 of the agent-quality rollout (see docs/plans/11-...md). After
	// the extension-gate tightening landed alongside the promotion, the
	// check's FP rate dropped to ~0 against the dogfood corpus. Entry now
	// lives in `entries-errors.ts`.
	{
		id: "ubs_magic_number_no_const",
		phase: "post",
		name: "Magic Number No Const",
		description:
			"Detects 3+ digit numeric literals in expression context (not initializer) — magic numbers without a named constant.",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"`setTimeout(fn, 5000)` tells nobody what `5000` represents. Hoist into a named constant (`const RETRY_DELAY_MS = 5000`) so cold readers see intent without grepping for the value.",
		fn: checkMagicNumberNoConst,
		resultsPropName: "magicNumberNoConst",
	},
	{
		id: "ubs_large_function",
		phase: "post",
		name: "Large Function",
		description:
			"Detects a single function spanning 80+ body lines — review/refactor candidate.",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Functions over ~80 lines stretch the cold-reader's working memory. Extract internal stages (parse / validate / dispatch / serialize) into helpers with names that explain what each stage does.",
		fn: checkLargeFunction,
		resultsPropName: "largeFunction",
	},
	{
		id: "ubs_deeply_nested_callback",
		phase: "post",
		name: "Deeply Nested Callback",
		description:
			"Detects 4+ levels of nested function/arrow callbacks — callback-hell smell.",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Nesting 4+ callbacks deep is callback hell. Refactor with `async`/`await`, `Promise.all`, or extract each level into a named function so the structure is grep-able and the failure modes are isolatable.",
		fn: checkDeeplyNestedCallback,
		resultsPropName: "deeplyNestedCallback",
		content_keywords: ["function", "=>"],
	},
	{
		id: "ubs_time_format_locale_dep",
		phase: "post",
		name: "Time Format Locale Dependent",
		description:
			"Detects JS `toLocaleString()` / Java `DateTimeFormatter.ofLocalized*` without an explicit locale — formatting drifts by environment.",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"`date.toLocaleString()` (no args) or Java `DateTimeFormatter.ofLocalized*` (no `withLocale`) produces different strings depending on the JVM/Node locale. Pass an explicit locale (`'en-US'`) or use a fixed pattern (ISO-8601) when serializing for storage / wire formats.",
		fn: checkTimeFormatLocaleDep,
		resultsPropName: "timeFormatLocaleDep",
		content_keywords: ["toLocaleString", "DateTimeFormatter"],
	},
	{
		id: "ubs_regex_in_loop_no_compile",
		phase: "post",
		name: "Regex in Loop No Compile",
		description:
			"Detects Python `re.match` / `re.search` / `re.sub` inside a loop without `re.compile` — recompiles per iteration.",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Calling `re.match(pattern, ...)` inside a loop recompiles `pattern` on every iteration. Hoist `re.compile(pattern)` outside the loop and call `pattern.match(...)` per iteration — Python caches compilations but the cache lookup itself is overhead.",
		fn: checkRegexInLoopNoCompile,
		resultsPropName: "regexInLoopNoCompile",
		content_keywords: ["re.match", "re.search", "re.compile"],
	},
	{
		id: "package_json_script_paths",
		phase: "post",
		name: "Package JSON Script Paths",
		description:
			"Detects package.json scripts that reference files which don't exist on disk (node ./X.mjs, tsc -p X.json, --config X). Catches the universal CI failure where a manifest declares a script path the file tree doesn't have.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"A package.json script references a file that doesn't exist. Either create the file at the referenced path, fix the path to point at an existing file, or remove the script if it's no longer needed. The script will fail the moment anyone runs it.",
		fn: checkPackageJsonScriptPaths,
		resultsPropName: "packageJsonScriptPaths",
	},
	// ========================================================================
	// Batch 1: agent-laziness checks (11 entries)
	// ========================================================================
	{
		id: "agent_thumbprint_prose",
		phase: "post",
		name: "Agent Thumbprint Prose",
		description:
			"Detects literal phrases LLMs use when giving up — \"in a real implementation\", \"for now\", \"placeholder\", \"TODO: actually implement\" — left in source comments instead of finishing the work.",
		tier: 1,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This phrase is a tell that the implementation was left incomplete. Either finish the code so the comment is no longer needed, or replace the comment with a tracked issue link (e.g. // TODO(TICKET-123): wire up real auth) so the gap is visible to reviewers and maintainers.",
		fn: checkAgentThumbprintProse,
		resultsPropName: "agentThumbprintProse",
	},
	{
		id: "stub_not_implemented_throw",
		phase: "post",
		name: "Stub Not-Implemented Throw",
		description:
			"Detects `throw new Error(\"not implemented\")` and variants in non-test source — placeholder stubs left after the agent ran out of context.",
		tier: 1,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Either implement the function or delete the stub. If the stub is intentional (abstract base class skeleton), throw a typed error with a meaningful message: `throw new MethodMustBeImplementedError(\"Subclass FooBase must implement bar()\")`.",
		fn: checkStubNotImplementedThrow,
		resultsPropName: "stubNotImplementedThrow",
	},
	{
		id: "dead_branch_literal",
		phase: "post",
		name: "Dead Branch Literal",
		description:
			"Detects `if (true)` / `if (false)` / `else if (true)` — debugger artifacts that bypass real control flow. Skips `while (true)` (legit event-loop idiom).",
		tier: 1,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Replace the literal with a real condition or remove the dead branch entirely. `if (true)` keeps the body running unconditionally and silently disables whatever was on the other side; `if (false)` is unreachable code masquerading as a branch.",
		fn: checkDeadBranchLiteral,
		resultsPropName: "deadBranchLiteral",
	},
	{
		id: "file_level_suppression",
		phase: "post",
		name: "File-Level Suppression",
		description:
			"Detects file-wide suppression directives (ts-nocheck, eslint-disable with no rule list, biome-ignore-all, pylint disable=all) — they hide every issue in the file, not just the one that prompted the suppression.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"File-wide suppressions are invisible at every site of the file — a cold reader sees no warnings even though the checker is silenced. Replace with line-level directives that name the specific rule and include a justification: `// @ts-expect-error -- TICKET-123: third-party types are wrong here`.",
		fn: checkFileLevelSuppression,
		resultsPropName: "fileLevelSuppression",
	},
	{
		id: "untestable_time_in_source",
		phase: "post",
		name: "Untestable Time / Nondeterminism in Source",
		description:
			"Detects inline Date.now / new Date() / Math.random / crypto.randomUUID / performance.now in non-test source. The #1 cause of \"passes locally, flakes in CI.\" Skips clock/random/uuid injection-point files.",
		tier: 1,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Inject a clock or RNG instead of calling the global directly. Pattern: take `clock: () => number` (or `randomUUID: () => string`) as a constructor / function parameter with a default of `Date.now` / `crypto.randomUUID`. Tests pass a deterministic fake; production gets the real one. Without this, every code path that touches the call becomes flaky to test.",
		fn: checkUntestableTimeInSource,
		resultsPropName: "untestableTimeInSource",
	},
	{
		id: "double_cast_unknown",
		phase: "post",
		name: "Double-Cast via Unknown",
		description:
			"Detects `as unknown as Foo` — agents reach for this when a single `as` won't satisfy TypeScript. Lying to the type system through a wider escape hatch.",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"`as unknown as Foo` bypasses TypeScript entirely. If the value really might be Foo, validate it with a schema parser (zod, valibot, ajv) at the boundary so the runtime check matches the type assertion. If it's truly unsafe but unavoidable, isolate the cast in a single named helper with a comment explaining the invariant the cast relies on.",
		fn: checkDoubleCastUnknown,
		resultsPropName: "doubleCastUnknown",
	},
	{
		id: "union_widened_with_string",
		phase: "post",
		name: "Union Widened With Bare String",
		description:
			"Detects `type X = \"a\" | \"b\" | string` patterns — TypeScript narrows the result back to `string`, defeating the literal alternatives.",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"`\"a\" | \"b\" | string` collapses to `string` — the literals provide no autocomplete or exhaustiveness benefit. If you genuinely need open-ended values, use the branded-string pattern: `type X = \"a\" | \"b\" | (string & {})`. If the values are known, drop the `| string` and use the literal union alone.",
		fn: checkUnionWidenedWithString,
		resultsPropName: "unionWidenedWithString",
	},
	{
		id: "nodeenv_branch_in_prod",
		phase: "post",
		name: "NODE_ENV Branch in Production",
		description:
			"Detects `process.env.NODE_ENV === \"test\"` (or development/staging/local) inside non-test, non-config source — production behavior branched on test mode.",
		tier: 1,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Production code should not branch on NODE_ENV. Either inject the dependency the test wants to fake (a config object, a mock client) or move the branch to a setup module that's only imported in non-production entry points. Otherwise tests and production silently disagree.",
		fn: checkNodeEnvBranchInProd,
		resultsPropName: "nodeenvBranchInProd",
	},
	{
		id: "fetch_without_timeout",
		phase: "post",
		name: "Fetch / Axios Without Timeout",
		description:
			"Detects fetch() and axios.{get,post,...}() calls without `signal:` / `timeout:` / AbortController in their options window.",
		tier: 1,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Without a timeout or abort signal, a slow upstream leaks request handles and ties up the calling code indefinitely. Pass `AbortSignal.timeout(ms)` (Node 18+ / browsers) or an AbortController.signal: `await fetch(url, { signal: AbortSignal.timeout(5000) });`. For axios, use `{ timeout: 5000 }`.",
		fn: checkFetchWithoutTimeout,
		resultsPropName: "fetchWithoutTimeout",
	},
	{
		id: "unbounded_promise_all",
		phase: "post",
		name: "Promise.all on Unbounded Array",
		description:
			"Detects `Promise.all(<ident>.map(asyncFn))` patterns where the source array isn't visibly bounded — fans out N parallel requests for an N-sized input.",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"`Promise.all(items.map(fn))` runs every item concurrently — with 10K rows you get 10K parallel sockets, exhausting connection pools and triggering rate limits. Use a concurrency-limited helper: `await pMap(items, fn, { concurrency: 10 })` or `p-limit`. Reserve raw Promise.all for short, hand-authored fixed lists.",
		fn: checkUnboundedPromiseAll,
		resultsPropName: "unboundedPromiseAll",
	},
	{
		id: "sync_io_on_hot_path",
		phase: "post",
		name: "Synchronous I/O on Hot Path",
		description:
			"Detects *Sync (readFileSync / execSync / spawnSync / statSync / etc.) inside HTTP handler / route / middleware files or functions whose names imply request handling.",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Synchronous I/O blocks the event loop — every concurrent request waits behind the disk / subprocess. Replace with the promisified API: `await readFile(path)`, `await new Promise(r => exec(cmd, r))` / execa, etc. Keep *Sync calls confined to startup, CLIs, and one-shot scripts where blocking the single thread is fine.",
		fn: checkSyncIoOnHotPath,
		resultsPropName: "syncIoOnHotPath",
	},
	// ========================================================================
	// Batch 2: test-hygiene checks (6 entries)
	// ========================================================================
	{
		id: "duplicate_test_names",
		phase: "post",
		name: "Duplicate Test Names",
		description:
			"Detects two `it()` / `test()` / `specify()` blocks with identical name strings within the same file — copy-paste-then-edit-half-of-it bug class.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Two test blocks share the same name. Either the second is a stale copy that should be deleted, or the assertions diverged and one of them needs a more specific name describing what makes it different. Reporters list both runs under the same name, so a regression in either one reads as ambiguous.",
		fn: checkDuplicateTestNames,
		resultsPropName: "duplicateTestNames",
	},
	{
		id: "real_io_in_tests",
		phase: "post",
		name: "Real Network / Filesystem in Tests",
		description:
			"Detects fetch / axios / http.request to a non-loopback URL or *Sync writes to non-tmp paths inside test files.",
		tier: 1,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Tests that hit the real network or real filesystem are flaky and slow. Mock the network with msw / nock / fetch-mock, and write only to os.tmpdir() / __fixtures__ / a memfs mock. Loopback (localhost / 127.0.0.1) is allowlisted for in-process test servers.",
		fn: checkRealIoInTests,
		resultsPropName: "realIoInTests",
	},
	{
		id: "test_nondeterminism",
		phase: "post",
		name: "Test Nondeterminism",
		description:
			"Detects Date.now / new Date() / Math.random / crypto.randomUUID / performance.now in test bodies without vi.useFakeTimers / equivalent mocking.",
		tier: 1,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Tests that read the real clock / RNG flake under any timing or seed change. Replace Date.now / new Date() with vi.setSystemTime / a stubbed clock, and Math.random / crypto.randomUUID with a seeded RNG. If the file uses vi.useFakeTimers() at the top level, the check is suppressed for the whole file.",
		fn: checkTestNondeterminism,
		resultsPropName: "testNondeterminism",
	},
	{
		id: "hardcoded_timeout_in_tests",
		phase: "post",
		name: "Hardcoded Timeout in Tests",
		description:
			"Detects `setTimeout(_, NNNN)` / `setImmediate(_, NNNN)` waits with non-zero literal millisecond delays inside test bodies — \"I gave up debugging the timing condition\" tell.",
		tier: 2,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"A literal millisecond wait is almost always wrong: too short and it flakes, too long and CI gets slow. Use `vi.waitFor(predicate)` / `await waitForElementToBeRemoved(...)` / poll a deterministic predicate. `setTimeout(_, 0)` is allowlisted because it's a microtask flush, not a wait.",
		fn: checkHardcodedTimeoutInTests,
		resultsPropName: "hardcodedTimeoutInTests",
	},
	{
		id: "test_missing_sut_import",
		phase: "post",
		name: "Test Missing SUT Import",
		description:
			"Detects test files (`foo.test.ts`) that don't import their SUT (`./foo` / `../foo`). Strong signal the test is performative — not actually exercising what its name claims.",
		tier: 1,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"`foo.test.ts` should import `./foo` (or a parent-dir variant) so that the test exercises real code from the SUT. If the test is testing a different file, rename it (e.g., `something-else.test.ts`); if the SUT lives elsewhere, fix the import path. As written, the test claims to cover code it doesn't touch.",
		fn: checkTestMissingSutImport,
		resultsPropName: "testMissingSutImport",
	},
	{
		id: "mocking_the_sut_self",
		phase: "post",
		name: "Mocking the SUT in Its Own Test",
		description:
			"Detects `vi.mock(\"./foo\")` / `jest.mock(\"./foo\")` inside `foo.test.ts` where the relative path resolves to the SUT itself.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"A test that mocks its own SUT is testing the mock, not the code. Either remove the `vi.mock(./foo)` and let the real implementation run, or rename the test file (e.g., `foo-integration.test.ts`) so it's clearly testing the contract some other consumer has with `./foo`. Mocking `./foo` inside `foo.test.ts` is almost always the agent silencing a failing test rather than fixing it.",
		fn: checkMockingTheSutSelf,
		resultsPropName: "mockingTheSutSelf",
	},
	// ========================================================================
	// Batch 5: cross-file (4 entries; new-export orphan deferred)
	// ========================================================================
	{
		id: "empty_body_handler",
		phase: "post",
		name: "Empty-Body Handler",
		description:
			"Detects functions whose name implies request handling (handle*, route*, on[A-Z]*, HTTP-verb-named) with empty bodies, single `return;`, or only a console.log / logger call.",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"The function declares an API surface that does nothing. Either implement the body, throw a typed `MethodNotImplementedError(\"<name>\")` so callers fail fast, or rename the function so it doesn't claim to handle work it doesn't.",
		fn: checkEmptyBodyHandler,
		resultsPropName: "emptyBodyHandler",
	},
	{
		id: "listener_pairing",
		phase: "post",
		name: "Listener Pairing (Generalized)",
		description:
			"Detects addEventListener / process.on / emitter.on calls without a paired removeEventListener / off / removeListener anywhere in the same file.",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Listeners outlive the registering scope when nothing removes them. Store the handler in a variable and pair the registration with the matching off / removeListener / removeEventListener in a teardown path (cleanup function, dispose, signal abort handler).",
		fn: checkListenerPairing,
		resultsPropName: "listenerPairing",
	},
	{
		id: "schema_type_drift",
		phase: "post",
		name: "Schema ↔ Type Drift",
		description:
			"Detects same-file Zod / valibot / yup schemas paired with TS interfaces / type aliases whose property sets diverge.",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"The runtime validator and the static type are supposed to agree about the shape — when they drift, callers see one truth and the runtime enforces a different one. Derive one from the other: `type User = z.infer<typeof UserSchema>` (Zod's recommended pattern) so the two cannot drift.",
		fn: checkSchemaTypeDrift,
		resultsPropName: "schemaTypeDrift",
	},
	{
		id: "migration_parity",
		phase: "post",
		name: "Migration Parity",
		description:
			"Detects `*_up.sql` files in migration directories without a paired `*_down.sql` — every up should be reversible.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Every migration should be reversible. Add the matching `_down.sql` (or a stub one with a TODO documenting why it's not safe to revert in this case). Without it, a botched deploy can't roll back without manual surgery.",
		fn: checkMigrationParity,
		resultsPropName: "migrationParity",
	},
	// ========================================================================
	// Batch 8: demo-data (3 entries)
	// ========================================================================
	{
		id: "demo_data_unmarked",
		phase: "post",
		name: "Unmarked Demo Data",
		description:
			"Detects fake/test data signatures (test emails @example.com, Stripe test cards, lorem ipsum, sentinel UUIDs, faker imports, mock/fake/sample identifier prefixes) that lack a `// @demo-data: <reason>` directive.",
		tier: 1,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Either remove the demo data and wire up the real source, or mark it explicitly with `// @demo-data: <reason>` directly above so cold readers (and the rendered UI) see that the value isn't real. For data that flows into a chart / list rendered to users, prefer wrapping with `demoData(\"<key>\", value, { reason })` from the vendored demo-runtime so the page mounts a banner.",
		fn: checkDemoDataUnmarked,
		resultsPropName: "demoDataUnmarked",
	},
	{
		id: "silent_demo_fallback",
		phase: "post",
		name: "Silent Demo Fallback",
		description:
			"Detects `try { real API call } catch { return [literal data] }` patterns — the worst form of demo-data leak because it silently substitutes fake data when the upstream is unavailable.",
		tier: 1,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"A catch clause that returns hardcoded data hides upstream failures from users — they see plausible results that aren't real. Either re-throw the error so the caller can show a real error state, return a typed `Result<Error, T>` so the UI can react, or wrap the literal in `demoData()` so the demo banner mounts when the fallback path runs.",
		fn: checkSilentDemoFallback,
		resultsPropName: "silentDemoFallback",
	},
	{
		id: "demo_runtime_missing_banner",
		phase: "post",
		name: "Demo Runtime Without Banner",
		description:
			"Detects root-layout files (app/layout.tsx, src/main.tsx, etc.) that import from `interlinked-cli/demo-runtime` (or a vendored sibling) but do not render <DemoBanner />. Without the banner, users see no signal that the page contains demo data.",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"The vendored demo-runtime expects `<DemoBanner />` to be mounted in the root layout so any `demoData()` value rendered in the page lifecycle triggers a visible banner. Add `<DemoBanner />` somewhere inside the root `<body>` (or its equivalent) so the runtime can announce when the user is looking at fake data.",
		fn: checkDemoRuntimeMissingBanner,
		resultsPropName: "demoRuntimeMissingBanner",
	},
];
