// Pre-block, severity=error checks for correctness/security issues with zero
// false-positive risk. See check-registry/types.ts for CheckPhase semantics.

import {
	checkAsyncPromiseExecutor,
	checkDangerouslySetInnerHTML,
	checkEvalUsage,
	checkInnerHtmlUsage,
	checkMisusedPromises,
	checkNanComparison,
	checkPackageJsonPublishInvariants,
	checkPromiseRejectNonError,
	checkSelfImport,
	checkThrowLiteral,
	checkUnsafeOptionalChaining,
} from "../generic-checks.js";
import type { CheckRegistration } from "./types.js";

export const ERROR_ENTRIES: CheckRegistration[] = [
	{
		id: "misused_promises",
		phase: "pre_block",
		name: "Misused Promises",
		description: "Detects floating promises and missing await",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"Do not pass async functions to synchronous APIs like .forEach() or .reduce(). Use a for...of loop with await instead, or Promise.all() with .map().",
		fn: checkMisusedPromises,
		resultsPropName: "misusedPromises",
	},
	{
		id: "async_promise_executor",
		phase: "pre_block",
		name: "Async Promise Executor",
		description: "Detects async functions passed to Promise constructor",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"Remove the async keyword from the Promise executor. If you need to await inside, restructure to use async/await outside the Promise constructor.",
		fn: checkAsyncPromiseExecutor,
		resultsPropName: "asyncPromiseExecutor",
	},
	{
		id: "self_import",
		phase: "pre_block",
		name: "Self Import",
		description: "Detects a module importing itself",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"This module imports from itself, which causes circular dependency issues or empty values at runtime. Move shared code to a separate module.",
		fn: checkSelfImport,
		resultsPropName: "selfImports",
	},
	{
		id: "eval_usage",
		phase: "pre_block",
		name: "Eval Usage",
		description: "Detects use of eval() and Function()",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"eval() and new Function() are security risks (code injection). Use JSON.parse() for data, or restructure to avoid dynamic code execution.",
		fn: checkEvalUsage,
		resultsPropName: "evalUsage",
	},
	{
		id: "inner_html",
		phase: "pre_block",
		name: "innerHTML Usage",
		description: "Detects direct innerHTML assignment (XSS risk)",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"innerHTML and dangerouslySetInnerHTML create XSS vulnerabilities. Use textContent for plain text, or a sanitization library for HTML.",
		fn: checkInnerHtmlUsage,
		resultsPropName: "innerHtml",
	},
	{
		id: "nan_comparison",
		phase: "pre_block",
		name: "NaN Comparison",
		description: "Detects direct comparison with NaN",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction: "NaN is never equal to itself. Use Number.isNaN(x) instead of x === NaN.",
		fn: checkNanComparison,
		resultsPropName: "nanComparison",
	},
	{
		id: "throw_literal",
		phase: "pre_block",
		name: "Throw Literal",
		description: "Detects throwing string literals instead of Error objects",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"Always throw Error objects (throw new Error('message')), not strings or other values. Throwing non-Error values loses stack traces and breaks error handling patterns.",
		fn: checkThrowLiteral,
		resultsPropName: "throwLiteral",
	},
	{
		id: "promise_reject_non_error",
		phase: "pre_block",
		name: "Promise.reject with non-Error",
		description:
			"Detects Promise.reject() called with a string / number / boolean / null / undefined literal",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"Reject with an Error instance: `Promise.reject(new Error('...'))`. Rejecting with a string/number/undefined drops the stack trace, breaks `instanceof Error` checks downstream, and forces catchers to `typeof`-narrow instead of using structured error types.",
		fn: checkPromiseRejectNonError,
		resultsPropName: "promiseRejectNonError",
	},
	{
		id: "unsafe_optional_chaining",
		phase: "pre_block",
		name: "Unsafe Optional Chaining",
		description: "Detects unsafe optional chaining patterns",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"Wrapping an optional chain in parentheses then accessing a property defeats the safety of ?. — if the chain returns undefined, the outer access will throw.",
		fn: checkUnsafeOptionalChaining,
		resultsPropName: "unsafeOptionalChaining",
	},
	{
		id: "dangerously_set_inner_html",
		phase: "pre_block",
		name: "dangerouslySetInnerHTML",
		description: "Detects React dangerouslySetInnerHTML usage",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"innerHTML and dangerouslySetInnerHTML create XSS vulnerabilities. Use textContent for plain text, or a sanitization library for HTML.",
		fn: checkDangerouslySetInnerHTML,
		resultsPropName: "dangerouslySetInnerHtml",
	},
	{
		id: "package_json_publish_invariants",
		phase: "pre_block",
		name: "Package JSON Publish Invariants",
		description:
			"Detects edits to a publishable package.json that silently drop publish-critical fields (name/version/license/repository/homepage/bugs/keywords/author/engines/main/types/exports/bin/files/publishConfig/sideEffects/type/scripts.prepublishOnly)",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"A field that was present in the pre-edit package.json is missing from this edit. Restore it or publish will ship a broken tarball. Common causes: a rewrite that forgot to include publish metadata, or a subagent stripping fields it didn't recognise. Re-read the file on disk, keep the listed field(s), then retry.",
		fn: checkPackageJsonPublishInvariants,
		resultsPropName: "packageJsonPublishInvariants",
	},
];
