// ===========================================
// Codex CLI feature-flag writer (shared)
// ===========================================
// Codex hooks are gated by `[features] hooks = true` in
// `<scope>/.codex/config.toml`. The legacy key was `codex_hooks` and is
// still recognized by Codex but emits a deprecation warning ("`[features]
// .codex_hooks` is deprecated. Use `[features].hooks` instead."). We
// always write the canonical key; on any run we also migrate existing
// `codex_hooks = true` lines to `hooks = true` in place so the warning
// goes away after the next `interlinked enable`.
//
// Used by:
//   - the legacy installer in `./hook-installers.ts`
//     (called from `interlinked enable --clients codex`), and
//   - the modern adapter's `postInstall` in `../harness/adapters/codex.ts`
//     (called from `interlinked install-hooks --runner codex`).
//
// We do not parse TOML fully — we only detect the `[features]` table and
// whether `hooks = true` (canonical) or `codex_hooks = true` (legacy) is
// already present, with comments stripped. If neither is present we
// either insert the canonical key inside an existing `[features]` block
// or append a new one at EOF.
//
// Line endings: we split on "\n" and join on "\n", which leaves any "\r"
// attached to the line it terminates — so every byte we pass through
// round-trips exactly and a Windows (CRLF) config stays CRLF. Lines we ADD
// are terminated with the file's own dominant ending (`dominantCr`) so we
// never leave a user's config with mixed endings. See `stripTomlLineComment`
// for why the comment strip must not use `.` or `$`.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

// Canonical key. Negative lookbehind on any word/$ char excludes the
// legacy `codex_hooks` from matching this regex (so we can detect them
// independently and decide whether a migration is needed).
const FEATURE_FLAG_REGEX = /(?<![\w$])hooks\s*=\s*true\b/;
// Legacy key — recognized for migration, never written.
const LEGACY_FEATURE_FLAG_REGEX = /\bcodex_hooks\s*=\s*true\b/;
const HOOKS_DIR = ".codex";
const CONFIG_TOML = "config.toml";

export type EnsureFeatureFlagAction =
	/** Wrote a fresh file (none existed). */
	| "created"
	/** Appended a `[features]` block / inserted `hooks = true` into an existing one. */
	| "appended"
	/** Replaced legacy `codex_hooks = true` with canonical `hooks = true`. */
	| "migrated"
	/** Canonical `hooks = true` already present; file untouched. */
	| "preserved";

/**
 * Public API — consumed by `./hook-installers.ts` and
 * `../harness/adapters/codex.ts`.
 *
 * Idempotently ensure `<base>/.codex/config.toml` enables hooks via the
 * canonical `[features] hooks = true` key. Migrates legacy `codex_hooks`
 * entries silently. Returns an action descriptor for the caller's logging.
 *
 * `base` is the directory containing `.codex/`. For project scope pass
 * the repo root; for user scope pass the user's home directory.
 */
export function ensureCodexFeatureFlag(base: string): EnsureFeatureFlagAction {
	const tomlPath = join(base, HOOKS_DIR, CONFIG_TOML);
	const dir = dirname(tomlPath);
	if (!existsSync(dir)) {
		mkdirSync(dir, { recursive: true });
	}

	if (!existsSync(tomlPath)) {
		writeFileSync(
			tomlPath,
			"# Generated by interlinked enable — do not remove the hooks flag\n" +
				"# unless you intend to disable Interlinked CLI hooks for Codex.\n" +
				"\n[features]\nhooks = true\n",
		);
		return "created";
	}

	const existing = readFileSync(tomlPath, "utf-8");
	// Strip line comments before searching — a `# hooks = true` line
	// shouldn't be treated as enabled.
	const uncommented = existing
		.split("\n")
		.map((line) => stripTomlLineComment(line))
		.join("\n");

	const canonicalPresent = FEATURE_FLAG_REGEX.test(uncommented);
	const legacyPresent = LEGACY_FEATURE_FLAG_REGEX.test(uncommented);

	if (canonicalPresent && !legacyPresent) return "preserved";

	if (legacyPresent) {
		// Migration: replace any `codex_hooks` keys with `hooks` and update
		// our generated comment text. If canonical is also somehow present
		// (mixed-version users), the strip below will leave it alone and
		// remove only the legacy occurrences.
		const migrated = stripOrRenameLegacyKey(existing, canonicalPresent);
		writeFileSync(tomlPath, migrated);
		return "migrated";
	}

	const updatedExistingFeatures = insertIntoExistingFeaturesBlock(existing);
	if (updatedExistingFeatures !== null) {
		writeFileSync(tomlPath, updatedExistingFeatures);
		return "appended";
	}

	// No [features] block yet — append a fresh one at EOF, terminated the same
	// way the rest of the file is so a CRLF config does not end up mixed.
	const eol = `${dominantCr(existing)}\n`;
	const sep = existing.endsWith("\n") ? "" : eol;
	const block = ["", "# Added by interlinked", "[features]", "hooks = true", ""].join(eol);
	writeFileSync(tomlPath, `${existing}${sep}${block}`);
	return "appended";
}

/**
 * The carriage return that terminates this file's lines: `"\r"` when CRLF
 * endings are the majority, `""` otherwise. Because we join lines with `"\n"`,
 * appending this to a line we author is what makes it CRLF.
 *
 * Ties go to `""` (LF) — that matches the ending we use for a file we create,
 * so an ambiguous file is nudged toward the one we'd have written ourselves.
 */
function dominantCr(content: string): "\r" | "" {
	// Counted via split rather than `match(…) ?? []` so a file with no newline
	// at all is just a 1-element split, not a null needing a fallback.
	const newlines = content.split("\n").length - 1;
	const crlf = content.split("\r\n").length - 1;
	// The remaining `newlines - crlf` terminators are bare LF.
	return crlf > newlines - crlf ? "\r" : "";
}

/** When `canonicalAlsoPresent`, strip legacy lines entirely (canonical
 *  remains and stays authoritative). Otherwise, rename the key in place
 *  so the line position inside `[features]` is preserved. Both modes
 *  also rewrite our generated comment text. */
function stripOrRenameLegacyKey(content: string, canonicalAlsoPresent: boolean): string {
	const lines = content.split("\n");
	const out: string[] = [];
	for (const line of lines) {
		const stripped = stripTomlLineComment(line);
		if (LEGACY_FEATURE_FLAG_REGEX.test(stripped)) {
			if (canonicalAlsoPresent) {
				// Drop the redundant legacy line entirely.
				continue;
			}
			// Replace just the key, preserving leading indent + any
			// trailing comment. `\bcodex_hooks(\s*=\s*true\b)` rewrites
			// `codex_hooks = true ...` → `hooks = true ...`.
			out.push(line.replace(/\bcodex_hooks(\s*=\s*true\b)/, "hooks$1"));
			continue;
		}
		out.push(line);
	}
	return out
		.join("\n")
		.replace(/do not remove the codex_hooks flag/g, "do not remove the hooks flag");
}

function insertIntoExistingFeaturesBlock(existing: string): string | null {
	const lines = existing.split("\n");
	let featuresStart = -1;
	let featuresEnd = lines.length;

	for (const [i, rawLine] of lines.entries()) {
		const normalized = stripTomlLineComment(rawLine).trim();
		if (!normalized.startsWith("[") || !normalized.endsWith("]")) continue;

		if (featuresStart === -1 && normalized === "[features]") {
			featuresStart = i;
			continue;
		}

		if (featuresStart !== -1) {
			featuresEnd = i;
			break;
		}
	}

	if (featuresStart === -1) return null;

	const before = lines.slice(0, featuresEnd);
	const after = lines.slice(featuresEnd);
	// Carry the file's own terminator so inserting into a CRLF config does not
	// leave one lone LF line in the middle of it — but only when the join will
	// actually put a "\n" after our line. A trailing "\r" with no "\n" is a bare
	// CR, which TOML does not accept as a newline.
	const cr = after.length > 0 ? dominantCr(existing) : "";
	before.push(`hooks = true${cr}`);
	return [...before, ...after].join("\n");
}

/**
 * Remove a TOML line comment (`#` to end of line) for DETECTION purposes. The
 * result is only ever tested/trimmed, never written back, so eating the line's
 * trailing terminator along with the comment is harmless.
 *
 * `[^\n]*` rather than `.*$` is load-bearing. JS `.` excludes all four line
 * terminators (\n, \r, U+2028, U+2029) and `$` without /m anchors at true
 * end-of-string, so on a CRLF file — where splitting on "\n" leaves a trailing
 * "\r" on every line — `/#.*$/` could never match and the comment survived the
 * "strip". A commented-out `# hooks = true` then read as ENABLED, a legacy key
 * inside a comment got rewritten, and `[features] # cfg` stopped looking like a
 * table header (so a duplicate `[features]` table was appended). U+2028/U+2029
 * are not line breaks in TOML, so consuming them here is also the correct read.
 */
function stripTomlLineComment(line: string): string {
	return line.replace(/#[^\n]*/, "");
}
