// ===========================================
// Codex CLI feature-flag writer (shared)
// ===========================================
// Codex hooks are gated by `[features] codex_hooks = true` in
// `<scope>/.codex/config.toml`. Without that flag set, Codex silently
// ignores any `hooks.json` we install. This helper writes the flag
// idempotently and is shared between:
//
//   - the legacy installer in `./hook-installers.ts`
//     (called from `interlinked enable --clients codex`), and
//   - the modern adapter's `postInstall` in `../harness/adapters/codex.ts`
//     (called from `interlinked install-hooks --runner codex`).
//
// We do not parse TOML fully — we only detect the `[features]` table and
// whether the literal `codex_hooks = true` is already present (comments
// stripped). If absent, we either append the key inside an existing
// `[features]` block or append a new `[features]` block at EOF. This keeps
// user-managed config mostly untouched and avoids pulling in a TOML parser
// dependency.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const FEATURE_FLAG_REGEX = /\bcodex_hooks\s*=\s*true\b/;
const HOOKS_DIR = ".codex";
const CONFIG_TOML = "config.toml";

/**
 * Public API — consumed by `./hook-installers.ts` and
 * `../harness/adapters/codex.ts`.
 *
 * Idempotently ensure `<base>/.codex/config.toml` enables hooks. Returns
 * an action descriptor for the caller's logging:
 *   - "created"   — wrote a fresh file (none existed)
 *   - "appended"  — appended a [features] block to an existing file
 *   - "preserved" — flag already present; left the file untouched
 *
 * `base` is the directory containing `.codex/`. For project scope pass the
 * repo root; for user scope pass the user's home directory.
 */
export function ensureCodexFeatureFlag(base: string): "created" | "appended" | "preserved" {
	const tomlPath = join(base, HOOKS_DIR, CONFIG_TOML);
	const dir = dirname(tomlPath);
	if (!existsSync(dir)) {
		mkdirSync(dir, { recursive: true });
	}

	if (!existsSync(tomlPath)) {
		writeFileSync(
			tomlPath,
			"# Generated by interlinked enable — do not remove the codex_hooks flag\n" +
				"# unless you intend to disable Interlinked CLI hooks for Codex.\n" +
				"\n[features]\ncodex_hooks = true\n",
		);
		return "created";
	}

	const existing = readFileSync(tomlPath, "utf-8");
	// Strip comments before searching — a `# codex_hooks = true` line
	// shouldn't be treated as enabled.
	const uncommented = existing
		.split("\n")
		.map((line) => line.replace(/#.*$/, ""))
		.join("\n");
	if (FEATURE_FLAG_REGEX.test(uncommented)) return "preserved";

	const updatedExistingFeatures = insertIntoExistingFeaturesBlock(existing);
	if (updatedExistingFeatures !== null) {
		writeFileSync(tomlPath, updatedExistingFeatures);
		return "appended";
	}

	// No [features] block yet — append a fresh one at EOF.
	const sep = existing.endsWith("\n") ? "" : "\n";
	writeFileSync(
		tomlPath,
		`${existing}${sep}\n# Added by interlinked\n[features]\ncodex_hooks = true\n`,
	);
	return "appended";
}

function insertIntoExistingFeaturesBlock(existing: string): string | null {
	const lines = existing.split("\n");
	let featuresStart = -1;
	let featuresEnd = lines.length;

	for (let i = 0; i < lines.length; i += 1) {
		const normalized = stripTomlLineComment(lines[i]).trim();
		if (!normalized.startsWith("[") || !normalized.endsWith("]")) continue;

		if (featuresStart === -1 && normalized === "[features]") {
			featuresStart = i;
			continue;
		}

		if (featuresStart !== -1) {
			featuresEnd = i;
			break;
		}
	}

	if (featuresStart === -1) return null;

	const before = lines.slice(0, featuresEnd);
	const after = lines.slice(featuresEnd);
	before.push("codex_hooks = true");
	return [...before, ...after].join("\n");
}

function stripTomlLineComment(line: string): string {
	return line.replace(/#.*$/, "");
}
