import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { ensureCodexFeatureFlag } from "./codex-feature-flag.js";

describe("ensureCodexFeatureFlag", () => {
	let tmp: string;

	beforeEach(() => {
		tmp = mkdtempSync(join(tmpdir(), "codex-flag-"));
	});

	afterEach(() => {
		rmSync(tmp, { recursive: true, force: true });
	});

	it("creates .codex/config.toml with the canonical `hooks` flag when none exists", () => {
		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("created");
		const tomlPath = join(tmp, ".codex", "config.toml");
		expect(existsSync(tomlPath)).toBe(true);
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toMatch(/\[features\]/);
		expect(toml).toMatch(/(?<![\w$])hooks\s*=\s*true/);
		// Must NOT write the deprecated key on a fresh file.
		expect(toml).not.toMatch(/\bcodex_hooks\s*=\s*true/);
		// The generated file must carry both comment lines verbatim — they
		// are the only guidance a human gets before deleting the flag.
		expect(toml).toContain(
			"# Generated by interlinked enable — do not remove the hooks flag\n",
		);
		expect(toml).toContain("# unless you intend to disable Interlinked CLI hooks for Codex.\n");
	});

	it("creates intermediate directories recursively when the base path itself does not exist", () => {
		// `base` here has no ancestor directories on disk at all, so mkdirSync
		// must be called with { recursive: true } — a non-recursive call (or
		// an empty options object) throws ENOENT because neither `deep` nor
		// `nested` exists yet.
		const nested = join(tmp, "deep", "nested", "base");
		expect(existsSync(nested)).toBe(false);
		const result = ensureCodexFeatureFlag(nested);
		expect(result).toBe("created");
		expect(existsSync(join(nested, ".codex", "config.toml"))).toBe(true);
	});

	it("does not attempt mkdirSync over a path that already exists as a non-directory", () => {
		// If `.codex` already exists (as a directory, as it normally would),
		// the existsSync(dir) guard must skip mkdirSync entirely. Pre-create
		// a plain FILE at the `.codex` path to make the two behaviors
		// observably different: a correct guard skips mkdirSync and fails
		// later at writeFileSync with ENOTDIR (can't write inside a file);
		// a guard that always calls mkdirSync fails earlier, at mkdirSync
		// itself, with EEXIST (can't mkdir over an existing file).
		writeFileSync(join(tmp, ".codex"), "not a directory");
		let caught: NodeJS.ErrnoException | undefined;
		try {
			ensureCodexFeatureFlag(tmp);
		} catch (err) {
			// SAFETY: fs errors on this code path are always Node ErrnoException
			// (errno + code fields) — that's the only error shape fs throws.
			caught = err as NodeJS.ErrnoException;
		}
		expect(caught).toBeDefined();
		expect(caught?.code).toBe("ENOTDIR");
	});

	it("preserves an existing config with zero whitespace around `hooks=true`", () => {
		// FEATURE_FLAG_REGEX must tolerate zero-or-more spaces on both sides
		// of `=` (not exactly one) — otherwise a canonical flag with no
		// surrounding whitespace is not detected as already present, and
		// the file gets a redundant second `hooks = true` appended.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "[features]\nhooks=true\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("preserved");
		expect(readFileSync(tomlPath, "utf-8")).toBe(existing);
	});

	it("preserves an existing config with zero whitespace after `hooks =`", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "[features]\nhooks =true\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("preserved");
		expect(readFileSync(tomlPath, "utf-8")).toBe(existing);
	});

	it("preserves an existing config that already enables canonical `hooks`", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "# user-managed\n[features]\nhooks = true\nfoo = 42\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("preserved");
		expect(readFileSync(tomlPath, "utf-8")).toBe(existing);
	});

	it("migrates legacy `codex_hooks = true` to canonical `hooks = true` in place", () => {
		// The migration must (a) silence Codex's deprecation warning by
		// replacing the legacy key, (b) preserve the line's position in
		// `[features]` so user-organized config stays put, and (c) leave
		// other keys in the block untouched.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "# user-managed\n[features]\ncodex_hooks = true\nfoo = 42\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("migrated");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toMatch(/(?<![\w$])hooks\s*=\s*true/);
		expect(toml).not.toMatch(/\bcodex_hooks\s*=\s*true/);
		expect(toml).toContain("foo = 42");
		// The rewritten lines must stay on separate lines — a mutant that
		// turns the final `.join("\n")` into `.join("")` would squash them
		// together, and a plain `.toContain("foo = 42")` can't tell the
		// difference because that substring survives the squash either way.
		expect(toml).toContain("hooks = true\nfoo = 42");
	});

	it("rewrites our generated comment text during migration", () => {
		// Files we wrote in earlier versions had a comment referencing the
		// legacy flag name. Migration should rewrite that prose too so the
		// comment stays accurate after the key changes.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing =
			"# Generated by interlinked enable — do not remove the codex_hooks flag\n" +
			"# unless you intend to disable Interlinked CLI hooks for Codex.\n" +
			"\n[features]\ncodex_hooks = true\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("migrated");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toContain("do not remove the hooks flag");
		expect(toml).not.toContain("do not remove the codex_hooks flag");
	});

	it("when both keys are present, drops the redundant legacy line and keeps canonical", () => {
		// Pathological case (manual edit, mixed-version install). Canonical
		// is authoritative; legacy line gets removed entirely so Codex
		// stops emitting the deprecation warning.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing =
			"[features]\nhooks = true\ncodex_hooks = true\nother = false\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("migrated");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toMatch(/(?<![\w$])hooks\s*=\s*true/);
		expect(toml).not.toMatch(/\bcodex_hooks\s*=\s*true/);
		expect(toml).toContain("other = false");
		// Exact match: a mutant that turns the "drop the redundant legacy
		// line" branch into a no-op (or that disables the
		// canonicalAlsoPresent check entirely) renames the legacy line
		// in place instead of dropping it, producing a duplicate
		// "hooks = true" line that a mere .toContain/.not.toMatch pair
		// can't see.
		expect(toml).toBe("[features]\nhooks = true\nother = false\n");
	});

	it("migrates a legacy key with no whitespace around the `=`", () => {
		// Exercises the exact whitespace tolerance of the in-place rename
		// regex: zero spaces on either side of `=` must still match and
		// rename correctly.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "[features]\ncodex_hooks=true\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("migrated");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toBe("[features]\nhooks=true\n");
	});

	it("migrates a legacy key with no whitespace after the `=`", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "[features]\ncodex_hooks =true\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("migrated");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toBe("[features]\nhooks =true\n");
	});

	it("leaves an unrelated commented-out legacy line untouched while migrating a real one", () => {
		// The comment-stripping regex used to decide whether a LINE contains
		// an active legacy key must match the whole trailing comment, not
		// just its first character — otherwise a multi-word comment that
		// happens to mention `codex_hooks = true` gets misread as an active
		// key and rewritten.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing =
			"# codex_hooks = true - deprecated example\n[features]\ncodex_hooks = true\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("migrated");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toBe(
			"# codex_hooks = true - deprecated example\n[features]\nhooks = true\n",
		);
	});

	it("preserves trailing comment when migrating in place", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "[features]\ncodex_hooks = true # legacy flag\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("migrated");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toContain("hooks = true # legacy flag");
	});

	it("appends [features] when neither key is present in an existing config", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = '[model]\nname = "synthetic-model-v5"\n';
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toContain("[model]");
		expect(toml).toMatch(/(?<![\w$])hooks\s*=\s*true/);
		expect(toml).not.toMatch(/\bcodex_hooks\s*=\s*true/);
		// Exact match: pins the separator logic AND proves a real, fresh
		// `[features]` block was created (not just a bare `hooks = true`
		// tacked onto raw EOF, which is what a broken
		// insertIntoExistingFeaturesBlock null-guard would produce here
		// since this config has no [features] section at all).
		expect(toml).toBe(
			'[model]\nname = "synthetic-model-v5"\n\n# Added by interlinked\n[features]\nhooks = true\n',
		);
	});

	it("separates existing content from the appended block with exactly one blank line, regardless of leading whitespace", () => {
		// existing STARTS with a newline but does not END with one — this
		// distinguishes the endsWith("\n") check from a startsWith("\n")
		// check, which a mutant could swap without any other test noticing
		// (a config ending in "\n" already looks identical either way).
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = '\n[model]\nname = "x"';
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toBe('\n[model]\nname = "x"\n\n# Added by interlinked\n[features]\nhooks = true\n');
	});

	it("adds the canonical flag inside an existing [features] block instead of duplicating it", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing =
			'[model]\nname = "synthetic-model-v5"\n\n[features]\nfoo = true\n[profiles.default]\napproval_policy = "never"\n';
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect((toml.match(/\[features\]/g) || []).length).toBe(1);
		expect(toml).toContain("[features]\nfoo = true\nhooks = true\n[profiles.default]");
	});

	it("ignores a commented-out flag and treats the file as missing the flag", () => {
		// A `# hooks = true` line is documentation, not enablement. We
		// must still append a real flag so hooks actually fire.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "# hooks = true\n[model]\nname = \"synthetic-model-v5\"\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toMatch(/^hooks\s*=\s*true$/m);
	});

	it("ignores a commented-out legacy flag too", () => {
		// A `# codex_hooks = true` line should not trigger migration —
		// nothing to migrate, the flag is already off.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "# codex_hooks = true\n[model]\nname = \"x\"\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toMatch(/^hooks\s*=\s*true$/m);
		// The original commented line is preserved.
		expect(toml).toContain("# codex_hooks = true");
	});

	it("creates the .codex directory if absent", () => {
		expect(existsSync(join(tmp, ".codex"))).toBe(false);
		ensureCodexFeatureFlag(tmp);
		expect(existsSync(join(tmp, ".codex"))).toBe(true);
	});

	it("detects an existing [features] header even with a trailing comment", () => {
		// stripTomlLineComment + .trim() must reduce "[features] # config" to
		// exactly "[features]" for header detection to fire. If the comment
		// strip fails (or over-strips to a single character), the header is
		// missed, insertIntoExistingFeaturesBlock returns null, and the
		// caller falls back to appending a SECOND [features] block instead
		// of inserting into the existing one.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = '[model]\nname = "x"\n\n[features] # config\nfoo = true\n';
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect((toml.match(/\[features\]/g) || []).length).toBe(1);
		expect(toml).toBe('[model]\nname = "x"\n\n[features] # config\nfoo = true\n\nhooks = true');
	});

	it("detects an existing [features] header with surrounding whitespace", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = '[model]\nname = "x"\n\n  [features]  \nfoo = true\n';
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect((toml.match(/\[features\]/g) || []).length).toBe(1);
		expect(toml).toBe('[model]\nname = "x"\n\n  [features]  \nfoo = true\n\nhooks = true');
	});

	it("does not treat an inline array value as the end of the [features] block", () => {
		// A line like `list = [1, 2]` ends with "]" but is not a section
		// header. The header-boundary check requires BOTH startsWith("[")
		// AND endsWith("]") (an OR-vs-AND mix-up, or losing either bracket
		// character from the check, makes this line look like a boundary
		// and truncates the block early).
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "[features]\nfoo = true\nlist = [1, 2]\nbar = true\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toBe("[features]\nfoo = true\nlist = [1, 2]\nbar = true\n\nhooks = true");
	});

	it("does not treat an unterminated bracket line as the end of the [features] block", () => {
		// A line starting with "[" but never closed by "]" must not be
		// mistaken for a boundary either — this is the other half of the
		// AND check (losing the "]" side specifically).
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "[features]\nfoo = true\n[incomplete\nbar = true\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toBe("[features]\nfoo = true\n[incomplete\nbar = true\n\nhooks = true");
	});

	it("finds the real [features] block past other bracketed sections that precede it", () => {
		// The "only set featuresStart the first time" guard must key off
		// the CURRENT featuresStart being -1 in combination with the header
		// text — not just one of those on its own — or an earlier,
		// unrelated section header gets mistaken for the target block.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = '[model]\nname = "x"\n\n[other]\nvalue = 1\n\n[features]\nfoo = true\n';
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toBe(
			'[model]\nname = "x"\n\n[other]\nvalue = 1\n\n[features]\nfoo = true\n\nhooks = true',
		);
	});

	it("inserts into the FIRST [features] block when duplicate headers exist", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "[features]\nfoo = true\n[features]\nbar = true\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toBe("[features]\nfoo = true\nhooks = true\n[features]\nbar = true\n");
	});
});
