import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { ensureCodexFeatureFlag } from "./codex-feature-flag.js";

describe("ensureCodexFeatureFlag", () => {
	let tmp: string;

	beforeEach(() => {
		tmp = mkdtempSync(join(tmpdir(), "codex-flag-"));
	});

	afterEach(() => {
		rmSync(tmp, { recursive: true, force: true });
	});

	it("creates .codex/config.toml with the canonical `hooks` flag when none exists", () => {
		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("created");
		const tomlPath = join(tmp, ".codex", "config.toml");
		expect(existsSync(tomlPath)).toBe(true);
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toMatch(/\[features\]/);
		expect(toml).toMatch(/(?<![\w$])hooks\s*=\s*true/);
		// Must NOT write the deprecated key on a fresh file.
		expect(toml).not.toMatch(/\bcodex_hooks\s*=\s*true/);
	});

	it("preserves an existing config that already enables canonical `hooks`", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "# user-managed\n[features]\nhooks = true\nfoo = 42\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("preserved");
		expect(readFileSync(tomlPath, "utf-8")).toBe(existing);
	});

	it("migrates legacy `codex_hooks = true` to canonical `hooks = true` in place", () => {
		// The migration must (a) silence Codex's deprecation warning by
		// replacing the legacy key, (b) preserve the line's position in
		// `[features]` so user-organized config stays put, and (c) leave
		// other keys in the block untouched.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "# user-managed\n[features]\ncodex_hooks = true\nfoo = 42\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("migrated");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toMatch(/(?<![\w$])hooks\s*=\s*true/);
		expect(toml).not.toMatch(/\bcodex_hooks\s*=\s*true/);
		expect(toml).toContain("foo = 42");
	});

	it("rewrites our generated comment text during migration", () => {
		// Files we wrote in earlier versions had a comment referencing the
		// legacy flag name. Migration should rewrite that prose too so the
		// comment stays accurate after the key changes.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing =
			"# Generated by interlinked enable — do not remove the codex_hooks flag\n" +
			"# unless you intend to disable Interlinked CLI hooks for Codex.\n" +
			"\n[features]\ncodex_hooks = true\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("migrated");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toContain("do not remove the hooks flag");
		expect(toml).not.toContain("do not remove the codex_hooks flag");
	});

	it("when both keys are present, drops the redundant legacy line and keeps canonical", () => {
		// Pathological case (manual edit, mixed-version install). Canonical
		// is authoritative; legacy line gets removed entirely so Codex
		// stops emitting the deprecation warning.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing =
			"[features]\nhooks = true\ncodex_hooks = true\nother = false\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("migrated");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toMatch(/(?<![\w$])hooks\s*=\s*true/);
		expect(toml).not.toMatch(/\bcodex_hooks\s*=\s*true/);
		expect(toml).toContain("other = false");
	});

	it("preserves trailing comment when migrating in place", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "[features]\ncodex_hooks = true # legacy flag\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("migrated");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toContain("hooks = true # legacy flag");
	});

	it("appends [features] when neither key is present in an existing config", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = '[model]\nname = "synthetic-model-v5"\n';
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toContain("[model]");
		expect(toml).toMatch(/(?<![\w$])hooks\s*=\s*true/);
		expect(toml).not.toMatch(/\bcodex_hooks\s*=\s*true/);
	});

	it("adds the canonical flag inside an existing [features] block instead of duplicating it", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing =
			'[model]\nname = "synthetic-model-v5"\n\n[features]\nfoo = true\n[profiles.default]\napproval_policy = "never"\n';
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect((toml.match(/\[features\]/g) || []).length).toBe(1);
		expect(toml).toContain("[features]\nfoo = true\nhooks = true\n[profiles.default]");
	});

	it("ignores a commented-out flag and treats the file as missing the flag", () => {
		// A `# hooks = true` line is documentation, not enablement. We
		// must still append a real flag so hooks actually fire.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "# hooks = true\n[model]\nname = \"synthetic-model-v5\"\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toMatch(/^hooks\s*=\s*true$/m);
	});

	it("ignores a commented-out legacy flag too", () => {
		// A `# codex_hooks = true` line should not trigger migration —
		// nothing to migrate, the flag is already off.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "# codex_hooks = true\n[model]\nname = \"x\"\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toMatch(/^hooks\s*=\s*true$/m);
		// The original commented line is preserved.
		expect(toml).toContain("# codex_hooks = true");
	});

	it("creates the .codex directory if absent", () => {
		expect(existsSync(join(tmp, ".codex"))).toBe(false);
		ensureCodexFeatureFlag(tmp);
		expect(existsSync(join(tmp, ".codex"))).toBe(true);
	});
});
