// ===========================================
// Hook Management — Install/Uninstall/Write Hooks
// ===========================================
// Comprehensive hook management for all supported AI coding clients.
// Handles hook script generation, installation into client settings,
// and .gitignore management.

import {
	chmodSync,
	existsSync,
	mkdirSync,
	readFileSync,
	rmSync,
	unlinkSync,
	writeFileSync,
} from "node:fs";
import { dirname, join, parse } from "node:path";
import { GEMINI_HOOK_EVENTS, installGeminiHooks, uninstallGeminiHooks } from "./hook-installers.js";
import { buildHookScript } from "./hooks-template.js";
import type { JsonObject } from "./json-types.js";
import type { ClientName } from "./settings.js";

// Marker used to identify Interlinked CLI-managed hook entries
const INTERLINKED_MARKER = "interlinked-activity";

// Hook script version — derived from package.json so there's one source of truth.
// Embedded in the generated .mjs script for staleness detection by `doctor`.
export const HOOK_SCRIPT_VERSION: string = ((): string => {
	try {
		const pkgPath = new URL("../../package.json", import.meta.url);
		const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
		return pkg.version || "0.0.0";
	} catch (_err) {
		/* intentional: package.json missing or unreadable — fallback version */
		return "0.0.0";
	}
})();

// Claude Code hook events registered in settings.json.
// PostToolUseFailure is intentionally omitted — registering it causes Claude Code
// to display "2 PostToolUse hooks ran" since it counts both registrations.
// The hook script still handles PostToolUseFailure if received (via isPostTool check).
const CLAUDE_HOOK_EVENTS = [
	"SessionStart",
	"SessionEnd",
	"UserPromptSubmit",
	"Stop",
	"PreToolUse",
	"PostToolUse",
	"PermissionRequest",
	"SubagentStart",
	"SubagentStop",
	"Notification",
	"PreCompact",
	"TaskCompleted",
	"TeammateIdle",
] as const;

// PostToolUse matcher — scope to mutating tools only.
// With matcher: "" (match-all), Claude Code counts a PostToolUse hook invocation
// for every tool in the turn (e.g. Read + Edit = "2 hooks ran"). Scoping to
// Edit|Write|MultiEdit ensures the count reflects actual mutations only.
// The hook script still receives all PostToolUse events that match this pattern.
const POST_TOOL_USE_MATCHER = "Edit|Write|MultiEdit";

// GitHub Copilot CLI hook events (camelCase — Copilot convention)
const COPILOT_HOOK_EVENTS = [
	"sessionStart",
	"sessionEnd",
	"userPromptSubmitted",
	"preToolUse",
	"postToolUse",
	"errorOccurred",
] as const;

interface HookEntry {
	matcher: string;
	hooks: Array<{ type: string; command: string }>;
}

// ===========================================
// Path Helpers
// ===========================================

/**
 * Walk up from `startDir` looking for a directory containing `.git/`.
 * Returns the project root path, or null if not found.
 */
export function findProjectRoot(startDir: string): string | null {
	let dir = startDir;
	const { root } = parse(dir);
	while (dir !== root) {
		if (existsSync(join(dir, ".git"))) {
			return dir;
		}
		dir = dirname(dir);
	}
	// Check the filesystem root too
	if (existsSync(join(root, ".git"))) {
		return root;
	}
	return null;
}

/**
 * Get the path to the hook script inside .interlinked/hooks/.
 */
export function getHookScriptPath(cwd: string): string {
	return join(cwd, ".interlinked", "hooks", "interlinked-activity.mjs");
}

// ===========================================
// Status Line — Install script + configure clients
// ===========================================

const STATUSLINE_SCRIPT_NAME = "statusline-interlinked.sh";

/**
 * Write the statusline script and configure it in user-level settings for
 * clients that support it (Claude Code, Copilot CLI).
 * Returns the path to the script, or null if no clients were configured.
 */
export function installStatusLine(clients: ClientName[]): string | null {
	const home = process.env.HOME || process.env.USERPROFILE || "";
	if (!home) return null;

	// Write the script to ~/.interlinked/statusline-interlinked.sh
	const scriptDir = join(home, ".interlinked");
	if (!existsSync(scriptDir)) {
		mkdirSync(scriptDir, { recursive: true });
	}
	const scriptPath = join(scriptDir, STATUSLINE_SCRIPT_NAME);

	const script = `#!/bin/bash
# Interlinked harness status line (auto-generated by interlinked enable)
# Works with: Claude Code, GitHub Copilot CLI, and any agent supporting statusLine.command
trap '' INT TERM PIPE

# Consume stdin (agents send session JSON; unused for now)
cat > /dev/null

BOLD="\\033[1m"
DIM="\\033[2m"
GREEN="\\033[32m"
YELLOW="\\033[33m"
CYAN="\\033[36m"
RESET="\\033[0m"

# Walk up from CWD looking for .interlinked/harness.sock — lets a
# harness daemon rooted at any monorepo ancestor serve subdir shells.
SOCKET=""
PID=""
DIR="$PWD"
for _ in 1 2 3 4 5 6 7 8 9 10; do
    if [ -S "$DIR/.interlinked/harness.sock" ]; then
        SOCKET="$DIR/.interlinked/harness.sock"
        [ -f "$DIR/.interlinked/harness.pid" ] && PID=$(cat "$DIR/.interlinked/harness.pid" 2>/dev/null)
        break
    fi
    P=$(dirname "$DIR")
    [ "$P" = "$DIR" ] && break
    DIR="$P"
done

[ -z "$SOCKET" ] && exit 0

if [ -n "$PID" ] && ps -p "$PID" > /dev/null 2>&1; then
    # tsgo check — walk up to find the package
    TS="tsc"
    DIR="$PWD"
    for _ in 1 2 3 4 5; do
        [ -d "$DIR/node_modules/@typescript/native-preview" ] && TS="tsgo" && break
        P=$(dirname "$DIR"); [ "$P" = "$DIR" ] && break; DIR="$P"
    done
    command -v tsgo &>/dev/null && TS="tsgo"

    if [ "$TS" = "tsgo" ]; then
        TS_FMT="\${CYAN}tsgo\${RESET}"
    else
        TS_FMT="\${DIM}tsc\${RESET}"
    fi

    # Classifier status
    CLS=""
    CLS_FILE=""
    for candidate in ".interlinked/classifier.status" "cli/.interlinked/classifier.status"; do
        [ -f "$candidate" ] && CLS_FILE="$candidate" && break
    done
    if [ -n "$CLS_FILE" ]; then
        CLS_RAW=$(cat "$CLS_FILE" 2>/dev/null)
        case "$CLS_RAW" in
            disabled) ;;
            *:no_key) CLS=" · \${YELLOW}cls ✗\${RESET}" ;;
            *:error)  CLS=" · \${YELLOW}cls ✗\${RESET}" ;;
            *:ok:*)   CLS=" · \${GREEN}cls ✓\${RESET}" ;;
            *:ready)  CLS=" · \${DIM}cls ●\${RESET}" ;;
        esac
    fi
    printf "%b" "\${GREEN}interlinked \${BOLD}▲\${RESET}\${DIM} pid \${PID} ·\${RESET} \${TS_FMT}\${CLS}"
else
    printf "%b" "\${YELLOW}interlinked \${BOLD}▼\${RESET}\${DIM} stale\${RESET}"
fi
`;
	writeFileSync(scriptPath, script);
	chmodSync(scriptPath, 0o755);

	// Configure statusLine in user-level settings for each supported client
	const statusLineConfig = {
		type: "command",
		command: scriptPath,
	};

	let configured = false;

	for (const client of clients) {
		let settingsPath: string | null = null;

		if (client === "claude") {
			settingsPath = join(home, ".claude", "settings.json");
		} else if (client === "copilot") {
			// Copilot reads ~/.copilot/config.json for user-level settings
			settingsPath = join(home, ".copilot", "config.json");
		}
		if (!settingsPath) continue;

		try {
			const dir = dirname(settingsPath);
			if (!existsSync(dir)) {
				mkdirSync(dir, { recursive: true });
			}

			let settings: JsonObject = {};
			if (existsSync(settingsPath)) {
				settings = JSON.parse(readFileSync(settingsPath, "utf-8"));
			}

			// Only write if statusLine isn't already configured
			if (!settings.statusLine) {
				settings.statusLine = statusLineConfig;
				writeFileSync(settingsPath, `${JSON.stringify(settings, null, 2)}\n`);
				configured = true;
			} else {
				// Update if it points to our script (in case path changed)
				const existing = settings.statusLine as JsonObject;
				if (
					typeof existing.command === "string" &&
					existing.command.includes("statusline-interlinked")
				) {
					existing.command = scriptPath;
					writeFileSync(settingsPath, `${JSON.stringify(settings, null, 2)}\n`);
					configured = true;
				}
			}
		} catch (_err) {
			/* intentional: malformed or unreadable client settings — skip this client */
		}
	}

	return configured ? scriptPath : null;
}

// ===========================================
// Hook Script Generation
// ===========================================

/**
 * Write the universal hook script to .interlinked/hooks/interlinked-activity.mjs.
 * This script reads config from .interlinked/config.local.json and
 * normalizes events from any supported AI coding client.
 */
export function writeHookScript(cwd: string): string {
	const scriptPath = getHookScriptPath(cwd);
	const hookDir = dirname(scriptPath);
	if (!existsSync(hookDir)) {
		mkdirSync(hookDir, { recursive: true });
	}

	// Always write the fresh hook script with local JSONL support.
	// Legacy scripts from .claude/hooks/ are NOT copied — they lack local writing.
	const script = buildHookScript(HOOK_SCRIPT_VERSION);

	writeFileSync(scriptPath, script);
	chmodSync(scriptPath, 0o755);
	return scriptPath;
}

/**
 * Delete the hook script from .interlinked/hooks/.
 */
export function deleteHookScript(cwd: string): boolean {
	const scriptPath = getHookScriptPath(cwd);
	if (existsSync(scriptPath)) {
		unlinkSync(scriptPath);
		return true;
	}
	return false;
}

/**
 * Delete the entire .interlinked/ directory.
 */
export function deleteConfigDir(cwd: string): boolean {
	const configDir = join(cwd, ".interlinked");
	if (existsSync(configDir)) {
		rmSync(configDir, { recursive: true, force: true });
		return true;
	}
	return false;
}

// ===========================================
// Hook Installation — All Clients
// ===========================================

interface InstallResult {
	client: ClientName;
	installed: boolean;
	events: string[];
	error?: string;
}

/**
 * Per-client install/uninstall configuration.
 * To add a new client: add an entry here and implement the install/uninstall functions.
 */
interface ClientInstallEntry {
	events: readonly string[];
	install: (cwd: string, hookScriptPath: string) => void;
	uninstall: (cwd: string) => boolean;
}

const CLIENT_INSTALL_REGISTRY: Record<ClientName, ClientInstallEntry> = {
	claude: {
		events: CLAUDE_HOOK_EVENTS,
		install: installAllClaudeHooks,
		uninstall: uninstallAllClaudeHooks,
	},
	copilot: {
		events: COPILOT_HOOK_EVENTS,
		install: installCopilotHooks,
		uninstall: uninstallCopilotHooks,
	},
	gemini: {
		events: GEMINI_HOOK_EVENTS,
		install: installGeminiHooks,
		uninstall: uninstallGeminiHooks,
	},
	// Future clients:
	// cursor: { events: CURSOR_HOOK_EVENTS, install: installCursorHooks, uninstall: uninstallCursorHooks },
};

/**
 * Install hooks into all specified clients.
 * Uses CLIENT_INSTALL_REGISTRY — add new clients there, not here.
 */
export function installAllHooks(
	cwd: string,
	hookScriptPath: string,
	clients: ClientName[],
): InstallResult[] {
	return clients.map((client) => {
		const entry = CLIENT_INSTALL_REGISTRY[client];
		if (!entry) {
			return { client, installed: false, events: [], error: `Unknown client: ${client}` };
		}
		try {
			entry.install(cwd, hookScriptPath);
			return { client, installed: true, events: [...entry.events] };
		} catch (e) {
			return {
				client,
				installed: false,
				events: [],
				error: e instanceof Error ? e.message : String(e),
			};
		}
	});
}

/**
 * Uninstall hooks from all specified clients.
 * Uses CLIENT_INSTALL_REGISTRY — add new clients there, not here.
 */
export function uninstallAllHooks(cwd: string, clients: ClientName[]): InstallResult[] {
	return clients.map((client) => {
		const entry = CLIENT_INSTALL_REGISTRY[client];
		if (!entry) {
			return { client, installed: false, events: [], error: `Unknown client: ${client}` };
		}
		try {
			const removed = entry.uninstall(cwd);
			return { client, installed: false, events: removed ? [...entry.events] : [] };
		} catch (e) {
			return {
				client,
				installed: false,
				events: [],
				error: e instanceof Error ? e.message : String(e),
			};
		}
	});
}

// ===========================================
// Claude Code — Full 14-Event Installation
// ===========================================

function getClaudeSettingsPath(cwd: string): string {
	return join(cwd, ".claude", "settings.json");
}

function installAllClaudeHooks(cwd: string, hookScriptPath: string): void {
	// Refuse to install if a parent directory already has interlinked hooks.
	// Claude Code merges hooks from all .claude/settings.json files in the path,
	// so duplicate registrations cause "2 PostToolUse hooks ran" and can swallow output.
	const parentWithHooks = findParentWithHooks(cwd, join(".claude", "settings.json"));
	if (parentWithHooks) {
		console.error(
			`\n⚠️  Skipping Claude hook installation — hooks already installed at ${parentWithHooks}/.claude/settings.json\n` +
				"   Claude Code merges hooks from all .claude/settings.json files in the path,\n" +
				"   so installing here would cause duplicate hooks.\n" +
				`   Run \`interlinked enable\` from ${parentWithHooks} instead.\n`,
		);
		return;
	}

	const settingsPath = getClaudeSettingsPath(cwd);
	const settings = readJsonFile(settingsPath) || {};

	if (!settings.hooks) settings.hooks = {};
	const hooks = settings.hooks as JsonObject;

	const hookCommand = buildHookCommand(hookScriptPath);

	for (const eventName of CLAUDE_HOOK_EVENTS) {
		installHookEntry(hooks, eventName, hookCommand);
	}

	writeJsonFile(settingsPath, settings);
}

/**
 * Walk up from cwd to the git root checking if any ancestor already has
 * interlinked hooks in the given settings file. Returns the ancestor path
 * if found, or null if no parent has hooks.
 */
function findParentWithHooks(cwd: string, settingsSubpath: string): string | null {
	const gitRoot = findProjectRoot(cwd);
	let dir = dirname(cwd);
	const stopAt = gitRoot || parse(cwd).root;

	while (dir.length >= stopAt.length) {
		const settingsPath = join(dir, settingsSubpath);
		if (existsSync(settingsPath)) {
			try {
				const content = readFileSync(settingsPath, "utf-8");
				if (content.includes(INTERLINKED_MARKER)) {
					return dir;
				}
			} catch (_err) {
				/* intentional: settings file unreadable — keep walking up */
			}
		}
		const parent = dirname(dir);
		if (parent === dir) break;
		dir = parent;
	}
	return null;
}

function cleanClaudeHooksFromFile(settingsPath: string): boolean {
	if (!existsSync(settingsPath)) return false;

	const settings = readJsonFile(settingsPath);
	if (!settings?.hooks) return false;

	const hooks = settings.hooks as JsonObject;
	let changed = false;
	for (const eventName of CLAUDE_HOOK_EVENTS) {
		const entries = hooks[eventName] as HookEntry[] | undefined;
		if (!entries) continue;

		const filtered = entries.filter(
			(entry: HookEntry) =>
				!entry.hooks?.some((h) => h.command?.includes(INTERLINKED_MARKER)),
		);

		if (filtered.length !== entries.length) {
			hooks[eventName] = filtered.length > 0 ? filtered : undefined;
			changed = true;
		}
	}

	// Clean up empty hooks object
	if (Object.values(hooks).every((v) => v === undefined)) {
		delete settings.hooks;
	}

	if (changed) {
		writeJsonFile(settingsPath, settings);
	}
	return changed;
}

function uninstallAllClaudeHooks(cwd: string): boolean {
	let changed = false;

	// Clean hooks from cwd's .claude/settings.json
	changed = cleanClaudeHooksFromFile(getClaudeSettingsPath(cwd)) || changed;

	// Also clean hooks from the git root's .claude/settings.json
	const projectRoot = findProjectRoot(cwd);
	if (projectRoot && projectRoot !== cwd) {
		changed = cleanClaudeHooksFromFile(getClaudeSettingsPath(projectRoot)) || changed;
	}

	return changed;
}

// ===========================================
// GitHub Copilot CLI — Install/Uninstall
// ===========================================

function getCopilotHooksPath(cwd: string): string {
	return join(cwd, ".github", "hooks", "hooks.json");
}

function installCopilotHooks(cwd: string, hookScriptPath: string): void {
	const hooksPath = getCopilotHooksPath(cwd);
	const dir = dirname(hooksPath);
	if (!existsSync(dir)) {
		mkdirSync(dir, { recursive: true });
	}

	const hookCommand = buildHookCommand(hookScriptPath);

	// Read existing config or start fresh
	let config: { version: number; hooks: Record<string, unknown[]> };
	if (existsSync(hooksPath)) {
		try {
			config = JSON.parse(readFileSync(hooksPath, "utf-8"));
			if (!config.hooks || typeof config.hooks !== "object") {
				config.hooks = {};
			}
		} catch (_err) {
			/* intentional: malformed hooks.json — start over with empty config */
			config = { version: 1, hooks: {} };
		}
	} else {
		config = { version: 1, hooks: {} };
	}

	for (const eventName of COPILOT_HOOK_EVENTS) {
		if (!config.hooks[eventName]) config.hooks[eventName] = [];
		const entries = config.hooks[eventName] as Array<{ type: string; bash?: string }>;

		// Check if already installed — update if stale
		const existing = entries.find((e) => e.bash?.includes(INTERLINKED_MARKER));
		if (existing) {
			if (existing.bash !== hookCommand) {
				existing.bash = hookCommand;
			}
			continue;
		}

		entries.push({
			type: "command",
			bash: hookCommand,
		});
	}

	config.version = 1;
	writeFileSync(hooksPath, `${JSON.stringify(config, null, 2)}\n`);
}

function uninstallCopilotHooks(cwd: string): boolean {
	const hooksPath = getCopilotHooksPath(cwd);
	if (!existsSync(hooksPath)) return false;

	let config: { version?: number; hooks?: Record<string, unknown[]> };
	try {
		config = JSON.parse(readFileSync(hooksPath, "utf-8"));
	} catch (_err) {
		/* intentional: unreadable copilot hooks.json — nothing to uninstall */
		return false;
	}
	if (!config.hooks) return false;

	let changed = false;
	for (const eventName of COPILOT_HOOK_EVENTS) {
		const entries = config.hooks[eventName] as
			| Array<{ type: string; bash?: string }>
			| undefined;
		if (!entries) continue;

		const filtered = entries.filter((e) => !e.bash?.includes(INTERLINKED_MARKER));
		if (filtered.length !== entries.length) {
			config.hooks[eventName] = filtered.length > 0 ? filtered : [];
			changed = true;
		}
	}

	if (changed) {
		// Remove file entirely if no hooks remain
		const hasHooks = Object.values(config.hooks).some(
			(arr) => Array.isArray(arr) && arr.length > 0,
		);
		if (!hasHooks) {
			rmSync(hooksPath, { force: true });
		} else {
			writeFileSync(hooksPath, `${JSON.stringify(config, null, 2)}\n`);
		}
	}

	return changed;
}

// ===========================================
// Shared Hook Entry Helper
// ===========================================

function installHookEntry(hooks: JsonObject, eventName: string, command: string): void {
	if (!hooks[eventName]) hooks[eventName] = [];
	const entries = hooks[eventName] as HookEntry[];

	// Check if already installed
	const existing = entries.find((entry) =>
		entry.hooks?.some((h) => h.command?.includes(INTERLINKED_MARKER)),
	);

	if (existing) {
		// Update command if it points to a stale path (e.g. .claude/hooks/ → .interlinked/hooks/)
		const hook = existing.hooks?.find((h) => h.command?.includes(INTERLINKED_MARKER));
		if (hook && hook.command !== command) {
			hook.command = command;
		}
		// Update matcher for PostToolUse (was "" catch-all, now scoped to mutating tools)
		const expectedMatcher = eventName === "PostToolUse" ? POST_TOOL_USE_MATCHER : "";
		if (existing.matcher !== expectedMatcher) {
			existing.matcher = expectedMatcher;
		}
		return;
	}

	entries.push({
		matcher: eventName === "PostToolUse" ? POST_TOOL_USE_MATCHER : "",
		hooks: [{ type: "command", command }],
	});
}

// ===========================================
// .gitignore Management
// ===========================================

const GITIGNORE_ENTRIES = [
	".interlinked/config.local.json",
	".interlinked/activity.jsonl",
	".interlinked/realtime-retry.jsonl",
	".interlinked/sync-errors.jsonl",
	".interlinked/sync-state.json",
	".interlinked/sessions/",
	".interlinked/checkpoints.json",
	".interlinked/guard-cache.json",
	".interlinked/guard-rules.local.json",
	".interlinked/harness.sock",
	".interlinked/harness.pid",
	".interlinked/pending-quality-warnings.json",
	".interlinked/index/",
	".interlinked/error-history.jsonl",
];

/**
 * Ensure .gitignore contains entries for Interlinked CLI local files.
 * Skips data-related entries when data dir is outside the repo.
 * Returns true if modifications were made.
 */
export function ensureGitignore(cwd: string): boolean {
	const gitignorePath = join(cwd, ".gitignore");
	let content = "";

	if (existsSync(gitignorePath)) {
		content = readFileSync(gitignorePath, "utf-8");
	}

	// Check if data dir is external (skip data gitignore entries)
	const dataRelated = new Set([
		".interlinked/activity.jsonl",
		".interlinked/realtime-retry.jsonl",
		".interlinked/sync-errors.jsonl",
		".interlinked/sync-state.json",
		".interlinked/sessions/",
		".interlinked/checkpoints.json",
	]);
	const envDataDir = process.env.INTERLINKED_DATA_DIR?.trim();
	const isExternalData = envDataDir && !envDataDir.startsWith(cwd);

	const lines = content.split("\n");
	const missingEntries: string[] = [];

	for (const entry of GITIGNORE_ENTRIES) {
		if (isExternalData && dataRelated.has(entry)) continue;
		const alreadyPresent = lines.some(
			(line) => line.trim() === entry || line.trim() === entry.replace(/\/$/, ""),
		);
		if (!alreadyPresent) {
			missingEntries.push(entry);
		}
	}

	if (missingEntries.length === 0) return false;

	// Add a section header if we're adding entries
	const additions: string[] = [];
	if (!content.includes("# Interlinked CLI") && !content.includes("# Interlinked")) {
		additions.push("");
		additions.push("# Interlinked CLI (local agent config)");
	}
	additions.push(...missingEntries);

	const newContent = `${content.trimEnd()}\n${additions.join("\n")}\n`;
	writeFileSync(gitignorePath, newContent);
	return true;
}

// ===========================================
// Hook Manager Detection
// ===========================================

interface HookManagerInfo {
	name: string;
	detected_at: string;
}

/**
 * Detect common git hook managers in the project.
 */
export function detectHookManagers(cwd: string): HookManagerInfo[] {
	const managers: HookManagerInfo[] = [];

	// Husky
	const huskyDir = join(cwd, ".husky");
	if (existsSync(huskyDir)) {
		managers.push({ name: "husky", detected_at: ".husky/" });
	} else {
		// Check package.json for husky references
		const pkgPath = join(cwd, "package.json");
		if (existsSync(pkgPath)) {
			try {
				const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
				if (
					pkg.devDependencies?.husky ||
					pkg.dependencies?.husky ||
					pkg.scripts?.prepare?.includes("husky")
				) {
					managers.push({ name: "husky", detected_at: "package.json" });
				}
			} catch (_err) {
				/* intentional: malformed package.json — skip husky detection */
			}
		}
	}

	// Lefthook
	const lefthookFiles = ["lefthook.yml", ".lefthook.yml", "lefthook.yaml", ".lefthook.yaml"];
	for (const file of lefthookFiles) {
		if (existsSync(join(cwd, file))) {
			managers.push({ name: "lefthook", detected_at: file });
			break;
		}
	}
	if (!managers.some((m) => m.name === "lefthook")) {
		const pkgPath = join(cwd, "package.json");
		if (existsSync(pkgPath)) {
			try {
				const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
				if (pkg.devDependencies?.lefthook || pkg.dependencies?.lefthook) {
					managers.push({ name: "lefthook", detected_at: "package.json" });
				}
			} catch (_err) {
				/* intentional: malformed package.json — skip lefthook detection */
			}
		}
	}

	// Overcommit
	if (existsSync(join(cwd, ".overcommit.yml"))) {
		managers.push({ name: "overcommit", detected_at: ".overcommit.yml" });
	}

	return managers;
}

// ===========================================
// JSON File Helpers
// ===========================================

function readJsonFile(path: string): JsonObject | null {
	if (!existsSync(path)) return null;
	try {
		return JSON.parse(readFileSync(path, "utf-8"));
	} catch (_err) {
		/* intentional: malformed JSON — caller treats null as "no config" */
		return null;
	}
}

function writeJsonFile(path: string, data: JsonObject): void {
	const dir = dirname(path);
	if (!existsSync(dir)) {
		mkdirSync(dir, { recursive: true });
	}
	writeFileSync(path, `${JSON.stringify(data, null, 2)}\n`);
}

function buildHookCommand(hookScriptPath: string): string {
	const escapedPath = hookScriptPath.replace(/(["\\`$])/g, "\\$1");
	// Guard: exit silently if the script doesn't exist (e.g., agent running from a subdirectory)
	return `test -f "${escapedPath}" && node "${escapedPath}" || true`;
}
