// Auto-extracted from hooks.ts by the sweep refactor.
// The big template literal emitting `.interlinked/hooks/interlinked-activity.mjs`
// was split out of hooks.ts to keep that file focused on install/uninstall logic.
//
// This file holds the DATA — the .mjs runtime script that gets written into
// user projects by `interlinked enable`. The generated .mjs must remain
// self-contained (no imports from the CLI package) because it is deployed
// standalone and must work even if the CLI is uninstalled.
//
// Do not edit the pattern strings (like `rm -rf`, `catch (_err) { void 0; /* intentional: no-op */ }`) inside this
// template — they are data used at runtime, not code.

//
// The template is assembled from sibling chunk modules under `./hook-template-chunks/`.
// Each chunk is a contiguous slice of the generated .mjs and exports a string constant.
// `buildHookScript` stitches them back together; the byte output is identical to the
// pre-split template. See `hooks-template.test.ts` for the byte-level invariants.

import { EVENT_NORMALIZERS_CHUNK } from "./hook-template-chunks/event-normalizers.js";
import { GUARDS_INLINE_CHUNK } from "./hook-template-chunks/guards-inline.js";
import { PROVIDER_RESPONSES_CHUNK } from "./hook-template-chunks/provider-responses.js";
import { REDACTION_CHUNK } from "./hook-template-chunks/redaction.js";
import { SESSION_STATE_CHUNK } from "./hook-template-chunks/session-state.js";

/**
 * Build the Interlinked activity hook script (`.mjs`) for the given version.
 * The version is embedded in the first comment for staleness detection.
 */
export function buildHookScript(version: string): string {
	return `#!/usr/bin/env node
// interlinked-hook-version: ${version}
// ===========================================
// Interlinked CLI Activity Hook (auto-generated)
// ===========================================
// Bridges lifecycle and tool-use events from AI coding agents into Interlinked CLI local logs
// and the server.
// Supports: Claude Code (14 events), GitHub Copilot CLI
// Generated by: interlinked enable
// Do not edit manually — re-run 'interlinked enable' to regenerate.

import { readFileSync, existsSync, appendFileSync, writeFileSync, mkdirSync, openSync, readSync, closeSync, statSync, unlinkSync } from "node:fs";
import { join, dirname } from "node:path";
import { createConnection } from "node:net";
import { execSync, execFileSync, spawn as nodeSpawn } from "node:child_process";

const CWD = process.cwd();

// --- Resolve data directory (mirrors config.ts getDataDir logic) ---
function resolveDataDir() {
    if (process.env.INTERLINKED_DATA_DIR) return process.env.INTERLINKED_DATA_DIR;
    const configDir = process.env.INTERLINKED_HOME || join(CWD, ".interlinked");
    const localConfigPath = join(configDir, "config.local.json");
    if (existsSync(localConfigPath)) {
        try {
            const lc = JSON.parse(readFileSync(localConfigPath, "utf-8"));
            if (lc.data_dir) return lc.data_dir;
        } catch (_err) { void 0; /* intentional: no-op */ }
    }
    return configDir;
}

function resolveConfigDir() {
    return process.env.INTERLINKED_HOME || join(CWD, ".interlinked");
}

const CONFIG_DIR = resolveConfigDir();
const DATA_DIR = resolveDataDir();

// Walk up from CWD looking for the nearest .interlinked/harness.sock.
// Lets a harness daemon rooted at a monorepo ancestor serve subdir edits
// without each subdir needing its own daemon. Falls back to the local
// CONFIG_DIR/harness.sock if no ancestor socket exists (so first-run
// scenarios — before any daemon is started — still see the local path).
function resolveHarnessSocket() {
    let dir = CWD;
    for (let i = 0; i < 10; i++) {
        const candidate = join(dir, ".interlinked", "harness.sock");
        if (existsSync(candidate)) return candidate;
        const parent = dirname(dir);
        if (parent === dir) break;
        dir = parent;
    }
    return join(CONFIG_DIR, "harness.sock");
}
const CONFIG_LOCAL_PATH = join(CONFIG_DIR, "config.local.json");
const CONFIG_SHARED_PATH = join(CONFIG_DIR, "config.json");
const ACTIVITY_PATH = join(DATA_DIR, "activity.jsonl");
const SESSIONS_DIR = join(DATA_DIR, "sessions");
const SYNC_STATE_PATH = join(DATA_DIR, "sync-state.json");
const REALTIME_RETRY_PATH = join(DATA_DIR, "realtime-retry.jsonl");
const SYNC_ERRORS_PATH = join(DATA_DIR, "sync-errors.jsonl");

// Track active subagent for attribution
let activeSubagent = null;

${REDACTION_CHUNK}

// ===========================================
// Harness Connection — Guard evaluation via Unix socket
// ===========================================
// Connects to the Interlinked Harness server for PreToolUse guard evaluation.
// Falls back to inline pattern matching if harness is not running.

const HARNESS_SOCK_PATH = resolveHarnessSocket();
const PENDING_WARNINGS_PATH = join(DATA_DIR, "pending-quality-warnings.json");
const HARNESS_PRE_TIMEOUT_MS = 5000;  // PreToolUse: allows grep acceleration (ripgrep on candidates)
const HARNESS_POST_TIMEOUT_MS = 15000; // PostToolUse: slow, quality checks run tsc/lint

/**
 * Flush any pending quality warnings from a previous PostToolUse to stderr.
 * Called at the start of every PreToolUse so the agent sees warnings
 * from the file it just edited BEFORE its next tool call.
 *
 * BLOCKING: If the harness is still running quality checks (marker file exists),
 * waits up to 12 seconds for checks to complete. This ensures the agent sees
 * all quality issues before proceeding.
 */
function flushPendingWarnings() {
    try {
        const markerPath = join(DATA_DIR, "quality-check-in-progress");

        // Wait for harness to finish quality checks (blocks the agent).
        if (existsSync(markerPath)) {
            const maxWaitMs = 12000;
            const start = Date.now();
            while (existsSync(markerPath) && (Date.now() - start) < maxWaitMs) {
                const waitUntil = Date.now() + 50;
                while (Date.now() < waitUntil) { /* spin */ }
            }
            // Clean up stale marker if harness timed out
            if (existsSync(markerPath)) {
                try { unlinkSync(markerPath); } catch (_err) { void 0; /* intentional: no-op */ }
            }
        }

        if (!existsSync(PENDING_WARNINGS_PATH)) return;
        const raw = readFileSync(PENDING_WARNINGS_PATH, "utf-8");
        const warnings = JSON.parse(raw);
        if (Array.isArray(warnings) && warnings.length > 0) {
            process.stderr.write("\\n[interlinked] Quality issues from previous edit:\\n");
            for (const w of warnings) {
                process.stderr.write(w + "\\n");
            }
            process.stderr.write("\\n");
        }
        unlinkSync(PENDING_WARNINGS_PATH);
    } catch {
        // Stale or corrupt file — clean up silently
        try { unlinkSync(PENDING_WARNINGS_PATH); } catch (_err) { void 0; /* intentional: no-op */ }
    }
}

/**
 * Auto-heal a stale harness: detect dead PID / orphaned socket and restart.
 * Called when evaluateViaHarness returns null (connection failed).
 * Rate-limited: at most once per 30 seconds per session to avoid restart storms.
 */
const HARNESS_PID_PATH = join(CONFIG_DIR, "harness.pid");
let lastRestartAttemptMs = 0;
const RESTART_COOLDOWN_MS = 30000;
let restartAttempted = false;

function tryHealHarness() {
    const now = Date.now();
    if (now - lastRestartAttemptMs < RESTART_COOLDOWN_MS) return false;
    lastRestartAttemptMs = now;

    try {
        // Check if PID file exists
        const pidFileExists = existsSync(HARNESS_PID_PATH);
        const sockFileExists = existsSync(HARNESS_SOCK_PATH);

        if (!pidFileExists && !sockFileExists) {
            // Harness was never started — try to start it
            if (!restartAttempted) {
                restartAttempted = true;
                process.stderr.write("[interlinked:harness] Harness not running — starting automatically...\\n");
                tryAutoStartHarness();
                return true;
            }
            return false;
        }

        // Check if the PID is still alive
        if (pidFileExists) {
            try {
                const pid = parseInt(readFileSync(HARNESS_PID_PATH, "utf-8").trim(), 10);
                if (!isNaN(pid)) {
                    try {
                        process.kill(pid, 0); // signal 0 = check existence
                        // Process is alive but socket failed — might be starting up, wait
                        return false;
                    } catch (_err) { void 0; /* intentional: Process is dead — stale PID file */ }
                }
            } catch (_err) { void 0; /* intentional: no-op */ }
        }

        // Harness is stale: clean up and restart
        process.stderr.write("[interlinked:harness] Harness is stale — restarting...\\n");
        try { unlinkSync(HARNESS_PID_PATH); } catch (_err) { void 0; /* intentional: no-op */ }
        try { unlinkSync(HARNESS_SOCK_PATH); } catch (_err) { void 0; /* intentional: no-op */ }

        // Also clean up stale marker files that would block the agent
        const markerPath = join(DATA_DIR, "quality-check-in-progress");
        try { unlinkSync(markerPath); } catch (_err) { void 0; /* intentional: no-op */ }

        tryAutoStartHarness();
        restartAttempted = true;
        return true;
    } catch {
        return false;
    }
}

/**
 * Send an event to the harness server and get a decision.
 * Returns null if harness is not available (fallback to inline).
 * Timeout varies: PreToolUse is fast (500ms), PostToolUse allows time for quality checks (15s).
 */
function evaluateViaHarness(harnessEvent) {
    const isPreTool = harnessEvent.hook_event === "PreToolUse" || harnessEvent.hook_event === "BeforeTool";
    const timeoutMs = isPreTool ? HARNESS_PRE_TIMEOUT_MS : HARNESS_POST_TIMEOUT_MS;

    return new Promise((resolve) => {
        if (!existsSync(HARNESS_SOCK_PATH)) {
            resolve(null); // Harness not running
            return;
        }
        const timeout = setTimeout(() => {
            try { sock.destroy(); } catch (_err) { void 0; /* intentional: no-op */ }
            resolve(null); // Timeout — fall back to inline
        }, timeoutMs);

        const sock = createConnection(HARNESS_SOCK_PATH);
        let responseData = "";

        sock.on("connect", () => {
            sock.write(JSON.stringify(harnessEvent) + "\\n");
        });
        let resolved = false;
        sock.on("data", (chunk) => {
            responseData += chunk.toString();
            // Look for newline-delimited JSON
            const newlineIdx = responseData.indexOf("\\n");
            if (newlineIdx !== -1 && !resolved) {
                resolved = true;
                clearTimeout(timeout);
                sock.destroy();
                try {
                    resolve(JSON.parse(responseData.slice(0, newlineIdx)));
                } catch {
                    resolve(null);
                }
            }
        });
        sock.on("error", () => {
            if (resolved) return;
            resolved = true;
            clearTimeout(timeout);
            resolve(null);
        });
        sock.on("close", () => {
            if (resolved) return;
            resolved = true;
            clearTimeout(timeout);
            if (responseData.trim()) {
                try { resolve(JSON.parse(responseData.trim())); } catch { resolve(null); }
            } else {
                resolve(null);
            }
        });
    });
}

const INLINE_STRONG_TYPING_PATTERNS = [
    /:\\s*any\\s*[;,)>=[\\]|&\\n\\r]/,
    /<\\s*any\\s*[>,]/,
    /\\bas\\s+any\\b/,
    /\\)\\s*:\\s*any\\b/,
    /\\bas\\s+unknown\\b/,
];

function stripInlineStringLiterals(line) {
    let result = line.replace(/"(?:[^"\\\\]|\\\\.)*"/g, '""');
    result = result.replace(/'(?:[^'\\\\]|\\\\.)*'/g, "''");
    result = result.replace(/\`(?:[^\`\\\\]|\\\\.)*\`/g, "\`\`");
    return result;
}

function findInlineStrongTypingMatches(content) {
    const lines = content.split("\\n");
    const matches = [];
    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        const trimmed = line.trim();
        if (trimmed.startsWith("//") || trimmed.startsWith("*") || trimmed.startsWith("/*")) continue;
        if (/^\\s*['"\`]/.test(line) && /['"\`]\\s*[;,]?\\s*$/.test(line)) continue;
        const stripped = stripInlineStringLiterals(line);
        for (const pattern of INLINE_STRONG_TYPING_PATTERNS) {
            if (pattern.test(stripped)) {
                matches.push({ line: i + 1, text: trimmed.slice(0, 120) });
                break;
            }
        }
    }
    return matches;
}

function inlinePostToolFallback(rawInput, event) {
    const toolName = event.tool_name || rawInput.tool_name || null;
    const toolInput = rawInput.tool_input || event.tool_input || null;
    const filePath = extractFilePath(toolName, toolInput);
    if (!filePath || !existsSync(filePath)) return null;
    if (!/\.(?:tsx?|jsx?|mjs|cjs)$/.test(filePath)) return null;
    let content = "";
    try {
        content = readFileSync(filePath, "utf-8");
    } catch {
        return null;
    }
    const matches = findInlineStrongTypingMatches(content);
    if (matches.length === 0) {
        return { summary: "inline strong_typing clean" };
    }
    const first = matches[0];
    const plural = matches.length === 1 ? "" : "s";
    return {
        warnings: [
            "[interlinked:strong_typing] " + filePath + " contains " + matches.length
                + " explicit any/unknown escape hatch occurrence" + plural
                + ". First: L" + first.line + " " + first.text,
        ],
        summary: "inline strong_typing warning",
    };
}

${GUARDS_INLINE_CHUNK}

/**
 * Try to auto-start the harness daemon on SessionStart.
 * Fire-and-forget, non-blocking. If Bun is not found, warn once.
 * First PreToolUse uses inline fallback; subsequent calls use harness once it's up.
 */
function tryAutoStartHarness() {
    try {
        // Find harness server.js — prefer pre-compiled JS for fast startup
        const candidates = [
            join(CONFIG_DIR, "..", "cli", "dist", "harness", "server.js"),
            join(CONFIG_DIR, "..", "node_modules", "interlinked-cli", "dist", "harness", "server.js"),
            join(CONFIG_DIR, "..", "node_modules", ".bin", "interlinked-harness"),
        ];

        // Also check global npm paths
        try {
            const globalDir = execSync("npm root -g", { encoding: "utf-8", timeout: 2000 }).trim();
            candidates.push(join(globalDir, "interlinked-cli", "dist", "harness", "server.js"));
        } catch (_err) { void 0; /* intentional: no-op */ }

        // Fall back to TypeScript source (slower — requires tsx or similar)
        candidates.push(
            join(CONFIG_DIR, "..", "cli", "src", "harness", "server.ts"),
            join(CONFIG_DIR, "..", "node_modules", "interlinked-cli", "src", "harness", "server.ts"),
        );

        let serverPath = null;
        for (const p of candidates) {
            if (existsSync(p)) { serverPath = p; break; }
        }

        if (!serverPath) {
            process.stderr.write("[interlinked] Harness server not found — inline fallback active.\\n");
            return;
        }

        // Spawn detached harness daemon using node
        const nodePath = process.execPath;
        const child = nodeSpawn(nodePath, [serverPath, "--cwd", CWD], {
            detached: true,
            stdio: "ignore",
        });
        child.unref();

        process.stderr.write("[interlinked] Starting harness daemon...\\n");
    } catch (_err) { void 0; /* intentional: Never block the agent — silently fall back to inline guard */ }
}

// --- Last-check file for status line visibility ---
const LAST_CHECK_PATH = join(DATA_DIR, "last-check.txt");
function writeLastCheck(summary) {
    try { writeFileSync(LAST_CHECK_PATH, summary + "\\n"); } catch (_err) { void 0; /* intentional: no-op */ }
}

${SESSION_STATE_CHUNK}

async function main() {
    const localConfig = existsSync(CONFIG_LOCAL_PATH)
        ? safeReadConfig(CONFIG_LOCAL_PATH)
        : null;
    const sharedConfig = existsSync(CONFIG_SHARED_PATH)
        ? safeReadConfig(CONFIG_SHARED_PATH)
        : null;
    if (!localConfig && !sharedConfig) process.exit(0);
    const config = {
        ...(sharedConfig || {}),
        ...(localConfig || {}),
    };

    // Resolve active server entry — pairs server_url with workspace_id
    const activeKey = config.active_server || "production";
    const activeServer = config.servers?.[activeKey];
    const serverUrl = activeServer?.server_url || config.server_url;
    const workspaceId = activeServer?.workspace_id || config.workspace_id;
    const workspaceKey = config.default_workspace_key || "main";
    const projectKey = config.default_project || "main";
    const syncMode = config.sync_mode || "realtime";

    // Resolve auth — prefer access_token, fall back to agent_handle
    const authHeader = config.access_token
        ? "Bearer " + config.access_token
        : config.agent_handle
          ? "Bearer " + config.agent_handle
          : null;

    // Retry any previously buffered realtime payloads first.
    if (syncMode !== "local" && serverUrl) {
        await flushRealtimeRetry(serverUrl, authHeader);
    }

    // --- Client Handler Registry ---
    // Each entry: { name, detect(input, source), normalize(input) }
    // First match wins. Claude is the catch-all for stdin — keep it last.
    // Codex's payload shape mirrors Claude's, so it must be detected via
    // the INTERLINKED_CLIENT environment variable (set by the hook command
    // installed into .codex/hooks.json) before falling through to Claude.
    // To add a new client (Cursor, Opencode, Amp, etc.):
    //   1. Add a normalizer function (normalizeXxxEvent)
    //   2. Add a detector entry below
    const RUNNER_ENV = process.env.INTERLINKED_CLIENT || "";
    const CLIENT_HANDLERS = [
        { name: "copilot", detect: (input, src) => src === "stdin" && !input.hook_event_name && typeof input.timestamp === "number", normalize: normalizeCopilotEvent },
        { name: "codex", detect: (_input, src) => src === "stdin" && RUNNER_ENV === "codex", normalize: normalizeCodexEvent },
        // Future clients — add detectors here, before the Claude catch-all.
        // Example shape (NOT active code — documentation for adding a new handler):
        //   Example: { name: "cursor",   detect: (input, src) => src === "stdin" && !!input.cursor_session_id, normalize: normalizeCursorEvent }
        //   Example: { name: "opencode", detect: (input, src) => src === "stdin" && input.client === "opencode", normalize: normalizeOpencodeEvent }
        //   Example: { name: "amp",      detect: (input, src) => src === "stdin" && !!input.amp_session,       normalize: normalizeAmpEvent }
        { name: "claude", detect: (input, src) => src === "stdin", normalize: normalizeClaudeEvent },
    ];

    // Parse input from stdin (Claude Code, GitHub Copilot CLI, future clients)
    let rawInput;
    let hookEvent, sessionId;

    let stdin = "";
    try { stdin = readFileSync(0, "utf-8"); } catch { process.exit(0); }
    if (!stdin.trim()) process.exit(0);
    try { rawInput = JSON.parse(stdin); } catch { process.exit(0); }
    const inputSource = "stdin";

    hookEvent = rawInput.hook_event_name || null;
    sessionId = rawInput.session_id || rawInput.sessionId || null;

    // Detect client and normalize event
    let event = null;
    let detectedClient = "unknown";
    for (const handler of CLIENT_HANDLERS) {
        if (handler.detect(rawInput, inputSource)) {
            event = handler.normalize(rawInput);
            detectedClient = handler.name;
            break;
        }
    }

    if (!event) process.exit(0);

    // Resolve hookEvent from normalized event for clients that don't send hook_event_name
    // (Copilot infers the event type from payload shape in its normalizer)
    if (!hookEvent && event.hook_event) {
        hookEvent = event.hook_event;
    }

    // Attach common fields available on all Claude Code events
    if (rawInput.cwd) event.cwd = rawInput.cwd;
    if (rawInput.permission_mode) event.permission_mode = rawInput.permission_mode;
    if (rawInput.transcript_path) event.transcript_path = rawInput.transcript_path;

    // Extract new thinking blocks from transcript (real-time capture)
    const transcriptPath = rawInput.transcript_path || null;
    const thinkingContent = extractNewThinking(transcriptPath);
    if (thinkingContent) event.thinking = thinkingContent;

    const agentName = resolveAgentName(config, rawInput, event, detectedClient, sessionId);

    // ===========================================
    // SessionStart: auto-start harness if socket missing
    // ===========================================
    if (hookEvent === "SessionStart" && !existsSync(HARNESS_SOCK_PATH)) {
        tryAutoStartHarness();
    }

    // ===========================================
    // Guard Evaluation (PreToolUse / BeforeTool)
    // ===========================================
${PROVIDER_RESPONSES_CHUNK}

    // For PreToolUse events: evaluate via harness (or inline fallback).
    // If blocked, output decision to stdout and exit.
    // The local write and server POST still happen for audit trail.

    const isPreTool = hookEvent === "PreToolUse" || hookEvent === "BeforeTool";
    const isPostTool = hookEvent === "PostToolUse" || hookEvent === "AfterTool" || hookEvent === "PostToolUseFailure";
    const isUserPrompt = hookEvent === "UserPromptSubmit" || hookEvent === "BeforeAgent";
    let guardDecision = null;

    // ===========================================
    // UserPromptSubmit: forward to harness for PII scan
    // ===========================================
    // If the content scanner is enabled and finds PII in the prompt, the
    // harness returns a redacted copy which we substitute into event.prompt
    // before the local JSONL write below. Never blocks — users can always
    // submit their prompt; we only mask the stored record.
    if (isUserPrompt && event.prompt) {
        const promptHarnessEvent = {
            hook_event: hookEvent,
            session_id: sessionId,
            agent_source: detectedClient,
            agent_name: agentName,
            tool_name: null,
            tool_input: null,
            prompt: event.prompt,
            cwd: rawInput.cwd || event.cwd || null,
            model: event.model || null,
            timestamp: new Date().toISOString(),
        };
        try {
            const promptDecision = await evaluateViaHarness(promptHarnessEvent);
            if (promptDecision && typeof promptDecision.redacted_prompt === "string") {
                event.prompt = promptDecision.redacted_prompt;
                if (event.tool_input_summary) {
                    // Keep the 200-char summary in sync with the masked prompt.
                    event.tool_input_summary = promptDecision.redacted_prompt.slice(0, 200);
                }
            }
        } catch (_err) { void 0; /* fail-open: raw prompt still gets inline secrets scrub via scrubPayload below */ }
    }

    // On PreToolUse: flush any pending quality warnings from the previous PostToolUse.
    // For Claude: writes to stderr (agents see it inline before their next action).
    // For Copilot: stderr is ignored, so we must DENY the next PreToolUse with the
    // warnings as the reason — it's the only way to surface feedback to the agent.
    if (isPreTool) {
        if (detectedClient === "copilot") {
            // Copilot ignores both stderr and non-deny stdout from hooks.
            // Quality warnings are logged locally but cannot be surfaced to the agent.
            // Only destructive command blocks (permissionDecision: "deny") reach the agent.
            // Clear pending warnings silently so they don't accumulate.
            try {
                const markerPath = join(DATA_DIR, "quality-check-in-progress");
                if (existsSync(markerPath)) { try { unlinkSync(markerPath); } catch (_err) { void 0; /* intentional: no-op */ } }
                if (existsSync(PENDING_WARNINGS_PATH)) { unlinkSync(PENDING_WARNINGS_PATH); }
            } catch (_err) { void 0; /* intentional: no-op */ }
        } else {
            flushPendingWarnings();
        }
    }

    if (isPreTool) {
        const preStartMs = Date.now();
        const harnessEvent = {
            hook_event: hookEvent,
            session_id: sessionId,
            agent_source: detectedClient,
            agent_name: agentName,
            tool_name: event.tool_name || rawInput.tool_name || null,
            tool_input: rawInput.tool_input || event.tool_input || null,
            tool_use_id: rawInput.tool_use_id || event.tool_use_id || null,
            cwd: rawInput.cwd || event.cwd || null,
            model: event.model || null,
            timestamp: new Date().toISOString(),
        };

        guardDecision = await evaluateViaHarness(harnessEvent);

        if (!guardDecision) {
            // Harness unavailable — try to heal (auto-restart if stale)
            const healed = tryHealHarness();
            if (healed) {
                // Wait briefly for harness to come up, then retry once
                const retryDelay = Date.now() + 1500;
                while (Date.now() < retryDelay) { /* spin */ }
                guardDecision = await evaluateViaHarness(harnessEvent);
            }
        }

        if (!guardDecision) {
            guardDecision = inlineGuardCheck(hookEvent, harnessEvent.tool_name, rawInput.tool_input);
        }

        const preElapsedMs = Date.now() - preStartMs;

        if (guardDecision?.warnings && guardDecision.warnings.length > 0) {
            for (const w of guardDecision.warnings) {
                process.stderr.write(w + "\\n");
            }
        }

        // If blocked on PreToolUse, output decision to stdout and exit
        if (guardDecision?.decision === "block") {
            appendLocal(event, hookEvent, sessionId, agentName, workspaceKey, projectKey);
            appendGuardDecision("block", guardDecision, event, hookEvent, sessionId, agentName, workspaceKey, projectKey, preElapsedMs);
            updateSessionState(sessionId, agentName, event);

            if (guardDecision.grep_stats) {
                const stats = guardDecision.grep_stats;
                const selectivity = stats.selectivity_pct != null ? stats.selectivity_pct.toFixed(1) : "?";
                const header = "[interlinked:index] Searched " + stats.candidates + " candidate files (from " + stats.total_files + " total, " + selectivity + "% selectivity)";
                const body = guardDecision.reason || "No matches found.";
                console.log(JSON.stringify(formatProviderResponse("pre_block_grep", { reason: header + "\\n" + body })));
            } else {
                console.log(JSON.stringify(formatProviderResponse("pre_block", { reason: guardDecision.reason || "Blocked by Interlinked guard" })));
            }
            process.exit(0);
        }

        // "ask" → user confirmation required. Surface Claude Code's permission
        // prompt so the human approves per-call. Reason includes rule id and
        // instruction for context.
        if (guardDecision?.decision === "ask") {
            appendLocal(event, hookEvent, sessionId, agentName, workspaceKey, projectKey);
            appendGuardDecision("ask", guardDecision, event, hookEvent, sessionId, agentName, workspaceKey, projectKey, preElapsedMs);
            updateSessionState(sessionId, agentName, event);
            console.log(JSON.stringify(formatProviderResponse("pre_ask", {
                reason: guardDecision.reason || "Interlinked pre-block rule matched — please confirm.",
                systemMessage: guardDecision.system_message,
            })));
            process.exit(0);
        }

        // Log PreToolUse warnings as guard_warn events
        if (guardDecision?.decision === "allow" && guardDecision.warnings?.length > 0) {
            appendGuardDecision("warn", guardDecision, event, hookEvent, sessionId, agentName, workspaceKey, projectKey, preElapsedMs);
        }

        // Log allow decisions (no warnings) so guard history is complete
        if (guardDecision?.decision === "allow" && (!guardDecision.warnings || guardDecision.warnings.length === 0)) {
            appendGuardDecision("allow", guardDecision, event, hookEvent, sessionId, agentName, workspaceKey, projectKey, preElapsedMs);
        }
    }

    // ===========================================
    // PostToolUse: Delegate quality checks to harness
    // ===========================================
    // The harness runs tsc, lint, secrets, strong_typing, and inline checks.
    // If harness is unavailable, degrade gracefully (no inline fallback).
    //
    // Skip PostToolUseFailure for any non-mutation tool. Quality checks need
    // a file on disk; failures from Bash/Read/Grep/etc. have nothing to check
    // and only produce noise. Restrict to known mutation tools so the failure
    // case mirrors the PostToolUse matcher (Edit|Write|MultiEdit).
    const mutationTools = new Set(["Edit", "Write", "MultiEdit", "NotebookEdit", "WriteFile", "EditFile", "write_file", "edit_file"]);
    const failingToolName = event.tool_name || rawInput.tool_name || "";
    const skipPostCheck = hookEvent === "PostToolUseFailure" && !mutationTools.has(failingToolName);
    if (isPostTool && !skipPostCheck) {
        const postStartMs = Date.now();
        const harnessEvent = {
            hook_event: hookEvent,
            session_id: sessionId,
            agent_source: detectedClient,
            agent_name: agentName,
            tool_name: event.tool_name || rawInput.tool_name || null,
            tool_input: rawInput.tool_input || event.tool_input || null,
            tool_use_id: rawInput.tool_use_id || event.tool_use_id || null,
            cwd: rawInput.cwd || event.cwd || null,
            model: event.model || null,
            timestamp: new Date().toISOString(),
        };

        let postResult = await evaluateViaHarness(harnessEvent);

        if (!postResult) {
            // Harness unavailable — try to heal (auto-restart if stale)
            const healed = tryHealHarness();
            if (healed) {
                const retryDelay = Date.now() + 1500;
                while (Date.now() < retryDelay) { /* spin */ }
                postResult = await evaluateViaHarness(harnessEvent);
            }
        }

        if (!postResult) {
            postResult = inlinePostToolFallback(rawInput, event);
        }

        const postElapsedMs = Date.now() - postStartMs;

        if (postResult) {
            const warnings = postResult.warnings || [];

            if (warnings.length > 0) {
                const issueList = warnings.join("\\n\\n");
                const toolLabel = event.tool_name || "unknown";
                const statusLine = "✗ " + warnings.length + " issue(s) on " + toolLabel + " (" + postElapsedMs + "ms)";
                const isBlockingPostDecision = postResult.decision === "block";
                const responseType = isBlockingPostDecision ? "post_block" : "post_warn";
                const responsePayload = isBlockingPostDecision
                    ? {
                        reason: issueList + "\\n\\nFix the issues above by changing the actual code.",
                    }
                    : {
                        reason: issueList,
                        summary: "[interlinked:" + toolLabel + "] Advisory findings:\\n" + issueList,
                    };
                writeLastCheck(statusLine);
                console.log(JSON.stringify(formatProviderResponse(responseType, responsePayload)));
                appendLocal(event, hookEvent, sessionId, agentName, workspaceKey, projectKey);
                appendGuardDecision(
                    isBlockingPostDecision ? "block" : "warn",
                    postResult,
                    event,
                    hookEvent,
                    sessionId,
                    agentName,
                    workspaceKey,
                    projectKey,
                    postElapsedMs,
                );
                updateSessionState(sessionId, agentName, event);
                captureCodeEdit(sessionId, agentName, event);
                process.exit(0);
            }

            // Success: log allow decision with structured check results
            appendGuardDecision("allow", postResult, event, hookEvent, sessionId, agentName, workspaceKey, projectKey, postElapsedMs);

            const toolLabel = event.tool_name || "unknown";
            const summary = postResult.summary || ("all clean (" + postElapsedMs + "ms)");
            writeLastCheck("[interlinked:" + toolLabel + "] " + summary);
            console.log(JSON.stringify(formatProviderResponse("post_success", {
                summary: "[interlinked:" + toolLabel + "] " + summary,
            })));
            appendLocal(event, hookEvent, sessionId, agentName, workspaceKey, projectKey);
            updateSessionState(sessionId, agentName, event);
            captureCodeEdit(sessionId, agentName, event);
            process.exit(0);
        } else {
            // Harness unavailable — still report that the hook ran
            const toolLabel = event.tool_name || "unknown";
            const elapsed = Date.now() - postStartMs;
            writeLastCheck("[interlinked:" + toolLabel + "] no harness (" + elapsed + "ms)");
            console.log(JSON.stringify(formatProviderResponse("post_success", {
                summary: "[interlinked:" + toolLabel + "] no harness (" + elapsed + "ms)",
            })));
        }
    }

    // --- Always write locally (works offline) ---
    appendLocal(event, hookEvent, sessionId, agentName, workspaceKey, projectKey);
    updateSessionState(sessionId, agentName, event);

    // Capture code edits from PostToolUse Edit/Write events
    if (isPostTool) {
        captureCodeEdit(sessionId, agentName, event);
    }

    // Reconcile commits on session end or stop
    if (event.event_type === "session_end" || event.event_type === "agent_stop") {
        reconcileCommits(sessionId);
    }

    // --- Fire-and-forget POST to server ---
    // Skipped when sync_mode is "local"
    if (syncMode !== "local" && serverUrl) {
        const realtimePayload = {
            workspace_uuid: workspaceId,
            workspace_key: workspaceKey,
            project_key: projectKey,
            agent_name: agentName,
            event_type: event.event_type,
            tool_name: event.tool_name,
            tool_input_summary: event.tool_input_summary,
            hook_event: event.hook_event,
            duration_ms: event.duration_ms || undefined,
            tokens_input: event.tokens?.input || undefined,
            tokens_output: event.tokens?.output || undefined,
            tokens_cache_read: event.tokens?.cache_read || undefined,
            tokens_cache_creation: event.tokens?.cache_creation || undefined,
            parent_agent: event.parent_agent || undefined,
            subagent_id: event.subagent_id || undefined,
            files_modified: event.files_modified || undefined,
            error_message: event.error ? String(event.error) : undefined,
            // v4 full-capture fields
            tool_input_json: event.tool_input !== undefined ? (typeof event.tool_input === "string" ? event.tool_input : JSON.stringify(event.tool_input)) : undefined,
            tool_response_json: event.tool_response !== undefined ? (typeof event.tool_response === "string" ? event.tool_response : JSON.stringify(event.tool_response)) : undefined,
            prompt: event.prompt || undefined,
            last_assistant_message: event.last_assistant_message || undefined,
            cwd: event.cwd || undefined,
            model: event.model || undefined,
            source: event.source || undefined,
            agent_type_hook: event.agent_type || undefined,
            tool_use_id: event.tool_use_id || undefined,
            session_id: sessionId || undefined,
            is_interrupt: event.is_interrupt || undefined,
            error_detail: event.error ? String(event.error) : undefined,
            notification_type: event.notification_type || undefined,
            notification_title: event.notification_title || undefined,
            task_subject: event.task_subject || undefined,
            task_id_hook: event.task_id || undefined,
            task_description_hook: event.task_description || undefined,
            trigger: event.trigger || undefined,
            reason: event.reason || undefined,
            permission_mode: event.permission_mode || undefined,
            transcript_path: event.transcript_path || undefined,
            teammate_name: event.teammate_name || undefined,
            team_name: event.team_name || undefined,
            custom_instructions: event.custom_instructions || undefined,
            stop_hook_active: event.stop_hook_active || undefined,
            permission_suggestions: event.permission_suggestions ? (typeof event.permission_suggestions === "string" ? event.permission_suggestions : JSON.stringify(event.permission_suggestions)) : undefined,
            agent_transcript_path: event.agent_transcript_path || undefined,
            thinking: event.thinking || undefined,
        };

        // Scrub secrets before sending to server
        scrubPayload(realtimePayload);

        try {
            const controller = new AbortController();
            const timeout = setTimeout(() => controller.abort(), 3000);

            const res = await fetch(serverUrl + "/api/hooks/activity", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    ...(authHeader ? { Authorization: authHeader } : {}),
                },
                signal: controller.signal,
                body: JSON.stringify(realtimePayload),
            });

            clearTimeout(timeout);
            if (!res.ok) {
                const transient = res.status === 429 || res.status >= 500;
                appendSyncError("realtime_post_http", "status " + res.status);
                if (transient) {
                    enqueueRealtimeRetry(realtimePayload);
                }
            }
        } catch (e) {
            appendSyncError(
                "realtime_post_network",
                e instanceof Error ? e.message : String(e),
            );
            enqueueRealtimeRetry(realtimePayload);
        }
    }

    // --- Batch sync on session end (realtime mode only) ---
    // Batch sync is cursor-based (only sends un-synced events), so this is a no-op
    // when all events were already sent via the realtime POST above.
    const isSessionEnd = event.event_type === "session_end" || event.event_type === "agent_stop";
    if (syncMode === "realtime" && isSessionEnd && serverUrl) {
        await batchSync(
            serverUrl,
            authHeader,
            workspaceId,
            workspaceKey,
            projectKey,
            agentName,
        );
    }
}

function safeReadConfig(path) {
    try {
        return JSON.parse(readFileSync(path, "utf-8"));
    } catch {
        return null;
    }
}

function sanitizeAgentName(value) {
    if (typeof value !== "string") return null;
    const trimmed = value.trim();
    if (!trimmed) return null;
    if (trimmed.toLowerCase() === "unknown") return null;
    return trimmed.slice(0, 80);
}

function readSessionAgent(sessionId) {
    if (!sessionId) return null;
    try {
        const sessionPath = join(SESSIONS_DIR, sessionId + ".json");
        if (!existsSync(sessionPath)) return null;
        const session = JSON.parse(readFileSync(sessionPath, "utf-8"));
        return sanitizeAgentName(session?.agent);
    } catch {
        return null;
    }
}

function extractAgentName(rawInput, event) {
    const candidates = [
        rawInput?.agent_name,
        rawInput?.agentName,
        rawInput?.parent_agent_name,
        rawInput?.parentAgentName,
        rawInput?.sender_name,
        rawInput?.senderName,
        rawInput?.agent?.name,
        event?.parent_agent,
    ];
    for (const candidate of candidates) {
        const normalized = sanitizeAgentName(candidate);
        if (normalized) return normalized;
    }
    return null;
}

function buildSessionAgent(clientName, sessionId) {
    const sid = typeof sessionId === "string" && sessionId.length > 0
        ? sessionId.replace(/[^a-zA-Z0-9]/g, "").slice(0, 8)
        : "global";
    const normalizedClient = sanitizeAgentName(clientName || "") || "agent";
    return ("session-" + normalizedClient.toLowerCase() + "-" + sid).slice(0, 80);
}

function resolveAgentName(config, rawInput, event, clientName, sessionId) {
    const configured = sanitizeAgentName(config?.agent_name);
    if (configured) return configured;

    const discovered = extractAgentName(rawInput, event);
    if (discovered) return discovered;

    const existingSessionAgent = readSessionAgent(sessionId);
    if (existingSessionAgent) return existingSessionAgent;

    return buildSessionAgent(clientName, sessionId);
}

${EVENT_NORMALIZERS_CHUNK}

function extractFilePath(toolName, toolInput) {
    if (!toolName || !toolInput) return null;
    const fileTools = ["Read", "Write", "Edit", "Update", "ReadFile", "WriteFile", "EditFile",
        "read_file", "write_file", "edit_file", "CreateFile", "create_file", "apply_patch",
        "view", "str_replace", "create"];
    if (toolName === "apply_patch") {
        const rawPatch = String(toolInput.command || toolInput.patch || toolInput.content || toolInput._raw_patch || "");
        const moveMatch = rawPatch.match(/^\\*\\*\\* Move to:\\s+(.+)$/m);
        if (moveMatch && moveMatch[1]) return moveMatch[1].trim();
        const fileMatch = rawPatch.match(/^\\*\\*\\* (?:Update|Add|Delete) File:\\s+(.+)$/m);
        return fileMatch && fileMatch[1] ? fileMatch[1].trim() : null;
    }
    if (!fileTools.includes(toolName)) return null;
    const path = toolInput.file_path || toolInput.filePath || toolInput.path || null;
    return typeof path === "string" ? path : null;
}

function truncate(str, maxLen) {
    if (!str) return "";
    return str.length > maxLen ? str.slice(0, maxLen) : str;
}

function summarize(toolName, input) {
    if (!toolName || !input) return toolName || "";
    switch (toolName) {
        case "Read": case "Write": case "Edit": case "Update":
        case "ReadFile": case "WriteFile": case "EditFile":
        case "read_file": case "write_file": case "edit_file":
            return truncate(String(input.file_path || input.filePath || input.path || ""), 200);
        case "Bash": case "Shell": case "shell": case "run_command":
            return truncate(String(input.command || input.cmd || ""), 200);
        case "apply_patch": {
            const patchPath = extractFilePath(toolName, input);
            return truncate(String(patchPath || toolName), 200);
        }
        case "Glob": case "glob": case "ListFiles": case "list_files":
            return truncate(String(input.pattern || input.glob || ""), 200);
        case "Grep": case "grep": case "SearchFiles": case "search_files":
            return truncate((String(input.pattern || input.query || "") + " " + String(input.path || "")).trim(), 200);
        case "WebSearch": case "web_search":
            return truncate(String(input.query || ""), 200);
        case "WebFetch": case "web_fetch":
            return truncate(String(input.url || ""), 200);
        default:
            return toolName;
    }
}

main().catch(() => process.exit(0));
`;
}
