// ===========================================
// Status Line — Install script + configure clients
// ===========================================
// Cross-client statusline installer: writes the bash render script to
// ~/.interlinked/ and wires it into each client's user-level settings.
// Pure formatting lives in the bash script below; all the math lives in
// src/harness/statusline-snapshot.ts. Split out of the `hook-installers.ts`
// barrel because it's the single largest, fully self-contained block and is
// orthogonal to any one client's install path.

import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { isNonEmptyString, isPlainObject } from "./hook-installers-shared.js";
import { CLIENT_CLAUDE, CLIENT_COPILOT } from "./hook-types.js";
import type { JsonObject } from "./json-types.js";
import type { ClientName } from "./settings.js";

const STATUSLINE_SCRIPT_NAME = "statusline-interlinked.sh";

/**
 * Re-run cadence for the statusline script. Triggers a render every N
 * seconds in addition to event-driven updates from Claude Code, so the
 * kinetic last-edit segment can fade by age and live counters stay
 * fresh during idle waits.
 */
const STATUSLINE_REFRESH_SECONDS = 5;

function writeStatuslineScript(scriptPath: string): void {
	// Bash script that renders a two-row, screenshot-demoable status line.
	// Reads pre-computed state from .interlinked/statusline.snapshot (written
	// by the harness on startup, rule reload, and a 10s tick) plus the
	// existing per-subsystem .status files. The script itself does pure
	// formatting — all the math lives in src/harness/statusline-snapshot.ts.
	//
	// Compatible with macOS bash 3.2 (no associative arrays).
	const script = `#!/bin/bash
# Interlinked status line — auto-generated by \`interlinked enable\`.
# Works with: Claude Code, GitHub Copilot CLI, and any agent supporting statusLine.command.
# Source of layout decisions: docs/design/statusline-redesign.md.
#
# Color/escape constants use \$'...' quoting so they hold real ESC bytes —
# avoids %b decoding issues when raw OSC 8 sequences from osc8() are
# concatenated alongside color codes.
trap '' INT TERM PIPE

# Consume stdin — Anthropic pipes session JSON we deliberately ignore.
# Interlinked's status line surfaces interlinked state only; model/cost/ctx
# belong to the platform default surface.
cat > /dev/null

# --- Colors (real ESC bytes via ANSI-C quoting) ---
BOLD=$'\\033[1m'
DIM=$'\\033[2m'
GREEN=$'\\033[32m'
YELLOW=$'\\033[33m'
RED=$'\\033[31m'
CYAN=$'\\033[36m'
MAGENTA=$'\\033[35m'
RESET=$'\\033[0m'
SEP="\${DIM} · \${RESET}"

# --- Locate the project's .interlinked dir by walking up from CWD ---
ROOT=""
PID=""
DIR="$PWD"
for _ in 1 2 3 4 5 6 7 8 9 10; do
    if [ -S "$DIR/.interlinked/harness.sock" ] || [ -d "$DIR/.interlinked" ]; then
        ROOT="$DIR"
        [ -f "$DIR/.interlinked/harness.pid" ] && PID=$(cat "$DIR/.interlinked/harness.pid" 2>/dev/null)
        break
    fi
    P=$(dirname "$DIR")
    [ "$P" = "$DIR" ] && break
    DIR="$P"
done

# Brand prefix — always present so a screenshot is self-attributing.
BRAND="\${MAGENTA}\${BOLD}◆ interlinked\${RESET}"

# Not enabled in this directory tree.
if [ -z "$ROOT" ]; then
    printf '%s' "\${BRAND}\${SEP}not running here\${SEP}\${CYAN}↻ interlinked enable\${RESET}"
    exit 0
fi

ID="$ROOT/.interlinked"
SNAP="$ID/statusline.snapshot"

# read_snap KEY [DEFAULT] — extract one key=value line from the snapshot.
read_snap() {
    local val
    val=$(grep -E "^$1=" "$SNAP" 2>/dev/null | head -1 | cut -d= -f2-)
    if [ -z "$val" ]; then
        printf '%s' "$2"
    else
        printf '%s' "$val"
    fi
}

# osc8 URL TEXT — wrap TEXT in an OSC 8 hyperlink using BEL terminator.
# Outputs real ESC + BEL bytes so callers can concatenate with color
# constants and emit via printf '%s'. Terminals that don't support OSC 8
# strip the escape sequences and render TEXT cleanly.
osc8() {
    printf '\\033]8;;%s\\007%s\\033]8;;\\007' "$1" "$2"
}

# Daemon health glyph.
ALIVE=0
if [ -n "$PID" ] && ps -p "$PID" > /dev/null 2>&1; then
    ALIVE=1
fi

if [ "$ALIVE" = "0" ]; then
    BRAND="\${RED}\${BOLD}◆ interlinked\${RESET}"
    LINE1="\${BRAND}\${SEP}\${YELLOW}▼ harness offline\${RESET}\${SEP}\${RED}Claude is bypassing guardrails\${RESET}"
    LINE2="\${CYAN}↻ interlinked harness start\${RESET}"
    printf '%s\\n%s' "$LINE1" "$LINE2"
    exit 0
fi

# --- Snapshot fields (with sensible defaults for missing keys) ---
SMODE=$(read_snap sync_mode realtime)
RULES=$(read_snap rules_total 0)
# Split check counts — \`tool_checks_enabled\` and \`inline_checks_enabled\`
# were introduced as a pair (see src/harness/statusline-snapshot.ts). When
# rendered against an older harness daemon that only writes \`checks_enabled\`,
# we degrade to a single number so the line never shows "0 tools / 0 inline".
TOOL_CHECKS=$(read_snap tool_checks_enabled "")
INLINE_CHECKS=$(read_snap inline_checks_enabled "")
CHECKS=$(read_snap checks_enabled 0)
CLSF=$(read_snap classifier_enabled disabled)
SCNF=$(read_snap scanner_enabled disabled)
IDXS=$(read_snap index_status missing)
IDXF=$(read_snap index_files 0)
# Daemon PID — written by the harness itself into the snapshot so a
# screenshot identifies *which* process produced these counters. Falls
# back to harness.pid (read at the top of this script) when the running
# daemon predates the snapshot field.
SNAP_PID=$(read_snap daemon_pid "")
DISPLAY_PID="$SNAP_PID"
[ -z "$DISPLAY_PID" ] && DISPLAY_PID="$PID"

# --- Last-check + pending review state ---
# Read here (not down with LINE2) so the BRAND can health-color from the
# same data before LINE1 is built. The row-2 priority chain below reuses
# every variable populated in this block.
LAST_CHECK="$ID/last-check.txt"
LAST_TXT=""
LAST_AGE=999999
if [ -f "$LAST_CHECK" ]; then
    LAST_TXT=$(head -1 "$LAST_CHECK" 2>/dev/null)
    NOW=$(date +%s)
    MT=$(stat -f %m "$LAST_CHECK" 2>/dev/null || stat -c %Y "$LAST_CHECK" 2>/dev/null || echo "$NOW")
    LAST_AGE=$((NOW - MT))
fi

# Format relative time as "Xs / Xm / Xh ago".
fmt_age() {
    local s="$1"
    if [ "$s" -lt 60 ]; then printf '%ss ago' "$s"
    elif [ "$s" -lt 3600 ]; then printf '%sm ago' "$((s / 60))"
    elif [ "$s" -lt 86400 ]; then printf '%sh ago' "$((s / 3600))"
    else printf '%sd ago' "$((s / 86400))"
    fi
}

# Extract one named field from the structured last-check line.
last_field() {
    echo "$LAST_TXT" | grep -oE "$1=[^|]*" | head -1 | sed -E "s/^$1=//; s/[[:space:]]+$//"
}

# Pending review count — promotes to row 2 if non-zero, and yellows BRAND.
REVIEW_FILE="$ID/scanner/review-pending"
REVIEW_COUNT=0
if [ -f "$REVIEW_FILE" ]; then
    REVIEW_COUNT=$(cat "$REVIEW_FILE" 2>/dev/null | tr -d '[:space:]')
    [ -z "$REVIEW_COUNT" ] && REVIEW_COUNT=0
fi

LAST_RESULT=$(last_field result)
LAST_FILE=$(last_field file)
LAST_TOOL=$(last_field tool)
LAST_COUNT=$(last_field count)
LAST_MS=$(last_field ms)
LAST_RULE=$(last_field rule)
LAST_SUMMARY=$(last_field summary)
LAST_TARGET="$LAST_FILE"
[ -z "$LAST_TARGET" ] && LAST_TARGET="$LAST_TOOL"

# --- Brand color reflects harness health ---
# Daemon-dead is colored RED earlier in the ALIVE=0 branch.
# Here (alive): RED on a recent block, YELLOW on recent warnings or
# pending PII review, GREEN otherwise. Time windows match LINE2's
# priority cutoffs so the color and the row-2 message stay coherent.
BRAND_COLOR="$GREEN"
if [ "$REVIEW_COUNT" != "0" ]; then
    BRAND_COLOR="$YELLOW"
elif [ "$LAST_RESULT" = "block" ] && [ "$LAST_AGE" -lt 300 ]; then
    BRAND_COLOR="$RED"
elif [ "$LAST_RESULT" = "warn" ] && [ "$LAST_AGE" -lt 120 ]; then
    BRAND_COLOR="$YELLOW"
fi
BRAND="\${BRAND_COLOR}\${BOLD}◆ interlinked\${RESET}"

# --- Row 1: tight, every segment earns its slot ---
# "◆ interlinked · 105 rules · 16 tools / 86 inline · classifier off · PII filter off · index off"
# Active counts (rules, tool/inline checks) read as scale; off-state badges
# read as capability marketing — what the product COULD do for them.

# Rule count — always links to loaded-rules.md (the harness-generated full
# list). The override file (guard-rules.local.json) only shows what's
# disabled, not what's loaded — bad first-click experience.
RULES_SEG="\${BOLD}$(osc8 "file://$ID/loaded-rules.md" "\${RULES} rules")\${RESET}"

# Check count — split into tool runners (subprocess wrappers like tsc/biome)
# vs inline detectors (in-process regex/AST checks). When the harness daemon
# is too old to write the split keys, fall back to the legacy single number
# so the line still says something honest. Both segments link to the same
# loaded-checks.md target — the markdown distinguishes them in headings.
if [ -n "$TOOL_CHECKS" ] && [ -n "$INLINE_CHECKS" ]; then
    CHECKS_TEXT="\${TOOL_CHECKS} tools / \${INLINE_CHECKS} inline"
else
    CHECKS_TEXT="\${CHECKS} checks"
fi
CHECKS_SEG="\${BOLD}$(osc8 "file://$ID/loaded-checks.md" "\${CHECKS_TEXT}")\${RESET}"

# Off-state badges — each links to its most actionable target:
# - classifier: docs explaining what it does (no toggle in user's config yet)
# - PII filter: guard-rules.local.json (the existing content_scanner toggle)
# - index: docs explaining the trigram index + the build command
DOCS_LINK="file://$ROOT/docs/harness.md"
CONFIG_LINK="file://$ID/guard-rules.local.json"

case "$CLSF" in
    enabled)  CLS_SEG="\${GREEN}$(osc8 "file://$ID/classifier.status" "classifier ✓")\${RESET}" ;;
    disabled) CLS_SEG="\${DIM}$(osc8 "$DOCS_LINK" "classifier off")\${RESET}" ;;
    *)        CLS_SEG="\${DIM}classifier ?\${RESET}" ;;
esac
case "$SCNF" in
    enabled)  SCN_SEG="\${GREEN}$(osc8 "file://$ID/content-scanner.status" "PII filter ✓")\${RESET}" ;;
    disabled) SCN_SEG="\${DIM}$(osc8 "$CONFIG_LINK" "PII filter off")\${RESET}" ;;
    *)        SCN_SEG="\${DIM}PII filter ?\${RESET}" ;;
esac
case "$IDXS" in
    ready)
        if [ "$IDXF" -ge 1000 ]; then
            IDXTXT="index $((IDXF / 1000))k files"
        else
            IDXTXT="index \${IDXF} files"
        fi
        IDX_SEG="\${GREEN}$(osc8 "file://$ID/trigram-index.bin" "\${IDXTXT}")\${RESET}"
        ;;
    missing)  IDX_SEG="\${DIM}$(osc8 "$DOCS_LINK" "index off")\${RESET}" ;;
    *)        IDX_SEG="\${YELLOW}index \${IDXS}\${RESET}" ;;
esac

# Sync segment — only shown when non-default (local or manual). Default
# realtime is the expected mode and not worth pixels.
SYNC_SEG=""
case "$SMODE" in
    realtime) ;;
    local)   SYNC_SEG="\${SEP}\${DIM}local-only sync\${RESET}" ;;
    manual)  SYNC_SEG="\${SEP}\${DIM}manual sync\${RESET}" ;;
esac

# PID segment — dim, last on the row. Identifies WHICH harness process
# wrote these counters. Critical when restarting daemons during
# development: the snapshot shows the live writer, the harness.pid file
# may briefly disagree mid-restart. Hyperlinks to the snapshot file
# itself so a click reveals the full key=value state.
PID_SEG=""
if [ -n "$DISPLAY_PID" ]; then
    PID_SEG="\${SEP}\${DIM}$(osc8 "file://$ID/statusline.snapshot" "pid \${DISPLAY_PID}")\${RESET}"
fi

LINE1="\${BRAND}\${SEP}\${RULES_SEG}\${SEP}\${CHECKS_SEG}\${SEP}\${CLS_SEG}\${SEP}\${SCN_SEG}\${SEP}\${IDX_SEG}\${SYNC_SEG}\${PID_SEG}"

# --- Row 2: outcome language from structured last-check.txt ---
# LAST_*/REVIEW_COUNT and the fmt_age/last_field helpers were populated
# above (alongside the BRAND coloring). The priority chain below just
# consumes them.

LINE2=""

# Priority 1: pending review needs the user.
if [ "$REVIEW_COUNT" != "0" ]; then
    LINE2="\${YELLOW}⚠ \${REVIEW_COUNT} file(s) awaiting review\${RESET}\${SEP}\${CYAN}interlinked review\${RESET}"

# Priority 2: a block fired in the last 5 min. The killer screenshot moment.
elif [ "$LAST_RESULT" = "block" ] && [ "$LAST_AGE" -lt 300 ]; then
    REASON="$LAST_SUMMARY"
    [ -z "$REASON" ] && REASON="$LAST_TARGET"
    RULE_PART=""
    [ -n "$LAST_RULE" ] && RULE_PART="\${SEP}\${DIM}rule: \${LAST_RULE}\${RESET}"
    LINE2="\${RED}\${BOLD}✗ blocked\${RESET}\${RED} \${REASON}\${RESET}\${SEP}\${DIM}$(fmt_age "$LAST_AGE")\${RESET}\${RULE_PART}"

# Priority 3: warnings caught on the last edit (within 2 min).
elif [ "$LAST_RESULT" = "warn" ] && [ "$LAST_AGE" -lt 120 ]; then
    FILE_LINK="$LAST_TARGET"
    [ -n "$LAST_FILE" ] && FILE_LINK=$(osc8 "file://$ROOT/$LAST_FILE" "$LAST_FILE")
    MS_PART=""
    [ -n "$LAST_MS" ] && MS_PART=" \${DIM}(\${LAST_MS}ms)\${RESET}"
    LINE2="\${YELLOW}⚠ caught \${LAST_COUNT} new issue(s) before they landed\${RESET}\${SEP}\${FILE_LINK}\${MS_PART}\${SEP}\${DIM}$(fmt_age "$LAST_AGE")\${RESET}"

# Priority 4: a clean edit landed within 60s — bright kinetic indicator.
elif [ "$LAST_RESULT" = "clean" ] && [ "$LAST_AGE" -lt 60 ]; then
    FILE_LINK="$LAST_TARGET"
    [ -n "$LAST_FILE" ] && FILE_LINK=$(osc8 "file://$ROOT/$LAST_FILE" "$LAST_FILE")
    MS_PART=""
    [ -n "$LAST_MS" ] && MS_PART=" \${DIM}(\${LAST_MS}ms)\${RESET}"
    LINE2="\${GREEN}✓ last edit verified clean\${RESET}\${SEP}\${FILE_LINK}\${MS_PART}"

# Priority 5: stale-but-present — always show something on row 2 if the
# harness has ever processed an edit, so screenshots at idle still
# convey activity.
elif [ -n "$LAST_RESULT" ]; then
    case "$LAST_RESULT" in
        clean) STALE_VERB="last edit verified clean" ;;
        warn)  STALE_VERB="last edit had \${LAST_COUNT} issue(s)" ;;
        block) STALE_VERB="last action blocked" ;;
        *)     STALE_VERB="hook last ran" ;;
    esac
    FILE_LINK="$LAST_TARGET"
    [ -n "$LAST_FILE" ] && FILE_LINK=$(osc8 "file://$ROOT/$LAST_FILE" "$LAST_FILE")
    LINE2="\${DIM}\${STALE_VERB} · \${FILE_LINK} · $(fmt_age "$LAST_AGE")\${RESET}"

# Priority 6: never-edited — first-paint marketing message.
else
    LINE2="\${DIM}ready · waiting for first edit to verify\${RESET}"
fi

if [ -n "$LINE2" ]; then
    printf '%s\\n%s' "$LINE1" "$LINE2"
else
    printf '%s' "$LINE1"
fi
`;
	writeFileSync(scriptPath, script);
	chmodSync(scriptPath, 0o755);
}

function applyStatuslineToSettings(
	settingsPath: string,
	scriptPath: string,
	statusLineConfig: { type: string; command: string; refreshInterval: number },
): boolean {
	try {
		const dir = dirname(settingsPath);
		if (!existsSync(dir)) {
			mkdirSync(dir, { recursive: true });
		}

		let settings: JsonObject = {};
		if (existsSync(settingsPath)) {
			const parsed: unknown = JSON.parse(readFileSync(settingsPath, "utf-8"));
			if (isPlainObject(parsed)) {
				settings = parsed;
			}
		}

		if (!settings.statusLine) {
			settings.statusLine = statusLineConfig;
			writeFileSync(settingsPath, `${JSON.stringify(settings, null, 2)}\n`);
			return true;
		}
		if (isPlainObject(settings.statusLine)) {
			const existing = settings.statusLine;
			if (
				isNonEmptyString(existing.command) &&
				existing.command.includes("statusline-interlinked")
			) {
				existing.command = scriptPath;
				existing.refreshInterval = statusLineConfig.refreshInterval;
				writeFileSync(settingsPath, `${JSON.stringify(settings, null, 2)}\n`);
				return true;
			}
		}
	} catch (_err) {
		/* intentional: malformed or unreadable client settings — skip this client */
	}
	return false;
}

function statuslineSettingsPath(client: ClientName, home: string): string | null {
	if (client === CLIENT_CLAUDE) {
		return join(home, ".claude", "settings.json");
	}
	if (client === CLIENT_COPILOT) {
		// Copilot reads ~/.copilot/config.json for user-level settings
		return join(home, ".copilot", "config.json");
	}
	return null;
}

/**
 * Public API — consumed by `src/commands/enable.ts` (re-exported via `src/lib/hooks.ts`).
 *
 * Write the statusline script and configure it in user-level settings for
 * clients that support it (Claude Code, Copilot CLI).
 * Returns the path to the script, or null if no clients were configured.
 */
export function installStatusLine(clients: ClientName[]): string | null {
	const home = process.env.HOME || process.env.USERPROFILE || "";
	if (!home) return null;

	// Write the script to ~/.interlinked/statusline-interlinked.sh
	const scriptDir = join(home, ".interlinked");
	if (!existsSync(scriptDir)) {
		mkdirSync(scriptDir, { recursive: true });
	}
	const scriptPath = join(scriptDir, STATUSLINE_SCRIPT_NAME);
	writeStatuslineScript(scriptPath);

	// refreshInterval re-runs the script every N seconds so the kinetic
	// last-edit segment can fade based on age, and counters
	// (reservations, index status) stay live during idle waits without
	// requiring an assistant message to trigger a render.
	const statusLineConfig = {
		type: "command",
		command: scriptPath,
		refreshInterval: STATUSLINE_REFRESH_SECONDS,
	};
	let configured = false;
	for (const client of clients) {
		const settingsPath = statuslineSettingsPath(client, home);
		if (!settingsPath) continue;
		configured =
			applyStatuslineToSettings(settingsPath, scriptPath, statusLineConfig) || configured;
	}
	return configured ? scriptPath : null;
}
