// ===========================================
// Self-contained OpenCode plugin source
// ===========================================
// Written to `.opencode/plugins/interlinked-opencode2.ts` so it can sit
// next to the v1 managed bridge (`.opencode/plugins/interlinked.ts`) without
// colliding on filename or plugin id. OpenCode auto-loads
// `{plugin,plugins}/*.{ts,js}`. The file has ZERO imports from this package.

import { OPENCODE2_DESTRUCTIVE_RM } from "./opencode-tool-map.js";

/** Marker grepped by doctor / uninstall. Distinct from the v1 provider-bridge marker. */
export const OPENCODE_PLUGIN_MARKER = "interlinked-opencode-plugin";

export const OPENCODE_PLUGIN_FILENAME = "interlinked-opencode2.ts";
export const OPENCODE_PLUGIN_ID = "interlinked-opencode2";

/** Public API — the exact bytes dropped onto disk. */
export function buildOpencodePluginSource(): string {
	return `// interlinked-provider-bridge:v1
// ${OPENCODE_PLUGIN_MARKER}
// Generated by interlinked-cli for the opencode2 binary. Talks to .interlinked/harness.sock.
// Do not edit by hand — re-run \`interlinked enable --clients opencode2\`.
import { createConnection } from "node:net";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";

const TIMEOUT_MS = 5000;
const MARKER = ${JSON.stringify(OPENCODE_PLUGIN_MARKER)};
const PLUGIN_ID = ${JSON.stringify(OPENCODE_PLUGIN_ID)};

function isOpenCodeV2() {
  const env = typeof process === "undefined" ? {} : process.env;
  const argv = typeof process === "undefined" ? [] : process.argv;
  if (Boolean(env.OPENCODE2) || env.INTERLINKED_CLIENT === "opencode2") return true;
  if (String(env.XDG_CONFIG_HOME || "").includes("opencode-v2")) return true;
  if (argv.some((part) => String(part).includes("opencode2"))) return true;
  // This file is the v2 plugin. Gate unless the process is clearly OpenCode v1.
  if (env.INTERLINKED_CLIENT === "opencode") return false;
  if (env.OPENCODE && !env.OPENCODE2) return false;
  return true;
}

function asRecord(value) {
  if (value !== null && typeof value === "object" && !Array.isArray(value)) return value;
  return {};
}

function str(obj, ...keys) {
  for (const key of keys) {
    const value = obj[key];
    if (typeof value === "string") return value;
  }
  return undefined;
}

function mapTool(tool, args) {
  const a = asRecord(args);
  if (tool === "bash" || tool === "shell") {
    const cwd = str(a, "workdir", "cwd");
    return { tool_name: "Bash", tool_input: { command: a.command, ...(cwd ? { cwd } : {}) } };
  }
  if (tool === "edit") {
    return {
      tool_name: "Edit",
      tool_input: {
        file_path: str(a, "filePath", "file_path", "path") || "",
        old_string: str(a, "oldString", "old_string") || "",
        new_string: str(a, "newString", "new_string") || "",
        ...(a.replaceAll === true || a.replace_all === true ? { replace_all: true } : {}),
      },
    };
  }
  if (tool === "write") {
    return {
      tool_name: "Write",
      tool_input: { file_path: str(a, "filePath", "file_path", "path") || "", content: str(a, "content") || "" },
    };
  }
  if (tool === "read") {
    return {
      tool_name: "Read",
      tool_input: {
        file_path: str(a, "filePath", "file_path", "path") || "",
        ...(a.offset !== undefined ? { offset: a.offset } : {}),
        ...(a.limit !== undefined ? { limit: a.limit } : {}),
      },
    };
  }
  if (tool === "apply_patch") {
    return { tool_name: "apply_patch", tool_input: { patchText: str(a, "patchText", "patch_text") || "" } };
  }
  if (tool === "grep") {
    return { tool_name: "Grep", tool_input: { pattern: str(a, "pattern") || "", path: str(a, "path"), glob: str(a, "include", "glob") } };
  }
  if (tool === "glob") {
    return { tool_name: "Glob", tool_input: { pattern: str(a, "pattern") || "", path: str(a, "path") } };
  }
  if (tool === "webfetch") {
    return { tool_name: "WebFetch", tool_input: { url: str(a, "url") || "" } };
  }
  if (tool === "task") {
    return {
      tool_name: "Task",
      tool_input: {
        description: str(a, "description") || "",
        prompt: str(a, "prompt") || "",
        subagent_type: str(a, "subagent_type", "agent") || "",
      },
    };
  }
  return { tool_name: tool, tool_input: a };
}

function findSocket(start) {
  let dir = start || process.cwd();
  for (let i = 0; i < 24; i++) {
    const candidate = join(dir, ".interlinked", "harness.sock");
    if (existsSync(candidate)) return candidate;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return null;
}

function coldBlock(toolName, toolInput) {
  if (toolName !== "Bash") return null;
  const command = typeof toolInput.command === "string" ? toolInput.command : "";
  if (/${OPENCODE2_DESTRUCTIVE_RM.source}/.test(command)) {
    return "BLOCKED: Recursive deletion of a filesystem root is not allowed (OpenCode cold fallback).";
  }
  if (/\\b(npm|pnpm|yarn|bun|pip|pip3|pipx|poetry|uv|cargo|gem|bundle|go)\\s+(install|add|get)\\b/.test(command)) {
    return "BLOCKED: Package installs require the Interlinked daemon (allowlist). Start it with \`interlinked harness start\`.";
  }
  return null;
}

function queryHarness(event) {
  const socketPath = findSocket(event.cwd);
  if (!socketPath) {
    const reason = coldBlock(event.tool_name, event.tool_input || {});
    return Promise.resolve(reason ? { decision: "block", reason } : { decision: "allow" });
  }
  return new Promise((resolve) => {
    let settled = false;
    const finish = (value) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      try { socket.destroy(); } catch { /* ignore */ }
      resolve(value);
    };
    const timer = setTimeout(() => {
      const reason = coldBlock(event.tool_name, event.tool_input || {});
      finish(reason ? { decision: "block", reason } : { decision: "allow" });
    }, TIMEOUT_MS);
    const socket = createConnection(socketPath);
    let buf = "";
    socket.on("connect", () => socket.write(JSON.stringify(event) + "\\n"));
    socket.on("data", (chunk) => {
      buf += chunk.toString("utf8");
      const nl = buf.indexOf("\\n");
      if (nl === -1) return;
      try {
        finish(JSON.parse(buf.slice(0, nl)));
      } catch {
        finish({ decision: "allow" });
      }
    });
    socket.on("error", () => {
      const reason = coldBlock(event.tool_name, event.tool_input || {});
      finish(reason ? { decision: "block", reason } : { decision: "allow" });
    });
    socket.on("close", () => {
      if (!settled) finish({ decision: "allow" });
    });
  });
}

function baseEvent(cwd, sessionId) {
  return {
    session_id: sessionId || "unknown",
    agent_source: "opencode2",
    agent_name: "opencode2",
    cwd: cwd || process.cwd(),
    timestamp: new Date().toISOString(),
  };
}

function readArgs(event) {
  const a = event && event.args;
  if (a && typeof a === "object") {
    if (typeof a.get === "function") return a.get();
    if (a.value !== undefined) return a.value;
  }
  return a || (event && event.input) || {};
}

function deny(event, reason) {
  if (event && typeof event.block === "function") {
    event.block(reason);
    return;
  }
  if (event && typeof event.abort === "function") {
    event.abort(reason);
    return;
  }
  throw new Error(reason);
}

async function gateBefore(event, pluginCwd) {
  const tool = (event && (event.tool || event.name || event.id)) || "unknown";
  const mapped = mapTool(typeof tool === "string" ? tool : String(tool), readArgs(event));
  const sessionId = event && (event.sessionID || event.sessionId);
  const decision = await queryHarness({
    ...baseEvent(pluginCwd, sessionId),
    hook_event: "PreToolUse",
    tool_name: mapped.tool_name,
    tool_input: mapped.tool_input,
    tool_use_id: event && event.callID,
  });
  if (decision && (decision.decision === "block" || decision.decision === "ask")) {
    deny(event, decision.reason || "Blocked by Interlinked");
  }
}

async function gateAfter(event, pluginCwd) {
  const tool = (event && (event.tool || event.name || event.id)) || "unknown";
  const mapped = mapTool(typeof tool === "string" ? tool : String(tool), readArgs(event));
  const sessionId = event && (event.sessionID || event.sessionId);
  await queryHarness({
    ...baseEvent(pluginCwd, sessionId),
    hook_event: "PostToolUse",
    tool_name: mapped.tool_name,
    tool_input: mapped.tool_input,
    tool_response: event && (event.output || event.result),
    tool_use_id: event && event.callID,
  });
}

let armed = false;
function arm() {
  if (armed) return false;
  armed = true;
  return true;
}

export const InterlinkedPlugin = async ({ directory, worktree }) => {
  void MARKER;
  void worktree;
  if (!isOpenCodeV2() || !arm()) return {};
  const pluginCwd = directory || process.cwd();
  return {
    "tool.execute.before": async (input, output) => {
      await gateBefore({
        tool: input && input.tool,
        args: output && output.args,
        sessionID: input && input.sessionID,
        callID: input && input.callID,
      }, pluginCwd);
    },
    "tool.execute.after": async (input, output) => {
      await gateAfter({
        tool: input && input.tool,
        args: input && input.args,
        output: output && output.output,
        sessionID: input && input.sessionID,
        callID: input && input.callID,
      }, pluginCwd);
    },
  };
};

export default {
  id: PLUGIN_ID,
  setup: async (ctx) => {
    void MARKER;
    if (!isOpenCodeV2() || !arm()) return;
    const pluginCwd = (ctx && ctx.location && ctx.location.directory) || process.cwd();
    if (ctx.tool && typeof ctx.tool.hook === "function") {
      await ctx.tool.hook("execute.before", (event) => gateBefore(event, pluginCwd));
      await ctx.tool.hook("execute.after", (event) => gateAfter(event, pluginCwd));
    }
    if (ctx.shell && typeof ctx.shell.hook === "function") {
      await ctx.shell.hook("execute.before", (event) => {
        const command = event && (event.command || readArgs(event).command);
        return gateBefore({ tool: "bash", args: { command }, sessionID: event && event.sessionID }, pluginCwd);
      });
    }
    if (ctx.session && typeof ctx.session.hook === "function") {
      await ctx.session.hook("created", (event) =>
        queryHarness({ ...baseEvent(pluginCwd, event && (event.id || event.sessionID)), hook_event: "SessionStart" }),
      );
      await ctx.session.hook("deleted", (event) =>
        queryHarness({ ...baseEvent(pluginCwd, event && (event.id || event.sessionID)), hook_event: "SessionEnd" }),
      );
      await ctx.session.hook("idle", (event) =>
        queryHarness({ ...baseEvent(pluginCwd, event && (event.id || event.sessionID)), hook_event: "Stop" }),
      );
    }
  },
};
`;
}
