// ===========================================
// File Discovery (git-based with fallback)
// ===========================================
// Prefers `git ls-files` so .gitignore + .interlinked/.claude/dist filters are
// respected. Falls back to a bounded manual walk for non-git directories.

import { execSync } from "node:child_process";
import { readdirSync, statSync } from "node:fs";
import { extname, join } from "node:path";

/** Public API — consumed by `verify.ts` and tests. */
export const CODE_EXTENSIONS = new Set([
	".ts",
	".tsx",
	".js",
	".jsx",
	".mjs",
	".cjs",
	".mts",
	".cts",
	".py",
	".rs",
	".go",
	".c",
	".cpp",
	".cc",
	".cxx",
	".h",
	".hpp",
	".java",
]);

const INTERLINKED_DIR = ".interlinked";
const MAX_WALK_ENTRIES = 50_000;
const MAX_FILE_BYTES = 1_000_000;

/** Public API — consumed by `verify.ts` (entry point for verify's file set). */
export function discoverFiles(root: string): string[] {
	// Try git ls-files first (respects .gitignore)
	try {
		const output = execSync("git ls-files --cached --others --exclude-standard -z", {
			cwd: root,
			encoding: "utf-8",
			timeout: 15_000,
			stdio: ["pipe", "pipe", "pipe"],
		});
		if (output.length > 0) {
			return output
				.split("\0")
				.filter(Boolean)
				.filter((f) => {
					// Skip generated/managed directories and build artifacts — not user code.
					// `.claude/hooks/*.mjs` is auto-generated by `interlinked enable` and
					// deployed as a self-contained runtime — findings there belong to
					// whatever source produced the hook, not the generated artifact.
					if (f.startsWith(".interlinked/") || f.includes("/.interlinked/")) return false;
					if (f.startsWith(".claude/") || f.includes("/.claude/")) return false;
					if (f.includes("/dist/") || f.startsWith("dist/")) return false;
					const ext = extname(f).toLowerCase();
					return CODE_EXTENSIONS.has(ext);
				})
				.map((f) => join(root, f));
		}
	} catch {
		/* intentional: not a git repo, or git is missing — fall through to manual walk */
	}

	// Fallback: manual walk (for non-git dirs)
	const files: string[] = [];
	const skip = new Set([
		"node_modules",
		".git",
		"dist",
		"build",
		"coverage",
		"target",
		"__pycache__",
		".venv",
		"venv",
	]);
	function walk(dir: string): void {
		if (files.length >= MAX_WALK_ENTRIES) return;
		try {
			for (const entry of readdirSync(dir)) {
				if (skip.has(entry) || entry.startsWith(".") || entry === INTERLINKED_DIR) continue;
				const full = join(dir, entry);
				const stat = statSync(full);
				if (stat.isDirectory()) walk(full);
				else if (
					stat.isFile() &&
					CODE_EXTENSIONS.has(extname(entry).toLowerCase()) &&
					stat.size < MAX_FILE_BYTES
				) {
					files.push(full);
				}
			}
		} catch {
			/* intentional: fall back to a filesystem walk outside git worktrees */
		}
	}
	walk(root);
	return files;
}
