// ===========================================
// Declarative code-quality section table
// ===========================================
// Each entry maps a bucket inside `CodeQualityResults` to the human-readable
// label, noun, pass-label, and severity color used by `streaming-output.ts`.
//
// Order mirrors the legacy inline call sequence:
//   1. Error-severity red sections (JSON, imports, export ripple).
//   2. Warning-severity yellow sections (size, typing, hygiene).
//   3. Agent-safety checks (mix of red + yellow).
//   4. Taste / structural checks.
//   5. Cross-file parity checks.

import type { CodeQualityResults } from "./tool-results-types.js";

export interface SectionSpec {
	label: string;
	key: keyof CodeQualityResults;
	noun: string;
	passLabel: string;
	color: string;
}

/** Public API — consumed by `streaming-output.ts`. */
export const SECTIONS: readonly SectionSpec[] = [
	// --- Error severity ---
	{
		label: "json validity",
		key: "jsonValidity",
		noun: "invalid JSON files",
		passLabel: "all JSON files valid",
		color: "31",
	},
	{
		label: "phantom imports",
		key: "phantomImports",
		noun: "unresolved imports",
		passLabel: "all imports resolve",
		color: "31",
	},
	{
		label: "export ripple",
		key: "exportRipple",
		noun: "broken import references",
		passLabel: "all import references valid",
		color: "31",
	},
	{
		label: "dead exports",
		key: "deadExports",
		noun: "named exports no other file imports",
		passLabel: "no dead exports",
		color: "33",
	},
	{
		label: "circular imports",
		key: "circularImports",
		noun: "import cycles involving this file",
		passLabel: "no import cycles",
		color: "33",
	},
	{
		label: "lifecycle cleanup",
		key: "lifecycleCleanup",
		noun: "subscription without paired cleanup in dispose/destroy",
		passLabel: "all subscriptions paired with cleanup",
		color: "33",
	},
	{
		label: "default export hygiene",
		key: "defaultExport",
		noun: "anonymous default export or symbol name not matching filename",
		passLabel: "no grep-hostile default exports",
		color: "33",
	},
	// --- Warning severity (fast inline) ---
	{
		label: "large files",
		key: "largeFiles",
		noun: "files over threshold lines",
		passLabel: "all files under threshold lines",
		color: "33",
	},
	{
		label: "strong typing",
		key: "strongTyping",
		noun: "any/unknown-type usages",
		passLabel: "no any/unknown-types",
		color: "33",
	},
	{
		label: "suppressions",
		key: "suppressions",
		noun: "suppression comments",
		passLabel: "no suppression comments",
		color: "33",
	},
	{
		label: "console statements",
		key: "consoleStatements",
		noun: "console.log/debug/info",
		passLabel: "no debug logging",
		color: "33",
	},
	{
		label: "silent catches",
		key: "silentCatches",
		noun: "empty catch blocks",
		passLabel: "no empty catch blocks",
		color: "33",
	},
	{
		label: "test regressions",
		key: "testRegressions",
		noun: "skipped/todo tests",
		passLabel: "no skipped or weakened tests",
		color: "33",
	},
	{
		label: "missing return types",
		key: "missingReturnTypes",
		noun: "exported functions without return types",
		passLabel: "all exported functions have return types",
		color: "33",
	},
	{
		label: "mock drift",
		key: "mockDrift",
		noun: "stale mock references",
		passLabel: "all mocks match module exports",
		color: "33",
	},
	{
		label: "incomplete renames",
		key: "incompleteRenames",
		noun: "orphaned string refs",
		passLabel: "no orphaned string references",
		color: "33",
	},
	{
		label: "test coverage gaps",
		key: "noTestFile",
		noun: "source files without tests",
		passLabel: "all source files have tests",
		color: "33",
	},
	{
		label: "function complexity",
		key: "complexity",
		noun: "complex functions",
		passLabel: "no overly complex functions",
		color: "33",
	},
	{
		label: "CRAP risk",
		key: "crap",
		noun: "high-CRAP functions (complexity × coverage)",
		passLabel: "no CRAP hotspots",
		color: "31",
	},
	// --- Agent safety checks ---
	{
		label: "misused promises",
		key: "misusedPromises",
		noun: "async callbacks in sync APIs",
		passLabel: "no misused promises",
		color: "31",
	},
	{
		label: "floating promises",
		key: "floatingPromises",
		noun: "unhandled async calls at statement position",
		passLabel: "no floating promises",
		color: "31",
	},
	{
		label: "broad object types",
		key: "broadObjectTypes",
		noun: "Record<K, any> / index-to-any / bare Function / bare object annotations",
		passLabel: "no broad object types",
		color: "31",
	},
	{
		label: "boolean trap",
		key: "booleanTrap",
		noun: "call sites with 2+ boolean literal arguments",
		passLabel: "no boolean traps",
		color: "31",
	},
	// Mythos Phase 2 — comment-vs-behavior drift detectors.
	{
		label: "comment claims limit",
		key: "commentClaimsLimitNoGuard",
		noun: 'functions whose comment says "max N" / "limited to N" without a guard',
		passLabel: "no comment-claims-limit drift",
		color: "33",
	},
	{
		label: "comment claims null",
		key: "commentClaimsNullThrowsInstead",
		noun: 'functions whose comment says "returns null" but body throws',
		passLabel: "no comment-claims-null drift",
		color: "33",
	},
	{
		label: "comment claims validation",
		key: "commentClaimsValidationMissing",
		noun: 'functions whose comment says "validates/sanitizes/escapes" without any check',
		passLabel: "no comment-claims-validation drift",
		color: "33",
	},
	{
		label: "comment claims idempotent",
		key: "commentClaimsIdempotentMutates",
		noun: 'functions whose comment says "idempotent" but body mutates unconditionally',
		passLabel: "no comment-claims-idempotent drift",
		color: "33",
	},
	{
		label: "comment claims throws",
		key: "commentClaimsThrowsDoesnt",
		noun: "functions whose @throws {ErrorX} declaration isn't actually thrown",
		passLabel: "no comment-claims-throws drift",
		color: "33",
	},
	{
		label: "iterator invalidation",
		key: "iteratorInvalidation",
		noun: "collection mutations during iteration over the same collection",
		passLabel: "no iterator invalidations",
		color: "31",
	},
	{
		label: "fresh collection key lookup",
		key: "freshCollectionKeyLookup",
		noun: "Map/Set lookups using fresh-identity keys (NaN, fresh literals, fresh Symbol)",
		passLabel: "no fresh-identity Map/Set keys",
		color: "31",
	},
	{
		label: "index bounds unchecked",
		key: "indexBoundsUnchecked",
		noun: "external-input numbers reaching array subscripts without a bounds guard",
		passLabel: "no unchecked external-input array indices",
		color: "31",
	},
	{
		label: "cleanup skipped on early exit",
		key: "cleanupSkippedOnEarlyExit",
		noun: "resource acquisitions where a throw/return bypasses the cleanup",
		passLabel: "no skipped cleanups on early exit",
		color: "31",
	},
	{
		label: "tainted to privileged sink",
		key: "taintedToPrivilegedSink",
		noun: "external-input values reaching eval/exec/vm.run/fs.write* without a validator",
		passLabel: "no tainted values reaching privileged sinks",
		color: "31",
	},
	{
		label: "await state TOCTOU",
		key: "awaitStateToctou",
		noun: "same field deref'd before and after an await without re-check",
		passLabel: "no await-state TOCTOU",
		color: "31",
	},
	{
		label: "cleanup reentrancy",
		key: "cleanupReentrancy",
		noun: "dispose/destroy methods that recurse or useEffect cleanups that mutate state",
		passLabel: "no cleanup reentrancy",
		color: "31",
	},
	{
		label: "boundary copy no revalidation",
		key: "boundaryCopyNoRevalidation",
		noun: "Object.assign / spread copies of external input into typed slots",
		passLabel: "no unvalidated boundary copies",
		color: "31",
	},
	{
		label: "magic literal in conditional",
		key: "magicLiteralInConditional",
		noun: "if/switch branches comparing against a bare literal",
		passLabel: "no magic literals in conditionals",
		color: "31",
	},
	{
		label: "async promise executor",
		key: "asyncPromiseExecutor",
		noun: "async Promise constructors",
		passLabel: "no async Promise executors",
		color: "31",
	},
	{
		label: "self imports",
		key: "selfImports",
		noun: "modules importing themselves",
		passLabel: "no self-imports",
		color: "31",
	},
	{
		label: "extraneous dependencies",
		key: "extraneousDeps",
		noun: "imports not in package.json",
		passLabel: "all imports in package.json",
		color: "31",
	},
	{
		label: "eval usage",
		key: "evalUsage",
		noun: "eval/Function/implied eval calls",
		passLabel: "no eval usage",
		color: "31",
	},
	{
		label: "innerHTML usage",
		key: "innerHtml",
		noun: "innerHTML/dangerouslySetInnerHTML",
		passLabel: "no innerHTML usage",
		color: "31",
	},
	{
		label: "NaN comparison",
		key: "nanComparison",
		noun: "direct NaN comparisons",
		passLabel: "no NaN comparisons",
		color: "31",
	},
	{
		label: "constant conditions",
		key: "constantCondition",
		noun: "constant conditionals",
		passLabel: "no constant conditions",
		color: "33",
	},
	{
		label: "unsafe optional chaining",
		key: "unsafeOptionalChaining",
		noun: "unsafe ?. chains",
		passLabel: "no unsafe optional chaining",
		color: "31",
	},
	{
		label: "number precision loss",
		key: "numberPrecisionLoss",
		noun: "unsafe large integers",
		passLabel: "no precision loss risks",
		color: "33",
	},
	{
		label: "non-null assertions",
		key: "nonNullAssertions",
		noun: "non-null assertion operators (!)",
		passLabel: "no non-null assertions",
		color: "33",
	},
	{
		label: "throw literal",
		key: "throwLiteral",
		noun: "throw non-Error values",
		passLabel: "no throw literals",
		color: "31",
	},
	{
		label: "promise reject non-error",
		key: "promiseRejectNonError",
		noun: "Promise.reject() with non-Error literal",
		passLabel: "no Promise.reject with non-Error",
		color: "31",
	},
	{
		label: "lossy error rethrow",
		key: "lossyErrorRethrow",
		noun: "catch (e) { throw new Error(...) } without { cause: e }",
		passLabel: "all rethrows preserve cause",
		color: "33",
	},
	{
		label: "silent promise catch",
		key: "silentPromiseSwallow",
		noun: ".catch(() => {}) handlers that swallow rejections",
		passLabel: "no silent .catch swallows",
		color: "33",
	},
	{
		label: "unnecessary async",
		key: "requireAwait",
		noun: "async functions without await",
		passLabel: "all async functions use await",
		color: "33",
	},
	{
		label: "accumulating spread",
		key: "accumulatingSpread",
		noun: "O(n²) spread in reduce",
		passLabel: "no accumulating spreads",
		color: "33",
	},
	{
		label: "excessive useState",
		key: "excessiveUseState",
		noun: "components with 8+ useState hooks",
		passLabel: "no excessive useState",
		color: "33",
	},
	{
		label: "dangerouslySetInnerHTML",
		key: "dangerouslySetInnerHtml",
		noun: "XSS-risk dangerouslySetInnerHTML usages",
		passLabel: "no dangerouslySetInnerHTML",
		color: "31",
	},
	{
		label: "direct DOM access",
		key: "directDomAccess",
		noun: "direct DOM access in React",
		passLabel: "no direct DOM access",
		color: "33",
	},
	{
		label: "inline object props",
		key: "inlineObjectProps",
		noun: "inline object props causing re-renders",
		passLabel: "no inline object props",
		color: "33",
	},
	{
		label: "async event handlers",
		key: "asyncEventHandler",
		noun: "async event handlers swallowing errors",
		passLabel: "no async event handlers",
		color: "33",
	},
	{
		label: "nested ternaries",
		key: "nestedTernaries",
		noun: "nested ternary operators",
		passLabel: "no nested ternaries",
		color: "33",
	},
	{
		label: "catch and log",
		key: "catchAndLog",
		noun: "catch blocks that only log",
		passLabel: "no catch-and-log blocks",
		color: "33",
	},
	{
		label: "unsafe JSON.parse",
		key: "jsonParseUnsafe",
		noun: "JSON.parse without try-catch",
		passLabel: "all JSON.parse wrapped in try-catch",
		color: "33",
	},
	{
		label: "unvalidated JSON boundary",
		key: "unvalidatedJsonBoundary",
		noun: "JSON.parse/.json() result reaches property access without schema validation",
		passLabel: "no unvalidated JSON boundaries",
		color: "33",
	},
	{
		label: "hardcoded timeouts",
		key: "hardcodedTimeout",
		noun: "hardcoded timeout/interval values",
		passLabel: "no hardcoded timeouts",
		color: "33",
	},
	{
		label: "disabled tests",
		key: "disabledTests",
		noun: "skipped/disabled tests",
		passLabel: "no disabled tests",
		color: "33",
	},
	{
		label: "placeholder tests",
		key: "placeholderTest",
		noun: "stub/pending tests contributing zero coverage",
		passLabel: "no placeholder tests",
		color: "31",
	},
	{
		label: "suppression hygiene",
		key: "suppressionHygiene",
		noun: "suppression entries with short reasons, missing ticket/expiry, or expired dates",
		passLabel: "suppressions are well-formed",
		color: "33",
	},
	{
		label: "target _blank",
		key: "targetBlankNoRel",
		noun: 'target="_blank" without rel="noopener"',
		passLabel: 'no unsafe target="_blank"',
		color: "33",
	},
	{
		label: "snapshot overuse",
		key: "snapshotOveruse",
		noun: "excessive snapshot assertions",
		passLabel: "no snapshot overuse",
		color: "33",
	},
	{
		label: "test importing test",
		key: "testImportingTest",
		noun: "tests importing from other tests",
		passLabel: "no cross-test imports",
		color: "33",
	},
	{
		label: "excessive useEffect",
		key: "excessiveUseEffect",
		noun: "components with 6+ useEffect hooks",
		passLabel: "no excessive useEffect",
		color: "33",
	},
	{
		label: "sequential awaits",
		key: "sequentialAwaits",
		noun: "independent awaits that could parallelize",
		passLabel: "no sequential awaits",
		color: "33",
	},
	{
		label: "index as key",
		key: "indexAsKey",
		noun: "array index used as React key",
		passLabel: "no index-as-key",
		color: "33",
	},
	{
		label: "missing effect cleanup",
		key: "missingEffectCleanup",
		noun: "useEffect without cleanup",
		passLabel: "all effects have cleanup",
		color: "33",
	},
	{
		label: "over-mocking",
		key: "overMocking",
		noun: "test files with 8+ mocks",
		passLabel: "no over-mocking",
		color: "33",
	},
	{
		label: "focused tests",
		key: "focusedTests",
		noun: "shipped focus markers (.only / fit / fdescribe)",
		passLabel: "no focused tests",
		color: "31",
	},
	{
		label: "migration ordering",
		key: "migrationOrdering",
		noun: "CREATE INDEX on column not in same-block CREATE TABLE",
		passLabel: "no migration ordering hazards",
		color: "31",
	},
	{
		label: "SQL schema consistency",
		key: "sqlSchemaConsistency",
		noun: "SQL queries referencing undeclared columns",
		passLabel: "SQL queries match declared schema",
		color: "33",
	},
	{
		label: "visibility filter missing",
		key: "visibilityFilterMissing",
		noun: "soft-delete table queries without archived/deleted filter",
		passLabel: "all soft-delete queries filtered",
		color: "33",
	},
	{
		label: "PII detection",
		key: "piiDetection",
		noun: "potential PII patterns in source",
		passLabel: "no PII patterns detected",
		color: "31",
	},
	{
		label: "assertion-free tests",
		key: "assertionFreeTest",
		noun: "test blocks with no assertion",
		passLabel: "every test block asserts something",
		color: "31",
	},
	{
		label: "tautological assertions",
		key: "tautologicalAssertion",
		noun: "assertions where both sides are identical",
		passLabel: "no tautological assertions",
		color: "31",
	},
	{
		label: "mocking the SUT",
		key: "mockingTheSut",
		noun: "test files mocking the module they test",
		passLabel: "no SUT mocking",
		color: "31",
	},
	{
		label: "private member test access",
		key: "privateMemberTestAccess",
		noun: "tests reaching past the public API",
		passLabel: "tests only touch public API",
		color: "33",
	},
	{
		label: "loop nesting depth",
		key: "loopNestingDepth",
		noun: "loops nested three or more deep",
		passLabel: "no excessive loop nesting",
		color: "33",
	},
	{
		label: "else-if chains",
		key: "elseIfChain",
		noun: "long else-if chains (3+ branches)",
		passLabel: "no long else-if chains",
		color: "33",
	},
	{
		label: "duplicate switch discriminants",
		key: "duplicateSwitchDiscriminant",
		noun: "same discriminant switched in multiple places",
		passLabel: "no duplicate switch discriminants",
		color: "33",
	},
	{
		label: "hybrid classes",
		key: "hybridClass",
		noun: "classes with both public fields and behavioral methods",
		passLabel: "no hybrid classes",
		color: "33",
	},
	{
		label: "fuzzy responsibility names",
		key: "fuzzyResponsibilityName",
		noun: "classes named *Manager/Helper/Util/Service",
		passLabel: "no fuzzy responsibility names",
		color: "33",
	},
	{
		label: "Law of Demeter violations",
		key: "lawOfDemeter",
		noun: "property chains deeper than four segments",
		passLabel: "no train wrecks",
		color: "33",
	},
	{
		label: "flag arguments",
		key: "flagArgument",
		noun: "boolean literals passed as function arguments",
		passLabel: "no flag arguments",
		color: "33",
	},
	{
		label: "commented-out code",
		key: "commentedOutCode",
		noun: "3+ consecutive lines of commented-out code",
		passLabel: "no commented-out code",
		color: "33",
	},
	{
		label: "conditional logic in tests",
		key: "conditionalInTest",
		noun: "tests with if/switch/try in the body",
		passLabel: "no conditionals in test bodies",
		color: "33",
	},
	{
		label: "non-deterministic tests",
		key: "nonDeterministicTest",
		noun: "tests using Date/Math.random without fake timers",
		passLabel: "no non-deterministic tests",
		color: "33",
	},
	{
		label: "empty catch blocks",
		key: "emptyCatch",
		noun: "empty-body catch blocks with no error handling",
		passLabel: "no empty catch blocks",
		color: "33",
	},
	{
		label: "tests without description",
		key: "testWithoutDescription",
		noun: "tests with empty or missing descriptions",
		passLabel: "every test has a description",
		color: "33",
	},
	{
		label: "assertion roulette",
		key: "assertionRoulette",
		noun: "tests with 8+ expect() calls",
		passLabel: "no assertion roulette",
		color: "33",
	},
	{
		label: "magic numbers",
		key: "magicNumber",
		noun: "numeric literals inside function calls",
		passLabel: "no magic numbers",
		color: "33",
	},
	{
		label: "function arg count",
		key: "functionArgCount",
		noun: "functions with 4+ arguments",
		passLabel: "no functions with excessive args",
		color: "33",
	},
	{
		label: "data clumps",
		key: "dataClump",
		noun: "3+ consecutive same-type primitive parameters",
		passLabel: "no data clumps",
		color: "33",
	},
	{
		label: "duplicate describes",
		key: "duplicateDescribe",
		noun: "repeated describe() names in the same test file",
		passLabel: "no duplicate describe names",
		color: "33",
	},
	{
		label: "cross-file switch discriminants",
		key: "crossFileSwitchDiscriminant",
		noun: "same discriminant switched in multiple files",
		passLabel: "no cross-file duplicate discriminants",
		color: "33",
	},
	{
		label: "single-implementation interfaces",
		key: "singleImplementationInterface",
		noun: "interfaces with exactly one implementor",
		passLabel: "no single-implementation interfaces",
		color: "33",
	},
	{
		label: "files without test",
		key: "filesWithoutTest",
		noun: "production files with no sibling test file",
		passLabel: "every production file has a test",
		color: "33",
	},
	{
		label: "project prod/test LOC ratio",
		key: "projectLocRatio",
		noun: "project-wide prod/test LOC ratio above limit",
		passLabel: "project prod/test LOC ratio within limits",
		color: "33",
	},
	// === UBS Plan 04 — rows 27–30 ===
	{
		label: "ubs js loose equality",
		key: "jsLooseEquality",
		noun: "loose `==` / `!=` comparisons in JS/TS",
		passLabel: "no loose equality (allowed: `x == null` idiom)",
		color: "33",
	},
	{
		label: "ubs float equality",
		key: "floatEquality",
		noun: "exact-equality comparisons against a float literal",
		passLabel: "no unsafe float equality",
		color: "33",
	},
	{
		label: "ubs java optional.get()",
		key: "javaOptionalGet",
		noun: "Java Optional.get() without isPresent/orElse guard",
		passLabel: "no unguarded Optional.get() calls",
		color: "33",
	},
	{
		label: "ubs division by variable",
		key: "divisionByVariable",
		noun: "divisions by an identifier (advisory)",
		passLabel: "no unguarded division by variable",
		color: "33",
	},
	// === UBS Plan 04 — rows 22–26 (critical-tier) ===
	{
		label: "ubs mutex lock unwrap",
		key: "mutexLockUnwrap",
		noun: "Mutex<T>...lock().unwrap() calls (panic on poisoned mutex)",
		passLabel: "no Mutex::lock().unwrap()",
		color: "31",
	},
	{
		label: "ubs subprocess shell=True",
		key: "subprocessShellTrue",
		noun: "subprocess.<fn>(..., shell=True) calls (command-injection vector)",
		passLabel: "no subprocess(..., shell=True)",
		color: "31",
	},
	{
		label: "ubs tls verify disabled",
		key: "tlsVerifyDisabled",
		noun: "TLS verification disabled (verify=False / InsecureSkipVerify / rejectUnauthorized)",
		passLabel: "TLS verification enabled everywhere",
		color: "31",
	},
	{
		label: "ubs python none equality",
		key: "pyNoneEquality",
		noun: "`x == None` / `x != None` comparisons (PEP 8: use `is None` / `is not None`)",
		passLabel: "no `== None` / `!= None`",
		color: "31",
	},
	{
		label: "ubs weak hash",
		key: "weakHash",
		noun: "MD5 / SHA-1 calls (broken hashes for security-bearing use)",
		passLabel: "no weak hashes",
		color: "31",
	},
	{
		label: "ubs eval input tainted",
		key: "evalInputTainted",
		noun: "eval / Function / exec / compile invoked with non-literal first arg",
		passLabel: "no tainted eval / Function / exec",
		color: "31",
	},
	{
		label: "ubs sql string concat",
		key: "sqlStringConcat",
		noun: "SQL keyword in a quoted string with `+` / template-literal interpolation",
		passLabel: "no SQL string concatenation",
		color: "31",
	},
	{
		label: "ubs py mutable default arg",
		key: "pyMutableDefaultArg",
		noun: "Python `def f(x=[])` / `def f(x={})` (mutable default shared across calls)",
		passLabel: "no Python mutable defaults",
		color: "33",
	},
	// === Plan 04 D.1 backlog (17 of 20) ===
	{
		label: "ubs tempfile mktemp race",
		key: "tempfileMktempRace",
		noun: "tempfile.mktemp() calls (TOCTOU race vector)",
		passLabel: "no tempfile.mktemp",
		color: "31",
	},
	{
		label: "ubs pickle untrusted load",
		key: "pickleUntrustedLoad",
		noun: "pickle.load / pickle.loads / cPickle calls (RCE on attacker bytes)",
		passLabel: "no pickle load/loads",
		color: "31",
	},
	{
		label: "ubs xml external entity",
		key: "xmlExternalEntity",
		noun: "xml.etree / xml.dom / xml.sax / lxml without defusedxml (XXE)",
		passLabel: "all XML parsing uses defusedxml",
		color: "31",
	},
	{
		label: "ubs os.system / os.popen tainted",
		key: "osSystemTainted",
		noun: "os.system(name) / os.popen(name) with non-literal arg (cmd injection)",
		passLabel: "no os.system / os.popen on tainted input",
		color: "31",
	},
	{
		label: "ubs unsafe format string",
		key: "unsafeFormatString",
		noun: "C/C++ printf / sprintf / fprintf with non-literal format",
		passLabel: "no unsafe format strings",
		color: "31",
	},
	{
		label: "ubs unchecked redirect",
		key: "uncheckedRedirect",
		noun: "JS redirect(url) / location.href = url with non-literal URL",
		passLabel: "no unchecked redirects",
		color: "31",
	},
	{
		label: "ubs goroutine no waitgroup",
		key: "goroutineNoWaitgroup",
		noun: "Go `go func()` without WaitGroup / errgroup",
		passLabel: "all goroutines synchronized",
		color: "33",
	},
	{
		label: "ubs defer in loop",
		key: "deferInLoop",
		noun: "Go `defer` inside a `for` loop (defers run at function return)",
		passLabel: "no defers inside loops",
		color: "33",
	},
	{
		label: "ubs string concat in loop",
		key: "ubsStringConcatInLoop",
		noun: "`result += chunk` inside a loop in immutable-string langs (O(n²))",
		passLabel: "no string concat in loop",
		color: "33",
	},
	{
		label: "ubs numeric comparison chain",
		key: "numericComparisonChain",
		noun: "Java 3+ consecutive instanceof / compareTo lines (missing polymorphism)",
		passLabel: "no numeric comparison chains",
		color: "33",
	},
	{
		label: "ubs print debug leak",
		key: "printDebugLeak",
		noun: "console.log / print / fmt.Println in non-test, non-CLI code",
		passLabel: "no print debug leaks",
		color: "33",
	},
	{
		label: "ubs hardcoded localhost",
		key: "ubsHardcodedLocalhost",
		noun: "localhost / 127.0.0.1 baked into source outside test/config/example",
		passLabel: "no hardcoded localhost",
		color: "33",
	},
	{
		label: "child process exec user input",
		key: "childProcessExecUserInput",
		noun: "Node child_process.exec/execSync/spawn with non-literal first arg",
		passLabel: "no tainted child_process invocations",
		color: "31",
	},
	{
		label: "mixed sync/async file api",
		key: "mixedSyncAsyncFileApi",
		noun: "function bodies mixing fs.*Sync with await fs.*",
		passLabel: "no mixed sync/async file APIs",
		color: "31",
	},
	{
		label: "cookie missing security flags",
		key: "cookieMissingSecurityFlags",
		noun: "Set-Cookie / cookies.set / res.cookie without httpOnly+secure",
		passLabel: "no insecure cookies",
		color: "31",
	},
	{
		label: "logger format user input",
		key: "loggerFormatUserInput",
		noun: "logger.<level>(req|ctx|input|user|...) — log-injection vector",
		passLabel: "no logger format-string injections",
		color: "31",
	},
	{
		label: "ubs magic number no const",
		key: "magicNumberNoConst",
		noun: "3+ digit numeric literals in expression context without named constant",
		passLabel: "no magic numbers without constants",
		color: "33",
	},
	{
		label: "ubs large function",
		key: "largeFunction",
		noun: "function spanning 80+ body lines",
		passLabel: "no large functions",
		color: "33",
	},
	{
		label: "ubs deeply nested callback",
		key: "deeplyNestedCallback",
		noun: "4+ levels of nested function/arrow callbacks",
		passLabel: "no deeply nested callbacks",
		color: "33",
	},
	{
		label: "ubs time format locale dep",
		key: "timeFormatLocaleDep",
		noun: "JS toLocaleString / Java DateTimeFormatter.ofLocalized* without explicit locale",
		passLabel: "all locale-dependent formatting is explicit",
		color: "33",
	},
	{
		label: "ubs regex in loop no compile",
		key: "regexInLoopNoCompile",
		noun: "Python re.match / re.search / re.sub inside loop without re.compile",
		passLabel: "no recompiled regex in loop",
		color: "33",
	},
	// === Batch 1: agent-laziness ===
	{
		label: "agent thumbprint prose",
		key: "agentThumbprintProse",
		noun: "agent-thumbprint phrases in source comments (\"for now\", \"in a real implementation\", placeholder narratives)",
		passLabel: "no agent-thumbprint phrases",
		color: "33",
	},
	{
		label: "stub not-implemented throw",
		key: "stubNotImplementedThrow",
		noun: "throw new Error(\"not implemented\" / \"TODO\" / \"stub\") in non-test source",
		passLabel: "no not-implemented stubs",
		color: "33",
	},
	{
		label: "dead branch literal",
		key: "deadBranchLiteral",
		noun: "if (true) / if (false) / else if (true) literal branch conditions",
		passLabel: "no dead branch literals",
		color: "33",
	},
	{
		label: "file-level suppression",
		key: "fileLevelSuppression",
		noun: "ts-nocheck / eslint-disable / biome-ignore-all directives at file head",
		passLabel: "no file-level suppression directives",
		color: "33",
	},
	{
		label: "untestable nondeterminism",
		key: "untestableTimeInSource",
		noun: "inline Date.now / new Date() / Math.random / crypto.randomUUID / performance.now in non-test source",
		passLabel: "no untestable nondeterminism",
		color: "33",
	},
	{
		label: "double-cast via unknown",
		key: "doubleCastUnknown",
		noun: "`as unknown as Foo` double-cast escape hatches",
		passLabel: "no double-cast escape hatches",
		color: "33",
	},
	{
		label: "union widened with string",
		key: "unionWidenedWithString",
		noun: "string-literal unions widened by a bare `string` (the literals are erased)",
		passLabel: "no string-widened unions",
		color: "33",
	},
	{
		label: "NODE_ENV branch in prod",
		key: "nodeenvBranchInProd",
		noun: "process.env.NODE_ENV comparisons inside production source",
		passLabel: "no NODE_ENV branches in production",
		color: "33",
	},
	{
		label: "fetch without timeout",
		key: "fetchWithoutTimeout",
		noun: "fetch / axios calls without signal: / timeout: / AbortController",
		passLabel: "all network calls have a timeout or abort signal",
		color: "33",
	},
	{
		label: "unbounded Promise.all",
		key: "unboundedPromiseAll",
		noun: "Promise.all(<ident>.map(...)) on unbounded source array",
		passLabel: "no unbounded fan-out",
		color: "33",
	},
	{
		label: "sync I/O on hot path",
		key: "syncIoOnHotPath",
		noun: "*Sync I/O calls inside HTTP handler / route / middleware files",
		passLabel: "no sync I/O on hot paths",
		color: "33",
	},
	// === Batch 2: test-hygiene ===
	{
		label: "duplicate test names",
		key: "duplicateTestNames",
		noun: "duplicate it() / test() / specify() name strings within a file",
		passLabel: "no duplicate test names",
		color: "33",
	},
	{
		label: "real network/FS in tests",
		key: "realIoInTests",
		noun: "real network or non-tmp filesystem calls inside test files",
		passLabel: "no real I/O in tests",
		color: "33",
	},
	{
		label: "test nondeterminism",
		key: "testNondeterminism",
		noun: "Date.now / Math.random / crypto.randomUUID in test bodies without fake-timers",
		passLabel: "no test nondeterminism",
		color: "33",
	},
	{
		label: "hardcoded timeout in tests",
		key: "hardcodedTimeoutInTests",
		noun: "setTimeout / setImmediate with literal ms delays inside test bodies",
		passLabel: "no hardcoded timeouts in tests",
		color: "33",
	},
	{
		label: "test missing SUT import",
		key: "testMissingSutImport",
		noun: "test files that don't import their SUT",
		passLabel: "all test files import their SUT",
		color: "33",
	},
	{
		label: "mocking the SUT self",
		key: "mockingTheSutSelf",
		noun: "vi.mock / jest.mock targeting the file under test from inside its own test",
		passLabel: "no SUT-self mocks",
		color: "31",
	},
	// === Batch 5: cross-file ===
	{
		label: "empty-body handler",
		key: "emptyBodyHandler",
		noun: "handler-named functions with empty / no-op bodies",
		passLabel: "no empty-body handlers",
		color: "33",
	},
	{
		label: "listener pairing",
		key: "listenerPairing",
		noun: "addEventListener / process.on / emitter.on without paired cleanup elsewhere in the file",
		passLabel: "all listeners paired with cleanup",
		color: "33",
	},
	{
		label: "schema/type drift",
		key: "schemaTypeDrift",
		noun: "same-file Zod schema vs TS interface drift",
		passLabel: "schema and type agree",
		color: "33",
	},
	{
		label: "migration parity",
		key: "migrationParity",
		noun: "_up.sql migrations without paired _down.sql",
		passLabel: "every migration is reversible",
		color: "33",
	},
	// === Batch 8: demo-data ===
	{
		label: "unmarked demo data",
		key: "demoDataUnmarked",
		noun: "fake-data signatures without `// @demo-data:` directive",
		passLabel: "no unmarked demo data",
		color: "33",
	},
	{
		label: "silent demo fallback",
		key: "silentDemoFallback",
		noun: "try { real API } catch { return [literal] } patterns",
		passLabel: "no silent demo fallbacks",
		color: "31",
	},
	{
		label: "demo runtime banner",
		key: "demoRuntimeMissingBanner",
		noun: "root-layout files importing demo runtime without rendering DemoBanner",
		passLabel: "demo runtime banner mounted",
		color: "33",
	},
];
