// interlinked-tdd: exempt · @codegen-data — pure SectionSpec data fragment; the per-file LOC cap targets code complexity, not data length (the detector logic lives in the checks modules). tsc/lint still run.
// ===========================================
// Taste / structural / iteration-safety sections
// ===========================================
// Trailing fragment of `agentSafetySections` in `./section-table-agent-safety.ts`.
// Covers the iteration-safety + taint + taste / structural / test-hygiene specs,
// from `iteratorInvalidation` through `projectLocRatio`. Spread — in order — by
// the parent fragment so the composed `agentSafetySections` stays byte-identical.

import type { SectionSpec } from "./section-table-types.js";

/** Iteration-safety + taint + taste / structural / test-hygiene sections. */
export const tasteStructuralSections: readonly SectionSpec[] = [
	{
		label: "design slop",
		key: "designSlop",
		noun: "AI-generated design tells (overused fonts, accent stripes, gradient text, AI palettes, bounce easing)",
		passLabel: "no AI design tells",
		color: "31",
	},
	{
		label: "iterator invalidation",
		key: "iteratorInvalidation",
		noun: "collection mutations during iteration over the same collection",
		passLabel: "no iterator invalidations",
		color: "31",
	},
	{
		label: "fresh collection key lookup",
		key: "freshCollectionKeyLookup",
		noun: "Map/Set lookups using fresh-identity keys (NaN, fresh literals, fresh Symbol)",
		passLabel: "no fresh-identity Map/Set keys",
		color: "31",
	},
	{
		label: "discriminated union exhaustiveness",
		key: "discriminatedUnionExhaustiveness",
		noun: "switch statements on literal/discriminated unions without a never-assertion default",
		passLabel: "no non-exhaustive discriminated-union switches",
		color: "31",
	},
	{
		label: "index bounds unchecked",
		key: "indexBoundsUnchecked",
		noun: "external-input numbers reaching array subscripts without a bounds guard",
		passLabel: "no unchecked external-input array indices",
		color: "31",
	},
	{
		label: "cleanup skipped on early exit",
		key: "cleanupSkippedOnEarlyExit",
		noun: "resource acquisitions where a throw/return bypasses the cleanup",
		passLabel: "no skipped cleanups on early exit",
		color: "31",
	},
	{
		label: "tainted to privileged sink",
		key: "taintedToPrivilegedSink",
		noun: "external-input values reaching eval/exec/vm.run/fs.write* without a validator",
		passLabel: "no tainted values reaching privileged sinks",
		color: "31",
	},
	{
		label: "await state TOCTOU",
		key: "awaitStateToctou",
		noun: "same field deref'd before and after an await without re-check",
		passLabel: "no await-state TOCTOU",
		color: "31",
	},
	{
		label: "cleanup reentrancy",
		key: "cleanupReentrancy",
		noun: "dispose/destroy methods that recurse or useEffect cleanups that mutate state",
		passLabel: "no cleanup reentrancy",
		color: "31",
	},
	{
		label: "boundary copy no revalidation",
		key: "boundaryCopyNoRevalidation",
		noun: "Object.assign / spread copies of external input into typed slots",
		passLabel: "no unvalidated boundary copies",
		color: "31",
	},
	{
		label: "magic literal in conditional",
		key: "magicLiteralInConditional",
		noun: "if/switch branches comparing against a bare literal",
		passLabel: "no magic literals in conditionals",
		color: "31",
	},
	{
		label: "NaN coercion guard",
		key: "nanCoercionGuard",
		noun: "coercion results in relational comparisons without a finite/NaN guard",
		passLabel: "no unguarded NaN coercions",
		color: "31",
	},
	{
		label: "unawaited async assertion",
		key: "unawaitedAsyncAssertion",
		noun: "expect(...).rejects/.resolves chains not awaited or returned",
		passLabel: "no floating async assertions in tests",
		color: "31",
	},
	{
		label: "array push return used",
		key: "arrayPushReturnUsed",
		noun: "push()/unshift() return values (the new length) used as a value",
		passLabel: "no push/unshift return-value misuse",
		color: "31",
	},
	{
		label: "variadic builtin iteratee",
		key: "arrayIterateeVariadicBuiltin",
		noun: "parseInt passed bare as a map/flatMap/Array.from iteratee",
		passLabel: "no variadic-builtin iteratees",
		color: "31",
	},
	{
		label: "write without mkdir",
		key: "writeWithoutMkdir",
		noun: "nested-path writes without a prior mkdir-recursive / existsSync guard",
		passLabel: "no writes missing a mkdir guard",
		color: "33",
	},
	{
		label: "duplicated policy constant",
		key: "duplicatedPolicyConstant",
		noun: "bare literals duplicating a same-file named policy constant",
		passLabel: "no duplicated policy constants",
		color: "33",
	},
	{
		label: "snapshot hygiene",
		key: "snapshotHygiene",
		noun: "writes of snapshot-review artifacts (*.snap.new / *.pending-snap) that must not be committed",
		passLabel: "no committed snapshot-review artifacts",
		color: "33",
	},
	{
		label: "payload field casing",
		key: "payloadFieldCasing",
		noun: "raw hook-payload contract fields read in one casing with no other-casing fallback",
		passLabel: "no single-casing raw-payload field reads",
		color: "33",
	},
	{
		label: "gitignored written config",
		key: "gitignoredWrittenConfig",
		noun: "file-writes to a path excluded by .gitignore (no negation carve-out)",
		passLabel: "no writes to gitignored paths",
		color: "33",
	},
	{
		label: "readme script drift",
		key: "readmeScriptDrift",
		noun: "markdown npm-run references to scripts missing from package.json",
		passLabel: "no stale npm-script references in docs",
		color: "33",
	},
	{
		label: "spec path ref",
		key: "specPathRef",
		noun: "present-tense claims that a path exists in-repo when the tree lacks it",
		passLabel: "no false present-tense path-existence claims",
		color: "33",
	},
	{
		label: "async promise executor",
		key: "asyncPromiseExecutor",
		noun: "async Promise constructors",
		passLabel: "no async Promise executors",
		color: "31",
	},
	{
		label: "self imports",
		key: "selfImports",
		noun: "modules importing themselves",
		passLabel: "no self-imports",
		color: "31",
	},
	{
		label: "extraneous dependencies",
		key: "extraneousDeps",
		noun: "imports not in package.json",
		passLabel: "all imports in package.json",
		color: "31",
	},
	{
		label: "eval usage",
		key: "evalUsage",
		noun: "eval/Function/implied eval calls",
		passLabel: "no eval usage",
		color: "31",
	},
	{
		label: "innerHTML usage",
		key: "innerHtml",
		noun: "innerHTML/dangerouslySetInnerHTML",
		passLabel: "no innerHTML usage",
		color: "31",
	},
	{
		label: "NaN comparison",
		key: "nanComparison",
		noun: "direct NaN comparisons",
		passLabel: "no NaN comparisons",
		color: "31",
	},
	{
		label: "constant conditions",
		key: "constantCondition",
		noun: "constant conditionals",
		passLabel: "no constant conditions",
		color: "33",
	},
	{
		label: "unsafe optional chaining",
		key: "unsafeOptionalChaining",
		noun: "unsafe ?. chains",
		passLabel: "no unsafe optional chaining",
		color: "31",
	},
	{
		label: "number precision loss",
		key: "numberPrecisionLoss",
		noun: "unsafe large integers",
		passLabel: "no precision loss risks",
		color: "33",
	},
	{
		label: "non-null assertions",
		key: "nonNullAssertions",
		noun: "non-null assertion operators (!)",
		passLabel: "no non-null assertions",
		color: "33",
	},
	{
		label: "throw literal",
		key: "throwLiteral",
		noun: "throw non-Error values",
		passLabel: "no throw literals",
		color: "31",
	},
	{
		label: "promise reject non-error",
		key: "promiseRejectNonError",
		noun: "Promise.reject() with non-Error literal",
		passLabel: "no Promise.reject with non-Error",
		color: "31",
	},
	{
		label: "lossy error rethrow",
		key: "lossyErrorRethrow",
		noun: "catch (e) { throw new Error(...) } without { cause: e }",
		passLabel: "all rethrows preserve cause",
		color: "33",
	},
	{
		label: "import from own barrel",
		key: "importFromOwnBarrel",
		noun: "imports from own-directory barrel ('./index' / './' / own package name)",
		passLabel: "no own-barrel re-imports",
		color: "33",
	},
	{
		label: "error dispatch by instanceof",
		key: "errorDispatchByInstanceof",
		noun: "`instanceof <BuiltinError>` inside a catch — fragile across realm boundaries",
		passLabel: "no instanceof-builtin-Error dispatch in catch",
		color: "33",
	},
	{
		label: "silent promise catch",
		key: "silentPromiseSwallow",
		noun: ".catch(() => {}) handlers that swallow rejections",
		passLabel: "no silent .catch swallows",
		color: "33",
	},
	{
		label: "unnecessary async",
		key: "requireAwait",
		noun: "async functions without await",
		passLabel: "all async functions use await",
		color: "33",
	},
	{
		label: "accumulating spread",
		key: "accumulatingSpread",
		noun: "O(n²) spread in reduce",
		passLabel: "no accumulating spreads",
		color: "33",
	},
	{
		label: "manual field copy",
		key: "manualFieldCopy",
		noun: "runs of hand-copied object fields",
		passLabel: "no manual field copies",
		color: "33",
	},
	{
		label: "excessive useState",
		key: "excessiveUseState",
		noun: "components with 8+ useState hooks",
		passLabel: "no excessive useState",
		color: "33",
	},
	{
		label: "dangerouslySetInnerHTML",
		key: "dangerouslySetInnerHtml",
		noun: "XSS-risk dangerouslySetInnerHTML usages",
		passLabel: "no dangerouslySetInnerHTML",
		color: "31",
	},
	{
		label: "direct DOM access",
		key: "directDomAccess",
		noun: "direct DOM access in React",
		passLabel: "no direct DOM access",
		color: "33",
	},
	{
		label: "inline object props",
		key: "inlineObjectProps",
		noun: "inline object props causing re-renders",
		passLabel: "no inline object props",
		color: "33",
	},
	{
		label: "async event handlers",
		key: "asyncEventHandler",
		noun: "async event handlers swallowing errors",
		passLabel: "no async event handlers",
		color: "33",
	},
	{
		label: "nested ternaries",
		key: "nestedTernaries",
		noun: "nested ternary operators",
		passLabel: "no nested ternaries",
		color: "33",
	},
	{
		label: "catch and log",
		key: "catchAndLog",
		noun: "catch blocks that only log",
		passLabel: "no catch-and-log blocks",
		color: "33",
	},
	{
		label: "unsafe JSON.parse",
		key: "jsonParseUnsafe",
		noun: "JSON.parse without try-catch",
		passLabel: "all JSON.parse wrapped in try-catch",
		color: "33",
	},
	{
		label: "unvalidated JSON boundary",
		key: "unvalidatedJsonBoundary",
		noun: "JSON.parse/.json() result reaches property access without schema validation",
		passLabel: "no unvalidated JSON boundaries",
		color: "33",
	},
	{
		label: "hardcoded timeouts",
		key: "hardcodedTimeout",
		noun: "hardcoded timeout/interval values",
		passLabel: "no hardcoded timeouts",
		color: "33",
	},
	{
		label: "disabled tests",
		key: "disabledTests",
		noun: "skipped/disabled tests",
		passLabel: "no disabled tests",
		color: "33",
	},
	{
		label: "placeholder tests",
		key: "placeholderTest",
		noun: "stub/pending tests contributing zero coverage",
		passLabel: "no placeholder tests",
		color: "31",
	},
	{
		label: "suppression hygiene",
		key: "suppressionHygiene",
		noun: "suppression entries with short reasons, missing ticket/expiry, or expired dates",
		passLabel: "suppressions are well-formed",
		color: "33",
	},
	{
		label: "target _blank",
		key: "targetBlankNoRel",
		noun: 'target="_blank" without rel="noopener"',
		passLabel: 'no unsafe target="_blank"',
		color: "33",
	},
	{
		label: "snapshot overuse",
		key: "snapshotOveruse",
		noun: "excessive snapshot assertions",
		passLabel: "no snapshot overuse",
		color: "33",
	},
	{
		label: "test importing test",
		key: "testImportingTest",
		noun: "tests importing from other tests",
		passLabel: "no cross-test imports",
		color: "33",
	},
	{
		label: "excessive useEffect",
		key: "excessiveUseEffect",
		noun: "components with 6+ useEffect hooks",
		passLabel: "no excessive useEffect",
		color: "33",
	},
	{
		label: "sequential awaits",
		key: "sequentialAwaits",
		noun: "independent awaits that could parallelize",
		passLabel: "no sequential awaits",
		color: "33",
	},
	{
		label: "index as key",
		key: "indexAsKey",
		noun: "array index used as React key",
		passLabel: "no index-as-key",
		color: "33",
	},
	{
		label: "missing effect cleanup",
		key: "missingEffectCleanup",
		noun: "useEffect without cleanup",
		passLabel: "all effects have cleanup",
		color: "33",
	},
	{
		label: "over-mocking",
		key: "overMocking",
		noun: "test files with 8+ mocks",
		passLabel: "no over-mocking",
		color: "33",
	},
	{
		label: "focused tests",
		key: "focusedTests",
		noun: "shipped focus markers (.only / fit / fdescribe)",
		passLabel: "no focused tests",
		color: "31",
	},
	{
		label: "migration ordering",
		key: "migrationOrdering",
		noun: "CREATE INDEX on column not in same-block CREATE TABLE",
		passLabel: "no migration ordering hazards",
		color: "31",
	},
	{
		label: "SQL schema consistency",
		key: "sqlSchemaConsistency",
		noun: "SQL queries referencing undeclared columns",
		passLabel: "SQL queries match declared schema",
		color: "33",
	},
	{
		label: "visibility filter missing",
		key: "visibilityFilterMissing",
		noun: "soft-delete table queries without archived/deleted filter",
		passLabel: "all soft-delete queries filtered",
		color: "33",
	},
	{
		label: "PII detection",
		key: "piiDetection",
		noun: "potential PII patterns in source",
		passLabel: "no PII patterns detected",
		color: "31",
	},
	{
		label: "assertion-free tests",
		key: "assertionFreeTest",
		noun: "test blocks with no assertion",
		passLabel: "every test block asserts something",
		color: "31",
	},
	{
		label: "tautological assertions",
		key: "tautologicalAssertion",
		noun: "assertions where both sides are identical",
		passLabel: "no tautological assertions",
		color: "31",
	},
	{
		label: "mocking the SUT",
		key: "mockingTheSut",
		noun: "test files mocking the module they test",
		passLabel: "no SUT mocking",
		color: "31",
	},
	{
		label: "private member test access",
		key: "privateMemberTestAccess",
		noun: "tests reaching past the public API",
		passLabel: "tests only touch public API",
		color: "33",
	},
	{
		label: "loop nesting depth",
		key: "loopNestingDepth",
		noun: "loops nested three or more deep",
		passLabel: "no excessive loop nesting",
		color: "33",
	},
	{
		label: "else-if chains",
		key: "elseIfChain",
		noun: "long else-if chains (3+ branches)",
		passLabel: "no long else-if chains",
		color: "33",
	},
	{
		label: "duplicate switch discriminants",
		key: "duplicateSwitchDiscriminant",
		noun: "same discriminant switched in multiple places",
		passLabel: "no duplicate switch discriminants",
		color: "33",
	},
	{
		label: "hybrid classes",
		key: "hybridClass",
		noun: "classes with both public fields and behavioral methods",
		passLabel: "no hybrid classes",
		color: "33",
	},
	{
		label: "fuzzy responsibility names",
		key: "fuzzyResponsibilityName",
		noun: "classes named *Manager/Helper/Util/Service",
		passLabel: "no fuzzy responsibility names",
		color: "33",
	},
	{
		label: "Law of Demeter violations",
		key: "lawOfDemeter",
		noun: "property chains deeper than four segments",
		passLabel: "no train wrecks",
		color: "33",
	},
	{
		label: "flag arguments",
		key: "flagArgument",
		noun: "boolean literals passed as function arguments",
		passLabel: "no flag arguments",
		color: "33",
	},
	{
		label: "commented-out code",
		key: "commentedOutCode",
		noun: "3+ consecutive lines of commented-out code",
		passLabel: "no commented-out code",
		color: "33",
	},
	{
		label: "conditional logic in tests",
		key: "conditionalInTest",
		noun: "tests with if/switch/try in the body",
		passLabel: "no conditionals in test bodies",
		color: "33",
	},
	{
		label: "non-deterministic tests",
		key: "nonDeterministicTest",
		noun: "tests using Date/Math.random without fake timers",
		passLabel: "no non-deterministic tests",
		color: "33",
	},
	{
		label: "empty catch blocks",
		key: "emptyCatch",
		noun: "empty-body catch blocks with no error handling",
		passLabel: "no empty catch blocks",
		color: "33",
	},
	{
		label: "tests without description",
		key: "testWithoutDescription",
		noun: "tests with empty or missing descriptions",
		passLabel: "every test has a description",
		color: "33",
	},
	{
		label: "assertion roulette",
		key: "assertionRoulette",
		noun: "tests with 8+ expect() calls",
		passLabel: "no assertion roulette",
		color: "33",
	},
	{
		label: "magic numbers",
		key: "magicNumber",
		noun: "numeric literals inside function calls",
		passLabel: "no magic numbers",
		color: "33",
	},
	{
		label: "function arg count",
		key: "functionArgCount",
		noun: "functions with 4+ arguments",
		passLabel: "no functions with excessive args",
		color: "33",
	},
	{
		label: "data clumps",
		key: "dataClump",
		noun: "3+ consecutive same-type primitive parameters",
		passLabel: "no data clumps",
		color: "33",
	},
	{
		label: "duplicate describes",
		key: "duplicateDescribe",
		noun: "repeated describe() names in the same test file",
		passLabel: "no duplicate describe names",
		color: "33",
	},
	{
		label: "cross-file switch discriminants",
		key: "crossFileSwitchDiscriminant",
		noun: "same discriminant switched in multiple files",
		passLabel: "no cross-file duplicate discriminants",
		color: "33",
	},
	{
		label: "single-implementation interfaces",
		key: "singleImplementationInterface",
		noun: "interfaces with exactly one implementor",
		passLabel: "no single-implementation interfaces",
		color: "33",
	},
	{
		label: "files without test",
		key: "filesWithoutTest",
		noun: "production files with no sibling test file",
		passLabel: "every production file has a test",
		color: "33",
	},
	{
		label: "project prod/test LOC ratio",
		key: "projectLocRatio",
		noun: "project-wide prod/test LOC ratio above limit",
		passLabel: "project prod/test LOC ratio within limits",
		color: "33",
	},
];
