// ===========================================================================
// Mutation-kill companion for src/registrars/coordination.ts.
//
// GENERATED by the commander-tree kill generator — every one of the 69 surviving
// mutants recorded against this file's `registerCoordinationCommands` symbol is a Stryker StringLiteral
// mutation (originalLexeme -> "") on a Commander `.description(...)` call or an
// `.option(flag, description[, default])` help-text argument. The existing
// coordination.test.ts suite asserts command names and
// `--long` option flags, and action-forwarding behavior — but never reads
// `.description()` on a Command or an Option, so none of these help-text literals were
// observed anywhere. This file closes exactly that gap: for every top-level command and
// every subcommand, it asserts the command's own description AND the full
// {flag: description} map of every option in one shot, so any single description string
// emptied anywhere in the file produces a visible mismatch.
//
// No mocking is needed: `registerCoordinationCommands` builds the whole Command tree synchronously and none
// of these assertions ever invoke `.action(...)` callbacks (which is where the
// lazily-imported command modules are used).
//
// regenerate: npx tsx scratch/fleet-r3/golden-gen/generate-commander.mts --file src/registrars/coordination.ts
// ===========================================================================

import { Command } from "commander";
import { describe, expect, it } from "vitest";
import { nonNull } from "../lib/non-null.js";
import { registerCoordinationCommands } from "./coordination.js";

function build(): Command {
	const program = new Command();
	registerCoordinationCommands(program);
	return program;
}

function top(program: Command, name: string): Command {
	return nonNull(
		program.commands.find((c) => c.name() === name),
		`missing top-level command: ${name}`,
	);
}

function child(parent: Command, name: string): Command {
	return nonNull(
		parent.commands.find((c) => c.name() === name),
		`missing subcommand: ${name} under ${parent.name()}`,
	);
}

/** Every option's `--long` flag mapped to its full description text. */
function optionDescriptions(cmd: Command): Record<string, string> {
	const out: Record<string, string> = {};
	for (const o of cmd.options) {
		out[nonNull(o.long, `option with no --long flag on ${cmd.name()}`)] = o.description;
	}
	return out;
}

describe("registerCoordinationCommands — command + option descriptions (mutation-kill)", () => {
	// test-contract: public-api — attach exposes its documented command and option help text
	it("attach", () => {
		const cmd = top(build(), "attach");
		expect(cmd.description()).toBe("Attach local CLI settings to workspace/agent and link remote identity");
		expect(optionDescriptions(cmd)).toEqual({
			"--server": "Server URL",
			"--workspace": "Active workspace ID (ws_...)",
			"--workspace-key": "Default internal workspace_key for MCP tool calls",
			"--project": "Default internal project_key for MCP tool calls",
			"--agent": "Agent identity to attach",
			"--auto": "Derive workspace_key/project from git repo",
			"--json": "Machine-readable output",
		});
	});

	// test-contract: public-api — reminder exposes its documented command and option help text
	it("reminder (parent — no own options)", () => {
		const cmd = top(build(), "reminder");
		expect(cmd.description()).toBe("File reminder management (warnings when files are touched)");
		expect(optionDescriptions(cmd)).toEqual({});
	});

	// test-contract: public-api — add exposes its documented command and option help text
	it("reminder > add", () => {
		const cmd = child(top(build(), "reminder"), "add");
		expect(cmd.description()).toBe("Add a file reminder");
		expect(optionDescriptions(cmd)).toEqual({
			"--glob": "File glob pattern to match",
			"--message": "Reminder message",
			"--ops": "Comma-separated operations (Edit,Write,Read)",
			"--once": "Fire once per session (default)",
			"--no-once": "Fire every time the file is touched",
			"--id": "Stable ID (auto-generated from glob if omitted)",
			"--team": "Write to guard-rules.json instead of local",
			"--json": "Machine-readable output",
		});
	});

	// test-contract: public-api — list exposes its documented command and option help text
	it("reminder > list", () => {
		const cmd = child(top(build(), "reminder"), "list");
		expect(cmd.description()).toBe("List active file reminders");
		expect(optionDescriptions(cmd)).toEqual({
			"--json": "Machine-readable output",
			"--short": "One-line summary",
			"--full": "Detailed output",
		});
	});

	// test-contract: public-api — remove exposes its documented command and option help text
	it("reminder > remove", () => {
		const cmd = child(top(build(), "reminder"), "remove");
		expect(cmd.description()).toBe("Remove a file reminder by id or glob");
		expect(optionDescriptions(cmd)).toEqual({
			"--team": "Remove from guard-rules.json instead of local",
			"--all": "Remove all reminders",
			"--json": "Machine-readable output",
		});
	});

	// test-contract: public-api — skill exposes its documented command and option help text
	it("skill (parent — no own options)", () => {
		const cmd = top(build(), "skill");
		expect(cmd.description()).toBe("Skill marker management (scopes distilled rules via active_when)");
		expect(optionDescriptions(cmd)).toEqual({});
	});

	// test-contract: public-api — enter exposes its documented command and option help text
	it("skill > enter", () => {
		const cmd = child(top(build(), "skill"), "enter");
		expect(cmd.description()).toBe("Mark a skill as active for the current session(s)");
		expect(optionDescriptions(cmd)).toEqual({
			"--ttl": "TTL like 30m, 1h, 90s (default 30m, capped at 4h)",
			"--session": "Target a specific session (default: broadcast)",
			"--source": "cli | hook | manual (default cli)",
			"--json": "Machine-readable output",
		});
	});

	// test-contract: public-api — leave exposes its documented command and option help text
	it("skill > leave", () => {
		const cmd = child(top(build(), "skill"), "leave");
		expect(cmd.description()).toBe("Clear a skill marker");
		expect(optionDescriptions(cmd)).toEqual({
			"--session": "Target a specific session (default: broadcast)",
			"--json": "Machine-readable output",
		});
	});

	// test-contract: public-api — list exposes its documented command and option help text
	it("skill > list", () => {
		const cmd = child(top(build(), "skill"), "list");
		expect(cmd.description()).toBe("Show currently-active skills across all sessions");
		expect(optionDescriptions(cmd)).toEqual({
			"--session": "Show only one session",
			"--json": "Machine-readable output",
		});
	});

	// test-contract: public-api — handoff exposes its documented command and option help text
	it("handoff", () => {
		const cmd = top(build(), "handoff");
		expect(cmd.description()).toBe("Explicit agent-to-agent handoff with context transfer");
		expect(optionDescriptions(cmd)).toEqual({
			"--include-files": "Include file context in handoff",
			"--json": "Machine-readable output",
		});
	});

	// test-contract: public-api — send exposes its documented command and option help text
	it("send", () => {
		const cmd = top(build(), "send");
		expect(cmd.description()).toBe("Send a message to an agent");
		expect(optionDescriptions(cmd)).toEqual({
			"--file": "Send file contents as message body",
			"--importance": "Message importance: normal, urgent",
			"--json": "Machine-readable output",
		});
	});

	// test-contract: public-api — tasks exposes its documented command and option help text
	it("tasks (parent — no own options)", () => {
		const cmd = top(build(), "tasks");
		expect(cmd.description()).toBe("Task management via the server");
		expect(optionDescriptions(cmd)).toEqual({});
	});

	// test-contract: public-api — list exposes its documented command and option help text
	it("tasks > list", () => {
		const cmd = child(top(build(), "tasks"), "list");
		expect(cmd.description()).toBe("List tasks");
		expect(optionDescriptions(cmd)).toEqual({
			"--status": "Filter by status",
			"--assignee": "Filter by assignee",
			"--priority": "Filter by priority",
			"--limit": "Max entries",
			"--json": "Machine-readable output",
			"--short": "One-line summary",
			"--full": "Detailed output",
		});
	});

	// test-contract: public-api — create exposes its documented command and option help text
	it("tasks > create", () => {
		const cmd = child(top(build(), "tasks"), "create");
		expect(cmd.description()).toBe("Create a new task");
		expect(optionDescriptions(cmd)).toEqual({
			"--description": "Task description",
			"--assignee": "Assign to agent",
			"--priority": "Task priority",
			"--json": "Machine-readable output",
		});
	});

	// test-contract: public-api — show exposes its documented command and option help text
	it("tasks > show", () => {
		const cmd = child(top(build(), "tasks"), "show");
		expect(cmd.description()).toBe("Show task detail");
		expect(optionDescriptions(cmd)).toEqual({
			"--json": "Machine-readable output",
		});
	});

	// test-contract: public-api — claim exposes its documented command and option help text
	it("tasks > claim", () => {
		const cmd = child(top(build(), "tasks"), "claim");
		expect(cmd.description()).toBe("Claim a task");
		expect(optionDescriptions(cmd)).toEqual({
			"--json": "Machine-readable output",
		});
	});

	// test-contract: public-api — complete exposes its documented command and option help text
	it("tasks > complete", () => {
		const cmd = child(top(build(), "tasks"), "complete");
		expect(cmd.description()).toBe("Mark a task as complete");
		expect(optionDescriptions(cmd)).toEqual({
			"--json": "Machine-readable output",
		});
	});

	// test-contract: public-api — workspace exposes its documented command and option help text
	it("workspace (parent — no own options)", () => {
		const cmd = top(build(), "workspace");
		expect(cmd.description()).toBe("Registry workspace management (ws_ IDs)");
		expect(optionDescriptions(cmd)).toEqual({});
	});

	// test-contract: public-api — list exposes its documented command and option help text
	it("workspace > list", () => {
		const cmd = child(top(build(), "workspace"), "list");
		expect(cmd.description()).toBe("Show workspaces");
		expect(optionDescriptions(cmd)).toEqual({
			"--json": "Machine-readable output",
		});
	});

	// test-contract: public-api — switch exposes its documented command and option help text
	it("workspace > switch", () => {
		const cmd = child(top(build(), "workspace"), "switch");
		expect(cmd.description()).toBe("Change active workspace");
		expect(optionDescriptions(cmd)).toEqual({});
	});

	// test-contract: boundary — unknown command names are rejected with stable lookup errors
	// Negative-path case (failure_triage's happy-path-only heuristic wants at
	// least one): both lookup helpers throw for a name that was never
	// registered, instead of silently returning undefined into the caller.
	it("top()/child() throw for a command name that was never registered", () => {
		const program = build();
		expect(() => top(program, "does-not-exist")).toThrow(/missing top-level command/);
		expect(() => child(top(program, "reminder"), "does-not-exist")).toThrow(/missing subcommand/);
	});
});
