// ===========================================================================
// Mutation-kill companion for src/registrars/harness.ts.
//
// GENERATED by the commander-tree kill generator — every one of the 68 surviving
// mutants recorded against this file's `registerHarnessCommands` symbol is a Stryker StringLiteral
// mutation (originalLexeme -> "") on a Commander `.description(...)` call or an
// `.option(flag, description[, default])` help-text argument. The existing
// harness.test.ts suite asserts command names and
// `--long` option flags, and action-forwarding behavior — but never reads
// `.description()` on a Command or an Option, so none of these help-text literals were
// observed anywhere. This file closes exactly that gap: for every top-level command and
// every subcommand, it asserts the command's own description AND the full
// {flag: description} map of every option in one shot, so any single description string
// emptied anywhere in the file produces a visible mismatch.
//
// No mocking is needed: `registerHarnessCommands` builds the whole Command tree synchronously and none
// of these assertions ever invoke `.action(...)` callbacks (which is where the
// lazily-imported command modules are used).
//
// regenerate: npx tsx scratch/fleet-r3/golden-gen/generate-commander.mts --file src/registrars/harness.ts
// ===========================================================================

import { Command } from "commander";
import { describe, expect, it } from "vitest";
import { nonNull } from "../lib/non-null.js";
import { registerHarnessCommands } from "./harness.js";

function build(): Command {
	const program = new Command();
	registerHarnessCommands(program);
	return program;
}

function top(program: Command, name: string): Command {
	return nonNull(
		program.commands.find((c) => c.name() === name),
		`missing top-level command: ${name}`,
	);
}

function child(parent: Command, name: string): Command {
	return nonNull(
		parent.commands.find((c) => c.name() === name),
		`missing subcommand: ${name} under ${parent.name()}`,
	);
}

/** Every option's `--long` flag mapped to its full description text. */
function optionDescriptions(cmd: Command): Record<string, string> {
	const out: Record<string, string> = {};
	for (const o of cmd.options) {
		out[nonNull(o.long, `option with no --long flag on ${cmd.name()}`)] = o.description;
	}
	return out;
}

describe("registerHarnessCommands — command + option descriptions (mutation-kill)", () => {
	// test-contract: public-api — harness exposes its documented command and option help text
	it("harness (parent — no own options)", () => {
		const cmd = top(build(), "harness");
		expect(cmd.description()).toBe("Local harness server: guard evaluation, auto-reservations, agent lifecycle");
		expect(optionDescriptions(cmd)).toEqual({});
	});

	// test-contract: public-api — start exposes its documented command and option help text
	it("harness > start", () => {
		const cmd = child(top(build(), "harness"), "start");
		expect(cmd.description()).toBe("Start the harness server (background daemon by default)");
		expect(optionDescriptions(cmd)).toEqual({
			"--no-daemon": "Run in foreground instead of background",
			"--protocol": "Socket protocol: raw, framed, or dual",
			"--session-id": "Framed socket session id",
			"--verbose": "Verbose logging",
			"--json": "Machine-readable output",
		});
	});

	// test-contract: public-api — stop exposes its documented command and option help text
	it("harness > stop", () => {
		const cmd = child(top(build(), "harness"), "stop");
		expect(cmd.description()).toBe("Stop the harness server");
		expect(optionDescriptions(cmd)).toEqual({
			"--json": "Machine-readable output",
		});
	});

	// test-contract: public-api — restart exposes its documented command and option help text
	it("harness > restart", () => {
		const cmd = child(top(build(), "harness"), "restart");
		expect(cmd.description()).toBe("Stop and restart the harness server (picks up config changes)");
		expect(optionDescriptions(cmd)).toEqual({
			"--no-daemon": "Run in foreground instead of daemon",
			"--protocol": "Socket protocol: raw, framed, or dual",
			"--session-id": "Framed socket session id",
			"--verbose": "Verbose output",
			"--json": "Machine-readable output",
		});
	});

	// test-contract: public-api — status exposes its documented command and option help text
	it("harness > status", () => {
		const cmd = child(top(build(), "harness"), "status");
		expect(cmd.description()).toBe("Show harness status, loaded rules, and active agents");
		expect(optionDescriptions(cmd)).toEqual({
			"--json": "Machine-readable output",
		});
	});

	// test-contract: public-api — checks exposes its documented command and option help text
	it("harness > checks", () => {
		const cmd = child(top(build(), "harness"), "checks");
		expect(cmd.description()).toBe(
			"Show the authoritative check inventory — per-family counts + total (static; no daemon needed)",
		);
		expect(optionDescriptions(cmd)).toEqual({
			"--json": "Machine-readable output",
			"--short": "One-line summary",
			"--full": "Include each count's authoritative source",
		});
	});

	// test-contract: public-api — health exposes its documented command and option help text
	it("harness > health", () => {
		const cmd = child(top(build(), "harness"), "health");
		expect(cmd.description()).toBe(
			"Check-health report from the recurrence log: repeat-rate per check id, probation candidates (demotion signal)",
		);
		expect(optionDescriptions(cmd)).toEqual({
			"--json": "Machine-readable output",
			"--short": "One-line summary",
			"--full": "Show every check id (default: top 25 by repeat-rate)",
		});
	});

	// test-contract: public-api — test exposes its documented command and option help text
	it("harness > test", () => {
		const cmd = child(top(build(), "harness"), "test");
		expect(cmd.description()).toBe(
			"Fire a synthetic PreToolUse event at the running harness and show its decision. Default: a Bash command. Use --write/--edit to test a file operation.",
		);
		expect(optionDescriptions(cmd)).toEqual({
			"--tool": "Tool name to simulate for the positional command",
			"--write": "Simulate a Write to <file> (pair with --from-file or --stdin)",
			"--from-file": "Read the proposed Write content from <path>",
			"--stdin": "Read the proposed Write content from stdin",
			"--edit": "Simulate an Edit to <file> (pair with --old and --new)",
			"--old": "old_string for --edit",
			"--new": "new_string for --edit",
			"--json": "Machine-readable output",
		});
	});

	// test-contract: public-api — reap exposes its documented command and option help text
	it("harness > reap", () => {
		const cmd = child(top(build(), "harness"), "reap");
		expect(cmd.description()).toBe(
			"List (default) or kill orphan harness daemons. --force to SIGTERM. --all also targets the active daemon.",
		);
		expect(optionDescriptions(cmd)).toEqual({
			"--force": "Actually SIGTERM the candidates (default is dry-run)",
			"--all": "Also target the active daemon (equivalent of pkill -f)",
			"--json": "Machine-readable output",
		});
	});

	// test-contract: public-api — clean exposes its documented command and option help text
	it("harness > clean", () => {
		const cmd = child(top(build(), "harness"), "clean");
		expect(cmd.description()).toBe("Remove stale harness.sock + harness.pid (refuses if a daemon is running)");
		expect(optionDescriptions(cmd)).toEqual({
			"--json": "Machine-readable output",
		});
	});

	// test-contract: public-api — mode exposes its documented command and option help text
	it("harness > mode", () => {
		const cmd = child(top(build(), "harness"), "mode");
		expect(cmd.description()).toBe(
			"Show or switch the operational tier (budget|quality|ci) — drives HARNESS_POST_TIMEOUT_MS",
		);
		expect(optionDescriptions(cmd)).toEqual({
			"--json": "Machine-readable output",
		});
	});

	// test-contract: public-api — latency exposes its documented command and option help text
	it("harness > latency", () => {
		const cmd = child(top(build(), "harness"), "latency");
		expect(cmd.description()).toBe("Show per-event latency report from .interlinked/logs/latency.jsonl");
		expect(optionDescriptions(cmd)).toEqual({
			"--json": "Machine-readable output",
			"--by-tool": "Include per-tool stats (events count + when-present p50/p99/max)",
		});
	});

	// test-contract: public-api — scanner exposes its documented command and option help text
	it("scanner (parent — no own options)", () => {
		const cmd = top(build(), "scanner");
		expect(cmd.description()).toBe("PII filter (content scanner) — toggle, inspect, audit");
		expect(optionDescriptions(cmd)).toEqual({});
	});

	// test-contract: public-api — on exposes its documented command and option help text
	it("scanner > on", () => {
		const cmd = child(top(build(), "scanner"), "on");
		expect(cmd.description()).toBe("Enable the PII filter (content scanner)");
		expect(optionDescriptions(cmd)).toEqual({
			"--reason": "Why — recorded in content-scanner.audit.jsonl",
			"--json": "Machine-readable output",
			"--short": "One-line summary",
		});
	});

	// test-contract: public-api — off exposes its documented command and option help text
	it("scanner > off", () => {
		const cmd = child(top(build(), "scanner"), "off");
		expect(cmd.description()).toBe("Disable the PII filter. The exact timestamp is recorded in the audit log.");
		expect(optionDescriptions(cmd)).toEqual({
			"--reason": "Why — recorded in content-scanner.audit.jsonl",
			"--json": "Machine-readable output",
			"--short": "One-line summary",
		});
	});

	// test-contract: public-api — toggle exposes its documented command and option help text
	it("scanner > toggle", () => {
		const cmd = child(top(build(), "scanner"), "toggle");
		expect(cmd.description()).toBe("Flip the PII filter on/off and record the transition");
		expect(optionDescriptions(cmd)).toEqual({
			"--reason": "Why — recorded in content-scanner.audit.jsonl",
			"--json": "Machine-readable output",
			"--short": "One-line summary",
		});
	});

	// test-contract: public-api — status exposes its documented command and option help text
	it("scanner > status", () => {
		const cmd = child(top(build(), "scanner"), "status");
		expect(cmd.description()).toBe("Show PII filter config + runtime state + recent toggle audit");
		expect(optionDescriptions(cmd)).toEqual({
			"--json": "Machine-readable output",
			"--short": "One-line summary",
			"--full": "Detailed output",
		});
	});

	// test-contract: public-api — review exposes its documented command and option help text
	it("scanner > review", () => {
		const cmd = child(top(build(), "scanner"), "review");
		expect(cmd.description()).toBe(
			"Review a WebFetch response flagged by the PII filter — pick allow / redact / block",
		);
		expect(optionDescriptions(cmd)).toEqual({
			"--key": "Review a specific cache key (default: newest pending)",
			"--allow": "Approve the full body (skips interactive prompt)",
			"--redact": "Replace flagged spans with <CATEGORY> placeholders",
			"--block": "Withhold the body entirely",
			"--reason": "Why — recorded in content-scanner.audit.jsonl",
			"--json": "Machine-readable output",
			"--short": "One-line summary",
		});
	});

	// test-contract: boundary — unknown command names are rejected with stable lookup errors
	// Negative-path case (failure_triage's happy-path-only heuristic wants at
	// least one): both lookup helpers throw for a name that was never
	// registered, instead of silently returning undefined into the caller.
	it("top()/child() throw for a command name that was never registered", () => {
		const program = build();
		expect(() => top(program, "does-not-exist")).toThrow(/missing top-level command/);
		expect(() => child(top(program, "harness"), "does-not-exist")).toThrow(/missing subcommand/);
	});
});
