// Tests for node-fetch / undici / global fetch footgun detectors.

import { describe, expect, it } from "vitest";
import { NODE_FETCH_FOOTGUNS } from "./node-fetch.js";

function find(id: string) {
	const f = NODE_FETCH_FOOTGUNS.find((g) => g.id === id);
	if (!f) throw new Error(`footgun ${id} not registered`);
	return f;
}

describe("node_fetch_no_timeout", () => {
	const fg = find("node_fetch_no_timeout");

	it("fires on bare fetch(url) with no options object", () => {
		const content = `const r = await fetch("https://api.example.com/v1");`;
		const matches = fg.detect(content, "src/client.ts");
		expect(matches).toHaveLength(1);
		expect(matches[0]?.line).toBe(1);
		expect(matches[0]?.text).toBe(`const r = await fetch("https://api.example.com/v1");`);
	});

	it("reports the correct 1-based line number for a fetch deeper in the file", () => {
		const content = ["// header comment", "async function load() {", '\treturn fetch("https://x/y");', "}"].join("\n");
		const matches = fg.detect(content, "src/load.ts");
		expect(matches).toHaveLength(1);
		expect(matches[0]?.line).toBe(3);
		expect(matches[0]?.text).toBe('return fetch("https://x/y");');
	});

	it("does NOT fire when the options carry a signal", () => {
		const content = `await fetch(url, { signal: controller.signal });`;
		expect(fg.detect(content, "src/client.ts")).toEqual([]);
	});

	it("does NOT fire when the args mention AbortSignal", () => {
		const content = `await fetch(url, { signal: AbortSignal.timeout(5000) });`;
		expect(fg.detect(content, "src/client.ts")).toEqual([]);
	});

	it("does NOT fire when the args mention timeout", () => {
		const content = `await fetch(url, { timeout: 5000 });`;
		expect(fg.detect(content, "src/client.ts")).toEqual([]);
	});

	it("does NOT fire on a member call like client.fetch(url) (word-boundary guard)", () => {
		const content = `await client.fetch("https://x/y");`;
		expect(fg.detect(content, "src/client.ts")).toEqual([]);
	});

	it("does NOT fire on prefetch(url) (preceding word-char guard)", () => {
		const content = `prefetch("https://x/y");`;
		expect(fg.detect(content, "src/client.ts")).toEqual([]);
	});

	it("fires once per bare fetch when several appear in one file", () => {
		const content = ['fetch("https://a");', "// gap", 'fetch("https://b", { signal: s });', 'fetch("https://c");'].join(
			"\n",
		);
		const matches = fg.detect(content, "src/multi.ts");
		// lines 1 and 4 are bare; line 3 has a signal.
		expect(matches.map((mch) => mch.line)).toEqual([1, 4]);
	});

	it("truncates the reported line text to 150 chars", () => {
		const filler = "x".repeat(400);
		const content = `fetch("https://api/${filler}");`;
		const matches = fg.detect(content, "src/long.ts");
		expect(matches).toHaveLength(1);
		expect(matches[0]?.text.length).toBe(150);
	});

	it("skips non-JS/TS files (e.g. .py extension)", () => {
		const content = `fetch("https://x/y")`;
		expect(fg.detect(content, "src/script.py")).toEqual([]);
	});

	it("skips files with no extension at all", () => {
		const content = `fetch("https://x/y")`;
		expect(fg.detect(content, "Makefile")).toEqual([]);
	});

	it("skips test files (path-based detection)", () => {
		const content = `fetch("https://x/y")`;
		expect(fg.detect(content, "src/client.test.ts")).toEqual([]);
	});

	it("skips generated files (generator marker in header)", () => {
		const content = ["// @generated by some-codegen-tool", 'fetch("https://x/y");'].join("\n");
		expect(fg.detect(content, "src/gen.ts")).toEqual([]);
	});

	it("returns [] when content has no fetch call at all", () => {
		const content = `const x = 1; doSomethingElse();`;
		expect(fg.detect(content, "src/none.ts")).toEqual([]);
	});

	it("matches across the supported .mts extension", () => {
		const content = `fetch("https://x/y");`;
		expect(fg.detect(content, "src/client.mts").length).toBeGreaterThan(0);
	});
});

describe("node_fetch_no_ok_check", () => {
	const fg = find("node_fetch_no_ok_check");

	it("fires on fetch(url).then(r => r.json()) with no r.ok check", () => {
		const content = `const data = await fetch("https://api/x").then(r => r.json());`;
		const matches = fg.detect(content, "src/client.ts");
		expect(matches).toHaveLength(1);
		expect(matches[0]?.line).toBe(1);
		expect(matches[0]?.text).toBe(`const data = await fetch("https://api/x").then(r => r.json());`);
	});

	it("fires with a different bound parameter name (resp => resp.json())", () => {
		const content = `fetch("https://api/x").then(resp => resp.json());`;
		expect(fg.detect(content, "src/client.ts").length).toBeGreaterThan(0);
	});

	it("does NOT fire when .ok appears within the surrounding window", () => {
		const content = `fetch("https://api/x").then(r => { if (!r.ok) throw new Error("bad"); return r.json(); });`;
		// The arrow form here is a block, so the json()-after-arrow regex
		// won't match; but a window-based .ok presence is the safety net.
		expect(fg.detect(content, "src/client.ts")).toEqual([]);
	});

	it("does NOT fire when an .ok guard precedes the then(r => r.json()) within 100 chars", () => {
		const content = [
			`const r0 = await fetch("https://api/x");`,
			`if (!r0.ok) throw new Error("bad");`,
			`const data = await fetch("https://api/y").then(r => r.json());`,
		].join("\n");
		// The .ok on line 2 sits inside the 100-char lookback window of the
		// match on line 3, so the detector treats it as guarded.
		expect(fg.detect(content, "src/client.ts")).toEqual([]);
	});

	it("does NOT fire when the bound name mismatches (r => q.json())", () => {
		// Backreference \1 requires the same identifier on both sides.
		const content = `fetch("https://api/x").then(r => q.json());`;
		expect(fg.detect(content, "src/client.ts")).toEqual([]);
	});

	it("reports the correct line number for a multi-line file", () => {
		const content = [
			"// preamble",
			"async function get() {",
			'\treturn fetch("https://api/z").then(r => r.json());',
			"}",
		].join("\n");
		const matches = fg.detect(content, "src/get.ts");
		expect(matches).toHaveLength(1);
		expect(matches[0]?.line).toBe(3);
		expect(matches[0]?.text).toBe('return fetch("https://api/z").then(r => r.json());');
	});

	it("fires when the json() match sits at the very start of the file (windowStart clamp at 0)", () => {
		const content = `fetch("u").then(r => r.json())`;
		const matches = fg.detect(content, "src/edge.ts");
		expect(matches).toHaveLength(1);
		expect(matches[0]?.line).toBe(1);
	});

	it("skips non-JS/TS files", () => {
		const content = `fetch("https://api/x").then(r => r.json())`;
		expect(fg.detect(content, "src/script.rb")).toEqual([]);
	});

	it("skips test files", () => {
		const content = `fetch("https://api/x").then(r => r.json())`;
		expect(fg.detect(content, "src/__tests__/client.test.ts")).toEqual([]);
	});

	it("skips generated files", () => {
		const content = ["/* @generated */", `fetch("https://api/x").then(r => r.json())`].join("\n");
		expect(fg.detect(content, "src/gen.ts")).toEqual([]);
	});

	it("returns [] when there is a fetch but no .then(r => r.json()) shape", () => {
		const content = `const r = await fetch("https://api/x"); const data = await r.json();`;
		expect(fg.detect(content, "src/none.ts")).toEqual([]);
	});

	it("fires twice when two unguarded fetch-then-json calls appear", () => {
		const content = [
			`fetch("https://a").then(r => r.json());`,
			"// some spacer line to push the next match outside the window".repeat(3),
			`fetch("https://b").then(s => s.json());`,
		].join("\n");
		const matches = fg.detect(content, "src/two.ts");
		expect(matches).toHaveLength(2);
		expect(matches.map((mch) => mch.line)).toEqual([1, 3]);
	});
});

describe("NODE_FETCH_FOOTGUNS registry shape", () => {
	it("registers exactly the two node-fetch detectors with stable ids", () => {
		expect(NODE_FETCH_FOOTGUNS.map((g) => g.id).sort()).toEqual(["node_fetch_no_ok_check", "node_fetch_no_timeout"]);
	});

	it("tags every detector with the node-fetch library and a non-empty fix instruction", () => {
		for (const g of NODE_FETCH_FOOTGUNS) {
			expect(g.library).toBe("node-fetch");
			expect(g.name.length).toBeGreaterThan(0);
			expect(g.fixInstruction.length).toBeGreaterThan(0);
		}
	});

	it("no_timeout fix instruction names the AbortSignal.timeout remedy", () => {
		expect(find("node_fetch_no_timeout").fixInstruction).toContain("AbortSignal.timeout");
	});

	it("no_ok_check fix instruction names the r.ok remedy", () => {
		expect(find("node_fetch_no_ok_check").fixInstruction).toContain("r.ok");
	});
});
