// Mutation-kill companion for src/harness/check-metadata/behavioral.ts.
//
// GENERATED by the string-class kill generator — every one of the 22 surviving
// mutants recorded against this file at generation time was a Stryker StringLiteral
// mutation (originalLexeme -> "") on a value inside one of the exported metadata tables
// below. A prior companion test suite (if any) asserted only the SHAPE of these tables
// (non-empty string, valid tier/determinism) — shape checks accept an empty string, so
// they cannot see a StringLiteral mutant. This file closes that gap by asserting the
// COMPLETE table via toEqual (not per-string toContain fragments): any single value
// emptied anywhere in the table produces a visible mismatch, in one block per table.
//
// regenerate: npx tsx scratch/fleet-r3/golden-gen/generate.mts --file src/harness/check-metadata/behavioral.ts
// (safe to re-run any time the table's real content legitimately changes — see the
// generator's own header for what it does and does not handle.)

import { describe, expect, it } from "vitest";
import { BEHAVIORAL_CHECK_META } from "./behavioral.js";
import type { CheckMeta } from "./types.js";

describe("BEHAVIORAL_CHECK_META content (mutation-kill)", () => {
	const EXPECTED_BEHAVIORAL_CHECK_META: Record<string, CheckMeta> = {
		repeated_edit_without_test: {
			name: "Repeated Edit Without Test",
			description: "File edited 3+ times without running tests",
			tier: 2,
			determinism: "heuristic",
		},
		suppression_as_workaround: {
			name: "Suppression as Workaround",
			description: "Suppression directive added after harness warning instead of fixing",
			tier: 1,
			determinism: "partially_deterministic",
		},
		domain_sensitive_test_nudge: {
			name: "Domain-Sensitive Test Nudge",
			description: "Security-sensitive code edited without running auth/security tests",
			tier: 2,
			determinism: "heuristic",
		},
		persistent_warning_escalation: {
			name: "Persistent Warning Escalation",
			description: "Same warning fires again after re-edit — escalated to error",
			tier: 1,
			determinism: "fully_deterministic",
		},
		tdd_cycle_violation: {
			name: "TDD Cycle Violation",
			description: "Implementation edits without establishing a red test first, or continued edits while tests are failing",
			tier: 2,
			determinism: "partially_deterministic",
		},
		tdd_regression: {
			name: "TDD Regression",
			description: "Tests were passing (green) but a subsequent edit caused them to fail (green→red)",
			tier: 1,
			determinism: "partially_deterministic",
		},
		tdd_green_confirmation: {
			name: "TDD Green Confirmation",
			description: "Positive signal: tests transitioned from red to green, completing the TDD cycle",
			tier: 2,
			determinism: "fully_deterministic",
		},
		tdd_commit_gate: {
			name: "TDD Commit Gate",
			description: "Pre-commit check ensuring tests pass and edited files have test coverage before git commit",
			tier: 1,
			determinism: "partially_deterministic",
		},
		test_timeout_inflation: {
			name: "Test Timeout Inflation",
			description: "An existing test-timeout literal ({timeout: N}, it() third-arg, or testTimeout config) is raised in the staged diff — buying wall-clock instead of fixing slowness or flakiness",
			tier: 1,
			determinism: "heuristic",
		},
		assertion_count_regression: {
			name: "Assertion Count Regression",
			description: "Staged test files net-removed assertions while production source changed — a deleted expect() weakens the oracle exactly when it should tighten (test-oracle-integrity.md)",
			tier: 1,
			determinism: "heuristic",
		},
		assertion_value_swap: {
			name: "Assertion Value Swap",
			description: "Same subject and matcher with a different expected value in one staged diff (toBe(5) → toBe(6)) — legitimate when the spec changed, the highest-signal line to review when it didn't; info-only, never blocks",
			tier: 1,
			determinism: "heuristic",
		},
	};

	// test-contract: public-api — BEHAVIORAL_CHECK_META is the agent-facing check-documentation surface (interlinked verify --json, doc generation); every name, description, tier, and determinism value it carries must survive intact.
	it("preserves every name, description, tier, and determinism value (22 StringLiteral survivors closed)", () => {
		expect(BEHAVIORAL_CHECK_META).toEqual(EXPECTED_BEHAVIORAL_CHECK_META);
	});

	// test-contract: invariant — every entry in BEHAVIORAL_CHECK_META keeps a non-empty name/description and a determinism value from the documented set, independent of the exact wording above.
	it("no entry ships blank required text", () => {
		for (const [id, meta] of Object.entries(BEHAVIORAL_CHECK_META)) {
			expect(meta.name, id).not.toBe("");
			expect(meta.description, id).not.toBe("");
			expect(["fully_deterministic", "partially_deterministic", "heuristic"], id).toContain(meta.determinism);
		}
	});
});
