// Mutation-kill companion for src/harness/check-metadata/generic-test-hygiene.ts.
//
// GENERATED by the string-class kill generator — every one of the 24 surviving
// mutants recorded against this file at generation time was a Stryker StringLiteral
// mutation (originalLexeme -> "") on a value inside one of the exported metadata tables
// below. A prior companion test suite (if any) asserted only the SHAPE of these tables
// (non-empty string, valid tier/determinism) — shape checks accept an empty string, so
// they cannot see a StringLiteral mutant. This file closes that gap by asserting the
// COMPLETE table via toEqual (not per-string toContain fragments): any single value
// emptied anywhere in the table produces a visible mismatch, in one block per table.
//
// regenerate: npx tsx scratch/fleet-r3/golden-gen/generate.mts --file src/harness/check-metadata/generic-test-hygiene.ts
// (safe to re-run any time the table's real content legitimately changes — see the
// generator's own header for what it does and does not handle.)

import { describe, expect, it } from "vitest";
import { GENERIC_TEST_HYGIENE_META } from "./generic-test-hygiene.js";
import type { CheckMeta } from "./types.js";

describe("GENERIC_TEST_HYGIENE_META content (mutation-kill)", () => {
	const EXPECTED_GENERIC_TEST_HYGIENE_META: Record<string, CheckMeta> = {
		duplicate_test_names: {
			name: "Duplicate Test Names",
			description: "Detects two it() / test() / specify() blocks with identical name strings within the same file.",
			tier: 1,
			determinism: "fully_deterministic",
		},
		real_io_in_tests: {
			name: "Real Network / Filesystem in Tests",
			description: "Detects fetch / axios / http calls to non-loopback URLs or *Sync writes to non-tmp paths inside test files.",
			tier: 1,
			determinism: "partially_deterministic",
		},
		test_nondeterminism: {
			name: "Test Nondeterminism",
			description: "Detects Date.now / Math.random / crypto.randomUUID in test bodies without fake-timers / clock mocking.",
			tier: 1,
			determinism: "partially_deterministic",
		},
		hardcoded_timeout_in_tests: {
			name: "Hardcoded Timeout in Tests",
			description: "Detects setTimeout / setImmediate with literal millisecond delays inside test bodies.",
			tier: 2,
			determinism: "fully_deterministic",
		},
		test_missing_sut_import: {
			name: "Test Missing SUT Import",
			description: "Detects test files that don't import their SUT (foo.test.ts without `./foo` / `../foo`).",
			tier: 1,
			determinism: "partially_deterministic",
		},
		mocking_the_sut_self: {
			name: "Mocking the SUT in Its Own Test",
			description: "Detects vi.mock / jest.mock targeting the file under test from inside its own test.",
			tier: 1,
			determinism: "fully_deterministic",
		},
		test_subprocess_default_timeout: {
			name: "Test Spawns Slow Subprocess Without Timeout",
			description: "Detects it() / test() callbacks that spawn a known-slow subprocess (tsc, biome, npx, tsx, eslint, vitest, the project CLI) via node:child_process exec/spawn primitives with no explicit `{ timeout: N }` options object or trailing numeric-timeout argument.",
			tier: 2,
			determinism: "heuristic",
		},
		mock_only_test: {
			name: "Mock-Only Test",
			description: "Detects it() / test() blocks whose every assertion is a call-interaction matcher (toHaveBeenCalled* / toHaveReturned*) with no value, output, or state assertion.",
			tier: 2,
			determinism: "partially_deterministic",
		},
		happy_path_only_test: {
			name: "Happy-Path-Only Test File",
			description: "Detects test files with 3+ cases that never assert a failure path (no .not.*, toThrow, .rejects, falsy assertion, or failure-named case).",
			tier: 2,
			determinism: "heuristic",
		},
		test_legitimacy: {
			name: "Test Legitimacy",
			description: "Requires per-case behavioral grounding for mutation-directed tests and flags broad truthiness, incidental call-order assertions, and explicitly private/internal imports.",
			tier: 2,
			determinism: "heuristic",
		},
		test_platform_conditional: {
			name: "Platform-Conditional Test Assertion",
			description: "A test comment narrates platform-variant behavior ('on platforms where…', 'macOS-only') while the NARRATED test never gates on it — evidence must be a PLATFORM-conditioned skipIf/runIf (process.platform, a platform-derived constant, or a platform-named flag) on that test or an enclosing suite, a platform branch in its body, or an unconditional .skip/.todo; a dependency gate like skipIf(!dockerAvailable), a gate on an unrelated sibling, or a mention in a comment/string is not evidence.",
			tier: 3,
			determinism: "heuristic",
		},
		test_silent_dependency_skip: {
			name: "Silent Dependency Skip",
			description: "`if (!X_AVAILABLE) return;` inside a test callback — bare, braced (`{ return; }`), or multi-line — records a PASS wherever the external dependency is missing; CI reports green while running nothing. Guards in helpers/lifecycle hooks are exempt. Use it.skipIf so the skip is reported.",
			tier: 1,
			determinism: "fully_deterministic",
		},
		procfs_probe_in_test: {
			name: "Procfs Probe in Test",
			description: "A test file uses a `/proc/…` path as an \"unwritable path\" fixture. Recursive mkdir under /proc does not throw on Linux — it spins forever and hangs the test worker until the CI job times out (invisible on macOS, which has no /proc). Only a literal whose whole value is an absolute procfs path counts; comments are masked and the informational files (/proc/cpuinfo, /proc/meminfo, …) are exempt on exact match. Fix: nest the fixture under a regular FILE (ENOTDIR everywhere).",
			tier: 1,
			determinism: "heuristic",
		},
	};

	// test-contract: public-api — GENERIC_TEST_HYGIENE_META is the agent-facing check-documentation surface (interlinked verify --json, doc generation); every name, description, tier, and determinism value it carries must survive intact.
	it("preserves every name, description, tier, and determinism value (24 StringLiteral survivors closed)", () => {
		expect(GENERIC_TEST_HYGIENE_META).toEqual(EXPECTED_GENERIC_TEST_HYGIENE_META);
	});

	// test-contract: invariant — every entry in GENERIC_TEST_HYGIENE_META keeps a non-empty name/description and a determinism value from the documented set, independent of the exact wording above.
	it("no entry ships blank required text", () => {
		for (const [id, meta] of Object.entries(GENERIC_TEST_HYGIENE_META)) {
			expect(meta.name, id).not.toBe("");
			expect(meta.description, id).not.toBe("");
			expect(["fully_deterministic", "partially_deterministic", "heuristic"], id).toContain(meta.determinism);
		}
	});
});
