// Mutation-kill companion for src/harness/check-metadata/generic-cross-file.ts.
//
// GENERATED by the string-class kill generator — every one of the 8 surviving
// mutants recorded against this file at generation time was a Stryker StringLiteral
// mutation (originalLexeme -> "") on a value inside one of the exported metadata tables
// below. A prior companion test suite (if any) asserted only the SHAPE of these tables
// (non-empty string, valid tier/determinism) — shape checks accept an empty string, so
// they cannot see a StringLiteral mutant. This file closes that gap by asserting the
// COMPLETE table via toEqual (not per-string toContain fragments): any single value
// emptied anywhere in the table produces a visible mismatch, in one block per table.
//
// regenerate: npx tsx scratch/fleet-r3/golden-gen/generate.mts --file src/harness/check-metadata/generic-cross-file.ts
// (safe to re-run any time the table's real content legitimately changes — see the
// generator's own header for what it does and does not handle.)

import { describe, expect, it } from "vitest";
import { GENERIC_CROSS_FILE_META } from "./generic-cross-file.js";
import type { CheckMeta } from "./types.js";

describe("GENERIC_CROSS_FILE_META content (mutation-kill)", () => {
	const EXPECTED_GENERIC_CROSS_FILE_META: Record<string, CheckMeta> = {
		empty_body_handler: {
			name: "Empty-Body Handler",
			description: "Detects handler-named functions (handle*, route*, on[A-Z]*, HTTP verb-named) with empty / no-op bodies.",
			tier: 2,
			determinism: "heuristic",
		},
		listener_pairing: {
			name: "Listener Pairing",
			description: "Detects addEventListener / process.on / emitter.on without paired removeEventListener / off / removeListener.",
			tier: 2,
			determinism: "heuristic",
		},
		schema_type_drift: {
			name: "Schema ↔ Type Drift",
			description: "Detects same-file Zod schemas and TS interfaces with overlapping name root but divergent property sets.",
			tier: 2,
			determinism: "heuristic",
		},
		migration_parity: {
			name: "Migration Parity",
			description: "Detects `*_up.sql` files without a matching `*_down.sql` in the same dir.",
			tier: 1,
			determinism: "fully_deterministic",
		},
	};

	// test-contract: public-api — GENERIC_CROSS_FILE_META is the agent-facing check-documentation surface (interlinked verify --json, doc generation); every name, description, tier, and determinism value it carries must survive intact.
	it("preserves every name, description, tier, and determinism value (8 StringLiteral survivors closed)", () => {
		expect(GENERIC_CROSS_FILE_META).toEqual(EXPECTED_GENERIC_CROSS_FILE_META);
	});

	// test-contract: invariant — every entry in GENERIC_CROSS_FILE_META keeps a non-empty name/description and a determinism value from the documented set, independent of the exact wording above.
	it("no entry ships blank required text", () => {
		for (const [id, meta] of Object.entries(GENERIC_CROSS_FILE_META)) {
			expect(meta.name, id).not.toBe("");
			expect(meta.description, id).not.toBe("");
			expect(["fully_deterministic", "partially_deterministic", "heuristic"], id).toContain(meta.determinism);
		}
	});
});
