// Mutation-kill companion for src/harness/check-metadata/generic-c.ts.
//
// GENERATED by the string-class kill generator — every one of the 10 surviving
// mutants recorded against this file at generation time was a Stryker StringLiteral
// mutation (originalLexeme -> "") on a value inside one of the exported metadata tables
// below. A prior companion test suite (if any) asserted only the SHAPE of these tables
// (non-empty string, valid tier/determinism) — shape checks accept an empty string, so
// they cannot see a StringLiteral mutant. This file closes that gap by asserting the
// COMPLETE table via toEqual (not per-string toContain fragments): any single value
// emptied anywhere in the table produces a visible mismatch, in one block per table.
//
// regenerate: npx tsx scratch/fleet-r3/golden-gen/generate.mts --file src/harness/check-metadata/generic-c.ts
// (safe to re-run any time the table's real content legitimately changes — see the
// generator's own header for what it does and does not handle.)

import { describe, expect, it } from "vitest";
import { GENERIC_C_META } from "./generic-c.js";
import type { CheckMeta } from "./types.js";

describe("GENERIC_C_META content (mutation-kill)", () => {
	const EXPECTED_GENERIC_C_META: Record<string, CheckMeta> = {
		c_unsafe_functions: {
			name: "C Unsafe Functions",
			description: "Detects unsafe C functions: strcpy, strcat, gets, sprintf",
			tier: 1,
			determinism: "fully_deterministic",
		},
		c_include_guard: {
			name: "C Include Guard",
			description: "Detects header files missing #pragma once or #ifndef guard",
			tier: 1,
			determinism: "fully_deterministic",
		},
		c_strcmp_boolean_misuse: {
			name: "C strcmp Boolean Misuse",
			description: "Detects strcmp return value used as boolean without comparison",
			tier: 1,
			determinism: "partially_deterministic",
		},
		c_unchecked_malloc: {
			name: "C Unchecked Malloc",
			description: "Detects malloc/calloc/realloc without null check",
			tier: 2,
			determinism: "partially_deterministic",
		},
		c_sprintf_usage: {
			name: "C sprintf Usage",
			description: "Detects sprintf — use snprintf for bounds safety",
			tier: 1,
			determinism: "fully_deterministic",
		},
	};

	// test-contract: public-api — GENERIC_C_META is the agent-facing check-documentation surface (interlinked verify --json, doc generation); every name, description, tier, and determinism value it carries must survive intact.
	it("preserves every name, description, tier, and determinism value (10 StringLiteral survivors closed)", () => {
		expect(GENERIC_C_META).toEqual(EXPECTED_GENERIC_C_META);
	});

	// test-contract: invariant — every entry in GENERIC_C_META keeps a non-empty name/description and a determinism value from the documented set, independent of the exact wording above.
	it("no entry ships blank required text", () => {
		for (const [id, meta] of Object.entries(GENERIC_C_META)) {
			expect(meta.name, id).not.toBe("");
			expect(meta.description, id).not.toBe("");
			expect(["fully_deterministic", "partially_deterministic", "heuristic"], id).toContain(meta.determinism);
		}
	});
});
