// Mutation-kill companion for src/harness/check-metadata/generic-endpoint.ts.
//
// GENERATED by the string-class kill generator — every one of the 15 surviving
// mutants recorded against this file at generation time was a Stryker StringLiteral
// mutation (originalLexeme -> "") on a value inside one of the exported metadata tables
// below. A prior companion test suite (if any) asserted only the SHAPE of these tables
// (non-empty string, valid tier/determinism) — shape checks accept an empty string, so
// they cannot see a StringLiteral mutant. This file closes that gap by asserting the
// COMPLETE table via toEqual (not per-string toContain fragments): any single value
// emptied anywhere in the table produces a visible mismatch, in one block per table.
//
// regenerate: npx tsx scratch/fleet-r3/golden-gen/generate.mts --file src/harness/check-metadata/generic-endpoint.ts
// (safe to re-run any time the table's real content legitimately changes — see the
// generator's own header for what it does and does not handle.)

import { describe, expect, it } from "vitest";
import { GENERIC_ENDPOINT_META } from "./generic-endpoint.js";
import type { CheckMeta } from "./types.js";

describe("GENERIC_ENDPOINT_META content (mutation-kill)", () => {
	const EXPECTED_GENERIC_ENDPOINT_META: Record<string, CheckMeta> = {
		endpoint_auth_missing: {
			name: "Endpoint Auth Missing",
			description: "Detects HTTP endpoints whose route-extracted auth_chain is empty AND no recognized auth middleware appears at the router-mount level. Covers Express, Hono, Next.js, FastAPI.",
			tier: 1,
			determinism: "heuristic",
			externality: "local_write",
		},
		endpoint_idor_shape: {
			name: "Endpoint IDOR Shape",
			description: "Detects handlers that read a path param and feed it to a DB call without an auth-context predicate — the canonical Insecure Direct Object Reference shape.",
			tier: 1,
			determinism: "heuristic",
			externality: "local_write",
		},
		endpoint_missing_tenant_filter: {
			name: "Endpoint Missing Tenant Filter",
			description: "Detects DB queries inside a handler scope whose WHERE clause omits all configured tenant columns (org_id, workspace_id, business_id, tenant_id). Conservative — dynamic WHEREs are skipped.",
			tier: 1,
			determinism: "heuristic",
			externality: "local_write",
		},
		endpoint_ssrf_shape: {
			name: "Endpoint SSRF Shape",
			description: "Detects handlers that read a URL-shaped value and pass it to an HTTP client without an allow-list sanitizer registered in `.interlinked/sanitizers.json#url`.",
			tier: 1,
			determinism: "heuristic",
			externality: "local_write",
		},
		endpoint_mass_assignment: {
			name: "Endpoint Mass Assignment",
			description: "Detects handlers that spread request body into a model create/update without an explicit field allowlist or schema validator (zod / Pydantic / pick).",
			tier: 1,
			determinism: "heuristic",
			externality: "local_write",
		},
	};

	// test-contract: public-api — GENERIC_ENDPOINT_META is the agent-facing check-documentation surface (interlinked verify --json, doc generation); every name, description, tier, determinism, and externality value it carries must survive intact.
	it("preserves every name, description, tier, determinism, and externality value (15 StringLiteral survivors closed)", () => {
		expect(GENERIC_ENDPOINT_META).toEqual(EXPECTED_GENERIC_ENDPOINT_META);
	});

	// test-contract: invariant — every entry in GENERIC_ENDPOINT_META keeps a non-empty name/description and a determinism value from the documented set, independent of the exact wording above.
	it("no entry ships blank required text", () => {
		for (const [id, meta] of Object.entries(GENERIC_ENDPOINT_META)) {
			expect(meta.name, id).not.toBe("");
			expect(meta.description, id).not.toBe("");
			expect(["fully_deterministic", "partially_deterministic", "heuristic"], id).toContain(meta.determinism);
		}
	});
});
