// Mutation-kill companion for src/harness/check-metadata/generic-agent-laziness.ts.
//
// GENERATED by the string-class kill generator — every one of the 26 surviving
// mutants recorded against this file at generation time was a Stryker StringLiteral
// mutation (originalLexeme -> "") on a value inside one of the exported metadata tables
// below. A prior companion test suite (if any) asserted only the SHAPE of these tables
// (non-empty string, valid tier/determinism) — shape checks accept an empty string, so
// they cannot see a StringLiteral mutant. This file closes that gap by asserting the
// COMPLETE table via toEqual (not per-string toContain fragments): any single value
// emptied anywhere in the table produces a visible mismatch, in one block per table.
//
// regenerate: npx tsx scratch/fleet-r3/golden-gen/generate.mts --file src/harness/check-metadata/generic-agent-laziness.ts
// (safe to re-run any time the table's real content legitimately changes — see the
// generator's own header for what it does and does not handle.)

import { describe, expect, it } from "vitest";
import { GENERIC_AGENT_LAZINESS_META } from "./generic-agent-laziness.js";
import type { CheckMeta } from "./types.js";

describe("GENERIC_AGENT_LAZINESS_META content (mutation-kill)", () => {
	const EXPECTED_GENERIC_AGENT_LAZINESS_META: Record<string, CheckMeta> = {
		agent_thumbprint_prose: {
			name: "Agent Thumbprint Prose",
			description: "Detects literal phrases LLMs use when giving up — placeholder narratives left in comments instead of finishing the work.",
			tier: 1,
			determinism: "partially_deterministic",
		},
		stub_not_implemented_throw: {
			name: "Stub Not-Implemented Throw",
			description: "Detects `throw new Error(\"not implemented\" | \"TODO\" | \"stub\" | ...)` and empty `throw new Error()` in non-test source.",
			tier: 1,
			determinism: "partially_deterministic",
		},
		dead_branch_literal: {
			name: "Dead Branch Literal",
			description: "Detects `if (true)` / `if (false)` / `else if (true)` debugger artifacts that bypass real control flow.",
			tier: 1,
			determinism: "partially_deterministic",
		},
		file_level_suppression: {
			name: "File-Level Suppression",
			description: "Detects file-wide suppression directives (ts-nocheck, eslint-disable with no rule list, biome-ignore-all, pylint disable=all).",
			tier: 1,
			determinism: "fully_deterministic",
		},
		untestable_time_in_source: {
			name: "Untestable Nondeterminism",
			description: "Detects inline Date.now / new Date() / Math.random / crypto.randomUUID / performance.now in non-test source — requires injection point.",
			tier: 1,
			determinism: "partially_deterministic",
		},
		double_cast_unknown: {
			name: "Double-Cast via Unknown",
			description: "Detects `as unknown as Foo` — agents reach for this when a single `as` won't satisfy TypeScript.",
			tier: 2,
			determinism: "partially_deterministic",
		},
		type_smuggling: {
			name: "Type-Smuggling Cast",
			description: "Detects `as T` casts where the source expression's static type has no structural overlap with `T` — the cast lies, instead of narrowing or widening. TypeScript compiler API; `as unknown`/`as any`/`as const` are exempt.",
			tier: 3,
			determinism: "partially_deterministic",
		},
		union_widened_with_string: {
			name: "Union Widened With Bare String",
			description: "Detects `\"a\" | \"b\" | string` — TypeScript narrows the union back to `string`, defeating the literal alternatives.",
			tier: 2,
			determinism: "heuristic",
		},
		nodeenv_branch_in_prod: {
			name: "NODE_ENV Branch in Production",
			description: "Detects `process.env.NODE_ENV === \"test\"` (or development/staging/local) inside non-test, non-config source.",
			tier: 1,
			determinism: "partially_deterministic",
		},
		fetch_without_timeout: {
			name: "Fetch / Axios Without Timeout",
			description: "Detects fetch() and axios calls without `signal:` / `timeout:` / AbortController in their options.",
			tier: 1,
			determinism: "heuristic",
		},
		unbounded_promise_all: {
			name: "Promise.all on Unbounded Array",
			description: "Detects `Promise.all(<ident>.map(asyncFn))` patterns — fans out N parallel requests for an N-sized input.",
			tier: 2,
			determinism: "heuristic",
		},
		sync_io_on_hot_path: {
			name: "Synchronous I/O on Hot Path",
			description: "Detects *Sync (readFileSync / execSync / etc.) inside HTTP handler / route / middleware files.",
			tier: 2,
			determinism: "heuristic",
		},
		placeholder_runtime_constant: {
			name: "Placeholder Runtime Constant",
			description: "Detects a numeric constant whose own comment confesses it is a temporary stand-in (\"stand-in until Phase B\", \"hardcoded for now\") — the Bun #31503 BSS_OVERFLOW_BLOCK_SIZE=64 class.",
			tier: 1,
			determinism: "heuristic",
		},
	};

	// test-contract: public-api — GENERIC_AGENT_LAZINESS_META is the agent-facing check-documentation surface (interlinked verify --json, doc generation); every name, description, tier, and determinism value it carries must survive intact.
	it("preserves every name, description, tier, and determinism value (26 StringLiteral survivors closed)", () => {
		expect(GENERIC_AGENT_LAZINESS_META).toEqual(EXPECTED_GENERIC_AGENT_LAZINESS_META);
	});

	// test-contract: invariant — every entry in GENERIC_AGENT_LAZINESS_META keeps a non-empty name/description and a determinism value from the documented set, independent of the exact wording above.
	it("no entry ships blank required text", () => {
		for (const [id, meta] of Object.entries(GENERIC_AGENT_LAZINESS_META)) {
			expect(meta.name, id).not.toBe("");
			expect(meta.description, id).not.toBe("");
			expect(["fully_deterministic", "partially_deterministic", "heuristic"], id).toContain(meta.determinism);
		}
	});
});
