// Mutation-kill companion for src/harness/check-metadata/generic-api-shape.ts.
//
// GENERATED by the string-class kill generator — every one of the 22 surviving
// mutants recorded against this file at generation time was a Stryker StringLiteral
// mutation (originalLexeme -> "") on a value inside one of the exported metadata tables
// below. A prior companion test suite (if any) asserted only the SHAPE of these tables
// (non-empty string, valid tier/determinism) — shape checks accept an empty string, so
// they cannot see a StringLiteral mutant. This file closes that gap by asserting the
// COMPLETE table via toEqual (not per-string toContain fragments): any single value
// emptied anywhere in the table produces a visible mismatch, in one block per table.
//
// regenerate: npx tsx scratch/fleet-r3/golden-gen/generate.mts --file src/harness/check-metadata/generic-api-shape.ts
// (safe to re-run any time the table's real content legitimately changes — see the
// generator's own header for what it does and does not handle.)

import { describe, expect, it } from "vitest";
import { GENERIC_API_SHAPE_META } from "./generic-api-shape.js";
import type { CheckMeta } from "./types.js";

describe("GENERIC_API_SHAPE_META content (mutation-kill)", () => {
	const EXPECTED_GENERIC_API_SHAPE_META: Record<string, CheckMeta> = {
		complexity: {
			name: "Function Complexity",
			description: "Flags functions with high branch count, deep nesting, or many parameters",
			tier: 2,
			determinism: "heuristic",
		},
		cognitive_complexity: {
			name: "Cognitive Complexity",
			description: "Per-function cognitive complexity (SonarSource model: nesting penalized, flat switch nearly free, boolean-run transitions +1) over the Sonar-default cap of 15; AST-computed, advisory-gated",
			tier: 2,
			determinism: "heuristic",
		},
		boolean_trap: {
			name: "Boolean Trap",
			description: "Detects call sites with 2+ boolean literal arguments — intent is opaque to a reader without jumping to the definition",
			tier: 2,
			determinism: "heuristic",
		},
		positional_optional_boolean: {
			name: "Positional Optional Boolean",
			description: "Signature-side twin of boolean_trap — flags function declarations with a positional optional boolean (`flag?: boolean`, `flag: boolean = false`, `flag = false`). Every call site is unreadable; move the bool into an options object or a string-literal union.",
			tier: 2,
			determinism: "heuristic",
		},
		many_optional_params: {
			name: "Many Optional Params",
			description: "Detects signatures with 3+ optional parameters (`?:` markers + `=` defaults). Each optional doubles call-shape surface and a default change is a silent semantic API break. Move them into an options object.",
			tier: 2,
			determinism: "heuristic",
		},
		same_typed_primitive_params: {
			name: "Same-Typed Primitive Params",
			description: "Detects exported / public-method signatures with two consecutive primitive parameters of the same surface type (string, number, boolean) — orderable-by-mistake at the call site",
			tier: 2,
			determinism: "heuristic",
		},
		comment_claims_limit_no_guard: {
			name: "Comment Claims Limit With No Guard",
			description: "Detects functions whose comment says `max N` / `at most N` / `limited to N` but whose body has no `< N` / `<= N` guard.",
			tier: 2,
			determinism: "partially_deterministic",
		},
		comment_claims_null_throws_instead: {
			name: "Comment Claims Null But Body Throws",
			description: "Detects functions whose comment says `returns null on failure` / `may return undefined` but whose body contains an unhandled `throw`.",
			tier: 2,
			determinism: "partially_deterministic",
		},
		comment_claims_validation_missing: {
			name: "Comment Claims Validation But No Check",
			description: "Detects functions whose comment says `validates X` / `sanitizes Y` / `escapes Z` but whose body has no conditional/regex/encode call.",
			tier: 2,
			determinism: "partially_deterministic",
		},
		comment_claims_idempotent_mutates: {
			name: "Comment Claims Idempotent But Mutates",
			description: "Detects functions whose comment says `idempotent` but whose body contains an unconditional mutation with no guard.",
			tier: 2,
			determinism: "partially_deterministic",
		},
		comment_claims_throws_doesnt: {
			name: "Declared @throws Never Thrown",
			description: "Detects JSDoc `@throws {ErrorX}` declarations where the body never throws that error class.",
			tier: 2,
			determinism: "partially_deterministic",
		},
	};

	// test-contract: public-api — GENERIC_API_SHAPE_META is the agent-facing check-documentation surface (interlinked verify --json, doc generation); every name, description, tier, and determinism value it carries must survive intact.
	it("preserves every name, description, tier, and determinism value (22 StringLiteral survivors closed)", () => {
		expect(GENERIC_API_SHAPE_META).toEqual(EXPECTED_GENERIC_API_SHAPE_META);
	});

	// test-contract: invariant — every entry in GENERIC_API_SHAPE_META keeps a non-empty name/description and a determinism value from the documented set, independent of the exact wording above.
	it("no entry ships blank required text", () => {
		for (const [id, meta] of Object.entries(GENERIC_API_SHAPE_META)) {
			expect(meta.name, id).not.toBe("");
			expect(meta.description, id).not.toBe("");
			expect(["fully_deterministic", "partially_deterministic", "heuristic"], id).toContain(meta.determinism);
		}
	});
});
