// Mutation-kill companion for src/harness/check-metadata/suggestion.ts.
//
// GENERATED by the string-class kill generator — every one of the 58 surviving
// mutants recorded against this file at generation time was a Stryker StringLiteral
// mutation (originalLexeme -> "") on a value inside one of the exported metadata tables
// below. A prior companion test suite (if any) asserted only the SHAPE of these tables
// (non-empty string, valid tier/determinism) — shape checks accept an empty string, so
// they cannot see a StringLiteral mutant. This file closes that gap by asserting the
// COMPLETE table via toEqual (not per-string toContain fragments): any single value
// emptied anywhere in the table produces a visible mismatch, in one block per table.
//
// regenerate: npx tsx scratch/fleet-r3/golden-gen/generate.mts --file src/harness/check-metadata/suggestion.ts
// (safe to re-run any time the table's real content legitimately changes — see the
// generator's own header for what it does and does not handle.)

import { describe, expect, it } from "vitest";
import { SUGGESTION_CHECK_META } from "./suggestion.js";
import type { CheckMeta } from "./types.js";

describe("SUGGESTION_CHECK_META content (mutation-kill)", () => {
	const EXPECTED_SUGGESTION_CHECK_META: Record<string, CheckMeta> = {
		"sql-injection": {
			name: "SQL Injection",
			description: "Detects potential SQL injection via string interpolation",
			tier: 2,
			determinism: "heuristic",
		},
		"perf-query-in-loop": {
			name: "Query in Loop",
			description: "Detects database queries inside loops",
			tier: 2,
			determinism: "heuristic",
		},
		"perf-await-in-loop": {
			name: "Await in Loop",
			description: "Detects sequential await calls inside loops",
			tier: 2,
			determinism: "heuristic",
		},
		"silent-catch": {
			name: "Silent Catch",
			description: "Detects empty catch blocks",
			tier: 2,
			determinism: "heuristic",
		},
		"unreachable-code": {
			name: "Unreachable Code",
			description: "Detects code after return/throw/break statements",
			tier: 2,
			determinism: "heuristic",
		},
		"boolean-trap": {
			name: "Boolean Trap",
			description: "Detects boolean parameters that reduce readability",
			tier: 3,
			determinism: "heuristic",
		},
		"function-arity": {
			name: "Function Arity",
			description: "Detects functions with too many parameters",
			tier: 3,
			determinism: "heuristic",
		},
		"narrative-naming": {
			name: "Narrative Naming",
			description: "Detects non-descriptive variable/function names",
			tier: 3,
			determinism: "heuristic",
		},
		"test-description-quality": {
			name: "Test Description Quality",
			description: "Detects low-quality test descriptions",
			tier: 3,
			determinism: "heuristic",
		},
		"catch-and-ignore": {
			name: "Catch and Ignore",
			description: "Detects catch blocks that swallow errors silently",
			tier: 2,
			determinism: "heuristic",
		},
		"god-file": {
			name: "God File",
			description: "Detects files that are too large or have too many responsibilities",
			tier: 3,
			determinism: "heuristic",
		},
		"magic-numbers": {
			name: "Magic Numbers",
			description: "Detects unexplained numeric literals",
			tier: 3,
			determinism: "heuristic",
		},
		"negated-condition-with-else": {
			name: "Negated Condition with Else",
			description: "Detects if(!x) {...} else {...} that should be inverted",
			tier: 3,
			determinism: "heuristic",
		},
		"nested-ternary": {
			name: "Nested Ternary",
			description: "Detects nested ternary expressions in suggestions",
			tier: 3,
			determinism: "heuristic",
		},
		"flag-arguments": {
			name: "Flag Arguments",
			description: "Detects boolean flag parameters that split function behavior",
			tier: 3,
			determinism: "heuristic",
		},
		"commented-out-code": {
			name: "Commented Out Code",
			description: "Detects commented-out code blocks",
			tier: 3,
			determinism: "heuristic",
		},
		"not-implemented-stub": {
			name: "Not Implemented Stub",
			description: "Detects TODO/FIXME stubs and throw new Error('not implemented')",
			tier: 2,
			determinism: "heuristic",
		},
		"empty-function-body": {
			name: "Empty Function Body",
			description: "Detects functions with empty bodies",
			tier: 2,
			determinism: "heuristic",
		},
		"deprecation-notice": {
			name: "Deprecation Notice",
			description: "Detects @deprecated JSDoc tags",
			tier: 2,
			determinism: "heuristic",
		},
		"orphaned-test-stub": {
			name: "Orphaned Test Stub",
			description: "Detects test stubs without assertions",
			tier: 2,
			determinism: "heuristic",
		},
		"deletion-comment": {
			name: "Deletion Comment",
			description: "Detects comments marking code for removal",
			tier: 2,
			determinism: "heuristic",
		},
		"mixed-error-strategy": {
			name: "Mixed Error Strategy",
			description: "Detects mixed error handling patterns in one file",
			tier: 3,
			determinism: "heuristic",
		},
		"bare-catch-block": {
			name: "Bare Catch Block",
			description: "Detects catch blocks with no error handling",
			tier: 2,
			determinism: "heuristic",
		},
		"catch-return-null": {
			name: "Catch Return Null",
			description: "Detects catch blocks that return null/undefined",
			tier: 2,
			determinism: "heuristic",
		},
		"throw-as-control-flow": {
			name: "Throw as Control Flow",
			description: "Detects throwing exceptions for control flow",
			tier: 3,
			determinism: "heuristic",
		},
		"untyped-catch": {
			name: "Untyped Catch",
			description: "Detects catch blocks with untyped error parameter",
			tier: 3,
			determinism: "heuristic",
		},
		"error-string-comparison": {
			name: "Error String Comparison",
			description: "Detects comparing error messages via string matching",
			tier: 3,
			determinism: "heuristic",
		},
		"inconsistent-error-strategy": {
			name: "Inconsistent Error Strategy",
			description: "Detects mixed throw/return-error patterns in one module",
			tier: 3,
			determinism: "heuristic",
		},
		"shotgun-surgery": {
			name: "Shotgun Surgery",
			description: "Detects sessions editing too many files",
			tier: 3,
			determinism: "heuristic",
		},
	};

	// test-contract: public-api — SUGGESTION_CHECK_META is the agent-facing check-documentation surface (interlinked verify --json, doc generation); every name, description, tier, and determinism value it carries must survive intact.
	it("preserves every name, description, tier, and determinism value (58 StringLiteral survivors closed)", () => {
		expect(SUGGESTION_CHECK_META).toEqual(EXPECTED_SUGGESTION_CHECK_META);
	});

	// test-contract: invariant — every entry in SUGGESTION_CHECK_META keeps a non-empty name/description and a determinism value from the documented set, independent of the exact wording above.
	it("no entry ships blank required text", () => {
		for (const [id, meta] of Object.entries(SUGGESTION_CHECK_META)) {
			expect(meta.name, id).not.toBe("");
			expect(meta.description, id).not.toBe("");
			expect(["fully_deterministic", "partially_deterministic", "heuristic"], id).toContain(meta.determinism);
		}
	});
});
