// ===========================================
// Built-in Rules — Databases, Containers, IaC, Cloud, Wrangler, Vercel
// ===========================================
// Covers DROP/TRUNCATE/DELETE, MongoDB, Redis, Docker, compose, kubectl,
// helm, terraform, pulumi, AWS, GCP, Azure, Cloudflare Wrangler, Vercel,
// and rsync --delete.

import type { GuardRule } from "../types.js";

/**
 * Public API — consumed by `rules/builtin-rules.ts` to assemble the full
 * BUILTIN_RULES array exported by `rules-loader.ts`.
 */
export const DATABASE_AND_CLOUD_RULES: GuardRule[] = [
	// --- Database destruction ---
	{
		id: "builtin-drop-database",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [
			{ field: "command", regex: "\\bDROP\\s+(DATABASE|TABLE|SCHEMA)\\b", flags: "i" },
		],
		reason: "Database/table/schema destruction is irreversible",
		suggestion: "Verify target and create a backup first",
		severity: "critical",
		category: "database",
	},
	{
		id: "builtin-truncate-table",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [{ field: "command", regex: "\\bTRUNCATE\\s+TABLE\\b", flags: "i" }],
		reason: "TRUNCATE TABLE deletes all data irrecoverably",
		suggestion: "Verify table name and use transaction",
		severity: "critical",
		category: "database",
	},
	{
		id: "builtin-delete-no-where",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [{ field: "command", regex: "\\bDELETE\\s+FROM\\s+\\w+\\s*;", flags: "i" }],
		reason: "DELETE without WHERE clause removes all rows",
		suggestion: "Add a WHERE clause to target specific rows",
		severity: "high",
		category: "database",
	},
	{
		id: "builtin-mongodb-drop",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [
			{ field: "command", regex: "\\b(dropDatabase|dropCollection)\\s*\\(", flags: "i" },
		],
		reason: "MongoDB drop operations are irreversible",
		suggestion: "Ask the user before dropping MongoDB collections",
		severity: "critical",
		category: "database",
	},
	{
		id: "builtin-redis-flush",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [
			{ field: "command", regex: "\\bredis-cli\\s.*(FLUSHALL|FLUSHDB)\\b", flags: "i" },
		],
		reason: "Redis FLUSHALL/FLUSHDB clears all data",
		suggestion: "Ask the user before flushing Redis",
		severity: "critical",
		category: "database",
	},

	// --- Container/orchestration destruction ---
	{
		id: "builtin-docker-prune",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [
			{
				field: "command",
				regex: "\\bdocker\\s+(system|volume|image)\\s+prune\\b",
				flags: "i",
			},
		],
		reason: "docker prune removes potentially important data",
		suggestion: "Ask the user before pruning Docker resources",
		severity: "high",
		category: "containers",
	},
	{
		id: "builtin-compose-down-v",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [
			{ field: "command", regex: "\\bdocker[- ]compose\\s+down\\s+-v\\b", flags: "i" },
		],
		reason: "docker-compose down -v removes volumes (data loss)",
		suggestion: "Use 'down' without -v to preserve data volumes",
		severity: "high",
		category: "containers",
	},
	{
		id: "builtin-kubectl-mass-delete",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [
			{
				field: "command",
				regex: "\\bkubectl\\s+delete\\s+(namespace|ns|all)\\s",
				flags: "i",
			},
		],
		reason: "kubectl mass deletion is not allowed",
		suggestion: "Delete specific resources instead",
		severity: "critical",
		category: "containers",
	},
	{
		id: "builtin-kubectl-drain",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [{ field: "command", regex: "\\bkubectl\\s+drain\\s", flags: "i" }],
		reason: "kubectl drain evicts all pods from a node",
		suggestion: "Ask the user before draining nodes",
		severity: "high",
		category: "containers",
	},
	{
		id: "builtin-helm-uninstall",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [{ field: "command", regex: "\\bhelm\\s+(uninstall|delete)\\s", flags: "i" }],
		reason: "helm uninstall/delete removes Kubernetes releases and their resources",
		suggestion: "Ask the user to run this manually",
		severity: "high",
		category: "containers",
	},
	{
		id: "builtin-docker-rm-force",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [{ field: "command", regex: "\\bdocker\\s+rm\\s+(-f|--force)\\s", flags: "i" }],
		reason: "docker rm -f kills running containers without graceful shutdown",
		suggestion: "Use docker stop first, then docker rm",
		severity: "high",
		category: "containers",
	},
	{
		id: "builtin-docker-volume-rm",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [
			{ field: "command", regex: "\\bdocker\\s+volume\\s+(rm|remove)\\s", flags: "i" },
		],
		reason: "docker volume rm destroys persistent data in named volumes",
		suggestion: "Ask the user before removing Docker volumes",
		severity: "high",
		category: "containers",
	},
	// Note: `builtin-kubectl-delete-all` was moved to
	// `builtin-rules-extras.ts` per Plan 02 §2.2 — the new entry uses a
	// negative-lookahead regex that intentionally permits
	// `kubectl delete pods --all` for scratch namespaces while still
	// blocking `kubectl delete deployments --all`,
	// `kubectl delete pvcs --all`, etc. The old broader-but-uncalibrated
	// rule was removed because the BUILTIN_RULES uniqueness invariant
	// (asserted in `__tests__/docs-freshness.test.ts`) forbids two rules
	// with the same id.

	// --- Infrastructure-as-Code ---
	{
		id: "builtin-terraform-destroy",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [{ field: "command", regex: "\\bterraform\\s+destroy\\b", flags: "i" }],
		reason: "terraform destroy removes infrastructure",
		suggestion: "Ask the user to run this manually",
		severity: "critical",
		category: "infrastructure",
	},
	{
		id: "builtin-terraform-auto-approve",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [
			{ field: "command", regex: "\\bterraform\\s+apply\\s+.*-auto-approve\\b", flags: "i" },
		],
		reason: "terraform apply -auto-approve skips human review",
		suggestion: "Remove -auto-approve to allow review",
		severity: "high",
		category: "infrastructure",
	},
	{
		id: "builtin-pulumi-destroy",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [{ field: "command", regex: "\\bpulumi\\s+destroy\\b", flags: "i" }],
		reason: "pulumi destroy removes infrastructure",
		suggestion: "Ask the user to run this manually",
		severity: "critical",
		category: "infrastructure",
	},

	// --- Cloud provider destruction ---
	{
		id: "builtin-aws-destructive",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [
			{
				field: "command",
				regex: "\\baws\\s.*(terminate-instances|delete-db-instance|delete-stack|delete-bucket)\\b",
				flags: "i",
			},
		],
		reason: "AWS destructive operations are not allowed from agent sessions",
		suggestion: "Ask the user to run this manually",
		severity: "critical",
		category: "cloud-providers",
	},
	{
		id: "builtin-aws-s3-recursive",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [
			{ field: "command", regex: "\\baws\\s+s3\\s+(rm|mv)\\s+.*--recursive\\b", flags: "i" },
		],
		reason: "Recursive S3 operations can destroy large amounts of data",
		suggestion: "Ask the user before running recursive S3 operations",
		severity: "high",
		category: "cloud-providers",
	},
	{
		id: "builtin-rsync-delete",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [{ field: "command", regex: "\\brsync\\s+.*--delete\\b", flags: "i" }],
		reason: "rsync --delete can wipe files at the destination",
		suggestion: "Use rsync without --delete, or ask the user",
		severity: "high",
		category: "cloud-providers",
	},
	{
		id: "builtin-gcloud-destructive",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [
			{ field: "command", regex: "\\bgcloud\\s+.*(\\bdelete\\b|\\bdestroy\\b)", flags: "i" },
		],
		reason: "GCP destructive operations are not allowed from agent sessions",
		suggestion: "Ask the user to run this manually",
		severity: "critical",
		category: "cloud-providers",
	},
	{
		id: "builtin-az-destructive",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [{ field: "command", regex: "\\baz\\s+.*\\bdelete\\b", flags: "i" }],
		reason: "Azure destructive operations are not allowed from agent sessions",
		suggestion: "Ask the user to run this manually",
		severity: "critical",
		category: "cloud-providers",
	},

	// --- Cloudflare Wrangler ---
	{
		id: "builtin-wrangler-state-delete",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [
			{
				field: "command",
				regex: "\\bwrangler\\s+(d1|kv|r2)\\s+(delete|execute\\s+.*DROP)\\b",
				flags: "i",
			},
		],
		reason: "Wrangler state deletion (D1/KV/R2) is irreversible",
		suggestion: "Ask the user to run this manually",
		severity: "critical",
		category: "wrangler",
	},
	{
		id: "builtin-wrangler-delete-worker",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [
			{ field: "command", regex: "\\bwrangler\\s+delete\\b", flags: "i" },
			{ field: "command", regex: "\\bwrangler\\s+pages\\s+project\\s+delete\\b", flags: "i" },
			{ field: "command", regex: "\\bwrangler\\s+pages\\s+deployment\\s+delete\\b", flags: "i" },
			{ field: "command", regex: "\\bwrangler\\s+queues\\s+delete\\b", flags: "i" },
			{ field: "command", regex: "\\bwrangler\\s+vectorize\\s+delete\\b", flags: "i" },
			{ field: "command", regex: "\\bwrangler\\s+workflows\\s+delete\\b", flags: "i" },
			{ field: "command", regex: "\\bwrangler\\s+hyperdrive\\s+delete\\b", flags: "i" },
			{ field: "command", regex: "\\bwrangler\\s+mtls-certificate\\s+delete\\b", flags: "i" },
			{ field: "command", regex: "\\bwrangler\\s+dispatch-namespace\\s+delete\\b", flags: "i" },
		],
		reason: "Deleting a Worker, Pages project/deployment, Queue, Vectorize, Workflow, Hyperdrive, mTLS certificate, or Dispatch namespace is irreversible",
		suggestion: "Ask the user to confirm and run this manually",
		severity: "critical",
		category: "wrangler",
	},
	{
		id: "builtin-wrangler-secret-delete",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "warn",
		patterns: [{ field: "command", regex: "\\bwrangler\\s+secret\\s+delete\\b", flags: "i" }],
		reason: "Deleting a secret may break a running Worker",
		suggestion: "Verify the secret is no longer referenced before deleting",
		severity: "high",
		category: "wrangler",
	},
	{
		id: "builtin-wrangler-kv-bulk-delete",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [
			{ field: "command", regex: "\\bwrangler\\s+kv\\s*:?\\s*bulk\\s+delete\\b", flags: "i" },
			{
				field: "command",
				regex: "\\bwrangler\\s+kv\\s*:?\\s*namespace\\s+delete\\b",
				flags: "i",
			},
		],
		reason: "Bulk KV deletion or namespace removal is irreversible",
		suggestion: "Ask the user to run this manually",
		severity: "critical",
		category: "wrangler",
	},
	{
		id: "builtin-wrangler-d1-dangerous-sql",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [
			{
				field: "command",
				regex: "\\bwrangler\\s+d1\\s+execute\\b.*--command\\s*=?\\s*[\"']?(DROP|TRUNCATE|DELETE\\s+FROM(?!.*WHERE))\\b",
				flags: "i",
			},
		],
		reason: "Destructive SQL via wrangler d1 execute is irreversible in production",
		suggestion: "Test on a local D1 database first, and ask the user to run against production",
		severity: "critical",
		category: "wrangler",
	},

	{
		id: "builtin-wrangler-prod-deploy-warn",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "warn",
		patterns: [
			{
				field: "command",
				regex: "\\bwrangler\\s+(deploy|publish)\\b.*--env(?:\\s+|=)(production|prod|live)\\b",
				flags: "i",
			},
		],
		reason: "Deploying to a production environment via wrangler has wide blast radius",
		suggestion: "Confirm tests passed and the change is intended for production before proceeding",
		severity: "high",
		category: "wrangler",
	},

	// --- Cloudflare cf CLI destructive commands ---
	{
		id: "builtin-cf-destructive-state",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [
			{ field: "command", regex: "\\bcf\\s+zones\\s+delete\\b", flags: "i" },
			{
				field: "command",
				regex: "\\bcf\\s+registrar\\s+(domain|domains)\\s+delete\\b",
				flags: "i",
			},
			{ field: "command", regex: "\\bcf\\s+accounts\\s+members\\s+delete\\b", flags: "i" },
		],
		reason: "Deleting a zone, registrar domain, or account member via cf is irreversible and account-wide",
		suggestion: "Ask the user to confirm and run this manually via the Cloudflare dashboard",
		severity: "critical",
		category: "cloudflare",
	},
	{
		id: "builtin-cf-dns-record-delete",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "warn",
		patterns: [
			{ field: "command", regex: "\\bcf\\s+dns\\s+records?\\s+delete\\b", flags: "i" },
		],
		reason: "DNS record deletion has wide blast radius and is reversible only via manual recreation",
		suggestion: "Confirm the record is intentional to delete; for transient testing prefer disabling",
		severity: "high",
		category: "cloudflare",
	},

	// --- Vercel CLI destructive commands ---
	{
		id: "builtin-vercel-remove",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "block",
		patterns: [
			{ field: "command", regex: "\\bvercel\\s+(rm|remove)\\b" },
			{ field: "command", regex: "\\bvercel\\s+project\\s+rm\\b" },
			{ field: "command", regex: "\\bvercel\\s+domains?\\s+rm\\b" },
			{ field: "command", regex: "\\bvercel\\s+dns\\s+rm\\b" },
			{ field: "command", regex: "\\bvercel\\s+certs?\\s+rm\\b" },
		],
		reason: "Removing Vercel deployments, projects, domains, or certs is irreversible",
		suggestion: "Ask the user to confirm and run this manually",
		severity: "critical",
		category: "vercel",
	},
	{
		id: "builtin-vercel-env-rm",
		enabled: true,
		trigger: "PreToolUse",
		tool_match: ["Bash", "Shell", "run_command"],
		action: "warn",
		patterns: [{ field: "command", regex: "\\bvercel\\s+env\\s+rm\\b" }],
		reason: "Removing Vercel environment variables may break a running deployment",
		suggestion: "Verify the env var is no longer referenced before deleting",
		severity: "high",
		category: "vercel",
	},
];
