// ===========================================
// Rules — Compiled-from-Markdown Rules
// ===========================================
// Loads rules produced by the `enforce` skill (see skills/enforce/SKILL.md).
//
// Two-file model:
//   .interlinked/compiled-rules.json           — pristine output (regenerated by the skill)
//   .interlinked/compiled-rules.overrides.json — user mods (survive recompiles)
//
// The loader reads both, applies overrides, and returns enabled GuardRule[]
// to the main `loadRules()` aggregator. Pristine + overrides separation lets
// users `/enforce remove --source <group_id>` without ever touching the
// compiler-owned file.

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { GuardRule } from "../types.js";

/**
 * Compiled rule sidecar — the `enforce` skill emits these fields on every
 * rule for provenance and lifecycle ops. The harness ignores `source` /
 * `compiled_action_reason` / `confidence` / `user_modified` at evaluation;
 * the CLI uses them.
 */
interface CompiledRuleSource {
	group_id: string;
	group_label?: string;
	file?: string;
	lines?: [number, number];
	quote?: string;
	url?: string;
	fetched_sha?: string;
	lexical_marker?: string;
	marker_class?: string;
}

interface CompiledRule extends GuardRule {
	source?: CompiledRuleSource;
	compiled_action_reason?: string;
	confidence?: number;
	user_modified?: boolean;
}

interface CompiledRulesFile {
	version?: number;
	rules?: CompiledRule[];
}

interface RuleModification {
	action?: GuardRule["action"];
	severity?: GuardRule["severity"];
	enabled?: boolean;
	note?: string;
}

interface CompiledRulesOverrides {
	version?: number;
	removed_groups?: string[];
	removed_rule_ids?: string[];
	disabled_rule_ids?: string[];
	modifications?: Record<string, RuleModification>;
}

function compiledRulesPath(cwd: string): string {
	return join(cwd, ".interlinked", "compiled-rules.json");
}

function compiledRulesOverridesPath(cwd: string): string {
	return join(cwd, ".interlinked", "compiled-rules.overrides.json");
}

function readCompiledRulesFile(cwd: string): CompiledRulesFile | null {
	const path = compiledRulesPath(cwd);
	if (!existsSync(path)) return null;
	try {
		const parsed = JSON.parse(readFileSync(path, "utf-8")) as unknown;
		if (parsed && typeof parsed === "object") return parsed as CompiledRulesFile;
		return null;
	} catch {
		// Malformed JSON — fall back to no compiled rules. The skill's self-checks
		// should have caught this; treating it as "no compiled rules" is safer
		// than throwing, because guard-rule loading must never block on a parse
		// error (matches `feedback_safety_continuity.md` — fail-open on safety).
		return null;
	}
}

function readCompiledRulesOverrides(cwd: string): CompiledRulesOverrides {
	const path = compiledRulesOverridesPath(cwd);
	if (!existsSync(path)) return {};
	try {
		const parsed = JSON.parse(readFileSync(path, "utf-8")) as unknown;
		if (parsed && typeof parsed === "object") return parsed as CompiledRulesOverrides;
		return {};
	} catch {
		return {};
	}
}

/**
 * Public API — consumed by `rules-loader.ts` via `loadRules()`.
 *
 * Reads `.interlinked/compiled-rules.json` and applies overrides from
 * `.interlinked/compiled-rules.overrides.json`. Returns the rules that
 * should be merged into the harness's active ruleset.
 *
 * Filtering logic (in order):
 *   1. Drop rules whose `source.group_id` appears in `removed_groups[]`.
 *   2. Drop rules whose `id` appears in `removed_rule_ids[]`.
 *   3. Apply per-rule `modifications{}` (action / severity / enabled).
 *   4. Set `enabled: false` on rules whose `id` appears in `disabled_rule_ids[]`.
 *   5. Caller filters out `enabled === false` per the existing convention in
 *      `loadRules()`.
 */
export function loadCompiledRules(cwd: string): GuardRule[] {
	const file = readCompiledRulesFile(cwd);
	if (!file?.rules || !Array.isArray(file.rules)) return [];

	const overrides = readCompiledRulesOverrides(cwd);
	const removedGroups = new Set(overrides.removed_groups ?? []);
	const removedIds = new Set(overrides.removed_rule_ids ?? []);
	const disabledIds = new Set(overrides.disabled_rule_ids ?? []);
	const mods = overrides.modifications ?? {};

	const out: GuardRule[] = [];
	for (const raw of file.rules) {
		if (!raw || typeof raw !== "object") continue;
		if (!raw.id) continue;

		// Filter by group + rule-id removal lists. Removed rules don't reach
		// the evaluator at all — they're not just disabled, they're absent.
		const groupId = raw.source?.group_id;
		if (groupId && removedGroups.has(groupId)) continue;
		if (removedIds.has(raw.id)) continue;

		// Clone so we don't mutate the source object.
		const rule: CompiledRule = { ...raw };

		// Apply per-rule modifications. Only action/severity/enabled are
		// honored; structural fields (patterns, tool_match, trigger) are
		// owned by the compiler and must not be hand-edited via overrides.
		const mod = mods[raw.id];
		if (mod) {
			if (mod.action !== undefined) rule.action = mod.action;
			if (mod.severity !== undefined) rule.severity = mod.severity;
			if (mod.enabled !== undefined) rule.enabled = mod.enabled;
			rule.user_modified = true;
		}

		// Disabled list overrides any modifications.enabled.
		if (disabledIds.has(raw.id)) {
			rule.enabled = false;
		} else if (rule.enabled === undefined) {
			rule.enabled = true;
		}

		out.push(rule);
	}
	return out;
}

/**
 * Public API — file paths watched by `watchRulesFiles()` so changes hot-reload.
 */
export function getCompiledRulesWatchPaths(cwd: string): string[] {
	return [compiledRulesPath(cwd), compiledRulesOverridesPath(cwd)];
}
