// ===========================================
// Rules — Distilled-from-Markdown Rules
// ===========================================
// Loads rules produced by the `enforce` skill (see skills/enforce/SKILL.md).
//
// Two-file model:
//   .interlinked/distilled-rules.json           — pristine output (regenerated by the skill)
//   .interlinked/distilled-rules.overrides.json — user mods (survive recompiles)
//
// The loader reads both, applies overrides, and returns enabled GuardRule[]
// to the main `loadRules()` aggregator. Pristine + overrides separation lets
// users `/enforce remove --source <group_id>` without ever touching the
// distiller-owned file.
//
// Naming history: this layer was originally called "compiled-rules" because
// the early framing treated `/enforce` as a markdown-to-rule compiler. In
// practice §4 paragraph classification is LLM-driven interpretation rather
// than parser-style mechanical translation, so the more honest verb is
// "distill" — extracting structured rules from informal prose with judgment
// and provenance. The legacy filenames (`compiled-rules.json` /
// `compiled-rules.overrides.json` / `compiled-rules.review.json`) are
// auto-migrated to the new names on first load via `migrateLegacyPaths()`
// below; existing users don't lose state.

import { existsSync, readFileSync, renameSync } from "node:fs";
import { join } from "node:path";
import { looksLikeReDoS } from "../redos-validation.js";
import type { GuardRule } from "../types.js";

/**
 * Distilled rule sidecar — the `enforce` skill emits these fields on every
 * rule for provenance and lifecycle ops. The harness ignores `source` /
 * `distilled_action_reason` / `confidence` / `user_modified` at evaluation;
 * the CLI uses them.
 */
interface DistilledRuleSource {
	group_id: string;
	group_label?: string;
	file?: string;
	lines?: [number, number];
	quote?: string;
	url?: string;
	fetched_sha?: string;
	lexical_marker?: string;
	marker_class?: string;
}

interface DistilledRule extends GuardRule {
	source?: DistilledRuleSource;
	distilled_action_reason?: string;
	/** Legacy alias for `distilled_action_reason`. Read for backwards compat
	 *  with rule files written by older /enforce runs; not emitted on new ones. */
	compiled_action_reason?: string;
	confidence?: number;
	user_modified?: boolean;
}

interface DistilledRulesFile {
	version?: number;
	rules?: DistilledRule[];
}

interface RuleModification {
	action?: GuardRule["action"];
	severity?: GuardRule["severity"];
	enabled?: boolean;
	note?: string;
}

interface DistilledRulesOverrides {
	version?: number;
	removed_groups?: string[];
	removed_rule_ids?: string[];
	disabled_rule_ids?: string[];
	modifications?: Record<string, RuleModification>;
}

function distilledRulesPath(cwd: string): string {
	return join(cwd, ".interlinked", "distilled-rules.json");
}

function distilledRulesOverridesPath(cwd: string): string {
	return join(cwd, ".interlinked", "distilled-rules.overrides.json");
}

/**
 * Auto-migrate legacy `compiled-rules.*` files to the new `distilled-rules.*`
 * names on first sight. Idempotent: only renames when the new path doesn't
 * already exist (so a half-migrated state can't clobber the new file). Best
 * effort — failures are swallowed because rule loading must remain fail-open
 * (cf. `feedback_safety_continuity.md`).
 */
function migrateLegacyPaths(cwd: string): void {
	const dir = join(cwd, ".interlinked");
	const pairs: Array<[string, string]> = [
		["compiled-rules.json", "distilled-rules.json"],
		["compiled-rules.overrides.json", "distilled-rules.overrides.json"],
		["compiled-rules.review.json", "distilled-rules.review.json"],
	];
	for (const [oldName, newName] of pairs) {
		const oldPath = join(dir, oldName);
		const newPath = join(dir, newName);
		if (existsSync(oldPath) && !existsSync(newPath)) {
			try {
				renameSync(oldPath, newPath);
			} catch {
				/* intentional: best-effort migration */
			}
		}
	}
}

function readDistilledRulesFile(cwd: string): DistilledRulesFile | null {
	const path = distilledRulesPath(cwd);
	if (!existsSync(path)) return null;
	try {
		const parsed = JSON.parse(readFileSync(path, "utf-8")) as unknown;
		if (parsed && typeof parsed === "object") return parsed as DistilledRulesFile;
		return null;
	} catch {
		// Malformed JSON — fall back to no distilled rules. The skill's self-checks
		// should have caught this; treating it as "no distilled rules" is safer
		// than throwing, because guard-rule loading must never block on a parse
		// error (matches `feedback_safety_continuity.md` — fail-open on safety).
		return null;
	}
}

function readDistilledRulesOverrides(cwd: string): DistilledRulesOverrides {
	const path = distilledRulesOverridesPath(cwd);
	if (!existsSync(path)) return {};
	try {
		const parsed = JSON.parse(readFileSync(path, "utf-8")) as unknown;
		if (parsed && typeof parsed === "object") return parsed as DistilledRulesOverrides;
		return {};
	} catch {
		return {};
	}
}

/** Normalized override lookup structures, derived once per load from the raw overrides file. */
interface OverrideLookups {
	removedGroups: Set<string>;
	removedIds: Set<string>;
	disabledIds: Set<string>;
	mods: Record<string, RuleModification>;
}

/** Turns the raw overrides file into the four lookup structures the per-rule pass consults. */
function buildOverrideLookups(overrides: DistilledRulesOverrides): OverrideLookups {
	return {
		removedGroups: new Set(overrides.removed_groups ?? []),
		removedIds: new Set(overrides.removed_rule_ids ?? []),
		disabledIds: new Set(overrides.disabled_rule_ids ?? []),
		mods: overrides.modifications ?? {},
	};
}

/**
 * Whether `raw` should be dropped entirely (not just disabled) — its
 * `source.group_id` is in the removed-groups list, or its `id` is in the
 * removed-ids list.
 */
function isRuleRemoved(
	raw: DistilledRule,
	removedGroups: Set<string>,
	removedIds: Set<string>,
): boolean {
	const groupId = raw.source?.group_id;
	if (groupId && removedGroups.has(groupId)) return true;
	return removedIds.has(raw.id);
}

/**
 * ReDoS gate. `/enforce`-distilled rules can carry regexes from arbitrary
 * third-party AGENTS.md / CLAUDE.md files; a nested-quantifier or
 * prefix-overlap shape hangs the daemon on adversarial input. Returns true
 * (and logs one stderr line so the operator notices) when any of the rule's
 * patterns fails the shape check — the caller skips the whole rule.
 */
function hasUnsafePattern(raw: DistilledRule): boolean {
	if (!Array.isArray(raw.patterns)) return false;
	const unsafe = raw.patterns.find(
		(p) => p && typeof p.regex === "string" && looksLikeReDoS(p.regex),
	);
	if (!unsafe) return false;
	process.stderr.write(
		`[interlinked] skipping distilled rule ${raw.id}: ReDoS-prone pattern ${
			unsafe.regex?.slice(0, 120) ?? ""
		}\n`,
	);
	return true;
}

/**
 * Applies the override `modifications{}` entry for this rule, if any, onto
 * the (already-cloned) rule in place. Only action/severity/enabled are
 * honored; structural fields (patterns, tool_match, trigger) are owned by
 * the distiller and must not be hand-edited via overrides.
 */
function applyRuleModification(rule: DistilledRule, mod: RuleModification | undefined): void {
	if (!mod) return;
	if (mod.action !== undefined) rule.action = mod.action;
	if (mod.severity !== undefined) rule.severity = mod.severity;
	if (mod.enabled !== undefined) rule.enabled = mod.enabled;
	rule.user_modified = true;
}

/**
 * Settles the final `enabled` flag: the disabled-ids list always wins (forces
 * `false`); otherwise a still-unset `enabled` (no modification touched it)
 * defaults to `true`.
 */
function resolveEnabledState(rule: DistilledRule, ruleId: string, disabledIds: Set<string>): void {
	if (disabledIds.has(ruleId)) {
		rule.enabled = false;
	} else if (rule.enabled === undefined) {
		rule.enabled = true;
	}
}

/**
 * Public API — consumed by `rules-loader.ts` via `loadRules()`.
 *
 * Reads `.interlinked/distilled-rules.json` and applies overrides from
 * `.interlinked/distilled-rules.overrides.json`. Returns the rules that
 * should be merged into the harness's active ruleset.
 *
 * Filtering logic (in order):
 *   1. Drop rules whose `source.group_id` appears in `removed_groups[]`.
 *   2. Drop rules whose `id` appears in `removed_rule_ids[]`.
 *   3. Apply per-rule `modifications{}` (action / severity / enabled).
 *   4. Set `enabled: false` on rules whose `id` appears in `disabled_rule_ids[]`.
 *   5. Caller filters out `enabled === false` per the existing convention in
 *      `loadRules()`.
 */
export function loadDistilledRules(cwd: string): GuardRule[] {
	migrateLegacyPaths(cwd);

	const file = readDistilledRulesFile(cwd);
	if (!file?.rules || !Array.isArray(file.rules)) return [];

	const overrides = readDistilledRulesOverrides(cwd);
	const { removedGroups, removedIds, disabledIds, mods } = buildOverrideLookups(overrides);

	const out: GuardRule[] = [];
	for (const raw of file.rules) {
		if (!raw || typeof raw !== "object") continue;
		if (!raw.id) continue;

		// Filter by group + rule-id removal lists. Removed rules don't reach
		// the evaluator at all — they're not just disabled, they're absent.
		if (isRuleRemoved(raw, removedGroups, removedIds)) continue;

		if (hasUnsafePattern(raw)) continue;

		// Clone so we don't mutate the source object.
		const rule: DistilledRule = { ...raw };

		applyRuleModification(rule, mods[raw.id]);

		// Disabled list overrides any modifications.enabled.
		resolveEnabledState(rule, raw.id, disabledIds);

		out.push(rule);
	}
	return out;
}

/**
 * Public API — file paths watched by `watchRulesFiles()` so changes hot-reload.
 */
export function getDistilledRulesWatchPaths(cwd: string): string[] {
	return [distilledRulesPath(cwd), distilledRulesOverridesPath(cwd)];
}
