import { describe, expect, it } from "vitest";
import {
	checkRustUncheckedCastSlice,
	checkUnalignedReinterpret,
} from "./reinterpret-alignment.js";

// Fixtures are passed as `content` strings to the two detectors below, so
// every assertion is grounded in the SUT call. Paths are synthetic — the
// detectors gate on extension + test/vendored/generated exemptions.

function runRust(content: string, path = "src/decode.rs"): ReturnType<typeof checkRustUncheckedCastSlice> {
	return checkRustUncheckedCastSlice(content, path);
}

function runJs(content: string, path = "src/decode.ts"): ReturnType<typeof checkUnalignedReinterpret> {
	return checkUnalignedReinterpret(content, path);
}

// ─── ubs_rust_unchecked_cast_slice ───────────────────────────────────────────

describe("checkRustUncheckedCastSlice — positives", () => {
	it("flags bare bytemuck::cast_slice on a byte slice", () => {
		const found = runRust(
			["fn decode(buf: &[u8]) -> &[u16] {", "    bytemuck::cast_slice(buf)", "}"].join("\n"),
		);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(2);
		expect(found[0]?.text).toContain("ubs_rust_unchecked_cast_slice:");
		expect(found[0]?.text).toContain(" — ");
	});

	it("flags a widening turbofish cast_slice::<u8, u16>", () => {
		const found = runRust(
			["fn widen(payload: &[u8]) -> &[u16] {", "    bytemuck::cast_slice::<u8, u16>(payload)", "}"].join(
				"\n",
			),
		);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(2);
	});

	it("flags from_raw_parts with a widening *const cast", () => {
		const found = runRust(
			[
				"unsafe fn as_words(ptr: *const u8, n: usize) -> Vec<u32> {",
				"    let s = std::slice::from_raw_parts(ptr as *const u32, n / 4);",
				"    s.to_vec()",
				"}",
			].join("\n"),
		);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(2);
	});

	it("flags transmute from &[u8]", () => {
		const found = runRust(
			[
				"fn words(bytes: &[u8]) -> &[u16] {",
				"    unsafe { std::mem::transmute::<&[u8], &[u16]>(bytes) }",
				"}",
			].join("\n"),
		);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(2);
	});

	it("dedupes two unchecked casts on the same line to one finding", () => {
		const found = runRust(
			"let (a, b) = (bytemuck::cast_slice(left), bytemuck::cast_slice(right));",
		);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(1);
	});

	it("caps findings at 10 per file", () => {
		const content = Array.from(
			{ length: 12 },
			(_, i) => `let v${i}: &[u16] = bytemuck::cast_slice(src${i});`,
		).join("\n");
		expect(runRust(content)).toHaveLength(10);
	});
});

describe("checkRustUncheckedCastSlice — negatives", () => {
	it("does not fire when the length is masked on the same line (& !1)", () => {
		const found = runRust(
			["fn even_view(buf: &[u8]) -> &[u16] {", "    bytemuck::cast_slice(&buf[..buf.len() & !1])", "}"].join(
				"\n",
			),
		);
		expect(found).toEqual([]);
	});

	it("does not fire on chunks_exact iteration (no reinterpret present)", () => {
		const found = runRust(
			[
				"fn sum(buf: &[u8]) -> u32 {",
				"    buf.chunks_exact(4).map(|c| u32::from_le_bytes([c[0], c[1], c[2], c[3]])).sum()",
				"}",
			].join("\n"),
		);
		expect(found).toEqual([]);
	});

	it("does not fire when a % size_of check appears two lines above", () => {
		const found = runRust(
			[
				"fn safe(buf: &[u8]) -> Option<&[u16]> {",
				"    if buf.len() % size_of::<u16>() != 0 {",
				"        return None;",
				"    }",
				"    Some(bytemuck::cast_slice(buf))",
				"}",
			].join("\n"),
		);
		expect(found).toEqual([]);
	});

	it("does not fire on cast_slice::<u8, u8> (target stays 1 byte wide)", () => {
		expect(runRust("let same: &[u8] = bytemuck::cast_slice::<u8, u8>(buf);")).toEqual([]);
	});

	it("does not fire on a comment-only occurrence", () => {
		const found = runRust(
			["// bytemuck::cast_slice(buf) panics when the length is odd", "fn docs_only() {}"].join("\n"),
		);
		expect(found).toEqual([]);
	});

	it("does not fire on a string-literal occurrence", () => {
		const found = runRust(
			["fn msg() -> String {", '    String::from("call cast_slice(buf) only after masking")', "}"].join(
				"\n",
			),
		);
		expect(found).toEqual([]);
	});

	it("does not fire on a non-.rs extension", () => {
		expect(runRust("bytemuck::cast_slice(buf)", "src/decode.ts")).toEqual([]);
	});

	it("does not fire on a test-file path", () => {
		expect(runRust("bytemuck::cast_slice(buf)", "app/tests/decode.rs")).toEqual([]);
	});

	it("does not fire on generator output", () => {
		const found = runRust(
			["// @generated by bindgen — do not edit", "let v: &[u16] = bytemuck::cast_slice(buf);"].join("\n"),
		);
		expect(found).toEqual([]);
	});

	it("does not fire on a vendored path", () => {
		expect(runRust("bytemuck::cast_slice(buf)", "vendor/fastutf/src/decode.rs")).toEqual([]);
	});
});

// ─── unaligned_reinterpret ───────────────────────────────────────────────────

describe("checkUnalignedReinterpret — positives", () => {
	it("flags new Uint16Array over a .buffer with no guard", () => {
		const found = runJs(
			["export function decode(buf: Uint8Array): Uint16Array {", "\treturn new Uint16Array(buf.buffer);", "}"].join(
				"\n",
			),
		);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(2);
		expect(found[0]?.text).toContain("unaligned_reinterpret:");
		expect(found[0]?.text).toContain(" — ");
	});

	it("flags new DataView over a buffer-ish identifier", () => {
		const found = runJs(
			["export function readHeader(bytes: ArrayBuffer): number {", "\tconst view = new DataView(bytes);", "\treturn view.getUint32(0);", "}"].join(
				"\n",
			),
		);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(2);
	});

	it("flags a wide view over a .slice(...) byte run", () => {
		const found = runJs(
			["function samples(payload: Uint8Array): Float32Array {", "\treturn new Float32Array(payload.slice(headerLen));", "}"].join(
				"\n",
			),
		);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(2);
	});

	it("flags a multi-line constructor over readFileSync output", () => {
		const found = runJs(
			["const words = new BigUint64Array(", "\treadFileSync(binPath).buffer,", ");"].join("\n"),
		);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(1);
	});

	it("still fires when the only guard sits more than 40 lines above", () => {
		const filler = Array.from({ length: 45 }, (_, i) => `const pad${i} = ${i};`).join("\n");
		const content = [
			'if (buf.byteLength % 2 !== 0) throw new Error("odd");',
			filler,
			"const view = new Uint16Array(buf.buffer);",
		].join("\n");
		const found = runJs(content);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(47);
	});

	it("caps findings at 10 per file", () => {
		const content = Array.from(
			{ length: 12 },
			(_, i) => `const v${i} = new Uint16Array(buf);`,
		).join("\n");
		expect(runJs(content)).toHaveLength(10);
	});
});

describe("checkUnalignedReinterpret — negatives", () => {
	it("does not fire on a numeric allocation", () => {
		expect(runJs("const table = new Uint16Array(64);")).toEqual([]);
	});

	it("does not fire on an element copy from an array literal", () => {
		expect(runJs("const rgb = new Uint16Array([1, 2, 3]);")).toEqual([]);
	});

	it("does not fire on Uint8Array views (element size 1)", () => {
		expect(runJs("const copy = new Uint8Array(buf.buffer);")).toEqual([]);
	});

	it("does not fire when a byteLength % guard precedes the view", () => {
		const found = runJs(
			[
				"function safeView(buf: Uint8Array): Uint16Array {",
				'\tif (buf.byteLength % 2 !== 0) throw new Error("odd byte count");',
				"\treturn new Uint16Array(buf.buffer);",
				"}",
			].join("\n"),
		);
		expect(found).toEqual([]);
	});

	it("does not fire when the guard sits within the 40-line window", () => {
		const filler = Array.from({ length: 30 }, (_, i) => `const pad${i} = ${i};`).join("\n");
		const content = [
			'if (buf.byteLength % 2 !== 0) throw new Error("odd");',
			filler,
			"const view = new Uint16Array(buf.buffer);",
		].join("\n");
		expect(runJs(content)).toEqual([]);
	});

	it("does not fire when the argument has no byte-buffer signal", () => {
		expect(runJs("const copy = new Float64Array(other);")).toEqual([]);
	});

	it("does not fire when a BYTES_PER_ELEMENT computation precedes the view", () => {
		const found = runJs(
			[
				"function aligned(raw: ArrayBuffer): Uint32Array {",
				"\tconst usable = raw.byteLength - (raw.byteLength % Uint32Array.BYTES_PER_ELEMENT);",
				"\treturn new Uint32Array(raw.slice(0, usable));",
				"}",
			].join("\n"),
		);
		expect(found).toEqual([]);
	});

	it("does not fire on a comment-only occurrence", () => {
		expect(runJs("// new Uint16Array(buf.buffer) would throw on odd byteLength")).toEqual([]);
	});

	it("does not fire on a string-literal occurrence", () => {
		expect(runJs('const example = "new Uint16Array(buf.buffer)";')).toEqual([]);
	});

	it("does not fire on a non-JS/TS extension", () => {
		expect(runJs("const v = new Uint16Array(buf.buffer);", "src/decode.py")).toEqual([]);
	});

	it("does not fire on a test-file path", () => {
		expect(runJs("const v = new Uint16Array(buf.buffer);", "src/decode.test.ts")).toEqual([]);
	});

	it("does not fire when the first argument never closes", () => {
		expect(runJs("const v = new Uint16Array(buf")).toEqual([]);
	});
});

// ─── Regressions: adversarial-review findings (2026-07) ─────────────────────
//
// Each fixture below reproduced a real false positive / false negative against
// the shared line-based stripper (`#` read as a Python comment, Rust lifetimes
// read as string openers) or the bounded first-argument scan. Keep them exact.

describe("checkUnalignedReinterpret — fresh-buffer guard (self-FP audit 2026-07-20)", () => {
	it("does not fire when the view wraps a fresh new SharedArrayBuffer(<literal>)", () => {
		// harness-process-reap.ts:197 — a literal-sized fresh buffer has a
		// compile-time-known byteLength; not the runtime-odd-length bug class.
		const found = runJs(
			[
				"function reap() {",
				"\tconst buf = new SharedArrayBuffer(4);",
				"\tAtomics.wait(new Int32Array(buf), 0, 0, 50);",
				"}",
			].join("\n"),
		);
		expect(found).toEqual([]);
	});

	it("does not fire on an inline new ArrayBuffer(<literal>)", () => {
		expect(runJs("const v = new Uint32Array(new ArrayBuffer(8));")).toEqual([]);
	});

	it("still fires on an unguarded runtime-length .buffer view", () => {
		expect(runJs("function h(bytes: Uint8Array) { return new Uint16Array(bytes.buffer); }")).toHaveLength(1);
	});
});

describe("checkUnalignedReinterpret — adversarial-review regressions (2026-07-10)", () => {
	it("keeps a guard containing a quote-bearing regex literal alive (no false positive)", () => {
		const found = runJs(
			[
				"export function toWords(buf: Uint8Array, hdr: string): Uint16Array | null {",
				'\tif (!/^"/.test(hdr) || buf.byteLength % 2 !== 0) return null;',
				"\treturn new Uint16Array(buf.buffer);",
				"}",
			].join("\n"),
		);
		expect(found).toEqual([]);
	});

	it("still fires on a view sharing a line with a quote-bearing regex literal", () => {
		const found = runJs(
			String.raw`const clean = s.replace(/"/g, ""); const view = new Uint16Array(buf.buffer);`,
		);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(1);
	});

	it("fires when a spaced comparison precedes the buffer-yielding ternary first argument", () => {
		const lt = runJs("const view = new DataView(n < 8 ? small.buffer : big.buffer, 0);");
		expect(lt).toHaveLength(1);
		expect(lt[0]?.line).toBe(1);
		// Mirror-image control: must keep firing too.
		const gt = runJs("const view = new DataView(n > 8 ? small.buffer : big.buffer, 0);");
		expect(gt).toHaveLength(1);
	});

	it(
		"stays linear and silent on a flood of never-closing wide-view constructors",
		() => {
			// This asserted `elapsed < 2500ms` and was flaky by construction: an
			// absolute wall-clock ceiling measures the MACHINE, not the code. Under
			// v8 coverage instrumentation the identical work took 3284ms and 2643ms
			// (measured 2026-07-31) — a red suite caused entirely by the harness
			// watching itself. Third instance of this class in the repo.
			//
			// A 64KB-vs-128KB ratio replaced it, asserting linear ≈2x against a 3x
			// threshold — and that was ALSO flaky, failing the full suite at 3.13 and
			// 4.26 (measured the same day). Separating 2x from 4x demands timing
			// PRECISION, and at ~25ms per sample JIT warm-up and scheduler noise
			// exceed the gap. The lesson is not "ratios are bad" but "do not ask a
			// noisy instrument for a fine distinction".
			//
			// So ask it for a COARSE one. The regression being guarded is enormous —
			// scan-to-EOF per match, ~7.8s vs ~0.1s at 200KB, about 78x. Measure a
			// small CONTROL and a 32x-larger SUBJECT in the same process: a linear
			// scan lands near 32x the control, a quadratic one near 1024x. Asserting
			// below 150x leaves ~4.7x headroom over linear while still catching a
			// quadratic blow-up ~7x below where it would land. Machine speed and
			// coverage instrumentation scale BOTH terms, so they cancel.
			const flood = (bytes: number) =>
				"new DataView(buf ".repeat(Math.ceil(bytes / 17) + 1).slice(0, bytes);
			// min-of-N: the minimum is the cleanest timing estimator, since noise can
			// only ever make a sample slower. The control gets more reps because it is
			// the denominator, where an over-estimate would mask a real regression.
			const timeOf = (bytes: number, reps: number): number => {
				const src = flood(bytes);
				let best = Number.POSITIVE_INFINITY;
				for (let i = 0; i < reps; i++) {
					const t0 = performance.now();
					expect(runJs(src, "src/a.ts")).toEqual([]);
					best = Math.min(best, performance.now() - t0);
				}
				return best;
			};

			const CONTROL_BYTES = 16 * 1024;
			const SUBJECT_BYTES = 32 * CONTROL_BYTES; // 512KB
			const control = timeOf(CONTROL_BYTES, 5);
			const subject = timeOf(SUBJECT_BYTES, 3);
			// Floor the denominator: a sub-millisecond control is unresolvable by
			// performance.now(), and a very fast machine must never fail this test.
			const ratio = subject / Math.max(control, 0.5);
			expect(ratio).toBeLessThan(150);
		},
		60_000,
	);
});

describe("checkUnalignedReinterpret — stripping/extraction regressions", () => {
	it("does not fire when the alignment guard reads a private class field", () => {
		const found = runJs(
			[
				"class D {",
				"\t#buffer;",
				"\tdecode(bytes) {",
				'\t\tif (this.#buffer.byteLength % 2 !== 0) throw new Error("odd");',
				"\t\tconst view = new Uint16Array(bytes);",
				"\t\treturn view;",
				"\t}",
				"}",
			].join("\n"),
		);
		expect(found).toEqual([]);
	});

	it("does not fire when the guard one line above touches a #private field (typed class)", () => {
		const found = runJs(
			[
				"class Decoder {",
				"\t#raw: Uint8Array;",
				"\tview(buf: Uint8Array): Uint16Array {",
				"\t\tif (this.#raw.byteLength % 2 !== 0) throw new Error();",
				"\t\treturn new Uint16Array(buf.buffer);",
				"\t}",
				"}",
			].join("\n"),
			"src/example.ts",
		);
		expect(found).toEqual([]);
	});

	it("fires on a wide view over a private-field byte buffer (this.#buf.buffer)", () => {
		const found = runJs(
			["class R {", "\t#buf;", "\tread() {", "\t\treturn new Uint16Array(this.#buf.buffer);", "\t}", "}"].join(
				"\n",
			),
		);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(4);
	});

	it("fires on new Uint16Array(this.#bytes.buffer) with no guard (typed class)", () => {
		const found = runJs(
			[
				"class Decoder {",
				"\t#bytes: Uint8Array;",
				"\tdecode(): Uint16Array {",
				"\t\treturn new Uint16Array(this.#bytes.buffer);",
				"\t}",
				"}",
			].join("\n"),
			"src/example.ts",
		);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(4);
	});

	it("fires when comment padding pushes the closing paren beyond 300 chars", () => {
		const found = runJs(`const view = new Uint16Array(buf.buffer /* ${"x".repeat(310)} */);`);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(1);
	});

	it("fires on a genuinely long first argument (350-char .slice expression)", () => {
		const found = runJs(`const f = new Float64Array(raw.slice(${"h".repeat(340)}, end));`);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(1);
	});

	it("fires when the first argument carries a two-parameter type-argument list", () => {
		const two = runJs(
			"return new DataView(toArrayBuffer<Header, Payload>(msg).buffer);",
			"src/example.ts",
		);
		expect(two).toHaveLength(1);
		expect(two[0]?.line).toBe(1);
		// One-type-param control (no comma) — must keep firing too.
		const one = runJs("return new DataView(toArrayBuffer<Header>(msg).buffer);", "src/example.ts");
		expect(one).toHaveLength(1);
	});
});

describe("checkRustUncheckedCastSlice — adversarial-review regressions (2026-07-10)", () => {
	it("fires when the pointer comes from a method call (.as_ptr()) inside from_raw_parts", () => {
		const found = runRust(
			[
				"fn words(bytes: &[u8]) -> &[u16] {",
				"    unsafe { std::slice::from_raw_parts(bytes.as_ptr() as *const u16, bytes.len() / 2) }",
				"}",
			].join("\n"),
		);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(2);
	});

	it("fires on the canonical Bun #31188 shape (buf.as_ptr() as *const u16, len / 2)", () => {
		const found = runRust(
			[
				"fn widen(buf: &[u8]) -> &[u16] {",
				"    unsafe { std::slice::from_raw_parts(buf.as_ptr() as *const u16, buf.len() / 2) }",
				"}",
			].join("\n"),
		);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(2);
	});

	it("fires past 160 chars of pointer expression before the widening cast", () => {
		const pad = "very_long_identifier_component_".repeat(6);
		const found = runRust(
			`let s = unsafe { std::slice::from_raw_parts(${pad} as *const u16, n) };`,
		);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(1);
	});

	it("does not fire inside a NESTED block comment (rustc block comments nest)", () => {
		const found = runRust(
			[
				"/* disabled while we investigate #31188:",
				" * old approach: /* inner note */",
				" * let words: &[u16] = bytemuck::cast_slice(buf);",
				" */",
				"fn decode() {}",
			].join("\n"),
		);
		expect(found).toEqual([]);
	});
});

describe("checkRustUncheckedCastSlice — stripping regressions", () => {
	it("fires on cast_slice on a line with lifetimes and an apostrophe in a trailing comment", () => {
		const found = runRust(
			[
				"fn widen<'a>(buf: &'a [u8]) -> &'a [u16] {",
				"    let words: &'a [u16] = bytemuck::cast_slice(buf); // caller's buffer",
				"    words",
				"}",
			].join("\n"),
		);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(2);
	});

	it("fires on cast_slice sharing a line with a raw string literal", () => {
		const found = runRust(
			[
				"fn send(payload: &[u8]) {",
				'\tprocess(r#"hdr"#, bytemuck::cast_slice::<u8, u16>(payload));',
				"}",
			].join("\n"),
		);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(2);
	});
});

// ─── Stripper edge cases: char literals, raw strings, unclosed constructs ────

describe("checkRustUncheckedCastSlice — char-literal & raw-string stripper coverage", () => {
	it("consumes a plain Rust char literal ('x') and still flags cast_slice later on the line", () => {
		const found = runRust("let c = 'x'; let w: &[u16] = bytemuck::cast_slice(buf);");
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(1);
	});

	it("consumes an escaped Rust char literal ('\\n') and still flags cast_slice later on the line", () => {
		const found = runRust("let nl = '\\n'; let w: &[u16] = bytemuck::cast_slice(buf);");
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(1);
	});

	it("does not treat an identifier-preceded r as a raw-string head (e.g. `xr`)", () => {
		const found = runRust('let xr = "weird"; bytemuck::cast_slice(buf);');
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(1);
	});

	it("consumes an unterminated Rust raw string through EOF without crashing", () => {
		expect(runRust('r#"never closes')).toEqual([]);
	});

	it("consumes an unterminated Rust block comment through EOF without crashing", () => {
		expect(
			runRust("/* unterminated comment mentioning bytemuck::cast_slice(buf) that never closes"),
		).toEqual([]);
	});

	it("consumes an unterminated multiline Rust string (double quote) through EOF without crashing", () => {
		expect(runRust('let s = "never closes')).toEqual([]);
	});

	it("continues a Rust string literal across an embedded newline (multiline strings are legal)", () => {
		const content = ['let s = "line one', 'line two"; bytemuck::cast_slice(buf);'].join("\n");
		const found = runRust(content);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(2);
	});

	it("treats a raw string at the very start of the file as a genuine raw-string head (start === 0)", () => {
		expect(runRust('r#"hdr"#;')).toEqual([]);
	});

	it("keeps an embedded newline inside a Rust raw string live, still closing correctly on the next line", () => {
		const content = ['let s = r#"line one', 'line two"#; bytemuck::cast_slice(buf);'].join("\n");
		const found = runRust(content);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(2);
	});

	it("treats a space-preceded bare r-string head as a genuine raw string (start > 0, non-identifier preceder)", () => {
		// start > 0 (not file-start) AND the preceding char is non-identifier
		// (a space) — distinct from the identifier-preceded `xr` negative case
		// above, which takes the OTHER side of that `&&`.
		const found = runRust(' r"hi"; bytemuck::cast_slice(buf);');
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(1);
	});
});

describe("checkUnalignedReinterpret — identifier/keyword slash disambiguation", () => {
	it("reads a slash after a non-keyword identifier as division, not a regex literal", () => {
		const found = runJs("const ratio = total/count; const view = new Uint16Array(buf.buffer);");
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(1);
	});

	it("reads a slash after a non-identifier, non-punctuation char (closing paren) as division", () => {
		const found = runJs("const ratio = f()/2; const view = new Uint16Array(buf.buffer);");
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(1);
	});

	it("treats a keyword-preceded slash as a regex literal that consumes to EOF when unterminated", () => {
		expect(runJs("return /abc")).toEqual([]);
	});

	it("keeps an escaped slash alive inside a regex literal without ending it early", () => {
		const found = runJs(
			String.raw`const re = /a\/b/; const view = new Uint16Array(buf.buffer);`,
		);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(1);
	});

	it("keeps a slash inside a regex character class from ending the literal ([...] handling)", () => {
		const found = runJs(
			String.raw`const re = /[a/b]/; const view = new Uint16Array(buf.buffer);`,
		);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(1);
	});

	it("does not let a regex literal span a newline; the view on a later line still fires", () => {
		const content = [
			"const r = /abc",
			"def/;",
			"const view = new Uint16Array(buf.buffer);",
		].join("\n");
		const found = runJs(content);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(3);
	});
});

describe("checkUnalignedReinterpret — quoted-string stripper edge cases", () => {
	it("does not let an unterminated JS double-quoted string swallow the next line", () => {
		const content = [
			'const s = "unterminated;',
			"const view = new Uint16Array(buf.buffer);",
		].join("\n");
		const found = runJs(content);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(2);
	});

	it("consumes an unterminated JS template literal through EOF without crashing", () => {
		expect(runJs("const s = `never closes")).toEqual([]);
	});

	it("keeps an escaped quote alive inside a JS string (does not end it early)", () => {
		const found = runJs(
			'const s = "a\\"b"; const view = new Uint16Array(buf.buffer);',
		);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(1);
	});

	it("treats a trailing backslash-newline in a JS string as a line continuation", () => {
		const content = [
			'const s = "line \\',
			'continues"; const view = new Uint16Array(buf.buffer);',
		].join("\n");
		const found = runJs(content);
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(2);
	});

	it("does not fire when the constructor argument is whitespace-only (empty after trim)", () => {
		expect(runJs("const v = new Uint16Array(   );")).toEqual([]);
	});

	it("consumes a JS single-quoted string and still flags a view later on the line", () => {
		const found = runJs("const s = 'hello'; const view = new Uint16Array(buf.buffer);");
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(1);
	});

	it("treats a slash at the very start of the scanned source as a regex-literal start (no preceding char)", () => {
		// isRegexLiteralStart walks left from the slash; when nothing precedes
		// it (not even whitespace) the walk goes negative and the slash reads
		// as a regex opener, not division — /abc/ is consumed as a literal and
		// the view on the same line still fires.
		const found = runJs("/abc/.test(x); const view = new Uint16Array(buf.buffer);");
		expect(found).toHaveLength(1);
		expect(found[0]?.line).toBe(1);
	});
});
