// Co-located tests for `checkTestFileExists`.
//
// The check has two FP shapes from the 139-repo audit (2026-05):
//   1. test files themselves (handled via `isTestFile`)
//   2. generator output that never has unit-test siblings by design
//      (handled via `isGeneratedFile` content marker — Supermodel's
//      sdk/DefaultApi.ts produced 67 FPs in one file).
//
// Filesystem coverage (does the check find an existing
// `*.test.ts` / `__tests__/*.test.ts`) lives in the call-site tests
// because it depends on `existsSync`. These tests focus on the gates
// that don't touch the filesystem.

import { describe, expect, test } from "vitest";
import { checkTestFileExists } from "./test-file-exists.js";
import { nonNull } from "../../lib/non-null.js";

describe("checkTestFileExists — generator-output gate (FP refinement)", () => {
	// Negative cases — these MUST be exempted.

	test("OpenAPI Generator output is exempted", () => {
		const code = [
			"/* tslint:disable */",
			"/* eslint-disable */",
			"/**",
			" * NOTE: This class is auto generated by OpenAPI Generator",
			" */",
			"export class DefaultApi {}",
		].join("\n");
		expect(checkTestFileExists("sdk/src/apis/DefaultApi.ts", code)).toEqual([]);
	});

	test("protoc-generated output is exempted", () => {
		const code = [
			"// Code generated by protoc-gen-go. DO NOT EDIT.",
			"export class ProtoMessage {}",
		].join("\n");
		expect(checkTestFileExists("proto/foo_pb.ts", code)).toEqual([]);
	});

	test("@generated tag is exempted", () => {
		const code = [
			"// @generated SignedSource<<...>>",
			"export type Schema = unknown;",
		].join("\n");
		expect(checkTestFileExists("src/Schema.ts", code)).toEqual([]);
	});

	// Positive cases — real hand-written source must STILL be flagged
	// for missing test files (the check's purpose). We use a path that
	// won't accidentally have a real test sibling on disk.

	test("STILL flags hand-written code without generator marker", () => {
		const code = [
			"// Real hand-written application code.",
			"export function realFunction() { return 42; }",
		].join("\n");
		const out = checkTestFileExists(
			"/tmp/__interlinked_test_does_not_exist__/lib/foo.ts",
			code,
		);
		expect(out.length).toBe(1);
		expect(nonNull(out[0]).text).toContain("no test file");
	});

	test("STILL flags when content is undefined (back-compat — no gate)", () => {
		// Original API: filePath only. We must preserve that behavior so
		// callers that haven't migrated still work.
		const out = checkTestFileExists(
			"/tmp/__interlinked_test_does_not_exist__/lib/bar.ts",
		);
		expect(out.length).toBe(1);
	});

	test("STILL flags real source where 'generated' appears past line 20", () => {
		// The detector window is 20 lines — past that, the marker doesn't
		// suppress.
		const lines = Array.from({ length: 25 }, (_, i) => `const x${i} = ${i};`);
		lines[24] = "// uses the auto-generated SDK elsewhere";
		const out = checkTestFileExists(
			"/tmp/__interlinked_test_does_not_exist__/lib/baz.ts",
			lines.join("\n"),
		);
		expect(out.length).toBe(1);
	});
});

describe("checkTestFileExists — type-only module gate (FP refinement)", () => {
	// A fabricated path with no test sibling on disk: the ONLY thing that can
	// return [] for these is the type-only gate. Without it the check fires.
	const NO_SIBLING = "/tmp/__interlinked_test_does_not_exist__";

	// Negative cases — pure type-definition modules MUST be exempted.

	test("a pure interface module is exempted", () => {
		const code = [
			"export interface Config {",
			"  enabled: boolean;",
			"}",
			"export interface Server { url: string; }",
		].join("\n");
		expect(checkTestFileExists(`${NO_SIBLING}/types/config.ts`, code)).toEqual([]);
	});

	test("a pure type-alias module is exempted", () => {
		const code = [
			'export type SyncMode = "realtime" | "local" | "manual";',
			"export type Handler = (e: string) => void;",
		].join("\n");
		expect(checkTestFileExists(`${NO_SIBLING}/types/modes.ts`, code)).toEqual([]);
	});

	// Positive cases — runtime code must STILL be flagged for a missing test.

	test("STILL flags a module that mixes a type with runtime code", () => {
		const code = [
			'export type Mode = "on" | "off";',
			'export const DEFAULT_MODE: Mode = "on";',
		].join("\n");
		const out = checkTestFileExists(`${NO_SIBLING}/lib/with-runtime.ts`, code);
		expect(out.length).toBe(1);
	});

	test("STILL flags a type-only module when content is undefined (no gate)", () => {
		// The gate is content-based — callers that pass no content keep the
		// original behavior.
		const out = checkTestFileExists(`${NO_SIBLING}/lib/types-no-content.ts`);
		expect(out.length).toBe(1);
	});
});
