// Regression test: the shell snippet generated by `installCodexHooks`
// (and the other relative-path installers) must parse and execute correctly
// under bash, sh, and zsh — Codex / Claude / Copilot all invoke hooks via
// the user's configured shell, and many CI environments use bash or dash.
// An earlier version of `buildHookCommand` joined the body with `"; "`,
// producing `while :; do; if ...` which is rejected by bash/sh/dash (only
// zsh tolerates the empty statement after `do`). This test pins the fix.

import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { installCodexHooks } from "../hook-installers.js";

interface HookEntry {
	type: string;
	command: string;
}
interface HookGroup {
	matcher: string;
	hooks: HookEntry[];
}
interface HookFile {
	hooks: Record<string, HookGroup[]>;
}

// zsh isn't installed on GitHub Actions ubuntu-latest runners. The bash/sh
// cases already cover the original regression (the old `[...].join("; ")`
// form produced `do;` / `then;` which only zsh tolerates and bash/sh reject),
// so the zsh case is a sanity check that good code still works on zsh — fine
// to skip when zsh is missing rather than fail with a confusing
// `.toMatch(undefined)` error.
const HAS_ZSH = spawnSync("zsh", ["-c", "true"], { stdio: "ignore" }).status === 0;

let tmp: string;

beforeEach(() => {
	tmp = mkdtempSync(join(tmpdir(), "codex-shell-"));
});

afterEach(() => {
	rmSync(tmp, { recursive: true, force: true });
});

function readPreToolCommand(): string {
	const path = join(tmp, ".codex", "hooks.json");
	const parsed = JSON.parse(readFileSync(path, "utf-8")) as HookFile;
	return parsed.hooks.PreToolUse[0].hooks[0].command;
}

function shellExits(shell: string, command: string): { code: number; stderr: string } {
	const res = spawnSync(shell, ["-c", command], {
		encoding: "utf-8",
		cwd: tmp,
	});
	return { code: res.status ?? -1, stderr: res.stderr };
}

describe("Codex hook command — shell portability", () => {
	it("parses without error under bash", () => {
		installCodexHooks(tmp, ".interlinked/hooks/interlinked-activity.mjs");
		const command = readPreToolCommand();
		// Replace the actual node invocation with a no-op echo so the test
		// doesn't depend on an installed hook script. We're testing parse
		// + control-flow, not script execution.
		const safeCommand = command.replace(/INTERLINKED_CLIENT[^|]*\|\| true/, 'echo "RAN"');
		const result = shellExits("bash", safeCommand);
		expect(result.stderr).not.toMatch(/syntax error/i);
		expect(result.code).toBe(0);
	});

	it("parses without error under sh", () => {
		installCodexHooks(tmp, ".interlinked/hooks/interlinked-activity.mjs");
		const command = readPreToolCommand();
		const safeCommand = command.replace(/INTERLINKED_CLIENT[^|]*\|\| true/, 'echo "RAN"');
		const result = shellExits("sh", safeCommand);
		expect(result.stderr).not.toMatch(/syntax error/i);
		expect(result.code).toBe(0);
	});

	it.skipIf(!HAS_ZSH)("parses without error under zsh", () => {
		installCodexHooks(tmp, ".interlinked/hooks/interlinked-activity.mjs");
		const command = readPreToolCommand();
		const safeCommand = command.replace(/INTERLINKED_CLIENT[^|]*\|\| true/, 'echo "RAN"');
		const result = shellExits("zsh", safeCommand);
		expect(result.stderr).not.toMatch(/syntax error/i);
		expect(result.code).toBe(0);
	});

	it("walks up from a subdirectory and finds the hook script at the repo root", () => {
		// Drop a fake hook script at the repo root; cd into a deep subdir;
		// run the generated command from there. The walk-up logic should
		// find the script and execute it.
		mkdirSync(join(tmp, ".interlinked", "hooks"), { recursive: true });
		writeFileSync(
			join(tmp, ".interlinked", "hooks", "interlinked-activity.mjs"),
			"#!/usr/bin/env node\nprocess.stdout.write('FOUND');\n",
		);
		mkdirSync(join(tmp, "deep", "nested", "subdir"), { recursive: true });
		installCodexHooks(tmp, ".interlinked/hooks/interlinked-activity.mjs");
		const command = readPreToolCommand();

		const res = spawnSync("bash", ["-c", command], {
			encoding: "utf-8",
			cwd: join(tmp, "deep", "nested", "subdir"),
			input: "{}",
		});
		expect(res.stderr).not.toMatch(/syntax error/i);
		expect(res.stdout).toContain("FOUND");
	});

	it("exits cleanly when the hook script is missing (no error to the user's shell)", () => {
		// Don't create the script; the walk-up should hit the filesystem
		// root and exit with status 0.
		installCodexHooks(tmp, ".interlinked/hooks/interlinked-activity.mjs");
		const command = readPreToolCommand();
		const result = shellExits("bash", command);
		expect(result.code).toBe(0);
	});

	it("emits the file via the legacy installCodexHooks pipeline", () => {
		installCodexHooks(tmp, ".interlinked/hooks/interlinked-activity.mjs");
		expect(existsSync(join(tmp, ".codex", "hooks.json"))).toBe(true);
	});
});
